************************************************************************
* Program Name      : ZISD03U_VEHICLE_ORDER2_LOG
* Author            : jun ho choi
* Creation Date     : 2004.04.13.
* Specifications By : jun ho choi
* Pattern           : 3-3
* Development Request No : UD1K909364
* Addl Documentation:
* Description       : Vehicle Order Interface Log
*
*
* Modification Logs
* Date       Developer    RequestNo    Description
*
*
*
************************************************************************
REPORT ZISD03U_VEHICLE_ORDER2_LOG NO STANDARD PAGE HEADING
                                  MESSAGE-ID ZMSD.


*
TABLES : ZTSD_VEH_OR,
         USR01,
         MARA,
         KNVV.


*
DATA : BEGIN OF BDC_TAB OCCURS 0.
       INCLUDE STRUCTURE BDCDATA.
DATA : END OF BDC_TAB.

DATA : BEGIN OF MESS_TAB OCCURS 0.
       INCLUDE STRUCTURE BDCMSGCOLL.
DATA : END OF MESS_TAB.

DATA : W_DATE(6) TYPE N,
       W_CHAR_5(5),
       W_CHAR_20(20),
       W_CHAR_MOD(10),
       W_CHAR_SEQ(10),
       W_VBELN LIKE VBAK-VBELN.

* BAPI
DATA : BEGIN OF ORDER_HEADER_INX.
       INCLUDE STRUCTURE BAPISDH1X.
DATA : END OF ORDER_HEADER_INX.

DATA : BEGIN OF RETURN OCCURS 0.
       INCLUDE STRUCTURE BAPIRET2.
DATA : END OF RETURN.

DATA : BEGIN OF ORDER_ITEM_IN OCCURS 0.
       INCLUDE STRUCTURE BAPISDITM.
DATA : END OF ORDER_ITEM_IN.

DATA : BEGIN OF ORDER_ITEM_INX OCCURS 0.
       INCLUDE STRUCTURE BAPISDITMX.
DATA : END OF ORDER_ITEM_INX.

DATA : BEGIN OF SCHEDULE_LINES OCCURS 0.
       INCLUDE STRUCTURE BAPISCHDL.
DATA : END OF SCHEDULE_LINES.

DATA : BEGIN OF SCHEDULE_LINESX OCCURS 0.
       INCLUDE STRUCTURE BAPISCHDLX.
DATA : END OF SCHEDULE_LINESX.
* BAPI

DATA : SAVE_OK_CODE(4).

DATA : W_CNT TYPE I.


*
SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-001.
PARAMETERS : P_PDATE LIKE ZTSD_VEH_OR-PDATE OBLIGATORY.
SELECT-OPTIONS : S_WO_SER FOR ZTSD_VEH_OR-WO_SER NO-EXTENSION,
                 S_NATION FOR ZTSD_VEH_OR-NATION NO-EXTENSION,
                 S_DEALER FOR ZTSD_VEH_OR-DEALER NO-EXTENSION.
SELECTION-SCREEN END OF BLOCK B1.


*
START-OF-SELECTION.
  PERFORM READ_DATA.


*
END-OF-SELECTION.
  PERFORM CALL_SCREEN.






************************************************************************
* TYPE FOR THE DATA OF TABLECONTROL 'TC_9000'
TYPES: BEGIN OF T_TC_9000.
         INCLUDE STRUCTURE ZTSD_VEH_OR.
TYPES:   FLAG,       "flag for mark column
       END OF T_TC_9000.

* INTERNAL TABLE FOR TABLECONTROL 'TC_9000'
DATA:     G_TC_9000_ITAB   TYPE T_TC_9000 OCCURS 0,
          G_TC_9000_WA     TYPE T_TC_9000, "work area
          G_TC_9000_COPIED.           "copy flag

* DECLARATION OF TABLECONTROL 'TC_9000' ITSELF
CONTROLS: TC_9000 TYPE TABLEVIEW USING SCREEN 9000.

* LINES OF TABLECONTROL 'TC_9000'
DATA:     G_TC_9000_LINES  LIKE SY-LOOPC.

DATA:     OK_CODE LIKE SY-UCOMM.

* Includes inserted by Screen Painter Wizard. DO NOT CHANGE THIS LINE!
INCLUDE ZISD03U_VEHICLE_ORDER2_LOG_F01.
INCLUDE ZISD03U_VEHICLE_ORDER2_LOG_PBO.
INCLUDE ZISD03U_VEHICLE_ORDER2_LOG_PAI.
