************************************************************************
* Program Name      : ZISD14R_PART_LIST
* Author            : jun ho choi
* Creation Date     : 2003.09.22.
* Specifications By : jun ho choi
* Pattern           : 1-2
* Development Request No : UD1K904910
* Addl Documentation:
* Description       : Main. PART(INF,PRC,HST,SUP)
*
* Modification Logs
* Date       Developer    RequestNo    Description
*
*
*
************************************************************************
REPORT ZISD14R_PART_LIST NO STANDARD PAGE HEADING
                         MESSAGE-ID ZMSD
                         LINE-SIZE 137.


*
TABLES : ZTSD_PART_INF,
         ZTSD_PART_PRC,
         ZTSD_PART_HST,
         ZTSD_PART_SUP.


*
DATA : BEGIN OF IT_PART_INF OCCURS 0.
       INCLUDE STRUCTURE ZTSD_PART_INF.
DATA : END OF IT_PART_INF.

DATA : BEGIN OF IT_PART_PRC OCCURS 0.
       INCLUDE STRUCTURE ZTSD_PART_PRC.
DATA : END OF IT_PART_PRC.

DATA : BEGIN OF IT_PART_HST OCCURS 0.
       INCLUDE STRUCTURE ZTSD_PART_HST.
DATA : END OF IT_PART_HST.

DATA : BEGIN OF IT_PART_SUP OCCURS 0.
       INCLUDE STRUCTURE ZTSD_PART_SUP.
DATA : END OF IT_PART_SUP.

DATA : OK_CODE(4),
       SAVE_OK_CODE(4).

DATA : W_CNT TYPE I,
       W_SAVE(1),
       W_ANSWER(1),
       W_GUBUN(1),
       W_TABIX LIKE SY-TABIX.

* PF-STATUS
TYPES : BEGIN OF TAB_TYPE,
        FCODE LIKE RSMPE-FUNC,
        END OF TAB_TYPE.

DATA : TAB TYPE STANDARD TABLE OF TAB_TYPE WITH
               NON-UNIQUE DEFAULT KEY INITIAL SIZE 10,
       WA_TAB TYPE TAB_TYPE.


*
SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-001.
PARAMETERS : P_ZCPTN LIKE ZTSD_PART_INF-ZCPTN,
             P_ZSQYY LIKE SY-DATUM+0(4) DEFAULT SY-DATUM+0(4)
                                        OBLIGATORY.
SELECTION-SCREEN SKIP 1.
PARAMETERS : P_INF RADIOBUTTON GROUP RADI USER-COMMAND RD1,
             P_PRC RADIOBUTTON GROUP RADI,
             P_HST RADIOBUTTON GROUP RADI,
             P_SUP RADIOBUTTON GROUP RADI DEFAULT 'X'.
SELECTION-SCREEN END OF BLOCK B1.


*
AT SELECTION-SCREEN OUTPUT.
  IF P_SUP NE 'X'.
    LOOP AT SCREEN. " WHERE NAME = 'P_ZSQYY'.
      CHECK SCREEN-NAME = 'P_ZSQYY'.
      SCREEN-INPUT = '0'.
      MODIFY SCREEN.
    ENDLOOP.
  ENDIF.


*
TOP-OF-PAGE.
  PERFORM TOP_OF_PAGE.


*
TOP-OF-PAGE DURING LINE-SELECTION.
  PERFORM TOP_OF_PAGE.


*
START-OF-SELECTION.
  PERFORM INIT_STATUS.
  PERFORM GET_DATA.


*
END-OF-SELECTION.
  PERFORM DISPLAY_DATA.


*
AT USER-COMMAND.
  PERFORM USER_COMMAND.


*
INCLUDE ZISD14L_PART_LIST_F01.
INCLUDE ZISD14L_PART_LIST_PBO.
INCLUDE ZISD14L_PART_LIST_PAI.
