*&---------------------------------------------------------------------*
*&  Include           ZRSD_OSR_SIGNOFF_TOP
*&---------------------------------------------------------------------*

TABLES: ZTPP_INPUT_OSR.

DATA : BEGIN OF IT_INPUT_OSR OCCURS 0.
        INCLUDE STRUCTURE ZTPP_INPUT_OSR.
DATA : END OF   IT_INPUT_OSR.

DATA : BEGIN OF IT_PLAN OCCURS 0.
        INCLUDE STRUCTURE ZTPP_SOFF_PLAN.
DATA : END OF IT_PLAN.

DATA : IT_UM     LIKE TABLE OF ZTSD_UM    WITH HEADER LINE.

DATA : IT_OSR_IF_HMA TYPE TABLE OF ZTPP_INPUT_OSR WITH  HEADER LINE,
       IT_OSR_IF_HAC TYPE TABLE OF ZTPP_INPUT_OSR WITH  HEADER LINE,
       IT_OSR_IF_GLV TYPE TABLE OF ZTPP_INPUT_OSR WITH  HEADER LINE.

*DATA:  IT_ZTSD_OSR_LOG TYPE TABLE OF ZTSD_OSR_SIGNOFF_LOG
*       WITH  HEADER LINE.

DATA : G_INDEX LIKE SY-INDEX,
       GV_REPID LIKE SY-REPID.

DATA : G_COMPANY(3).              "   HMA, HAC

DATA: G_TCAP TYPE I.

DATA: W_MSGTXT(100),
      W_CN TYPE I.

DATA: BEGIN OF IT_CAPACITY OCCURS 150,
      DATE LIKE SY-DATUM,
      CAP TYPE I,
      END OF IT_CAPACITY.
** for ALV
DATA: OK_CODE      LIKE SY-UCOMM.

DATA : IT_FIELDCAT     TYPE LVC_T_FCAT WITH HEADER LINE,
       IT_FIELDCAT_FI  TYPE LVC_T_FCAT WITH HEADER LINE,
       IT_FIELDCAT_CO  TYPE LVC_T_FCAT WITH HEADER LINE,
       IT_FIELDNAME    TYPE SLIS_T_FIELDCAT_ALV,
       IT_SORT         TYPE LVC_T_SORT WITH HEADER LINE,
       IT_FIELDCAT_DET TYPE LVC_T_FCAT WITH HEADER LINE. "/Detail

DATA : WA_IS_LAYOUT TYPE LVC_S_LAYO, "/The Layout Structure
*      it_color type LVC_T_SCOL,
*      wa_color like line of it_color,
      W_FIELDNAME    LIKE LINE OF IT_FIELDCAT.

DATA: WA_SAVE    TYPE C   VALUE 'A',   "for Parameter I_SAVE
      WA_VARIANT TYPE DISVARIANT.      "for parameter IS_VARIANT

DATA: WA_CUSTOM_CONTROL TYPE        SCRFNAME VALUE 'ALV_CONTAINER',
      ALV_GRID          TYPE REF TO CL_GUI_ALV_GRID,
      GRID_CONTAINER    TYPE REF TO CL_GUI_CUSTOM_CONTAINER.

DATA: W_DATE LIKE SY-DATUM,
      W_TIME LIKE SY-UZEIT.

SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-001.
SELECT-OPTIONS: S_WORDER FOR ZTPP_INPUT_OSR-WORK_ORDER.
PARAMETERS: P_DATE LIKE SY-DATUM DEFAULT SY-DATUM OBLIGATORY.
SELECTION-SCREEN END OF BLOCK B1.

SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME TITLE TEXT-002.
PARAMETERS: P_BATCH AS CHECKBOX  DEFAULT 'X'.
SELECTION-SCREEN SKIP.

PARAMETERS: P_REC RADIOBUTTON GROUP RA1,
            P_DIS RADIOBUTTON GROUP RA1.

SELECTION-SCREEN SKIP.

SELECTION-SCREEN END OF BLOCK B2.
