*----------------------------------------------------------------------*
*   INCLUDE ZRSD04R_ORDER_DEVIATION_T01                                *
*----------------------------------------------------------------------*
TABLES : ZSSD_OR_DEVIATION,  " ORDER DEVIATION
         ZTPP_WOSUM,   "ERP_WO QTY SUMMARY
         ZSSD_OR_DEV_COUNT,  "ORDER DEVIATION COUNT
         VBAK,         "Sales Document: Header Data
         VBAP.         "Sales Document: Item Data

DATA : ITAB TYPE STANDARD TABLE OF ZSSD_OR_DEVIATION WITH NON-UNIQUE
                 DEFAULT KEY INITIAL SIZE 100,
       T_DEV TYPE ZSSD_OR_DEVIATION.

DATA : ITAB2 TYPE STANDARD TABLE OF ZSSD_OR_DEV_COUNT WITH NON-UNIQUE
                 DEFAULT KEY INITIAL SIZE 100,
       T_CNT TYPE ZSSD_OR_DEV_COUNT.

*DATA : ITAB TYPE ZSSD_OR_DEVIATION  .
*        INCLUDE STRUCTURE ZSSD_OR_DEVIATION.
*DATA : END OF ITAB.

DATA: BEGIN OF LTAB OCCURS 0.
DATA:  BSTNK  LIKE VBAK-BSTNK.
        INCLUDE STRUCTURE ZSSD_OR_DEVIATION.
DATA: END OF LTAB.

DATA : W_CNT TYPE I,
       W_GI_DATE LIKE SY-DATUM,
       W_IV_DATE LIKE SY-DATUM.

DATA : OK_CODE(4),
       SAVE_OK_CODE(4).
DATA : ALV_GRID       TYPE REF TO CL_GUI_ALV_GRID,
       ALV_GRID2       TYPE REF TO CL_GUI_ALV_GRID,
       CONTAINER      TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
       CONTAINER2      TYPE REF TO CL_GUI_CUSTOM_CONTAINER.

DATA : GS_VARIANT      TYPE DISVARIANT.
DATA : GS_VARIANT2     TYPE DISVARIANT.
DATA : GS_LAYOUT TYPE LVC_S_LAYO .
DATA : GT_HEADER       TYPE TABLE OF SLIS_LISTHEADER WITH HEADER LINE,
       GT_FIELDCAT_LVC TYPE LVC_T_FCAT WITH HEADER LINE.

SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-001.
SELECTION-SCREEN SKIP 1.
SELECT-OPTIONS : S_DATE FOR SY-DATUM.
SELECTION-SCREEN END OF BLOCK B1.
