************************************************************************
* Program Name      : ZRSD10R_ORDER_BALANCE
* Author            : jun ho choi
* Creation Date     : 2003.08.20.
* Specifications By : jun ho choi
* Pattern           : Report 1-2
* Development Request No : UD1K904835
* Addl Documentation:
* Description       : Order Balance each by item
*
* Modification Logs
* Date       Developer    RequestNo    Description
*
*
*
************************************************************************
REPORT ZRSD10R_ORDER_BALANCE NO STANDARD PAGE HEADING
                             MESSAGE-ID ZMSD.


*
TABLES : ZSSD_OR_BALANCE,
         VBAK,
         VBAP,
         VBFA,
         MARC,
         KNA1.


*
DATA : IT_OR_BAL TYPE STANDARD TABLE OF ZSSD_OR_BALANCE WITH NON-UNIQUE
                 DEFAULT KEY INITIAL SIZE 100,
       T_OR_BAL TYPE ZSSD_OR_BALANCE.

DATA : BEGIN OF IT_VBAK OCCURS 0.
       INCLUDE STRUCTURE VBAK.
DATA : END OF IT_VBAK.

DATA : BEGIN OF IT_VBAP OCCURS 0.
       INCLUDE STRUCTURE VBAP.
DATA : END OF IT_VBAP.

DATA : BEGIN OF IT_VBEP OCCURS 0.
       INCLUDE STRUCTURE VBEP.
DATA : END OF IT_VBEP.

DATA : W_CNT TYPE I,
       W_GI_DATE LIKE SY-DATUM,
       W_IV_DATE LIKE SY-DATUM,
       W_GI_QTY LIKE VBFA-RFMNG,
       W_IV_QTY LIKE VBFA-RFMNG,
       W_VBELN LIKE VBEP-VBELN,
       W_POSNR LIKE VBEP-POSNR.

DATA : OK_CODE(4),
       SAVE_OK_CODE(4).
DATA : ALV_GRID       TYPE REF TO CL_GUI_ALV_GRID,
       CONTAINER      TYPE REF TO CL_GUI_CUSTOM_CONTAINER.
DATA : GS_VARIANT     TYPE DISVARIANT.
DATA : GS_LAYOUT TYPE LVC_S_LAYO.


*
SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-001.
PARAMETERS : P_VTWEG LIKE VBAK-VTWEG OBLIGATORY DEFAULT '30'.
SELECTION-SCREEN SKIP 1.
PARAMETERS : P_SPMON LIKE S001-SPMON OBLIGATORY DEFAULT SY-DATUM+0(6).
SELECT-OPTIONS : S_MATNR FOR VBAP-MATNR NO-EXTENSION NO INTERVALS,
                 S_SUBPR FOR ZSSD_OR_BALANCE-SUBPR
                                        NO-EXTENSION NO INTERVALS.
SELECTION-SCREEN SKIP 1.
SELECT-OPTIONS : S_KUNNR FOR VBAK-KUNNR NO-EXTENSION NO INTERVALS,
                 S_VBELN FOR VBAK-VBELN NO-EXTENSION NO INTERVALS.
SELECTION-SCREEN END OF BLOCK B1.


*
START-OF-SELECTION.
  PERFORM READ_DATA.
  PERFORM MODIFY_DATA.



*
END-OF-SELECTION.
  PERFORM CALL_SCREEN.





INCLUDE ZRSD10R_ORDER_BALANCE_F01.
INCLUDE ZRSD10R_ORDER_BALANCE_PBO.
INCLUDE ZRSD10R_ORDER_BALANCE_PAI.
