*&---------------------------------------------------------------------*
*&  Include           ZSDF00200TTOP
*&---------------------------------------------------------------------*
TABLES : ZSSD_DN_H, ZSSD_DN_I,
         NAST,
         LIKP, LIPS, T001W.

DATA : BEGIN OF IT_LIST OCCURS 0,
       POSNR LIKE LIPS-POSNR,
       PSTYV LIKE LIPS-PSTYV,
       KDMAT LIKE LIPS-KDMAT,
       ARKTX LIKE LIPS-ARKTX,
       LFIMG LIKE LIPS-LFIMG,
       VRKME LIKE LIPS-VRKME,
       MATNR LIKE LIPS-MATNR,
       VOLUM(15),
       END OF IT_LIST.

DATA : BEGIN OF IT_DN_H OCCURS 0.
        INCLUDE STRUCTURE ZSSD_DN_H.
DATA : END OF IT_DN_H.

DATA : BEGIN OF IT_DN_I OCCURS 0.
        INCLUDE STRUCTURE ZSSD_DN_I.
DATA : END OF IT_DN_I.

* smart form
DATA : FUNC_MOD_NAME TYPE RS38L_FNAM.
DATA : CONTROL_PARAMETERS TYPE SSFCTRLOP.
DATA : OUTPUT_OPTIONS TYPE SSFCOMPOP.
DATA : JOB_OUTPUT_INFO TYPE SSFCRESCL.

DATA : V_OTF LIKE ITCOO OCCURS 0 WITH HEADER LINE,
       V_PDF TYPE  RCL_BAG_TLINE,
       V_SIZE TYPE I.
DATA : BEGIN OF IT_PDF OCCURS 0,
       LINE(134),
       END OF IT_PDF.

DATA : BEGIN OF EMAIL_DATA.
        INCLUDE STRUCTURE SODOCCHGI1.
DATA : END OF EMAIL_DATA.
DATA : BEGIN OF EMAIL_SEND OCCURS 10.
        INCLUDE STRUCTURE SOMLRECI1.
DATA : END OF EMAIL_SEND.

DATA : OBJPACK LIKE SOPCKLSTI1 OCCURS 2 WITH HEADER LINE.
DATA : IT_TEXT LIKE SOLISTI1 OCCURS 20 WITH HEADER LINE.
