***INCLUDE SDZAVDAT .

* where-clause for central address select
  DATA: GV_FB_ADDR_GET_SELECTION  LIKE ADDR1_SEL.
  DATA: GV_FB_ADDR_GET_SELECTION2 LIKE ADDR2_SEL.

* address_group
  CONSTANTS: BEGIN OF GCS_ADDRESS_GROUP,
               MAN_ADDRESS   LIKE   ADRG-ADDR_GROUP VALUE 'SD01',
               ORG_UNIT      LIKE   ADRG-ADDR_GROUP VALUE 'CA01',
             END OF GCS_ADDRESS_GROUP.

* application table and application field
  CONSTANTS:
*   sd
    GCF_APPL_TABLE_SD    LIKE   ADDR_REF-APPL_TABLE VALUE 'VBUK',
    GCF_APPL_FIELD_SD    LIKE   ADDR_REF-APPL_FIELD VALUE 'VBELN',
*   transport
    GCF_APPL_TABLE_TRA   LIKE   ADDR_REF-APPL_TABLE VALUE 'VTTK',
    GCF_APPL_FIELD_TRA   LIKE   ADDR_REF-APPL_FIELD VALUE 'TKNUM'.

* address type
  CONSTANTS:
    GCF_ADDRESS_TYPE_COMPANY       TYPE   AD_ADRTYPE   VALUE '1',
    GCF_ADDRESS_TYPE_PRIVATE       TYPE   AD_ADRTYPE   VALUE '2',
    GCF_ADDRESS_TYPE_CONT_PERSON   TYPE   AD_ADRTYPE   VALUE '3'.

* address origin
  CONSTANTS:
    GCF_ADDR_ORIGIN_MASTER_DATA     TYPE   ADDR_ORIGIN   VALUE 'A',
    GCF_ADDR_ORIGIN_MAN             TYPE   ADDR_ORIGIN   VALUE 'B',
    GCF_ADDR_ORIGIN_MAN_INH         TYPE   ADDR_ORIGIN   VALUE 'C'.

* address indicator
  CONSTANTS:
    GCF_ADDR_IND_MASTER_DATA          TYPE   ADRDA   VALUE 'A',
    GCF_ADDR_IND_MAN                  TYPE   ADRDA   VALUE 'B',
    GCF_ADDR_IND_MAN_INH              TYPE   ADRDA   VALUE 'C',
    GCF_ADDR_IND_MASTER_DATA_ADRC     TYPE   ADRDA   VALUE 'D',
    GCF_ADDR_IND_MAN_ADRC             TYPE   ADRDA   VALUE 'E',
    GCF_ADDR_IND_MAN_INH_ADRC         TYPE   ADRDA   VALUE 'F',
    GCF_ADDR_IND_PRIVATE_ADDRESS      TYPE   ADRDA   VALUE 'G',
*   combinations of address indicator
    GCF_ADDR_IND_COMB_ALL(7)          TYPE   C   VALUE 'ABCDEFG',
    GCF_ADDR_IND_COMB_ALL_OR_NULL(8)  TYPE   C   VALUE ' ABCDEFG',
    GCF_ADDR_IND_COMB_MASTER(3)       TYPE   C   VALUE 'ADG',
    GCF_ADDR_IND_COMB_MASTER_ADRC(2)  TYPE   C   VALUE 'DG',
    GCF_ADDR_IND_COMB_MAN_ALL(4)      TYPE   C   VALUE 'BCEF',
    GCF_ADDR_IND_COMB_MAN_OLD(2)      TYPE   C   VALUE 'BC',
    GCF_ADDR_IND_COMB_MAN_ADRC(2)     TYPE   C   VALUE 'EF',
    GCF_ADDR_IND_COMB_OLD(3)          TYPE   C   VALUE 'ABC',
    GCF_ADDR_IND_COMB_OLD_OR_NULL(4)  TYPE   C   VALUE ' ABC',
    GCF_ADDR_IND_COMB_ADRC(4)         TYPE   C   VALUE 'DEFG',
    GCF_ADDR_IND_COMB_MAN_INH(2)      TYPE   C   VALUE 'CF',
    GCF_ADDR_IND_COMB_MAN(2)          TYPE   C   VALUE 'BE'.

* include CAM-Flag (CAM active or not active)
  INCLUDE SAPCAMFL.
