REPORT ZZVBUND1.
TABLES: BSEG, BKPF, T003, KNA1, LFA1, BSIS, BSAS, BSIK, BSAK, BSID,BSAD.
TABLES: VF_DEBI, VF_KRED.


*TYPES: BKPF_TYPE LIKE BKPF,
*       BSEG_TYPE LIKE BSEG,
*       BSIS_TYPE LIKE BSIS,
*       BSAS_TYPE LIKE BSAS,
*       BSIK_TYPE LIKE BSIK,
*       BSAK_TYPE LIKE BSAK,
*       BSID_TYPE LIKE BSID,
*       BSAD_TYPE LIKE BSAD.
*
*DATA: XBKPF TYPE BKPF_TYPE OCCURS 0 WITH HEADER LINE,
*      EBKPF TYPE BKPF_TYPE OCCURS 0 WITH HEADER LINE,
*      XBSEG TYPE BSEG_TYPE OCCURS 0 WITH HEADER LINE,
*      YBSEG TYPE BSEG_TYPE OCCURS 0 WITH HEADER LINE,
*      XBSIS TYPE BSIS_TYPE OCCURS 0 WITH HEADER LINE,
*      XBSAS TYPE BSAS_TYPE OCCURS 0 WITH HEADER LINE,
*      XBSIK TYPE BSIK_TYPE OCCURS 0 WITH HEADER LINE,
*      XBSAK TYPE BSAK_TYPE OCCURS 0 WITH HEADER LINE,
*      XBSID TYPE BSID_TYPE OCCURS 0 WITH HEADER LINE,
*      XBSAD TYPE BSAD_TYPE OCCURS 0 WITH HEADER LINE,
*      XVBUND LIKE LFA1-VBUND,
*      V_ERROR TYPE C,
*      V_FLAG  TYPE C.

*DATA: IT_BSIK LIKE BSIK OCCURS 0.
DATA: BEGIN OF IT_BSIS OCCURS 0,
        BUKRS LIKE BSEG-BUKRS,
        GJAHR LIKE BSIK-GJAHR,
        BELNR LIKE BSEG-BELNR,
        BUZEI LIKE BSEG-BUZEI,
        VBUND LIKE BSIK-VBUND,
        HKONT LIKE BSEG-HKONT,
      END OF IT_BSIS.

DATA: BEGIN OF IT_BSEG OCCURS 0,
        BUKRS LIKE BSEG-BUKRS,
        BELNR LIKE BSEG-BELNR,
        GJAHR LIKE BSEG-GJAHR,
        BUZEI LIKE BSEG-BUZEI,
        HKONT LIKE BSEG-HKONT,
        KOART LIKE BSEG-KOART,
        AUGDT LIKE BSEG-AUGDT,
        AUGBL LIKE BSEG-AUGBL,
        EBELN LIKE BSEG-EBELN,
        EBELP LIKE BSEG-EBELP,
      END OF IT_BSEG.
*----------------------------------------------------------------
PARAMETERS:
          P_BUKRS     LIKE BKPF-BUKRS MEMORY ID BUK,
          P_HKONT     LIKE BSIS-HKONT.

*SELECT-OPTIONS:
*          S_LIFNR     FOR  BSIK-LIFNR.

SELECT-OPTIONS:
          S_GJAHR     FOR  BKPF-GJAHR,
          S_BELNR     FOR  BKPF-BELNR.
*          S_CPUDT     FOR  BKPF-CPUDT.

PARAMETERS: UPDATE DEFAULT SPACE AS CHECKBOX,
            AWTYP LIKE TTYP-AWTYP. " DEFAULT 'MKPF' .

*----------------------------------------------------------------
*
* COep, coej,
* cooi
* bsad, bsak, bsid, bsik
* glfunct
* glt1
* anla, anek
* regup
*

*TABLES: BSIK, LFA1, BSEG.

START-OF-SELECTION.

  SELECT BUKRS GJAHR BELNR BUZEI VBUND HKONT
    INTO TABLE IT_BSIS
    FROM BSIS
    WHERE BUKRS =  P_BUKRS
      AND HKONT =  P_HKONT
      AND AUGDT = '00000000'
      AND AUGBL = ''
      AND GJAHR IN S_GJAHR
      AND BELNR IN S_BELNR.

  LOOP AT IT_BSIS.
    PERFORM UPDATE_VBUND.
  ENDLOOP.

*&---------------------------------------------------------------------*
*&      Form  update_vbund
*&---------------------------------------------------------------------*
FORM UPDATE_VBUND.
  DATA: P_VBUND LIKE BSEG-VBUND.

  CHECK UPDATE = 'X'.
  REFRESH IT_BSEG.
  SELECT BUKRS BELNR GJAHR BUZEI HKONT KOART AUGDT AUGBL EBELN EBELP
     INTO TABLE IT_BSEG
     FROM BSEG
      WHERE BUKRS = IT_BSIS-BUKRS
        AND GJAHR = IT_BSIS-GJAHR
        AND BELNR = IT_BSIS-BELNR
        AND BUZEI = IT_BSIS-BUZEI.

  READ TABLE IT_BSEG INDEX 1.
  CHECK SY-SUBRC = 0.

  CLEAR P_VBUND.
  SELECT SINGLE VBUND INTO P_VBUND
    FROM EKKO AS A
    INNER JOIN LFA1 AS B
       ON A~LIFNR = B~LIFNR
    WHERE A~EBELN = IT_BSEG-EBELN.

  UPDATE BSEG SET VBUND = P_VBUND
     WHERE BUKRS = IT_BSEG-BUKRS
       AND GJAHR = IT_BSEG-GJAHR
       AND BELNR = IT_BSEG-BELNR
       AND BUZEI = IT_BSEG-BUZEI.

  UPDATE BSIS SET VBUND = P_VBUND
     WHERE BUKRS = IT_BSEG-BUKRS
       AND HKONT = IT_BSEG-HKONT
       AND AUGDT = IT_BSEG-AUGDT
       AND AUGBL = IT_BSEG-AUGBL
       AND GJAHR = IT_BSEG-GJAHR
       AND BELNR = IT_BSEG-BELNR
       AND BUZEI = IT_BSEG-BUZEI.
  WRITE:/ 'UPDATED ', IT_BSIS-GJAHR, IT_BSIS-BELNR, 'with:', P_VBUND.

ENDFORM.                    " update_vbund
