FUNCTION Z_FRF_PM_LOG_UPLOAD.
*"----------------------------------------------------------------------
*"*"Local interface:
*"  IMPORTING
*"     REFERENCE(I_LOG) TYPE  ZTRF_PM_BDC_LOG
*"----------------------------------------------------------------------
CHECK NOT I_LOG IS INITIAL.
  DATA: LA_LOG TYPE ZTRF_PM_BDC_LOG.
  DATA: LT_LOG TYPE ZTRF_PM_BDC_LOG OCCURS 0 WITH HEADER LINE.
  REFRESH LT_LOG. CLEAR LT_LOG.
  SELECT SINGLE *
              FROM ZTRF_PM_BDC_LOG
              INTO LA_LOG
              WHERE DATUM EQ I_LOG-DATUM
              AND   UZEIT EQ I_LOG-UZEIT
              AND   TTYPE EQ I_LOG-TTYPE.
  IF SY-SUBRC EQ 0.
    MOVE-CORRESPONDING I_LOG TO LT_LOG.
    APPEND LT_LOG. CLEAR LT_LOG.
    UPDATE ZTRF_PM_BDC_LOG FROM TABLE LT_LOG.
    IF SY-SUBRC EQ 0.
      COMMIT WORK.
    ELSE.
      ROLLBACK WORK.
    ENDIF.
  ELSE.
    MOVE-CORRESPONDING I_LOG TO LT_LOG.
    APPEND LT_LOG. CLEAR LT_LOG.
    INSERT ZTRF_PM_BDC_LOG FROM TABLE LT_LOG ACCEPTING DUPLICATE KEYS.
    IF SY-SUBRC EQ 0.
      COMMIT WORK.
    ELSE.
      ROLLBACK WORK.
    ENDIF.
  ENDIF.
ENDFUNCTION.
