*&---------------------------------------------------------------------*
*& Include MZAHR0011TOP                                                *
*&                                                                     *
*&---------------------------------------------------------------------*

PROGRAM  SAPMZAHR0011                  .

TABLES: PA0001,
        PA0008,
        HRP1000,
        CSKT,
        ZTHR_PCPXX,
        ZTHR_PCP00,
        ZTHR_PCP01,
        ZTHR_PCP02,
        ZTHR_PCP05.

CONTROLS: TC9000 TYPE TABLEVIEW USING SCREEN 9000.

*... internal tables
DATA: BEGIN OF IT_MAINT OCCURS 0,
      CHKBX,
      FORMS(10),
      ZSEQN    LIKE ZTHR_PCP05-ZSEQN,
      ZOBJC    LIKE ZTHR_PCP00-ZOBJC,
      ZOBJT    LIKE ZTHR_AHC01-ZJOBK,
      ZHEDT    LIKE ZTHR_PCP00-ZHEDC,
      ZSENR    LIKE ZTHR_PCP00-ZSENR,
      ZHEDC    LIKE ZTHR_PCP00-ZHEDC,
      HOURS    LIKE ZTHR_PCP00-ZSALY,
      ZWKTM    LIKE ZTHR_PCP05-ZWKTM,
      ZEXTR    LIKE ZTHR_PCP05-ZEXTR,
      ZVAL1    LIKE ZTHR_PCP02-ZVAL1,
      AMUNT    LIKE ZTHR_PCP00-ZSALY,
      ANCUR    LIKE ZTHR_PCP00-ANCUR,
      COUNT    TYPE I.
DATA: END OF IT_MAINT.

DATA: BEGIN OF IT_MAINT1 OCCURS 0,
      ZYEAR    LIKE ZTHR_PCP05-ZYEAR,
      ZMONS    LIKE ZTHR_PCP00-ZMONS,
      ZCOST    LIKE ZTHR_PCP00-ZCOST,
      KTEXT    LIKE CSKT-KTEXT,
      FORMS(10),
      ZSEQN    LIKE ZTHR_PCP05-ZSEQN,
      ZOBJC    LIKE ZTHR_PCP00-ZOBJC,
      ZOBJT    LIKE ZTHR_AHC01-ZJOBK,
      ZHEDT    LIKE ZTHR_PCP00-ZHEDC,
      ZSENR    LIKE ZTHR_PCP00-ZSENR,
      ZHEDC    LIKE ZTHR_PCP00-ZHEDC,
      HOURS    LIKE ZTHR_PCP00-ZSALY,
      ZWKTM    LIKE ZTHR_PCP05-ZWKTM,
      ZVAL1    LIKE ZTHR_PCP02-ZVAL1,
      AMUNT    LIKE ZTHR_PCP00-ZSALY,
      ANCUR    LIKE ZTHR_PCP00-ANCUR.
DATA: END OF IT_MAINT1.

DATA: BEGIN OF IT_DOWN OCCURS 0,
      ZGRUP(40),
      ZYEAR(10),
      ZMONS(10),
      ZCOST(40),
      KTEXT(40),
      FORMS(10),
*      ZSEQN(40),
*      ZOBJC(40),
      ZOBJT(40),
      ZHEDT(40),
      ZSENR(40),
      ZHEDC(40),
      HOURS(40),
      ZWKTM(40),
      ZVAL1(40),
      AMUNT(40),
      ANCUR(40).
DATA: END OF IT_DOWN.

DATA: IT_COPYT LIKE IT_MAINT OCCURS 0 WITH HEADER LINE.
DATA: IT_COPYT1 LIKE IT_MAINT1 OCCURS 0 WITH HEADER LINE.

DATA :BEGIN OF  IT_SORT_t  OCCURS 0.
        INCLUDE STRUCTURE IT_MAINT .
DATA:  xx TYPE I,
       END OF IT_SORT_t.

DATA: BEGIN OF IT_PCPXX OCCURS 0.
        INCLUDE STRUCTURE ZTHR_PCPXX.
DATA: HOURY    LIKE ZTHR_PCP00-ZSALY,
      END OF IT_PCPXX.

DATA: BEGIN OF IT_YEARS OCCURS 1,
      ZYEAR    LIKE ZTHR_PCP03-ZYEAR.
DATA: END OF IT_YEARS.

DATA: BEGIN OF IT_VERSN OCCURS 1,
      ZVERS    LIKE ZTHR_PCP03-ZVERS.
DATA: END OF IT_VERSN.

DATA: BEGIN OF IT_GROUP OCCURS 1,
      ZGRUP    LIKE ZTHR_PCP01-ZGRUP,
      ZGTXT    LIKE ZTHR_PCP01-ZGTXT.
DATA: END OF IT_GROUP.

DATA: BEGIN OF IT_KOSTL OCCURS 1,
      ZKOST    LIKE CSKT-KOSTL,
      ZKTXT    LIKE CSKT-KTEXT.
DATA: END OF IT_KOSTL.

DATA: IT_FIELD     LIKE HELP_VALUE OCCURS 1 WITH HEADER LINE,
      DYNPFIELDS   LIKE STANDARD TABLE OF DYNPREAD WITH HEADER LINE.

RANGES: R_ZJOBC FOR ZTHR_AHC01-ZJOBC.

*... variants
DATA: W_KOSTL      LIKE PA0001-KOSTL,      " parameter ; cost center
      W_KTEXT      LIKE RPCYERKX-KTEXT,    " parameter ; cost name
      W_ZYEAR      LIKE ZTHR_AHC01-ZYEAR,  " parameter ; year
      W_ZMONS      LIKE ZTHR_AHC01-ZMONS,  " parameter ; month
      W_ZVERS      LIKE ZTHR_AHC01-ZVERS,  " parameter ; version
      W_ZGRUP      LIKE ZTHR_PCP01-ZGRUP,  " parameter ; work type
      W_ZGTXT      LIKE ZTHR_PCP01-ZGTXT.  " parameter ; work type name

DATA: W_FNAME      LIKE  HELP_INFO-FIELDNAME,
      W_TABIX      LIKE  SY-TABIX,
      W_FLDVL      LIKE  HELP_INFO-FLDVALUE.
