*&---------------------------------------------------------------------*
*& Include MZAHR0001TOP                                                *
*&                                                                     *
*&---------------------------------------------------------------------*
PROGRAM SAPMZAHR0001 MESSAGE-ID ZMHR.

TABLES: ZTHR_WTMNG,
        T512W,
        T512T.

CONTROLS: TC9000 TYPE TABLEVIEW USING SCREEN 9000.
*
DATA: BEGIN OF IT_WTMNG OCCURS 0.
      INCLUDE STRUCTURE ZTHR_WTMNG.
DATA: CHKBX,
      STATUS.
DATA: END OF IT_WTMNG.
DATA: TMP_WTMNG LIKE IT_WTMNG OCCURS 0 WITH HEADER LINE,
      DEL_WTMNG LIKE IT_WTMNG OCCURS 0 WITH HEADER LINE,
      CMP_WTMNG LIKE IT_WTMNG OCCURS 0 WITH HEADER LINE.
*
DATA: FIELD_LISTS  LIKE HELP_VALUE OCCURS 3 WITH HEADER LINE,
      SELECT_VALUE LIKE HELP_VTAB OCCURS 3 WITH HEADER LINE,
      DYNPFIELDS   LIKE STANDARD TABLE OF DYNPREAD WITH HEADER LINE.
DATA: BEGIN OF VALUETAB OCCURS 20,
      VALUE      LIKE HELP_VTAB-VALUE.
DATA: END OF VALUETAB.
*
DATA: W_FLAGS,
      W_MODES       TYPE C VALUE 'D',
      W_ANSWER.
*
DATA: W_ZFORM       LIKE ZTHR_WTMNG-ZFORM,
      W_LGART       LIKE ZTHR_WTMNG-LGART,
      W_LGTXT       LIKE ZTHR_WTMNG-LGTXT,
      W_ZCOLN       LIKE ZTHR_WTMNG-ZCOLN,
      W_ZPRNT       LIKE ZTHR_WTMNG-ZPRNT.

DATA: T_ZCOLN       LIKE ZTHR_WTMNG-ZCOLN,
      T_TOLIN       TYPE I.
