REPORT ZRHR_BEN_0168.
*
  TABLES: PA0021,
          PA0106,
          PA0171,
          ITCSY,
          RPBENDBF,
          *RPBENDBF,
          RPBEN_DB.

  FIELD-SYMBOLS <FS>.
*
  DATA: IT_RPBEN LIKE RPBEN_DB OCCURS 0 WITH HEADER LINE,
        IT_BENEF LIKE RPBENDBF OCCURS 0 WITH HEADER LINE,
        IT_ERROR LIKE RPBENERR OCCURS 0 WITH HEADER LINE.

  DATA: ST_BENEF LIKE RPBENEEDAT.
*
  DATA: W_PERNR       LIKE PA0171-PERNR,
        W_BEGDA       LIKE PA0171-BEGDA,
        W_ENDDA       LIKE PA0171-ENDDA,
        W_WAERS       LIKE PA0008-WAERS,
        W_PLTYP       LIKE PA0168-PLTYP,
        W_CONTI       LIKE RPBENDBF-CONTINGENT,
        W_TEMPF(5),
        W_CURRC(20).

  DATA: W_FNAME(20).
*&---------------------------------------------------------------------*
*&                 FORM GET_INSURE_PLAN
*&---------------------------------------------------------------------*
FORM GET_INSURE_PLAN TABLES INTTAB STRUCTURE ITCSY
                            OUTTAB STRUCTURE ITCSY.
  LOOP AT INTTAB.
    CASE SY-TABIX.
      WHEN 1. W_PERNR = INTTAB-VALUE.
        CLEAR PA0171.
        SELECT SINGLE BAREA INTO PA0171-BAREA
          FROM PA0171 WHERE PERNR = INTTAB-VALUE.
      WHEN 2.
        W_BEGDA+(4) = INTTAB-VALUE+6(4).
        W_BEGDA+4(2) = INTTAB-VALUE+(2).
        W_BEGDA+6(2) = INTTAB-VALUE+3(2).
      WHEN 3.
        W_ENDDA+(4) = INTTAB-VALUE+6(4).
        W_ENDDA+4(2) = INTTAB-VALUE+(2).
        W_ENDDA+6(2) = INTTAB-VALUE+3(2).
      WHEN 4. W_WAERS = INTTAB-VALUE.
      WHEN 5. W_PLTYP = INTTAB-VALUE.
    ENDCASE.
  ENDLOOP.
*
  CALL FUNCTION 'HR_BEN_READ_INSURANCE_PLANS'
    EXPORTING
      PERNR                  = W_PERNR
      BAREA                  = PA0171-BAREA
      BEGDA                  = W_BEGDA
      ENDDA                  = W_ENDDA
      DESIRED_CURRENCY       = W_WAERS
      REACTION               = 'N'
    TABLES
      EX_INSU_PLANS          = IT_RPBEN
      ERROR_TABLE            = IT_ERROR.
*
  CASE W_PLTYP.
    WHEN 'ADD'.    W_PLTYP = 'BLIF'.
    WHEN 'BLIF'.   W_PLTYP = 'ADD'.
    WHEN 'CLIF'.   W_PLTYP = 'LTD'.
    WHEN 'LTD'.    W_PLTYP = 'OLIF'.
    WHEN 'OLIF'.   W_PLTYP = 'SLIF'.
    WHEN 'SLIF'.   W_PLTYP = 'CLIF'.
  ENDCASE.
*
  CLEAR IT_RPBEN.
  READ TABLE IT_RPBEN WITH KEY PLTYP = W_PLTYP.
*
  LOOP AT OUTTAB.
    CLEAR W_FNAME.
    CONCATENATE 'IT_RPBEN-' OUTTAB-NAME INTO W_FNAME.
    ASSIGN (W_FNAME) TO <FS>.
    CASE OUTTAB-NAME.
      WHEN 'BEGDA' OR 'ENDDA'.
        WRITE <FS> TO OUTTAB-VALUE MM/DD/YYYY.
      WHEN 'COVAM' OR 'EECST'.
        CLEAR W_CURRC.
        WRITE <FS> TO W_CURRC CURRENCY 'USD'.
        OUTTAB-VALUE = W_CURRC.
      WHEN 'ERCST' OR 'BNCST'.
        CLEAR W_CURRC.
        IF <FS> > 0.
          WRITE <FS> TO W_CURRC CURRENCY 'USD'.
          OUTTAB-VALUE = W_CURRC.
        ELSE.
          OUTTAB-VALUE = <FS>.
        ENDIF.
      WHEN OTHERS.
        OUTTAB-VALUE = <FS>.
    ENDCASE.
    MODIFY OUTTAB. CLEAR OUTTAB.
  ENDLOOP.
*
  IF W_PLTYP = 'LTD'.
    OUTTAB-VALUE = IT_RPBEN-TXT_PLAN.
    MODIFY OUTTAB TRANSPORTING VALUE WHERE NAME = 'TXT_PLTYPE'.
  ENDIF.
ENDFORM.
*&---------------------------------------------------------------------*
*&                 FORM GET_BENEFICIARIES
*&---------------------------------------------------------------------*
FORM GET_BENEFICIARIES TABLES INTTAB STRUCTURE ITCSY
                              OUTTAB STRUCTURE ITCSY.
  LOOP AT INTTAB.
    CASE SY-TABIX.
      WHEN 1.
        W_PERNR = INTTAB-VALUE.
      WHEN 2.
        W_BEGDA+(4) = INTTAB-VALUE+6(4).
        W_BEGDA+4(2) = INTTAB-VALUE+(2).
        W_BEGDA+6(2) = INTTAB-VALUE+3(2).
      WHEN 3.
        W_ENDDA+(4) = INTTAB-VALUE+6(4).
        W_ENDDA+4(2) = INTTAB-VALUE+(2).
        W_ENDDA+6(2) = INTTAB-VALUE+3(2).
      WHEN 4.
        W_PLTYP = INTTAB-VALUE.
      WHEN 5.
        W_CONTI = INTTAB-VALUE.
    ENDCASE.
  ENDLOOP.
*
  CLEAR PA0171.
  SELECT SINGLE BAREA BENGR BSTAT
    INTO (PA0171-BAREA, PA0171-BENGR, PA0171-BSTAT)
    FROM PA0171 WHERE PERNR = W_PERNR.
*
  ST_BENEF-PERNR = W_PERNR.
  ST_BENEF-BAREA = PA0171-BAREA.
  ST_BENEF-BENGR = PA0171-BENGR.
  ST_BENEF-BSTAT = PA0171-BSTAT.
*
  CALL FUNCTION 'HR_BEN_READ_BENEFICIARIES'
    EXPORTING
      EE_BENEFIT_DATA       = ST_BENEF
      BPCAT                 = 'B'
      PLTYP                 = W_PLTYP
      BEGDA                 = W_BEGDA
      ENDDA                 = W_ENDDA
      REACTION              = 'N'
    TABLES
      EXISTING_BEN          = IT_BENEF
      ERROR_TABLE           = IT_ERROR.
*
  DELETE IT_BENEF WHERE CONTINGENT <> W_CONTI.
*
  LOOP AT IT_BENEF.
    CASE SY-TABIX.
      WHEN 1.
        WRITE IT_BENEF-BEGDA TO OUTTAB-VALUE MM/DD/YYYY.
        MODIFY OUTTAB TRANSPORTING VALUE WHERE NAME = 'OUTVA1'.
        OUTTAB-VALUE = IT_BENEF-BEN_NAME.
        MODIFY OUTTAB TRANSPORTING VALUE WHERE NAME = 'OUTVA2'.
        OUTTAB-VALUE = IT_BENEF-RELATION.
        MODIFY OUTTAB TRANSPORTING VALUE WHERE NAME = 'OUTVA3'.
        W_TEMPF = IT_BENEF-BEN_PCT.
        OUTTAB-VALUE = W_TEMPF.
        MODIFY OUTTAB TRANSPORTING VALUE WHERE NAME = 'OUTVA4'.
        W_TEMPF = SY-TABIX.
        OUTTAB-VALUE = W_TEMPF.
        MODIFY OUTTAB TRANSPORTING VALUE WHERE NAME = 'TFILL'.
      WHEN 2.
        WRITE IT_BENEF-BEGDA TO OUTTAB-VALUE MM/DD/YYYY.
        MODIFY OUTTAB TRANSPORTING VALUE WHERE NAME = 'OUTVA5'.
        OUTTAB-VALUE = IT_BENEF-BEN_NAME.
        MODIFY OUTTAB TRANSPORTING VALUE WHERE NAME = 'OUTVA6'.
        OUTTAB-VALUE = IT_BENEF-RELATION.
        MODIFY OUTTAB TRANSPORTING VALUE WHERE NAME = 'OUTVA7'.
        W_TEMPF = IT_BENEF-BEN_PCT.
        OUTTAB-VALUE = W_TEMPF.
        MODIFY OUTTAB TRANSPORTING VALUE WHERE NAME = 'OUTVA8'.
        W_TEMPF = SY-TABIX.
        OUTTAB-VALUE = W_TEMPF.
        MODIFY OUTTAB TRANSPORTING VALUE WHERE NAME = 'TFILL'.
      WHEN 3.
        WRITE IT_BENEF-BEGDA TO OUTTAB-VALUE MM/DD/YYYY.
        MODIFY OUTTAB TRANSPORTING VALUE WHERE NAME = 'OUTVA9'.
        OUTTAB-VALUE = IT_BENEF-BEN_NAME.
        MODIFY OUTTAB TRANSPORTING VALUE WHERE NAME = 'OUTVA10'.
        OUTTAB-VALUE = IT_BENEF-RELATION.
        MODIFY OUTTAB TRANSPORTING VALUE WHERE NAME = 'OUTVA11'.
        W_TEMPF = IT_BENEF-BEN_PCT.
        OUTTAB-VALUE = W_TEMPF.
        MODIFY OUTTAB TRANSPORTING VALUE WHERE NAME = 'OUTVA12'.
        W_TEMPF = SY-TABIX.
        OUTTAB-VALUE = W_TEMPF.
        MODIFY OUTTAB TRANSPORTING VALUE WHERE NAME = 'TFILL'.
      WHEN 4.
        WRITE IT_BENEF-BEGDA TO OUTTAB-VALUE MM/DD/YYYY.
        MODIFY OUTTAB TRANSPORTING VALUE WHERE NAME = 'OUTVA13'.
        OUTTAB-VALUE = IT_BENEF-BEN_NAME.
        MODIFY OUTTAB TRANSPORTING VALUE WHERE NAME = 'OUTVA14'.
        OUTTAB-VALUE = IT_BENEF-RELATION.
        MODIFY OUTTAB TRANSPORTING VALUE WHERE NAME = 'OUTVA15'.
        W_TEMPF = IT_BENEF-BEN_PCT.
        OUTTAB-VALUE = W_TEMPF.
        MODIFY OUTTAB TRANSPORTING VALUE WHERE NAME = 'OUTVA16'.
        W_TEMPF = SY-TABIX.
        OUTTAB-VALUE = W_TEMPF.
        MODIFY OUTTAB TRANSPORTING VALUE WHERE NAME = 'TFILL'.
      WHEN 5.
        WRITE IT_BENEF-BEGDA TO OUTTAB-VALUE MM/DD/YYYY.
        MODIFY OUTTAB TRANSPORTING VALUE WHERE NAME = 'OUTVA17'.
        OUTTAB-VALUE = IT_BENEF-BEN_NAME.
        MODIFY OUTTAB TRANSPORTING VALUE WHERE NAME = 'OUTVA18'.
        OUTTAB-VALUE = IT_BENEF-RELATION.
        MODIFY OUTTAB TRANSPORTING VALUE WHERE NAME = 'OUTVA19'.
        W_TEMPF = IT_BENEF-BEN_PCT.
        OUTTAB-VALUE = W_TEMPF.
        MODIFY OUTTAB TRANSPORTING VALUE WHERE NAME = 'OUTVA20'.
        W_TEMPF = SY-TABIX.
        OUTTAB-VALUE = W_TEMPF.
        MODIFY OUTTAB TRANSPORTING VALUE WHERE NAME = 'TFILL'.
    ENDCASE.
  ENDLOOP.
*
  IF SY-SUBRC <> 0.
    OUTTAB-VALUE = '0'.
    MODIFY OUTTAB TRANSPORTING VALUE WHERE NAME = 'TFILL'.
  ENDIF.
ENDFORM.
