REPORT ZRHR_BEN_0021.
*
  TABLES: PA0021,
          PA0106,
          ITCSY.

  DATA: W_FULNM(30).
*&---------------------------------------------------------------------*
*&                 FORM GET_FAMILY_INFO
*&---------------------------------------------------------------------*
FORM GET_FAMILY_INFO TABLES INTTAB STRUCTURE ITCSY
                            OUTTAB STRUCTURE ITCSY.
  READ TABLE INTTAB INDEX 1.
  CLEAR PA0021.
  SELECT SUBTY FGBDT FAVOR FANAM
    INTO (PA0021-SUBTY, PA0021-FGBDT, PA0021-FAVOR, PA0021-FANAM)
    FROM PA0021 WHERE PERNR = INTTAB-VALUE
                  AND SUBTY IN ('1', '2')
                  AND ENDDA = '99991231'.
    CLEAR W_FULNM.
    CONCATENATE PA0021-FAVOR PA0021-FANAM INTO W_FULNM
                SEPARATED BY SPACE.
    CASE PA0021-SUBTY.
      WHEN '1'.
        READ TABLE OUTTAB INDEX 1.
        OUTTAB-VALUE = 'Spouse'.
        MODIFY OUTTAB INDEX 1.
        READ TABLE OUTTAB INDEX 3.
        OUTTAB-VALUE = W_FULNM.
        MODIFY OUTTAB INDEX 3.
        READ TABLE OUTTAB INDEX 5.
        WRITE PA0021-FGBDT TO OUTTAB-VALUE MM/DD/YYYY.
        MODIFY OUTTAB INDEX 5.
      WHEN '2'.
        READ TABLE OUTTAB INDEX 2.
        OUTTAB-VALUE = 'Child'.
        MODIFY OUTTAB INDEX 2.
        READ TABLE OUTTAB INDEX 4.
        OUTTAB-VALUE = W_FULNM.
        MODIFY OUTTAB INDEX 4.
        READ TABLE OUTTAB INDEX 6.
        WRITE PA0021-FGBDT TO OUTTAB-VALUE MM/DD/YYYY.
        MODIFY OUTTAB INDEX 6.
    ENDCASE.
  ENDSELECT.
*
  READ TABLE INTTAB INDEX 1.
  CLEAR PA0106.
  SELECT SUBTY PERID INTO (PA0106-SUBTY, PA0106-PERID)
    FROM PA0106 WHERE PERNR = INTTAB-VALUE
                  AND SUBTY IN ('1', '2')
                  AND ENDDA = '99991231'.
    CASE PA0106-SUBTY.
      WHEN '1'.
        READ TABLE OUTTAB INDEX 7.
        OUTTAB-VALUE = PA0106-PERID.
        MODIFY OUTTAB INDEX 7.
      WHEN '2'.
        READ TABLE OUTTAB INDEX 8.
        OUTTAB-VALUE = PA0106-PERID.
        MODIFY OUTTAB INDEX 8.
    ENDCASE.
  ENDSELECT.
ENDFORM.
