
DATA: UPD_ICDTXT_ZIBLINOU        TYPE C.
DATA: BEGIN OF ICDTXT_ZIBLINOU        OCCURS 20.
        INCLUDE STRUCTURE CDTXT.
DATA: END OF ICDTXT_ZIBLINOU       .

TABLES: *ZTBLINOU                      , ZTBLINOU                      .
DATA: UPD_ZTBLINOU                       TYPE C.

