
DATA: UPD_ICDTXT_ZTBLINRTMP      TYPE C.
DATA: BEGIN OF ICDTXT_ZTBLINRTMP      OCCURS 20.
        INCLUDE STRUCTURE CDTXT.
DATA: END OF ICDTXT_ZTBLINRTMP     .

TABLES: *ZTBLINR_TMP                   , ZTBLINR_TMP                   .
DATA: UPD_ZTBLINR_TMP                    TYPE C.

