
DATA: UPD_ICDTXT_ZTIMIMG00       TYPE C.
DATA: BEGIN OF ICDTXT_ZTIMIMG00       OCCURS 20.
        INCLUDE STRUCTURE CDTXT.
DATA: END OF ICDTXT_ZTIMIMG00      .

TABLES: *ZTIMIMG00                     , ZTIMIMG00                     .
DATA: UPD_ZTIMIMG00                      TYPE C.

