
DATA: UPD_ICDTXT_ZTIMIMG02       TYPE C.
DATA: BEGIN OF ICDTXT_ZTIMIMG02       OCCURS 20.
        INCLUDE STRUCTURE CDTXT.
DATA: END OF ICDTXT_ZTIMIMG02      .

TABLES: *ZTIMIMG02                     , ZTIMIMG02                     .
DATA: UPD_ZTIMIMG02                      TYPE C.

