
DATA: UPD_ICDTXT_ZTIMIMGTX       TYPE C.
DATA: BEGIN OF ICDTXT_ZTIMIMGTX       OCCURS 20.
        INCLUDE STRUCTURE CDTXT.
DATA: END OF ICDTXT_ZTIMIMGTX      .

TABLES: *ZTIMIMGTX                     , ZTIMIMGTX                     .
DATA: UPD_ZTIMIMGTX                      TYPE C.

