
DATA: UPD_ICDTXT_ZTIDSHSD        TYPE C.
DATA: BEGIN OF ICDTXT_ZTIDSHSD        OCCURS 20.
        INCLUDE STRUCTURE CDTXT.
DATA: END OF ICDTXT_ZTIDSHSD       .

TABLES: *ZTIDSHSD                      , ZTIDSHSD                      .
DATA: UPD_ZTIDSHSD                       TYPE C.

