
DATA: UPD_ICDTXT_ZTIMIMG13       TYPE C.
DATA: BEGIN OF ICDTXT_ZTIMIMG13       OCCURS 20.
        INCLUDE STRUCTURE CDTXT.
DATA: END OF ICDTXT_ZTIMIMG13      .

TABLES: *ZTIMIMG13                     , ZTIMIMG13                     .
DATA: UPD_ZTIMIMG13                      TYPE C.

