DATA: OBJECTID                TYPE CDHDR-OBJECTID,
      TCODE                   TYPE CDHDR-TCODE,
      PLANNED_CHANGE_NUMBER   TYPE CDHDR-PLANCHNGNR,
      UTIME                   TYPE CDHDR-UTIME,
      UDATE                   TYPE CDHDR-UDATE,
      USERNAME                TYPE CDHDR-USERNAME,
      CDOC_PLANNED_OR_REAL    TYPE CDHDR-CHANGE_IND,
      CDOC_UPD_OBJECT         TYPE CDHDR-CHANGE_IND VALUE 'U',
      CDOC_NO_CHANGE_POINTERS TYPE CDHDR-CHANGE_IND.

