*&---------------------------------------------------------------------*
*& Report  ZEXIMGDOWNUP                                                *
*&---------------------------------------------------------------------*
*&---------------------------------------------------------------------*
REPORT ZRIMIMGUPDOWN NO STANDARD PAGE HEADING
                     LINE-SIZE 101
                     MESSAGE-ID ZEX.

*----------------------------------------------------------------------*
*  TABLE DEFINE
*----------------------------------------------------------------------*
TABLES: ZTIMIMG00,
        ZTIMIMG01,
        ZTIMIMG02,
        ZTIMIMG03,
        ZTIMIMG04,
        ZTIMIMG05,
        ZTIMIMG06,
        ZTIMIMG07,
        ZTIMIMG08,
        ZTIMIMG09,
        ZTIMIMG10,
        ZTIMIMG11,
        ZTIMIMG12,
        ZTIMIMG13,
        ZTIMIMG17,
        ZTIMIMG18,
        ZTIMIMG19,
        ZTIMIMG20,
        ZTIMIMG21,
        ZTIMIMG22,
        ZTIMIMG23,
        ZTIMIMG24,
        ZTIMGTXT,
        ZTIEPORT,
        USR01.

*----------------------------------------------------------------------*
*  DATA                                                                *
*----------------------------------------------------------------------*
DATA: BEGIN OF IT_ZTIMIMG00  OCCURS 0.
      INCLUDE STRUCTURE ZTIMIMG00.
DATA: END OF IT_ZTIMIMG00.

DATA: BEGIN OF IT_ZTIMIMG01  OCCURS 0.
      INCLUDE STRUCTURE ZTIMIMG01.
DATA: END OF IT_ZTIMIMG01.

DATA: BEGIN OF IT_ZTIMIMG02  OCCURS 0.
      INCLUDE STRUCTURE ZTIMIMG02.
DATA: END OF IT_ZTIMIMG02.

DATA: BEGIN OF IT_ZTIMIMG03  OCCURS 0.
      INCLUDE STRUCTURE ZTIMIMG03.
DATA: END OF IT_ZTIMIMG03.

DATA: BEGIN OF IT_ZTIMIMG04  OCCURS 0.
      INCLUDE STRUCTURE ZTIMIMG04.
DATA: END OF IT_ZTIMIMG04.

DATA: BEGIN OF IT_ZTIMIMG05  OCCURS 0.
      INCLUDE STRUCTURE ZTIMIMG05.
DATA: END OF IT_ZTIMIMG05.

DATA: BEGIN OF IT_ZTIMIMG06  OCCURS 0.
      INCLUDE STRUCTURE ZTIMIMG06.
DATA: END OF IT_ZTIMIMG06.

DATA: BEGIN OF IT_ZTIMIMG07  OCCURS 0.
      INCLUDE STRUCTURE ZTIMIMG07.
DATA: END OF IT_ZTIMIMG07.

DATA: BEGIN OF IT_ZTIMIMG08  OCCURS 0.
      INCLUDE STRUCTURE ZTIMIMG08.
DATA: END OF IT_ZTIMIMG08.

DATA: BEGIN OF IT_ZTIMIMG09  OCCURS 0.
      INCLUDE STRUCTURE ZTIMIMG09.
DATA: END OF IT_ZTIMIMG09.

DATA: BEGIN OF IT_ZTIMIMG10  OCCURS 0.
      INCLUDE STRUCTURE ZTIMIMG10.
DATA: END OF IT_ZTIMIMG10.

DATA: BEGIN OF IT_ZTIMIMG11  OCCURS 0.
      INCLUDE STRUCTURE ZTIMIMG11.
DATA: END OF IT_ZTIMIMG11.

DATA: BEGIN OF IT_ZTIMIMG12  OCCURS 0.
      INCLUDE STRUCTURE ZTIMIMG12.
DATA: END OF IT_ZTIMIMG12.

DATA: BEGIN OF IT_ZTIMIMG13  OCCURS 0.
      INCLUDE STRUCTURE ZTIMIMG13.
DATA: END OF IT_ZTIMIMG13.

DATA: BEGIN OF IT_ZTIMIMG17  OCCURS 0.
      INCLUDE STRUCTURE ZTIMIMG17.
DATA: END OF IT_ZTIMIMG17.

DATA: BEGIN OF IT_ZTIMIMG18  OCCURS 0.
      INCLUDE STRUCTURE ZTIMIMG18.
DATA: END OF IT_ZTIMIMG18.

DATA: BEGIN OF IT_ZTIMIMG19  OCCURS 0.
      INCLUDE STRUCTURE ZTIMIMG19.
DATA: END OF IT_ZTIMIMG19.

DATA: BEGIN OF IT_ZTIMIMG20  OCCURS 0.
      INCLUDE STRUCTURE ZTIMIMG20.
DATA: END OF IT_ZTIMIMG20.

DATA: BEGIN OF IT_ZTIMIMG21  OCCURS 0.
      INCLUDE STRUCTURE ZTIMIMG21.
DATA: END OF IT_ZTIMIMG21.

DATA: BEGIN OF IT_ZTIMIMG22  OCCURS 0.
      INCLUDE STRUCTURE ZTIMIMG22.
DATA: END OF IT_ZTIMIMG22.

DATA: BEGIN OF IT_ZTIMIMG23  OCCURS 0.
      INCLUDE STRUCTURE ZTIMIMG23.
DATA: END OF IT_ZTIMIMG23.

DATA: BEGIN OF IT_ZTIMIMG24  OCCURS 0.
      INCLUDE STRUCTURE ZTIMIMG24.
DATA: END OF IT_ZTIMIMG24.

DATA: BEGIN OF IT_ZTIMGTXT  OCCURS 0.
      INCLUDE STRUCTURE ZTIMGTXT.
DATA: END OF IT_ZTIMGTXT.

DATA: BEGIN OF IT_ZTIEPORT OCCURS 0.
      INCLUDE STRUCTURE ZTIEPORT.
DATA: END OF IT_ZTIEPORT.

DATA:  BEGIN OF IT_TAB  OCCURS 0,
       TABNAME    LIKE  DD02T-TABNAME,
       DDTEXT     LIKE  DD02T-DDTEXT.
DATA:  END OF IT_TAB.

DATA:  BEGIN OF IT_SELECTED OCCURS 0,
       TABNAME    LIKE  DD02T-TABNAME.
DATA: END OF IT_SELECTED.

DATA:  BEGIN OF IT_TXT  OCCURS 0,
       MANDT       LIKE ZTIMIMG09-MANDT,
       STAWN       LIKE ZTIMIMG09-STAWN,
       ZFAPLDT(8)  TYPE C,
       ZFTEXTE     LIKE ZTIMIMG09-ZFTEXTE,
       ZFTEXTK     LIKE ZTIMIMG09-ZFTEXTK,
       ZFTXCD      LIKE ZTIMIMG09-ZFTXCD,
       ZFBASIC(5)  TYPE C,"LIKE ZTIMIMG09-ZFBASIC ,
       ZFEXEC(5)   TYPE C,"LIKE ZTIMIMG09-ZFEXEC  ,
       ZFSPECR(5)  TYPE C,"LIKE ZTIMIMG09-ZFTXCD,
       ZFIRLW      LIKE ZTIMIMG09-ZFIRLW ,
       ERNAM       LIKE ZTIMIMG09-ERNAM,
       CDAT(8)     TYPE C,
       UNAM        LIKE ZTIMIMG09-UNAM,
       UDAT(8)     TYPE C.
DATA: END OF IT_TXT.

DATA: W_FILENAME   LIKE RLGRAP-FILENAME,
      W_TABNAME    LIKE DD02T-TABNAME,
      MARKFIELD(1) TYPE C.

DATA: W_SELECTED_LINES  TYPE P.           " º±≈√ LINE COUNT

*----------------------------------------------------------------------*
* INITIALIZATION                                                       *
*----------------------------------------------------------------------*
INITIALIZATION.
   SET TITLEBAR 'ZEDU'.

*----------------------------------------------------------------------*
*  Start of Selection
*----------------------------------------------------------------------*
START-OF-SELECTION.
*  PERFORM P1000_READIMPORTFILE.
  PERFORM P1000_READ_TABLE.

*----------------------------------------------------------------------*
*  End of Selection
*----------------------------------------------------------------------*
END-OF-SELECTION.
  PERFORM P1000_WRITE_TABLE.

AT USER-COMMAND.
   CASE SY-UCOMM.
     WHEN 'DOWNLOAD'.
           PERFORM P2000_MULTI_SELECTION.
           IF W_SELECTED_LINES EQ 1.
              READ TABLE IT_SELECTED INDEX 1.
              PERFORM P2000_CREATE_DOWNFILE USING IT_SELECTED-TABNAME.
           ELSEIF W_SELECTED_LINES GT 1.
              MESSAGE E965.
           ELSEIF W_SELECTED_LINES EQ 0.
              MESSAGE S766.
              EXIT.
           ENDIF.

     WHEN 'UPLOAD'.
           PERFORM P2000_MULTI_SELECTION.
           IF W_SELECTED_LINES EQ 1.
              READ TABLE IT_SELECTED INDEX 1.
              PERFORM P2000_CREATE_UPFILE USING IT_SELECTED-TABNAME.
           ELSEIF W_SELECTED_LINES GT 1.
              MESSAGE E965.
           ELSEIF W_SELECTED_LINES EQ 0.
              MESSAGE S766.
              EXIT.
           ENDIF.
*------- Abbrechen (CNCL) ----------------------------------------------
    WHEN 'CNCL'.
      SET SCREEN 0.    LEAVE SCREEN.
*------- Suchen (SUCH) -------------------------------------------------
    WHEN 'SUCH'.
*------- Sortieren nach Feldbezeichnung (SORB) -------------------------
    WHEN 'SORB'.
*------- Sortieren nach Feldname (SORF) --------------------------------
    WHEN 'SORF'.
*------- Techn. Name ein/aus (TECH) ------------------------------------
    WHEN 'TECH'.
*------- Weiter suchen (WESU) ------------------------------------------
    WHEN 'WESU'.
    WHEN  OTHERS.
   ENDCASE.

*&---------------------------------------------------------------------*
*&      FORM  UPDATE_TABLE
*&---------------------------------------------------------------------*
FORM P2000_UPDATETABLE.

  IF SY-SUBRC NE 0.
    ROLLBACK WORK.
    MESSAGE E952(ZIM).
  ELSE.
    COMMIT WORK.
    MESSAGE I953(ZIM).
  ENDIF.

ENDFORM.                    " UPDATE_TABLE
*&---------------------------------------------------------------------*
*&      FORM  P3000_WRITE
*&---------------------------------------------------------------------*
FORM P3000_WRITE.

  LOOP AT IT_TAB.
  ENDLOOP.

ENDFORM.                    " P3000_WRITE.
*&---------------------------------------------------------------------*
*&      Form  P1000_READ_TABLE
*&---------------------------------------------------------------------*
FORM P1000_READ_TABLE.

  REFRESH IT_TAB.
  CLEAR   IT_TAB.

* IMG 00~24.
  SELECT DISTINCT *
    INTO CORRESPONDING FIELDS OF TABLE IT_TAB
    FROM DD02T
   WHERE TABNAME    GE 'ZTIMIMG00'
     AND TABNAME    LE 'ZTIMIMG24'
     AND DDLANGUAGE EQ 'E'
     AND AS4LOCAL   EQ 'A'.

* Port Code
  SELECT    DISTINCT *
  APPENDING CORRESPONDING FIELDS OF TABLE IT_TAB
    FROM    DD02T
   WHERE    TABNAME    IN ('ZTIEPORT', 'ZTIMGTXT')
     AND    DDLANGUAGE EQ 'E'
     AND    AS4LOCAL   EQ 'A'.

ENDFORM.                    " P1000_READ_TABLE
*&---------------------------------------------------------------------*
*&      Form  P1000_WRITE_TABLE
*&---------------------------------------------------------------------*
FORM P1000_WRITE_TABLE.

  SET TITLEBAR 'ZEDU'.
  SET PF-STATUS 'ZEDU'.

  PERFORM P2000_TITLE_WRITE.

  SORT IT_TAB BY TABNAME.
  LOOP AT IT_TAB.
    PERFORM P2000_LINE_WRITE.
  ENDLOOP.
  WRITE :/ SY-ULINE.

ENDFORM.                    " P1000_WRITE_TABLE
*&---------------------------------------------------------------------*
*&      Form  P2000_TITLE_WRITE
*&---------------------------------------------------------------------*
FORM P2000_TITLE_WRITE.

  SKIP 2.
  FORMAT COLOR COL_BACKGROUND INTENSIFIED OFF.
  WRITE :/40 '<<IMG Data Upload & Download>>' CENTERED
                COLOR COL_NEGATIVE INTENSIFIED OFF.
  SKIP 2.
  FORMAT COLOR COL_HEADING INTENSIFIED OFF.
  WRITE :/ SY-ULINE.
  WRITE :/ SY-VLINE NO-GAP, (99) 'Select Table' CENTERED NO-GAP,
           SY-VLINE.
  WRITE :/ SY-ULINE.

ENDFORM.                    " P2000_TITLE_WRITE
*&---------------------------------------------------------------------*
*&      Form  P2000_LINE_WRITE
*&---------------------------------------------------------------------*
FORM P2000_LINE_WRITE.

  FORMAT COLOR COL_NORMAL INTENSIFIED OFF.
  WRITE :/                                          SY-VLINE,
           MARKFIELD AS CHECKBOX COLOR COL_HEADING, SY-VLINE,
           IT_TAB-TABNAME COLOR COL_POSITIVE      , SY-VLINE,
           IT_TAB-DDTEXT                          , SY-VLINE.
  HIDE  :  IT_TAB.

ENDFORM.                    " P2000_LINE_WRITE
*&---------------------------------------------------------------------*
*&      Form  P2000_MULTI_SELECTION
*&---------------------------------------------------------------------*
FORM P2000_MULTI_SELECTION.

  REFRESH IT_SELECTED.
  CLEAR : IT_SELECTED,
          W_SELECTED_LINES.

  DO.
    CLEAR MARKFIELD.
    READ LINE SY-INDEX FIELD VALUE MARKFIELD.
    IF SY-SUBRC NE 0.   EXIT.   ENDIF.        " EXIT CHECKING
    IF ( MARKFIELD EQ 'x' ) OR ( MARKFIELD EQ 'X' ).
       MOVE : IT_TAB-TABNAME     TO IT_SELECTED-TABNAME.
       APPEND IT_SELECTED.
       ADD 1 TO W_SELECTED_LINES.
    ENDIF.
  ENDDO.

ENDFORM.                    " P2000_MULTI_SELECTION
*&---------------------------------------------------------------------*
*&      Form  P2000_CREATE_DOWNFILE
*&---------------------------------------------------------------------*
FORM P2000_CREATE_DOWNFILE USING    P_TABNAME.

  REFRESH : IT_ZTIMIMG00,  IT_ZTIMIMG01, IT_ZTIMIMG02, IT_ZTIMIMG03,
            IT_ZTIMIMG04,  IT_ZTIMIMG05, IT_ZTIMIMG06, IT_ZTIMIMG07,
            IT_ZTIMIMG08,  IT_ZTIMIMG09, IT_ZTIMIMG17, IT_ZTIMIMG24,
            IT_ZTIEPORT,   IT_ZTIMGTXT.
  CLEAR   : IT_ZTIMIMG00,  IT_ZTIMIMG01, IT_ZTIMIMG02, IT_ZTIMIMG03,
            IT_ZTIMIMG04,  IT_ZTIMIMG05, IT_ZTIMIMG06, IT_ZTIMIMG07,
            IT_ZTIMIMG08,  IT_ZTIMIMG09, IT_ZTIMIMG17, IT_ZTIMIMG24,
            IT_ZTIEPORT,   IT_ZTIMGTXT.
  CASE P_TABNAME.
    WHEN 'ZTIMIMG00'.
      SELECT *
        INTO CORRESPONDING FIELDS OF TABLE IT_ZTIMIMG00
        FROM (P_TABNAME).
      PERFORM P2000_DOWNLOAD  TABLES IT_ZTIMIMG00
                              USING  P_TABNAME.
    WHEN 'ZTIMIMG01'.
      SELECT *
        INTO CORRESPONDING FIELDS OF TABLE IT_ZTIMIMG01
        FROM ZTIMIMG01.
      PERFORM P2000_DOWNLOAD  TABLES IT_ZTIMIMG01
                              USING  P_TABNAME.
    WHEN 'ZTIMIMG02'.
      SELECT *
        INTO CORRESPONDING FIELDS OF TABLE IT_ZTIMIMG02
        FROM ZTIMIMG02.
      PERFORM P2000_DOWNLOAD  TABLES IT_ZTIMIMG02
                              USING  P_TABNAME.
    WHEN 'ZTIMIMG03'.
      SELECT *
        INTO CORRESPONDING FIELDS OF TABLE IT_ZTIMIMG03
        FROM ZTIMIMG03.
      PERFORM P2000_DOWNLOAD  TABLES IT_ZTIMIMG03
                              USING  P_TABNAME.
    WHEN 'ZTIMIMG04'.
      SELECT *
        INTO CORRESPONDING FIELDS OF TABLE IT_ZTIMIMG04
        FROM ZTIMIMG04.
      PERFORM P2000_DOWNLOAD  TABLES IT_ZTIMIMG04
                              USING  P_TABNAME.
    WHEN 'ZTIMIMG05'.
      SELECT *
        INTO CORRESPONDING FIELDS OF TABLE IT_ZTIMIMG05
        FROM ZTIMIMG05.
      PERFORM P2000_DOWNLOAD  TABLES IT_ZTIMIMG05
                              USING  P_TABNAME.
    WHEN 'ZTIMIMG06'.
      SELECT *
        INTO CORRESPONDING FIELDS OF TABLE IT_ZTIMIMG06
        FROM ZTIMIMG06.
      PERFORM P2000_DOWNLOAD  TABLES IT_ZTIMIMG06
                              USING  P_TABNAME.
    WHEN 'ZTIMIMG07'.
      SELECT *
        INTO CORRESPONDING FIELDS OF TABLE IT_ZTIMIMG07
        FROM ZTIMIMG07.
      PERFORM P2000_DOWNLOAD  TABLES IT_ZTIMIMG07
                              USING  P_TABNAME.
    WHEN 'ZTIMIMG08'.
      SELECT *
        INTO CORRESPONDING FIELDS OF TABLE IT_ZTIMIMG08
        FROM ZTIMIMG08.
      PERFORM P2000_DOWNLOAD  TABLES IT_ZTIMIMG08
                              USING  P_TABNAME.
    WHEN 'ZTIMIMG09'.
      SELECT *
        INTO CORRESPONDING FIELDS OF TABLE IT_ZTIMIMG09
        FROM ZTIMIMG09.
      PERFORM P2000_DOWNLOAD  TABLES IT_ZTIMIMG09
                              USING  P_TABNAME.
    WHEN 'ZTIMIMG10'.
      SELECT *
        INTO CORRESPONDING FIELDS OF TABLE IT_ZTIMIMG10
        FROM ZTIMIMG10.
      PERFORM P2000_DOWNLOAD  TABLES IT_ZTIMIMG10
                              USING  P_TABNAME.
    WHEN 'ZTIMIMG11'.
      SELECT *
        INTO CORRESPONDING FIELDS OF TABLE IT_ZTIMIMG11
        FROM ZTIMIMG11.
      PERFORM P2000_DOWNLOAD  TABLES IT_ZTIMIMG11
                              USING  P_TABNAME.
    WHEN 'ZTIMIMG12'.
      SELECT *
        INTO CORRESPONDING FIELDS OF TABLE IT_ZTIMIMG12
        FROM ZTIMIMG12.
      PERFORM P2000_DOWNLOAD  TABLES IT_ZTIMIMG12
                              USING  P_TABNAME.
    WHEN 'ZTIMIMG13'.
      SELECT *
        INTO CORRESPONDING FIELDS OF TABLE IT_ZTIMIMG13
        FROM ZTIMIMG13.
      PERFORM P2000_DOWNLOAD  TABLES IT_ZTIMIMG13
                              USING  P_TABNAME.
    WHEN 'ZTIMIMG17'.
      SELECT *
        INTO CORRESPONDING FIELDS OF TABLE IT_ZTIMIMG17
        FROM ZTIMIMG17.
      PERFORM P2000_DOWNLOAD  TABLES IT_ZTIMIMG17
                              USING  P_TABNAME.
    WHEN 'ZTIMIMG18'.
      SELECT *
        INTO CORRESPONDING FIELDS OF TABLE IT_ZTIMIMG18
        FROM ZTIMIMG18.
      PERFORM P2000_DOWNLOAD  TABLES IT_ZTIMIMG18
                              USING  P_TABNAME.
    WHEN 'ZTIMIMG19'.
      SELECT *
        INTO CORRESPONDING FIELDS OF TABLE IT_ZTIMIMG19
        FROM ZTIMIMG19.
      PERFORM P2000_DOWNLOAD  TABLES IT_ZTIMIMG19
                              USING  P_TABNAME.
    WHEN 'ZTIMIMG20'.
      SELECT *
        INTO CORRESPONDING FIELDS OF TABLE IT_ZTIMIMG20
        FROM ZTIMIMG20.
      PERFORM P2000_DOWNLOAD  TABLES IT_ZTIMIMG20
                              USING  P_TABNAME.
    WHEN 'ZTIMIMG21'.
      SELECT *
        INTO CORRESPONDING FIELDS OF TABLE IT_ZTIMIMG21
        FROM ZTIMIMG21.
      PERFORM P2000_DOWNLOAD  TABLES IT_ZTIMIMG21
                              USING  P_TABNAME.
    WHEN 'ZTIMIMG22'.
      SELECT *
        INTO CORRESPONDING FIELDS OF TABLE IT_ZTIMIMG22
        FROM ZTIMIMG22.
      PERFORM P2000_DOWNLOAD  TABLES IT_ZTIMIMG22
                              USING  P_TABNAME.
    WHEN 'ZTIMIMG23'.
      SELECT *
        INTO CORRESPONDING FIELDS OF TABLE IT_ZTIMIMG23
        FROM ZTIMIMG23.
      PERFORM P2000_DOWNLOAD  TABLES IT_ZTIMIMG23
                              USING  P_TABNAME.
    WHEN 'ZTIMIMG24'.
      SELECT *
        INTO CORRESPONDING FIELDS OF TABLE IT_ZTIMIMG24
        FROM ZTIMIMG24.
      PERFORM P2000_DOWNLOAD  TABLES IT_ZTIMIMG24
                              USING  P_TABNAME.
    WHEN 'ZTIEPORT'.
      SELECT *
        INTO CORRESPONDING FIELDS OF TABLE IT_ZTIEPORT
        FROM ZTIEPORT.
      PERFORM P2000_DOWNLOAD  TABLES IT_ZTIEPORT
                              USING  P_TABNAME.
    WHEN 'ZTIMGTXT'.
      SELECT *
        INTO CORRESPONDING FIELDS OF TABLE IT_ZTIMGTXT
        FROM ZTIMGTXT.
      PERFORM P2000_DOWNLOAD  TABLES IT_ZTIMGTXT
                              USING  P_TABNAME.
    WHEN OTHERS.
  ENDCASE.

ENDFORM.                    " P2000_CREATE_DOWNFILE
*&---------------------------------------------------------------------*
*&      Form  P2000_DOWNLOAD
*&---------------------------------------------------------------------*
FORM P2000_DOWNLOAD TABLES   P_TAB
                    USING    P_TABNAME.

  CLEAR : W_FILENAME.

  CONCATENATE 'C:\' P_TABNAME '.txt' INTO W_FILENAME.
  CALL FUNCTION 'DOWNLOAD'
       EXPORTING
            FILENAME = W_FILENAME
            FILETYPE = 'DAT'
       TABLES
            DATA_TAB = P_TAB.

ENDFORM.                    " P2000_DOWNLOAD

*&---------------------------------------------------------------------*
*&      Form  P2000_CREATE_UPFILE
*&---------------------------------------------------------------------*
FORM P2000_CREATE_UPFILE USING    P_TABNAME.

  REFRESH : IT_ZTIMIMG00,  IT_ZTIMIMG01, IT_ZTIMIMG02, IT_ZTIMIMG03,
            IT_ZTIMIMG04,  IT_ZTIMIMG05, IT_ZTIMIMG06, IT_ZTIMIMG07,
            IT_ZTIMIMG08,  IT_ZTIMIMG09, IT_ZTIMIMG17, IT_ZTIEPORT,
            IT_ZTIMGTXT.
  CLEAR   : IT_ZTIMIMG00,  IT_ZTIMIMG01, IT_ZTIMIMG02, IT_ZTIMIMG03,
            IT_ZTIMIMG04,  IT_ZTIMIMG05, IT_ZTIMIMG06, IT_ZTIMIMG07,
            IT_ZTIMIMG08,  IT_ZTIMIMG09, IT_ZTIMIMG17, IT_ZTIEPORT,
            IT_ZTIMGTXT.

  CASE P_TABNAME.
    WHEN 'ZTIMIMG00'.
      PERFORM P2000_UPLOAD    TABLES  IT_ZTIMIMG00
                              USING   P_TABNAME.
      MODIFY ZTIMIMG00   FROM TABLE   IT_ZTIMIMG00.

    WHEN 'ZTIMIMG01'.
      PERFORM P2000_UPLOAD    TABLES  IT_ZTIMIMG01
                              USING   P_TABNAME.
      MODIFY ZTIMIMG01   FROM TABLE   IT_ZTIMIMG01.

    WHEN 'ZTIMIMG02'.
      PERFORM P2000_UPLOAD    TABLES  IT_ZTIMIMG02
                              USING   P_TABNAME.
      MODIFY ZTIMIMG02   FROM TABLE   IT_ZTIMIMG02.

    WHEN 'ZTIMIMG03'.
      PERFORM P2000_UPLOAD    TABLES  IT_ZTIMIMG03
                              USING   P_TABNAME.
      MODIFY ZTIMIMG03   FROM TABLE   IT_ZTIMIMG03.

    WHEN 'ZTIMIMG04'.
      PERFORM P2000_UPLOAD    TABLES  IT_ZTIMIMG04
                              USING   P_TABNAME.
      MODIFY ZTIMIMG04   FROM TABLE   IT_ZTIMIMG04.

    WHEN 'ZTIMIMG05'.
      PERFORM P2000_UPLOAD    TABLES  IT_ZTIMIMG05
                              USING   P_TABNAME.
      MODIFY ZTIMIMG05   FROM TABLE   IT_ZTIMIMG05.

    WHEN 'ZTIMIMG06'.
      PERFORM P2000_UPLOAD    TABLES  IT_ZTIMIMG06
                              USING   P_TABNAME.
      MODIFY ZTIMIMG06   FROM TABLE   IT_ZTIMIMG06.

    WHEN 'ZTIMIMG07'.
      PERFORM P2000_UPLOAD    TABLES  IT_ZTIMIMG07
                              USING   P_TABNAME.
      MODIFY ZTIMIMG07   FROM TABLE   IT_ZTIMIMG07.

    WHEN 'ZTIMIMG08'.
      PERFORM P2000_UPLOAD    TABLES  IT_ZTIMIMG08
                              USING   P_TABNAME.
      MODIFY ZTIMIMG08   FROM TABLE   IT_ZTIMIMG08.

    WHEN 'ZTIMIMG09'.
      PERFORM P2000_UPLOAD    TABLES  IT_ZTIMIMG09
                              USING   P_TABNAME.
      MODIFY ZTIMIMG09   FROM TABLE   IT_ZTIMIMG09.


    WHEN 'ZTIEPORT'.
      PERFORM P2000_UPLOAD    TABLES  IT_ZTIEPORT
                              USING   P_TABNAME.
      MODIFY ZTIEPORT    FROM TABLE   IT_ZTIEPORT.

    WHEN 'ZTIMIMG10'.
      PERFORM P2000_UPLOAD    TABLES  IT_ZTIMIMG10
                              USING   P_TABNAME.
      MODIFY ZTIMIMG10   FROM TABLE   IT_ZTIMIMG10.

    WHEN 'ZTIMIMG11'.
      PERFORM P2000_UPLOAD    TABLES  IT_ZTIMIMG11
                              USING   P_TABNAME.
      MODIFY ZTIMIMG11   FROM TABLE   IT_ZTIMIMG11.

    WHEN 'ZTIMIMG12'.
      PERFORM P2000_UPLOAD    TABLES  IT_ZTIMIMG12
                              USING   P_TABNAME.
      MODIFY ZTIMIMG12   FROM TABLE   IT_ZTIMIMG12.

    WHEN 'ZTIMIMG13'.
      PERFORM P2000_UPLOAD    TABLES  IT_ZTIMIMG13
                              USING   P_TABNAME.
      MODIFY ZTIMIMG13   FROM TABLE   IT_ZTIMIMG13.

    WHEN 'ZTIMIMG17'.
      PERFORM P2000_UPLOAD    TABLES  IT_ZTIMIMG17
                              USING   P_TABNAME.
      MODIFY ZTIMIMG17   FROM TABLE   IT_ZTIMIMG17.

    WHEN 'ZTIMIMG18'.
      PERFORM P2000_UPLOAD    TABLES  IT_ZTIMIMG18
                              USING   P_TABNAME.
      MODIFY ZTIMIMG18   FROM TABLE   IT_ZTIMIMG18.

    WHEN 'ZTIMIMG19'.
      PERFORM P2000_UPLOAD    TABLES  IT_ZTIMIMG19
                              USING   P_TABNAME.
      MODIFY ZTIMIMG19   FROM TABLE   IT_ZTIMIMG19.

    WHEN 'ZTIMIMG20'.
      PERFORM P2000_UPLOAD    TABLES  IT_ZTIMIMG20
                              USING   P_TABNAME.
      MODIFY ZTIMIMG20   FROM TABLE   IT_ZTIMIMG20.

    WHEN 'ZTIMIMG21'.
      PERFORM P2000_UPLOAD    TABLES  IT_ZTIMIMG21
                              USING   P_TABNAME.
      MODIFY ZTIMIMG21   FROM TABLE   IT_ZTIMIMG21.

    WHEN 'ZTIMIMG22'.
      PERFORM P2000_UPLOAD    TABLES  IT_ZTIMIMG22
                              USING   P_TABNAME.
      MODIFY ZTIMIMG22   FROM TABLE   IT_ZTIMIMG22.

    WHEN 'ZTIMIMG23'.
      PERFORM P2000_UPLOAD    TABLES  IT_ZTIMIMG23
                              USING   P_TABNAME.
      MODIFY ZTIMIMG23   FROM TABLE   IT_ZTIMIMG23.

    WHEN 'ZTIMIMG24'.
      PERFORM P2000_UPLOAD    TABLES  IT_ZTIMIMG24
                              USING   P_TABNAME.
      MODIFY ZTIMIMG24   FROM TABLE   IT_ZTIMIMG24.

    WHEN 'ZTIMGTXT'.
      PERFORM P2000_UPLOAD    TABLES  IT_ZTIMGTXT
                              USING   P_TABNAME.
      MODIFY ZTIMGTXT    FROM TABLE   IT_ZTIMGTXT.
    WHEN OTHERS.
  ENDCASE.
  IF SY-SUBRC NE 0.
     ROLLBACK WORK.
     MESSAGE  E952(ZIM).
  ELSE.
     COMMIT WORK.
     MESSAGE  I953(ZIM).
  ENDIF.

ENDFORM.                    " P2000_CREATE_UPFILE
*&---------------------------------------------------------------------*
*&      Form  P2000_UPLOAD
*&---------------------------------------------------------------------*
FORM P2000_UPLOAD TABLES   P_TAB
                  USING    P_TABNAME.

  DATA : L_DATE_FORMAT(10)  TYPE  C.
  CLEAR : W_FILENAME.

  SELECT SINGLE * FROM USR01 WHERE BNAME EQ SY-UNAME.
  CASE USR01-DATFM.
     WHEN '1'.
        L_DATE_FORMAT = 'DD.MM.YYYY'.
     WHEN '2'.
        L_DATE_FORMAT = 'MM/DD/YYYY'.
     WHEN '3'.
        L_DATE_FORMAT = 'MM-DD-YYYY'.
     WHEN '4'.
        L_DATE_FORMAT = 'YYYY.MM.DD'.
     WHEN '5'.
        L_DATE_FORMAT = 'YYYY/MM/DD'.
     WHEN '6'.
        L_DATE_FORMAT = 'YYYY-MM-DD'.
  ENDCASE.

  CONCATENATE 'C:\' P_TABNAME '.TXT' INTO W_FILENAME.
  CALL FUNCTION 'WS_UPLOAD'
    EXPORTING
      FILENAME = W_FILENAME
      FILETYPE = 'DAT'
      DAT_D_FORMAT = L_DATE_FORMAT
    TABLES
      DATA_TAB = P_TAB.

  IF SY-SUBRC NE 0.
     MESSAGE E463(ZIM1) WITH W_FILENAME.
  ENDIF.

ENDFORM.                    " P2000_UPLOAD
