FUNCTION Z_CO_MONTH_VIEW_BY_IG.
*"----------------------------------------------------------------------
*"*"Local interface:
*"  EXPORTING
*"     VALUE(SELECT_VALUE)
*"----------------------------------------------------------------------
  DATA: BEGIN OF FIELDS OCCURS 50.
          INCLUDE STRUCTURE HELP_VALUE.
  DATA: END OF FIELDS.
  DATA: BEGIN OF VALUETAB OCCURS 50,
          LINE(80),
  END OF VALUETAB.

  __CLS FIELDS.__CLS VALUETAB.

* Fill the structure table
  FIELDS-TABNAME = 'ZHLPSTRC'.
  FIELDS-FIELDNAME = 'VALUE'.
  FIELDS-SELECTFLAG = 'X'.
  APPEND FIELDS.CLEAR FIELDS.


  FIELDS-TABNAME = 'ZHLPSTRC'.
  FIELDS-FIELDNAME = 'TEXT'.
  FIELDS-SELECTFLAG = ' '.
  APPEND FIELDS.CLEAR FIELDS.

* Fill the value table

  VALUETAB-LINE = '01'. APPEND VALUETAB.
  VALUETAB-LINE = 'January   '. APPEND VALUETAB.
  VALUETAB-LINE = '02'. APPEND VALUETAB.
  VALUETAB-LINE = 'February  '. APPEND VALUETAB.
  VALUETAB-LINE = '03'. APPEND VALUETAB.
  VALUETAB-LINE = 'March     '. APPEND VALUETAB.
  VALUETAB-LINE = '04'. APPEND VALUETAB.
  VALUETAB-LINE = 'April     '. APPEND VALUETAB.
  VALUETAB-LINE = '05'. APPEND VALUETAB.
  VALUETAB-LINE = 'May       '. APPEND VALUETAB.
  VALUETAB-LINE = '06'. APPEND VALUETAB.
  VALUETAB-LINE = 'June      '. APPEND VALUETAB.
  VALUETAB-LINE = '07'. APPEND VALUETAB.
  VALUETAB-LINE = 'July      '. APPEND VALUETAB.
  VALUETAB-LINE = '08'. APPEND VALUETAB.
  VALUETAB-LINE = 'August    '. APPEND VALUETAB.
  VALUETAB-LINE = '09'. APPEND VALUETAB.
  VALUETAB-LINE = 'September '. APPEND VALUETAB.
  VALUETAB-LINE = '10'. APPEND VALUETAB.
  VALUETAB-LINE = 'October   '. APPEND VALUETAB.
  VALUETAB-LINE = '11'. APPEND VALUETAB.
  VALUETAB-LINE = 'November  '. APPEND VALUETAB.
  VALUETAB-LINE = '12'. APPEND VALUETAB.
  VALUETAB-LINE = 'December  '. APPEND VALUETAB.

* Call the help value screen
  CALL FUNCTION 'HELP_VALUES_GET_WITH_TABLE'
       EXPORTING
            TITLE_IN_VALUES_LIST = 'Month list'
            TITEL                = 'Month'
       IMPORTING
            SELECT_VALUE         = SELECT_VALUE
       TABLES
            FIELDS               = FIELDS
            VALUETAB             = VALUETAB.

ENDFUNCTION.
