FUNCTION Z_FCO_MANAGEMENT_SKF.
*"----------------------------------------------------------------------
*"*"Local interface:
*"  IMPORTING
*"     VALUE(IM_PGMNO) LIKE  ZTCO_SKF_MANAGE-PGMNO
*"     VALUE(IM_KOKRS) LIKE  ZTCO_SKF_MANAGE-KOKRS
*"     VALUE(IM_GJAHR) LIKE  ZTCO_SKF_MANAGE-GJAHR
*"     VALUE(IM_PERBL) LIKE  ZTCO_SKF_MANAGE-PERBL
*"     VALUE(IM_PERBL_T) LIKE  ZTCO_SKF_MANAGE-PERBL OPTIONAL
*"     VALUE(IM_VERSN) LIKE  ZTCO_SKF_MANAGE-VERSN
*"     VALUE(IM_KOSTL_F) LIKE  CSKS-KOSTL OPTIONAL
*"     VALUE(IM_KOSTL_T) LIKE  CSKS-KOSTL OPTIONAL
*"     VALUE(IM_GNAME) LIKE  ZTCO_SKF_MANAGE-GNAME OPTIONAL
*"     VALUE(IM_PRZNR_F) LIKE  CBPR-PRZNR OPTIONAL
*"     VALUE(IM_PRZNR_T) LIKE  CBPR-PRZNR OPTIONAL
*"  EXPORTING
*"     VALUE(SUBRC) LIKE  SYST-SUBRC
*"----------------------------------------------------------------------


  TABLES ZTCO_SKF_MANAGE.
  DATA   LV_CNT      LIKE  COSP-PERBL.
  DATA   LV_PERCOUNT LIKE  COSP-PERBL.     "Period Counter


  IF IM_PERBL_T IS INITIAL.
    ZTCO_SKF_MANAGE-PGMNO = IM_PGMNO.
    ZTCO_SKF_MANAGE-KOKRS = IM_KOKRS.
    ZTCO_SKF_MANAGE-GJAHR = IM_GJAHR.
    ZTCO_SKF_MANAGE-PERBL = IM_PERBL.
    ZTCO_SKF_MANAGE-VERSN = IM_VERSN.
    IF IM_GNAME IS INITIAL.
      IF IM_PGMNO = 'ZCOA40'.
        ZTCO_SKF_MANAGE-KOSTL_F = IM_PRZNR_F.
        ZTCO_SKF_MANAGE-KOSTL_T = IM_PRZNR_T.
      ELSE.
        ZTCO_SKF_MANAGE-KOSTL_F = IM_KOSTL_F.
        ZTCO_SKF_MANAGE-KOSTL_T = IM_KOSTL_T.
      ENDIF.
    ELSE.
      ZTCO_SKF_MANAGE-GNAME = IM_GNAME.
    ENDIF.

    ZTCO_SKF_MANAGE-STATUS = 'O'.
    ZTCO_SKF_MANAGE-ERDAT = SY-DATUM.
    ZTCO_SKF_MANAGE-ERZET = SY-UZEIT.
    ZTCO_SKF_MANAGE-ERNAM = SY-UNAME.

    MODIFY ZTCO_SKF_MANAGE.
    IF SY-SUBRC <> 0.
      SUBRC = SY-SUBRC.
      EXIT.
    ENDIF.

  ELSE.
    CLEAR LV_PERCOUNT.
    LV_PERCOUNT = IM_PERBL_T - IM_PERBL + 1.
*     Period Counter : Set From-Period .
    CLEAR LV_CNT.
    LV_CNT = IM_PERBL.

    DO LV_PERCOUNT TIMES.
      ZTCO_SKF_MANAGE-PGMNO = IM_PGMNO.
      ZTCO_SKF_MANAGE-KOKRS = IM_KOKRS.
      ZTCO_SKF_MANAGE-GJAHR = IM_GJAHR.
      ZTCO_SKF_MANAGE-PERBL = LV_CNT.
      ZTCO_SKF_MANAGE-VERSN = IM_VERSN.

      IF IM_GNAME IS INITIAL.
        ZTCO_SKF_MANAGE-KOSTL_F = IM_KOSTL_F.
        ZTCO_SKF_MANAGE-KOSTL_T = IM_KOSTL_T.
      ELSE.
        ZTCO_SKF_MANAGE-GNAME = IM_GNAME.
      ENDIF.

      ZTCO_SKF_MANAGE-STATUS = 'O'.
      ZTCO_SKF_MANAGE-ERDAT = SY-DATUM.
      ZTCO_SKF_MANAGE-ERZET = SY-UZEIT.
      ZTCO_SKF_MANAGE-ERNAM = SY-UNAME.

      MODIFY ZTCO_SKF_MANAGE.
      IF SY-SUBRC <> 0.
        SUBRC = SY-SUBRC.
        EXIT.
      ENDIF.

*       Period Counter
      LV_CNT = LV_CNT + 1.
    ENDDO.
  ENDIF.


ENDFUNCTION.
