FUNCTION Z_FCO_POST_PA_PLANNING.
*"----------------------------------------------------------------------
*"*"Local interface:
*"  IMPORTING
*"     REFERENCE(OPERATINGCONCERN) LIKE  BAPI1167-OPERATINGCONCERN
*"       DEFAULT 'H201'
*"     REFERENCE(TYPEOFPA) LIKE  BAPI1167-TYPEOFPA DEFAULT '1'
*"     REFERENCE(TESTRUN) LIKE  BAPI1167-TESTRUN DEFAULT SPACE
*"     REFERENCE(IM_VRGAR) LIKE  CE3H201-VRGAR DEFAULT 'F'
*"     REFERENCE(IM_PERBL) LIKE  CE3H201-PERBL
*"     REFERENCE(IM_BUKRS) LIKE  CE4H201_ACCT-BUKRS DEFAULT 'H201'
*"     REFERENCE(IM_WERKS) LIKE  CE4H201_ACCT-WERKS
*"     REFERENCE(IM_PALEDGER) LIKE  CE3H201-PALEDGER DEFAULT '01'
*"     REFERENCE(IM_VERSI) LIKE  CE3H201-VERSI
*"     REFERENCE(IM_KNDNR) LIKE  CE4H201_ACCT-KNDNR
*"     REFERENCE(IM_ARTNR) LIKE  CE4H201_ACCT-ARTNR
*"     REFERENCE(IM_VKORG) LIKE  CE4H201_ACCT-VKORG
*"     REFERENCE(IM_VTWEG) LIKE  CE4H201_ACCT-VTWEG
*"     REFERENCE(IM_ABSMG) LIKE  CE3H201-ABSMG001
*"     REFERENCE(IM_ABSMG_ME) LIKE  CE4H201_ACCT-ABSMG_ME
*"     REFERENCE(IM_ERLOS) LIKE  CE3H201-ERLOS001
*"     REFERENCE(IM_REC_WAERS) LIKE  CE3H201-REC_WAERS
*"  EXCEPTIONS
*"      ERROR
*"----------------------------------------------------------------------


  DATA : IT_L_SELECTEDFIELDS  LIKE STANDARD TABLE OF BAPI_COPA_FIELD
                              WITH  HEADER LINE,
         IT_L_SELECTION	      LIKE STANDARD TABLE OF BAPI_COPA_SELECTION
                              WITH  HEADER LINE,
         IT_L_DATA	      LIKE STANDARD TABLE OF BAPI_COPA_DATA
                              WITH  HEADER LINE,
         IT_L_RETURN	      LIKE STANDARD TABLE OF BAPIRET2
                              WITH  HEADER LINE.

* Field-List
  CLEAR : IT_L_SELECTEDFIELDS, IT_L_SELECTEDFIELDS[].

  IT_L_SELECTEDFIELDS-FIELDNAME = 'VRGAR'.
  APPEND IT_L_SELECTEDFIELDS. CLEAR IT_L_SELECTEDFIELDS.
  IT_L_SELECTEDFIELDS-FIELDNAME = 'PERIO'.
  APPEND IT_L_SELECTEDFIELDS. CLEAR IT_L_SELECTEDFIELDS.
  IT_L_SELECTEDFIELDS-FIELDNAME = 'BUKRS'.
  APPEND IT_L_SELECTEDFIELDS. CLEAR IT_L_SELECTEDFIELDS.
  IT_L_SELECTEDFIELDS-FIELDNAME = 'WERKS'.
  APPEND IT_L_SELECTEDFIELDS. CLEAR IT_L_SELECTEDFIELDS.
  IT_L_SELECTEDFIELDS-FIELDNAME = 'PALEDGER'.
  APPEND IT_L_SELECTEDFIELDS. CLEAR IT_L_SELECTEDFIELDS.
  IT_L_SELECTEDFIELDS-FIELDNAME = 'VERSI'.
  APPEND IT_L_SELECTEDFIELDS. CLEAR IT_L_SELECTEDFIELDS.
  IT_L_SELECTEDFIELDS-FIELDNAME = 'KNDNR'.
  APPEND IT_L_SELECTEDFIELDS. CLEAR IT_L_SELECTEDFIELDS.
  IT_L_SELECTEDFIELDS-FIELDNAME = 'ARTNR'.
  APPEND IT_L_SELECTEDFIELDS. CLEAR IT_L_SELECTEDFIELDS.
  IT_L_SELECTEDFIELDS-FIELDNAME = 'VKORG'.
  APPEND IT_L_SELECTEDFIELDS. CLEAR IT_L_SELECTEDFIELDS.
  IT_L_SELECTEDFIELDS-FIELDNAME = 'VTWEG'.
  APPEND IT_L_SELECTEDFIELDS. CLEAR IT_L_SELECTEDFIELDS.
  IT_L_SELECTEDFIELDS-FIELDNAME = 'ABSMG'.
  APPEND IT_L_SELECTEDFIELDS. CLEAR IT_L_SELECTEDFIELDS.
  IT_L_SELECTEDFIELDS-FIELDNAME = 'ABSMG_ME'.
  APPEND IT_L_SELECTEDFIELDS. CLEAR IT_L_SELECTEDFIELDS.
  IT_L_SELECTEDFIELDS-FIELDNAME = 'ERLOS'.
  APPEND IT_L_SELECTEDFIELDS. CLEAR IT_L_SELECTEDFIELDS.


* Conv.
  DATA : LV_PALEDGER LIKE IM_PALEDGER.
  CLEAR LV_PALEDGER.
  CALL FUNCTION 'CONVERSION_EXIT_ALPHA_INPUT'
       EXPORTING
            INPUT  = IM_PALEDGER
       IMPORTING
            OUTPUT = LV_PALEDGER.

  DATA : LV_KNDNR(10).
  CLEAR LV_KNDNR.
  CALL FUNCTION 'CONVERSION_EXIT_ALPHA_INPUT'
       EXPORTING
            INPUT  = IM_KNDNR
       IMPORTING
            OUTPUT = LV_KNDNR.


* SELECTION
  CLEAR : IT_L_SELECTION, IT_L_SELECTION[].

  IT_L_SELECTION-FIELDNAME = 'VRGAR'.
  IT_L_SELECTION-SIGN      = 'I'.
  IT_L_SELECTION-OPTION    = 'EQ'.
  IT_L_SELECTION-LOW       = IM_VRGAR.
  APPEND IT_L_SELECTION.
  CLEAR IT_L_SELECTION.

  IT_L_SELECTION-FIELDNAME = 'PERIO'.
  IT_L_SELECTION-SIGN      = 'I'.
  IT_L_SELECTION-OPTION    = 'EQ'.
  IT_L_SELECTION-LOW       = IM_PERBL.
  APPEND IT_L_SELECTION.
  CLEAR IT_L_SELECTION.

  IT_L_SELECTION-FIELDNAME = 'BUKRS'.
  IT_L_SELECTION-SIGN      = 'I'.
  IT_L_SELECTION-OPTION    = 'EQ'.
  IT_L_SELECTION-LOW       = IM_BUKRS.
  APPEND IT_L_SELECTION.
  CLEAR IT_L_SELECTION.

  IT_L_SELECTION-FIELDNAME = 'WERKS'.
  IT_L_SELECTION-SIGN      = 'I'.
  IT_L_SELECTION-OPTION    = 'EQ'.
  IT_L_SELECTION-LOW       = IM_WERKS.
  APPEND IT_L_SELECTION.
  CLEAR IT_L_SELECTION.

  IT_L_SELECTION-FIELDNAME = 'PALEDGER'.
  IT_L_SELECTION-SIGN      = 'I'.
  IT_L_SELECTION-OPTION    = 'EQ'.
  IT_L_SELECTION-LOW       = LV_PALEDGER.
  APPEND IT_L_SELECTION.
  CLEAR IT_L_SELECTION.

  IT_L_SELECTION-FIELDNAME = 'VERSI'.
  IT_L_SELECTION-SIGN      = 'I'.
  IT_L_SELECTION-OPTION    = 'EQ'.
  IT_L_SELECTION-LOW       = IM_VERSI.
  APPEND IT_L_SELECTION.
  CLEAR IT_L_SELECTION.

  IT_L_SELECTION-FIELDNAME = 'KNDNR'.
  IT_L_SELECTION-SIGN      = 'I'.
  IT_L_SELECTION-OPTION    = 'EQ'.
  IT_L_SELECTION-LOW       = LV_KNDNR.
  APPEND IT_L_SELECTION.
  CLEAR IT_L_SELECTION.

  IT_L_SELECTION-FIELDNAME = 'ARTNR'.
  IT_L_SELECTION-SIGN      = 'I'.
  IT_L_SELECTION-OPTION    = 'EQ'.
  IT_L_SELECTION-LOW       = IM_ARTNR.
  APPEND IT_L_SELECTION.
  CLEAR IT_L_SELECTION.

  IT_L_SELECTION-FIELDNAME = 'VKORG'.
  IT_L_SELECTION-SIGN      = 'I'.
  IT_L_SELECTION-OPTION    = 'EQ'.
  IT_L_SELECTION-LOW       = IM_VKORG.
  APPEND IT_L_SELECTION.
  CLEAR IT_L_SELECTION.

  IT_L_SELECTION-FIELDNAME = 'VTWEG'.
  IT_L_SELECTION-SIGN      = 'I'.
  IT_L_SELECTION-OPTION    = 'EQ'.
  IT_L_SELECTION-LOW       = IM_VTWEG.
  APPEND IT_L_SELECTION.
  CLEAR IT_L_SELECTION.


* DATA.
  CLEAR : IT_L_DATA, IT_L_DATA[].

  IT_L_DATA-RECORD_ID = '000001'.
  IT_L_DATA-FIELDNAME = 'BUKRS'.
  IT_L_DATA-VALUE     = IM_BUKRS.
* CURRENCY
  APPEND IT_L_DATA.

  IT_L_DATA-RECORD_ID = '000001'.
  IT_L_DATA-FIELDNAME = 'WERKS'.
  IT_L_DATA-VALUE     = IM_WERKS.
* CURRENCY
  APPEND IT_L_DATA.

  IT_L_DATA-RECORD_ID = '000001'.
  IT_L_DATA-FIELDNAME = 'KNDNR'.
  IT_L_DATA-VALUE     = LV_KNDNR.
* CURRENCY
  APPEND IT_L_DATA.

  IT_L_DATA-RECORD_ID = '000001'.
  IT_L_DATA-FIELDNAME = 'PERIO'.
  IT_L_DATA-VALUE     = IM_PERBL.
* CURRENCY
  APPEND IT_L_DATA.

  IT_L_DATA-RECORD_ID = '000001'.
  IT_L_DATA-FIELDNAME = 'ARTNR'.
  IT_L_DATA-VALUE     = IM_ARTNR.
* CURRENCY
  APPEND IT_L_DATA.

  IT_L_DATA-RECORD_ID = '000001'.
  IT_L_DATA-FIELDNAME = 'VKORG'.
  IT_L_DATA-VALUE     = IM_VKORG.
* CURRENCY
  APPEND IT_L_DATA.

  IT_L_DATA-RECORD_ID = '000001'.
  IT_L_DATA-FIELDNAME = 'VTWEG'.
  IT_L_DATA-VALUE     = IM_VTWEG.
* CURRENCY
  APPEND IT_L_DATA.

  IT_L_DATA-RECORD_ID = '000001'.
  IT_L_DATA-FIELDNAME = 'VRGAR'.
  IT_L_DATA-VALUE     = IM_VRGAR.
* CURRENCY
  APPEND IT_L_DATA.

  IT_L_DATA-RECORD_ID = '000001'.
  IT_L_DATA-FIELDNAME = 'VERSI'.
  IT_L_DATA-VALUE     = IM_VERSI.
* CURRENCY
  APPEND IT_L_DATA.

  IT_L_DATA-RECORD_ID = '000001'.
  IT_L_DATA-FIELDNAME = 'PALEDGER'.
  IT_L_DATA-VALUE     = LV_PALEDGER.
* CURRENCY
  APPEND IT_L_DATA.

  IT_L_DATA-RECORD_ID = '000001'.
  IT_L_DATA-FIELDNAME = 'ABSMG'.
  IT_L_DATA-VALUE     = IM_ABSMG.
* CURRENCY
  APPEND IT_L_DATA.

  IT_L_DATA-RECORD_ID = '000001'.
  IT_L_DATA-FIELDNAME = 'ABSMG_ME'.
  IT_L_DATA-VALUE     = IM_ABSMG_ME.
* CURRENCY
  APPEND IT_L_DATA.

  IT_L_DATA-RECORD_ID = '000001'.
  IT_L_DATA-FIELDNAME = 'ERLOS'.
  IT_L_DATA-VALUE     = IM_ERLOS.
  IT_L_DATA-CURRENCY  = IM_REC_WAERS.
  APPEND IT_L_DATA.

* Call FM
  CALL FUNCTION 'BAPI_COPAPLANNING_POSTDATA'
       EXPORTING
            OPERATINGCONCERN     = OPERATINGCONCERN
            TYPEOFPROFITANALYSIS = TYPEOFPA
            TESTRUN              = SPACE
       TABLES
            SELECTEDFIELDS       = IT_L_SELECTEDFIELDS
            SELECTION            = IT_L_SELECTION
            DATA                 = IT_L_DATA
            RETURN               = IT_L_RETURN.

* internal message
* -> Errors In system : Do not Catch system errors

* Check
  CLEAR IT_L_RETURN.
  LOOP AT IT_L_RETURN .
*    IF IT_L_RETURN-TYPE CA 'EA'.
*      RAISE ERROR.
*    ENDIF.
    MESSAGE ID     IT_L_RETURN-ID
            TYPE   IT_L_RETURN-TYPE
            NUMBER IT_L_RETURN-NUMBER
       WITH IT_L_RETURN-MESSAGE_V1
            IT_L_RETURN-MESSAGE_V2
            IT_L_RETURN-MESSAGE_V3
            IT_L_RETURN-MESSAGE_V4.
  ENDLOOP.

* Commit
  COMMIT WORK AND WAIT.

ENDFUNCTION.
