FUNCTION Z_POPUP_TO_GET_DATE.
*"----------------------------------------------------------------------
*"*"Local interface:
*"       IMPORTING
*"             VALUE(FIELDNAME)
*"             VALUE(TABNAME)
*"             VALUE(TITEL)
*"             VALUE(VALUEIN) LIKE  SY-DATUM
*"       EXPORTING
*"             VALUE(ANSWER)
*"             VALUE(VALUEOUT) LIKE  SY-DATUM
*"       EXCEPTIONS
*"              FIELDNAME_NOT_FOUND
*"----------------------------------------------------------------------
* gpx
  DATA: ZAEHLER(3) TYPE N.
  DATA: ZAEHLER2(3) TYPE N.
  DATA: ZAEHLER3(3) TYPE N.
  ZAEHLER2 = 25.
  ANSWER = ' '.
 PERFORM GET_FIELD(RDDFIE00) USING TABNAME FIELDNAME SY-LANGU DFIES
                             SY-SUBRC.
  IF SY-SUBRC NE 0.
    RAISE FIELDNAME_NOT_FOUND.
  ENDIF.
  MOVE DFIES-VALEXI TO WERT.
  MOVE DFIES-SCRTEXT_L TO SPOP-TEXTLINE1.
  IF DFIES-SCRTEXT_L+20 NE SPACE OR SPOP-TEXTLINE1 EQ SPACE.
    MOVE DFIES-SCRTEXT_M TO SPOP-TEXTLINE1.
    IF SPOP-TEXTLINE1 EQ SPACE.
      MOVE DFIES-SCRTEXT_S TO SPOP-TEXTLINE1.
      IF SPOP-TEXTLINE1 EQ SPACE.
        MOVE SPACE TO SPOP-TEXTLINE1.
      ENDIF.
    ENDIF.
  ENDIF.
  MOVE SPOP-TEXTLINE1 TO HTEXTLINE.
  TRANSLATE HTEXTLINE USING ' ^'.
  IF HTEXTLINE CS '^^^'.
    MOVE SPOP-TEXTLINE1 TO HTEXTLINE.
    WRITE '.....................' TO SPOP-TEXTLINE1+SY-FDPOS.
  ENDIF.
  V_LENGTH = DFIES-OUTPUTLEN.
  CLEAR SPOP-VARVALUE1.
  ZAEHLER = DFIES-OUTPUTLEN + 45.
  IF ZAEHLER LT 60.
    ZAEHLER = 60.
  ENDIF.
  SHIFT HTEXTLINE BY 30 PLACES RIGHT.
  MOVE TITEL TO HTEXTLINE(30).
  CONDENSE HTEXTLINE.
  DATUM = VALUEIN.
  ASSIGN SPOP-VARFIELD(DFIES-OUTPUTLEN) TO <F>.
  IF DFIES-OUTPUTLEN LT 55.
    WRITE SPACE TO SPOP-VARFIELD+DFIES-OUTPUTLEN.
  ENDIF.
  IF ZAEHLER GT 70.
    ZAEHLER3 = ZAEHLER - 70.
    IF ZAEHLER3 GT 25.
      ZAEHLER3 = 25.
    ENDIF.
    ZAEHLER2 = ZAEHLER2 - ZAEHLER3.
    ZAEHLER = ZAEHLER - ZAEHLER3.
  ENDIF.
  CLEAR ANTWORT.
  CALL SCREEN 200 STARTING AT ZAEHLER2  6
                  ENDING   AT ZAEHLER 8.
* VALUEIN  = SPOP-VARFIELD.
  VALUEOUT = VDBEPP-DBEAR.
  IF ANTWORT = 'J'.CLEAR ANTWORT.ENDIF.
  ANSWER = ANTWORT.

ENDFUNCTION.
