DATA ref_P_1 TYPE ZSAPBF_S_CPRC_RATIO .
DATA ref_P_DUMMY1 TYPE PPC_ORD_INF .
DATA ref_SO_1 TYPE PPC_ORD_INF .
PARAMETER P_1 LIKE ref_P_1-CPRC_RATIO MODIF ID BL1 .
PARAMETER P_DUMMY1 LIKE ref_P_DUMMY1-ORDERID MODIF ID BL1 .
SELECT-OPTIONS: SO_1 FOR ref_SO_1-MATERIALNR MODIF ID BL1 .
