FUNCTION Z_FPP_GET_ALC_MEID.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  EXPORTING
*"     VALUE(FLAG) TYPE  ZRESULT
*"  TABLES
*"      I_CONTENTS STRUCTURE  ZSPPVM_ALC_TO_MEIN
*"----------------------------------------------------------------------
  DATA: WS_ZTPPVM LIKE ZTPPVM,
        L_INDEX LIKE SY-TABIX.
  LOOP AT I_CONTENTS.
    L_INDEX = SY-TABIX.

    WS_ZTPPVM-K04PLN = I_CONTENTS-K04PLN.
    WS_ZTPPVM-K04PDAT = I_CONTENTS-K04PDAT.
    WS_ZTPPVM-K04SER = I_CONTENTS-K04SER.

    WS_ZTPPVM-P_MODEL = I_CONTENTS-K01CAR.
    WS_ZTPPVM-P_BODY_SERIAL = I_CONTENTS-K01BNO.
    WS_ZTPPVM-P_AIRBAG_NO11 = I_CONTENTS-K01MEID.
    WS_ZTPPVM-FLAG = 'ME'.
    WS_ZTPPVM-ZEDAT = SY-DATUM.
    WS_ZTPPVM-ZETIM = SY-UZEIT.
    WS_ZTPPVM-ZRESULT = 'S'.

*    INSERT ZTPPVM FROM WS_ZTPPVM.
    MODIFY ZTPPVM FROM WS_ZTPPVM.

    IF SY-SUBRC = 0.
      COMMIT WORK.
      I_CONTENTS-K01SDAT = SY-DATUM.
      I_CONTENTS-K01STIM = SY-UZEIT.
      I_CONTENTS-K01FLG = 'S'.
      FLAG = 'S'.
    ELSE.
      ROLLBACK WORK.
      I_CONTENTS-K01SDAT = SY-DATUM.
      I_CONTENTS-K01STIM = SY-UZEIT.
      I_CONTENTS-K01FLG = 'E'.
      FLAG = 'E'.
    ENDIF.
    MODIFY I_CONTENTS INDEX L_INDEX.
  ENDLOOP.

ENDFUNCTION.
