FUNCTION Z_FPP_PROD_PLAN_TO_GCC.
*"----------------------------------------------------------------------
*"*"Local interface:
*"  IMPORTING
*"     VALUE(I_CONFLG) TYPE  CHAR1
*"     VALUE(I_FDATE) LIKE  SY-DATUM OPTIONAL
*"     VALUE(I_TDATE) LIKE  SY-DATUM OPTIONAL
*"  TABLES
*"      IT_PLAN STRUCTURE  ZTPP_PLAN_HMC
*"----------------------------------------------------------------------

  DATA: V_SEQ LIKE ZTPP_GCC_ELOG-ELOG_SEQ,
        V_DAYTIME LIKE ZTPP_GCC_ELOG-ELOG_DAYTIME,
        V_DATE LIKE SY-DATUM.

*  DATA: BEGIN OF IT_PLAN OCCURS 0,
*         PRDT_DATE LIKE SY-DATUM,
*         QTY LIKE ZTPP_PLAN_HMC-QTY_PLAN,
*         SUM TYPE I,
*         END OF IT_PLAN.
*
*  DATA: IT_ZTPP_GCCELOG LIKE TABLE OF ZTPP_GCC_ELOG WITH HEADER LINE.
*
  CONCATENATE SY-DATUM SY-UZEIT INTO V_DAYTIME.

  CLEAR: V_SEQ.

  IF I_CONFLG = 'N'.
    V_DATE = SY-DATUM - 1.

*    SELECT PRDT_DATE COUNT( * ) AS QTY
*                    SUM( QTY_PLAN ) AS SUM
*               INTO CORRESPONDING FIELDS OF TABLE IT_PLAN
*       FROM ZTPP_PLAN_HMC
*       WHERE PRDT_DATE = V_DATE
*       GROUP BY PRDT_DATE.

    SELECT * INTO TABLE IT_PLAN
        FROM ZTPP_PLAN_HMC
        WHERE PRDT_DATE = V_DATE.

  ELSE.

    IF NOT I_FDATE IS INITIAL AND NOT I_TDATE IS INITIAL.

      SELECT * INTO TABLE IT_PLAN
        FROM ZTPP_PLAN_HMC
        WHERE PRDT_DATE BETWEEN I_FDATE AND I_TDATE.

    ELSE.
      IF I_FDATE IS INITIAL AND I_TDATE IS INITIAL.
        V_DATE = SY-DATUM - 1.
      ENDIF.
      IF NOT I_FDATE IS INITIAL AND I_TDATE IS INITIAL.
        V_DATE = I_FDATE.
      ENDIF.
      IF I_FDATE IS INITIAL AND NOT I_TDATE IS INITIAL.
        V_DATE = I_TDATE.
      ENDIF.

      SELECT * INTO TABLE IT_PLAN
            FROM ZTPP_PLAN_HMC
            WHERE PRDT_DATE = V_DATE.
    ENDIF.
  ENDIF.

*  V_SEQ = '1'.
*
*  LOOP AT IT_PLAN.
*    T_GCCELOG-ELOG_DATE = IT_PLAN-PRDT_DATE.
*    T_GCCELOG-ELOG_KIND = 'SIGN'.
*    T_GCCELOG-ELOG_SEQ = V_SEQ.
*    T_GCCELOG-ELOG_HKMC = 'HMC'.
*
*    T_GCCELOG-ELOG_LOC = 'HMMA'.
*    T_GCCELOG-ELOG_DAYTIME = V_DAYTIME.
*    T_GCCELOG-ELOG_QTY = IT_PLAN-QTY.
*    T_GCCELOG-ELOG_SUM = IT_PLAN-SUM.
*    APPEND T_GCCELOG.
*    CLEAR:T_GCCELOG.
*  ENDLOOP.

*** UPDATE ZTPP_GCC_ELOG

*  LOOP AT T_GCCELOG.
*    MOVE-CORRESPONDING T_GCCELOG TO IT_ZTPP_GCCELOG.
**    IT_GCCELOG-IF_DATE = SY-DATUM.
**    IT_GCCELOG-IF_TIME = SY-UZEIT.
*    IT_ZTPP_GCCELOG-IF_USER = SY-UNAME.
*    APPEND IT_ZTPP_GCCELOG.
*  ENDLOOP.
*  MODIFY ZTPP_GCC_ELOG FROM TABLE IT_ZTPP_GCCELOG.

ENDFUNCTION.
