FUNCTION Z_FPP_GET_PMT07AB.
*"----------------------------------------------------------------------
*"*"Local interface:
*"  TABLES
*"      T_ZSPP_PMT07AB STRUCTURE  ZSPP_PMT07AB
*"----------------------------------------------------------------------
  DATA IT_ZTPP_PMT07AB LIKE TABLE OF ZTPP_PMT07AB WITH HEADER LINE.

*------> MOVE INBOUNDED TABLE TO ITAB
  LOOP AT T_ZSPP_PMT07AB.
    MOVE-CORRESPONDING T_ZSPP_PMT07AB TO IT_ZTPP_PMT07AB.
    APPEND IT_ZTPP_PMT07AB.
  ENDLOOP.

*------> TEMP TABLE INSERT
  INSERT ZTPP_PMT07AB FROM TABLE IT_ZTPP_PMT07AB
                      ACCEPTING DUPLICATE KEYS.

*------> RETURN CODE
  IF SY-SUBRC EQ 0.
    MOVE  'S'  TO  T_ZSPP_PMT07AB-ZZRET.
  ELSE.
    MOVE  'E'  TO  T_ZSPP_PMT07AB-ZZRET.
    DELETE FROM ZTPP_PMT07AB CLIENT SPECIFIED WHERE MANDT = SY-MANDT.
  ENDIF.
  MODIFY T_ZSPP_PMT07AB TRANSPORTING ZZRET
         WHERE ZZRET EQ SPACE.

ENDFUNCTION.
