FUNCTION Z_FPP_UPDATE_GCC_ELOG.
*"----------------------------------------------------------------------
*"*"Local interface:
*"  EXPORTING
*"     VALUE(IF_RESULT) TYPE  ZRESULT
*"     VALUE(IF_MESSAGE) TYPE  ZMESS
*"  TABLES
*"      T_GCCELOG STRUCTURE  ZSPP_GCC_ELOG
*"----------------------------------------------------------------------
  DATA: IT_ZTPP_GCCELOG LIKE TABLE OF ZTPP_GCC_ELOG WITH HEADER LINE,
        WA_GCCELOG LIKE ZSPP_GCC_ELOG.

  LOOP AT T_GCCELOG INTO WA_GCCELOG.
    UPDATE ZTPP_GCC_ELOG
    SET ELOG_FLAG = WA_GCCELOG-ELOG_FLAG
    ELOG_EAITIME = WA_GCCELOG-ELOG_EAITIME
    IF_DATE = SY-DATUM
    IF_TIME = SY-UZEIT
    WHERE ELOG_DATE = WA_GCCELOG-ELOG_DATE
      AND ELOG_KIND = WA_GCCELOG-ELOG_KIND
      AND ELOG_SEQ = WA_GCCELOG-ELOG_SEQ
      AND ELOG_HKMC = WA_GCCELOG-ELOG_HKMC
      AND ELOG_EXDO = WA_GCCELOG-ELOG_EXDO
      AND ELOG_NAT = WA_GCCELOG-ELOG_NAT
      AND ELOG_LOC = WA_GCCELOG-ELOG_LOC
      AND ELOG_DAYTIME = WA_GCCELOG-ELOG_DAYTIME.
    IF SY-SUBRC <> 0.
      IF_RESULT = 'E'.
      CONCATENATE 'Error:' WA_GCCELOG-ELOG_KIND WA_GCCELOG-ELOG_SEQ
                  WA_GCCELOG-ELOG_NAT WA_GCCELOG-ELOG_DAYTIME
                  INTO IF_MESSAGE SEPARATED BY SPACE.
    ENDIF.
    CLEAR WA_GCCELOG.
  ENDLOOP.
  IF IF_RESULT IS INITIAL.
    IF_RESULT = 'Y'.
  ENDIF.

ENDFUNCTION.
