FUNCTION Z_FPP_GET_PMM03AN.
*"----------------------------------------------------------------------
*"*"Local interface:
*"  TABLES
*"      T_PMM03AN STRUCTURE  ZSPP_PMM03AN
*"----------------------------------------------------------------------
 DATA IT_ZTPP_PMM03AN LIKE TABLE OF ZTPP_PMM03AN WITH HEADER LINE.

*------> MOVE INBOUNDED TABLE TO ITAB
  LOOP AT T_PMM03AN.
    MOVE-CORRESPONDING T_PMM03AN TO IT_ZTPP_PMM03AN.
    APPEND IT_ZTPP_PMM03AN.
  ENDLOOP.

*------> TEMP TABLE INSERT
  INSERT ZTPP_PMM03AN FROM TABLE IT_ZTPP_PMM03AN
                      ACCEPTING DUPLICATE KEYS.

*------> RETURN CODE
  IF SY-SUBRC EQ 0.
    MOVE  'S'  TO  T_PMM03AN-ZZRET.
  ELSE.
    MOVE  'E'  TO  T_PMM03AN-ZZRET.
    DELETE FROM ZTPP_PMM03AN CLIENT SPECIFIED WHERE MANDT = SY-MANDT.
  ENDIF.
  MODIFY T_PMM03AN TRANSPORTING ZZRET
         WHERE ZZRET EQ SPACE.





ENDFUNCTION.
