FUNCTION Z_FPP_SEQ_MAIN_PRE_CHECK.
*"----------------------------------------------------------------------
*"*"Local interface:
*"  EXPORTING
*"     REFERENCE(O_FLAG) TYPE  CHAR1
*"----------------------------------------------------------------------
  DATA: LT_PMT07JB_B LIKE TABLE OF ZTPP_PMT07JB_B WITH HEADER LINE,
        LT_LOG_SSR1 LIKE TABLE OF ZTPP_PMT07JB_B WITH HEADER LINE,
        LT_LOG_SO LIKE TABLE OF ZTPP_PMT07JB_B WITH HEADER LINE.

  DATA: L_SSR1 LIKE ZTPP_PMT07JB_B-SSR1,
        L_SALES  LIKE ZTPP_WOSUM-SALES.

  SELECT * INTO TABLE LT_PMT07JB_B
    FROM ZTPP_PMT07JB_B.

  SORT LT_PMT07JB_B BY SSR1.
  O_FLAG = 'S'.

  L_SSR1 = '**'.
  LOOP AT LT_PMT07JB_B.
    CLEAR: LT_LOG_SSR1, LT_LOG_SO.
    IF L_SSR1 = LT_PMT07JB_B-SSR1.
      O_FLAG = 'E'.
      LT_LOG_SSR1-SSR1 = LT_PMT07JB_B-SSR1.
      LT_LOG_SSR1-ORDR = LT_PMT07JB_B-ORDR.
      LT_LOG_SSR1-DIST = LT_PMT07JB_B-DIST.
      LT_LOG_SSR1-EXTC = LT_PMT07JB_B-EXTC.
      LT_LOG_SSR1-INTC = LT_PMT07JB_B-INTC.
*      lT_LOG_ssr1-LINE = '1'.
      APPEND LT_LOG_SSR1.
*      O_MESS = 'is duplicated. Please check ZTPP_PMT07JB-SSR1'.
*           CONCATENATE LT_PMT07JB_B-SSR1 O_MESS INTO O_MESS
*                  SEPARATED BY SPACE.
*      EXIT.
    ELSE.
      L_SSR1 = LT_PMT07JB_B-SSR1.
    ENDIF.

    CLEAR: L_SALES.
    SELECT SINGLE SALES INTO L_SALES
     FROM ZTPP_WOSUM
     WHERE WO_SER = LT_PMT07JB_B-ORDR
       AND NATION = LT_PMT07JB_B-DIST+0(3)
       AND DEALER =  LT_PMT07JB_B-DIST+3(2)
       AND EXTC = LT_PMT07JB_B-EXTC
       AND INTC = LT_PMT07JB_B-INTC.
    IF L_SALES IS INITIAL.
      O_FLAG = 'E'.
      LT_LOG_SO-SSR1 = LT_PMT07JB_B-SSR1.
      LT_LOG_SO-ORDR = LT_PMT07JB_B-ORDR.
      LT_LOG_SO-DIST = LT_PMT07JB_B-DIST.
      LT_LOG_SO-EXTC = LT_PMT07JB_B-EXTC.
      LT_LOG_SO-INTC = LT_PMT07JB_B-INTC.
*      lT_LOG_so-LINE = '2'.
      APPEND LT_LOG_SO.
*      O_MESS = 'No Sales Order Found for'.
*      CONCATENATE O_MESS LT_PMT07JB_B-ORDR LT_PMT07JB_B-DIST
*                  LT_PMT07JB_B-EXTC LT_PMT07JB_B-INTC INTO O_MESS
*                  SEPARATED BY SPACE.
*      EXIT.
    ENDIF.
  ENDLOOP.

  SORT LT_LOG_SSR1 BY SSR1 ORDR DIST EXTC INTC.
  DELETE ADJACENT DUPLICATES FROM LT_LOG_SSR1
         COMPARING SSR1 ORDR DIST EXTC INTC.

  SORT LT_LOG_SO BY ORDR DIST EXTC INTC.
  DELETE ADJACENT DUPLICATES FROM LT_LOG_SO
     COMPARING ORDR DIST EXTC INTC.

  WRITE: /(40) 'Duplicated Serial No:'.
  LOOP AT LT_LOG_SSR1.
    WRITE: /(10) LT_LOG_SSR1-SSR1,
            (10) LT_LOG_SSR1-ORDR,
            (10) LT_LOG_SSR1-DIST,
            (10) LT_LOG_SSR1-EXTC,
            (10) LT_LOG_SSR1-INTC.
  ENDLOOP.

  WRITE: /.
  WRITE: /(40) 'No Sales Order:'.
  LOOP AT LT_LOG_SO.
*        WRITE: /(10) LT_CHECK_LOG-SSR1,
    WRITE: /(10) LT_LOG_SO-ORDR,
            (10) LT_LOG_SO-DIST,
            (10) LT_LOG_SO-EXTC,
            (10) LT_LOG_SO-INTC.
  ENDLOOP.
ENDFUNCTION.
