FUNCTION Z_FPP_GET_PMM03AM.
*"----------------------------------------------------------------------
*"*"Local interface:
*"  TABLES
*"      T_PMM03AM STRUCTURE  ZSPP_PMM03AM
*"----------------------------------------------------------------------
 DATA IT_ZTPP_PMM03AM LIKE TABLE OF ZTPP_PMM03AM WITH HEADER LINE.

*------> MOVE INBOUNDED TABLE TO ITAB
  LOOP AT T_PMM03AM.
    MOVE-CORRESPONDING T_PMM03AM TO IT_ZTPP_PMM03AM.
    APPEND IT_ZTPP_PMM03AM.
  ENDLOOP.

*------> TEMP TABLE INSERT
  INSERT ZTPP_PMM03AM FROM TABLE IT_ZTPP_PMM03AM
                      ACCEPTING DUPLICATE KEYS.

*------> RETURN CODE
  IF SY-SUBRC EQ 0.
    MOVE  'S'  TO  T_PMM03AM-ZZRET.
  ELSE.
    MOVE  'E'  TO  T_PMM03AM-ZZRET.
    DELETE FROM ZTPP_PMM03AM CLIENT SPECIFIED WHERE MANDT = SY-MANDT.
  ENDIF.
  MODIFY T_PMM03AM TRANSPORTING ZZRET
         WHERE ZZRET EQ SPACE.





ENDFUNCTION.
