FUNCTION Z_FPP_GET_PMT07JB.
*"----------------------------------------------------------------------
*"*"Local interface:
*"  TABLES
*"      T_ZSPP_PMT07JB STRUCTURE  ZSPP_PMT07JB
*"----------------------------------------------------------------------

  DATA IT_ZTPP_PMT07JB LIKE TABLE OF ZTPP_PMT07JB WITH HEADER LINE.

*------> MOVE INBOUNDED TABLE TO ITAB
  LOOP AT T_ZSPP_PMT07JB.
    MOVE-CORRESPONDING T_ZSPP_PMT07JB TO IT_ZTPP_PMT07JB.
    APPEND IT_ZTPP_PMT07JB.
  ENDLOOP.

*------> TEMP TABLE INSERT
  INSERT ZTPP_PMT07JB FROM TABLE IT_ZTPP_PMT07JB
                      ACCEPTING DUPLICATE KEYS .

*------> RETURN CODE
  IF SY-SUBRC EQ 0.
    MOVE  'S'   TO   T_ZSPP_PMT07JB-ZZRET.
  ELSE.
    MOVE  'E'   TO   T_ZSPP_PMT07JB-ZZRET.
    DELETE FROM ZTPP_PMT07JB CLIENT SPECIFIED WHERE MANDT = SY-MANDT.
  ENDIF.

  MODIFY T_ZSPP_PMT07JB TRANSPORTING ZZRET
                WHERE ZZRET EQ SPACE.
ENDFUNCTION.
