FUNCTION ZPP_GET_PROD_CHECKSUM_OLD.
*"----------------------------------------------------------------------
*"*"Local interface:
*"       IMPORTING
*"             VALUE(I_DATE) LIKE  SY-DATUM
*"       TABLES
*"              T_GCCELOG STRUCTURE  ZSPP_GCC_ELOG
*"----------------------------------------------------------------------

*  DATA: V_DATE LIKE SY-DATUM
  DATA: V_SEQ LIKE ZTPP_GCC_ELOG-ELOG_SEQ,
        V_DAYTIME LIKE ZTPP_GCC_ELOG-ELOG_DAYTIME.

  DATA: BEGIN OF IT_ACT OCCURS 0,
        PRDT_DATE LIKE SY-DATUM,
        DEST LIKE ZTPP_ACT_HMC-DEST,
        QTY LIKE ZTPP_ACT_HMC-QTY_SIGNOFF,
        SUM TYPE I,
        END OF IT_ACT.

  DATA: BEGIN OF IT_TEMP OCCURS 0,
        PRDT_DATE LIKE SY-DATUM,
        DEST(3),
        QTY LIKE ZTPP_ACT_HMC-QTY_SIGNOFF,
        SUM TYPE I,
        END OF IT_TEMP.

  DATA: BEGIN OF IT_PLAN OCCURS 0,
         PRDT_DATE LIKE SY-DATUM,
*        DEST LIKE ZTPP_ACT_HMC-DEST,
         QTY LIKE ZTPP_PLAN_HMC-QTY_PLAN,
         SUM TYPE I,
         END OF IT_PLAN.

  DATA: BEGIN OF IT_DELIVERY OCCURS 0,
        PRDT_DATE LIKE SY-DATUM,
        DIST LIKE ZTPP_DELIVER_HMC-DIST,
        QTY LIKE ZTPP_DELIVER_HMC-QTY_DD,
        SUM TYPE I,
        END OF IT_DELIVERY.

  DATA: IT_ZTPP_GCCELOG LIKE TABLE OF ZTPP_GCC_ELOG WITH HEADER LINE.

*  V_DATE = SY-DATUM - 1.
  CONCATENATE SY-DATUM SY-UZEIT INTO V_DAYTIME.

*** get Production qty
  SELECT PRDT_DATE DEST COUNT( * ) AS QTY
                        SUM( QTY_SIGNOFF ) AS SUM
             INTO CORRESPONDING FIELDS OF TABLE IT_ACT
     FROM ZTPP_ACT_HMC
     WHERE PRDT_DATE = I_DATE
     GROUP BY PRDT_DATE DEST.

  LOOP AT IT_ACT.
    MOVE-CORRESPONDING IT_ACT TO IT_TEMP.
    COLLECT IT_TEMP.
    CLEAR: IT_TEMP, IT_ACT.
  ENDLOOP.

*  SELECT SINGLE ELOG_SEQ INTO V_SEQ
*    FROM ZTPP_GCC_ELOG
*    WHERE ELOG_DATE = I_DATE
*     AND ELOG_KIND = 'PRST'.
*  IF SY-SUBRC = 0.
*    V_SEQ = V_SEQ + 1.
*  ELSE.
  V_SEQ = '1'.
*  ENDIF.

  LOOP AT IT_TEMP.
    T_GCCELOG-ELOG_DATE = IT_TEMP-PRDT_DATE.
    T_GCCELOG-ELOG_KIND = 'PRST'.
    T_GCCELOG-ELOG_SEQ = V_SEQ.
    T_GCCELOG-ELOG_HKMC = 'HMC'.
    IF IT_TEMP-DEST = 'B28'.
      T_GCCELOG-ELOG_EXDO = 'D'.
    ELSE.
      T_GCCELOG-ELOG_EXDO = 'E'.
    ENDIF.
    T_GCCELOG-ELOG_NAT = IT_TEMP-DEST.
    T_GCCELOG-ELOG_LOC = 'HMMA'.

    T_GCCELOG-ELOG_DAYTIME = V_DAYTIME.
    T_GCCELOG-ELOG_QTY = IT_TEMP-QTY.
    T_GCCELOG-ELOG_SUM = IT_TEMP-SUM.
    APPEND T_GCCELOG.
    CLEAR:T_GCCELOG.
  ENDLOOP.

*** get plan qty
*  CLEAR: V_SEQ.
*  SELECT PRDT_DATE COUNT( * ) AS QTY
*                  SUM( QTY_PLAN ) AS SUM
*             INTO CORRESPONDING FIELDS OF TABLE IT_PLAN
*     FROM ZTPP_PLAN_HMC
*     WHERE PRDT_DATE = I_DATE
*     GROUP BY PRDT_DATE.
*
**  SELECT SINGLE ELOG_SEQ INTO V_SEQ
**     FROM ZTPP_GCC_ELOG
**     WHERE ELOG_DATE = I_DATE
**      AND ELOG_KIND = 'SIGN'.
**  IF SY-SUBRC = 0.
**    V_SEQ = V_SEQ + 1.
**  ELSE.
*  V_SEQ = '1'.
**  ENDIF.
*
*  LOOP AT IT_PLAN.
*    T_GCCELOG-ELOG_DATE = IT_PLAN-PRDT_DATE.
*    T_GCCELOG-ELOG_KIND = 'SIGN'.
*    T_GCCELOG-ELOG_SEQ = V_SEQ.
*    T_GCCELOG-ELOG_HKMC = 'HMC'.
*
*    T_GCCELOG-ELOG_LOC = 'HMMA'.
*    T_GCCELOG-ELOG_DAYTIME = V_DAYTIME.
*    T_GCCELOG-ELOG_QTY = IT_PLAN-QTY.
*    T_GCCELOG-ELOG_SUM = IT_PLAN-SUM.
*    APPEND T_GCCELOG.
*    CLEAR:T_GCCELOG.
*  ENDLOOP.
*
**** GET SALES ACTUAL QTY
*  CLEAR: V_SEQ.
*  SELECT PRDT_DATE DIST COUNT( * ) AS QTY
*                        SUM( QTY_DD ) AS SUM
*             INTO CORRESPONDING FIELDS OF TABLE IT_DELIVERY
*     FROM ZTPP_DELIVER_HMC
*     WHERE PRDT_DATE = I_DATE
*     GROUP BY PRDT_DATE DIST.
*
**  SELECT SINGLE ELOG_SEQ INTO V_SEQ
**    FROM ZTPP_GCC_ELOG
**    WHERE ELOG_DATE = I_DATE
**     AND ELOG_KIND = 'GCDS'.
**  IF SY-SUBRC = 0.
**    V_SEQ = V_SEQ + 1.
**  ELSE.
*  V_SEQ = '1'.
**  ENDIF.
*
*  LOOP AT IT_DELIVERY.
*    T_GCCELOG-ELOG_DATE = IT_DELIVERY-PRDT_DATE.
*    T_GCCELOG-ELOG_KIND = 'GCDS'.
*    T_GCCELOG-ELOG_SEQ = V_SEQ.
*    T_GCCELOG-ELOG_HKMC = 'HMC'.
*    IF IT_DELIVERY-DIST = 'B28'.
*      T_GCCELOG-ELOG_EXDO = 'D'.
*    ELSE.
*      T_GCCELOG-ELOG_EXDO = 'E'.
*    ENDIF.
*    T_GCCELOG-ELOG_NAT = IT_DELIVERY-DIST.
*    T_GCCELOG-ELOG_LOC = 'HMMA'.
*    T_GCCELOG-ELOG_DAYTIME = V_DAYTIME.
*
*    T_GCCELOG-ELOG_QTY = IT_DELIVERY-QTY.
*    T_GCCELOG-ELOG_SUM = IT_DELIVERY-SUM.
*    APPEND T_GCCELOG.
*    CLEAR:T_GCCELOG.
*  ENDLOOP.

*** UPDATE ZTPP_GCC_ELOG

*  LOOP AT T_GCCELOG.
*    MOVE-CORRESPONDING T_GCCELOG TO IT_ZTPP_GCCELOG.
**    IT_GCCELOG-IF_DATE = SY-DATUM.
**    IT_GCCELOG-IF_TIME = SY-UZEIT.
*    IT_ZTPP_GCCELOG-IF_USER = SY-UNAME.
*    APPEND IT_ZTPP_GCCELOG.
*  ENDLOOP.
*  MODIFY ZTPP_GCC_ELOG FROM TABLE IT_ZTPP_GCCELOG.

ENDFUNCTION.
