*&---------------------------------------------------------------------*
*&  Include           ZHARC00300_F02
*&---------------------------------------------------------------------*
SPLIT GS_ABAP AT SPACE INTO: GS_STR-FLD01
                            GS_STR-FLD02
                            GS_STR-FLD03
                            GS_STR-FLD04
                            GS_STR-FLD05
                            GS_STR-FLD06
                            GS_STR-FLD07
                            GS_STR-FLD08
                            GS_STR-FLD09
                            GS_STR-FLD10
                            GS_STR-FLD11
                            GS_STR-FLD12
                            GS_STR-FLD13
                            GS_STR-FLD14
                            GS_STR-FLD15
                            GS_STR-FLD16
                            GS_STR-FLD17
                            GS_STR-FLD18
                            GS_STR-FLD19
                            GS_STR-FLD20
                            GS_STR-FLD21
                            GS_STR-FLD22
                            GS_STR-FLD23
                            GS_STR-FLD24
                            GS_STR-FLD25
                            GS_STR-FLD26
                            GS_STR-FLD27
                            GS_STR-FLD28
                            GS_STR-FLD29
                            GS_STR-FLD30
                            GS_STR-FLD31
                            GS_STR-FLD32
                            GS_STR-FLD33
                            GS_STR-FLD34
                            GS_STR-FLD35
                            GS_STR-FLD36
                            GS_STR-FLD37
                            GS_STR-FLD38
                            GS_STR-FLD39
                            GS_STR-FLD40
                            GS_STR-FLD41
                            GS_STR-FLD42
                            GS_STR-FLD43
                            GS_STR-FLD44
                            GS_STR-FLD45
                            GS_STR-FLD46
                            GS_STR-FLD47
                            GS_STR-FLD48
                            GS_STR-FLD49
                            GS_STR-FLD50
                            GS_STR-FLD51
                            GS_STR-FLD52
                            GS_STR-FLD53
                            GS_STR-FLD54
                            GS_STR-FLD55
                            GS_STR-FLD56
                            GS_STR-FLD57
                            GS_STR-FLD58
                            GS_STR-FLD59
                            GS_STR-FLD60
                            GS_STR-FLD61
                            GS_STR-FLD62
                            GS_STR-FLD63
                            GS_STR-FLD64
                            GS_STR-FLD65
                            GS_STR-FLD66
                            GS_STR-FLD67
                            GS_STR-FLD68
                            GS_STR-FLD69
                            GS_STR-FLD70
                            GS_STR-FLD71
                            GS_STR-FLD72
                            GS_STR-FLD73
                            GS_STR-FLD74
                            GS_STR-FLD75.
