*&---------------------------------------------------------------------*
*&  Include           YAC_FIND_TABLE_CAL_F04
*&---------------------------------------------------------------------*

  CLEAR: GS_ASTB1, GS_ASTB2, GS_ASTB3.

  SELECT SINGLE POSITION
    INTO DD03L-POSITION
    FROM DD03L
   WHERE TABNAME   EQ GT_TABLE-TABNAME
     AND FIELDNAME EQ GT_FIELDNAME-FIELDNAME.

  IF SY-SUBRC EQ 0 OR GT_FIELDNAME-FIELDNAME EQ '*'.
    MOVE-CORRESPONDING GT_PGML      TO GT_ASTB1.
    MOVE-CORRESPONDING GT_TABLE     TO GT_ASTB1.
    MOVE-CORRESPONDING GT_FIELDNAME TO GT_ASTB1.

    COLLECT GT_ASTB1.

    MOVE-CORRESPONDING GT_TABLE     TO GT_ASTB2.
    MOVE-CORRESPONDING GT_FIELDNAME TO GT_ASTB2.

    MOVE-CORRESPONDING GT_TABLE     TO GT_ASTB3.
    MOVE-CORRESPONDING GT_FIELDNAME TO GT_ASTB3.

    IF GT_FIELDNAME-FIELDNAME EQ '*'.
      MOVE-CORRESPONDING GT_PGML    TO GT_ASTB3.
    ELSE.
      CLEAR: GT_ASTB2-PROGNAME.
      CLEAR: GT_ASTB3-PROGNAME.
    ENDIF.

    COLLECT GT_ASTB2.
    COLLECT GT_ASTB3.
  ENDIF.
