*&-------------------------------------------------------------*
*& Report ZTCO_SHOPCOST_W
*&-------------------------------------------------------------*
*System name         : HMI SYSTEM
*Sub system name     : ARCHIVE
*Program name        : Archiving : ZTCO_SHOPCOST (Write)
*Program descrition  : Generated automatically by the ZHACR00800
*Created on   : 20130521          Created by   : T00302
*Changed on :                           Changed by    :
*Changed descrition :
*"-------------------------------------------------------------*
REPORT ZTCO_SHOPCOST_W .

***** Include TOP
INCLUDE ZTCO_SHOPCOST_T .

***** Selection screen.
SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME TITLE TEXT-001.
SELECT-OPTIONS S_BDATJ FOR ZTCO_SHOPCOST-BDATJ.
*SELECT-OPTIONS S_ELEMT FOR ZTCO_SHOPCOST-ELEMT.
*SELECT-OPTIONS S_FSC_MA FOR ZTCO_SHOPCOST-FSC_MATNR.
*SELECT-OPTIONS S_KALNR FOR ZTCO_SHOPCOST-KALNR.
*SELECT-OPTIONS S_KLVAR FOR ZTCO_SHOPCOST-KLVAR.
*SELECT-OPTIONS S_KOKRS FOR ZTCO_SHOPCOST-KOKRS.
*SELECT-OPTIONS S_KOSTL FOR ZTCO_SHOPCOST-KOSTL.
*SELECT-OPTIONS S_KSTAR FOR ZTCO_SHOPCOST-KSTAR.
*SELECT-OPTIONS S_LLV_MA FOR ZTCO_SHOPCOST-LLV_MATNR.
*SELECT-OPTIONS S_LSTAR FOR ZTCO_SHOPCOST-LSTAR.
SELECT-OPTIONS S_POPER FOR ZTCO_SHOPCOST-POPER.
*SELECT-OPTIONS S_RECORD FOR ZTCO_SHOPCOST-RECORD_TYPE.
*SELECT-OPTIONS S_SHOP FOR ZTCO_SHOPCOST-SHOP.
*SELECT-OPTIONS S_TYPPS FOR ZTCO_SHOPCOST-TYPPS.
*SELECT-OPTIONS S_VERSN FOR ZTCO_SHOPCOST-VERSN.
SELECTION-SCREEN SKIP 1.
PARAMETERS: TESTRUN               AS CHECKBOX,
            CREATE    DEFAULT  'X' AS CHECKBOX,
            OBJECT    LIKE         ARCH_IDX-OBJECT
                      DEFAULT 'ZTCO_SHOPC' NO-DISPLAY .
SELECTION-SCREEN SKIP 1.
PARAMETERS: COMMENT   LIKE ADMI_RUN-COMMENTS OBLIGATORY.
SELECTION-SCREEN END OF BLOCK B2.

***** Main login - common routine of include
PERFORM ARCHIVE_PROCESS.

***** Common routine
INCLUDE ZITARCW.

***** History for each object,
***** processing required for each part defined,
FORM OPEN_CURSOR_FOR_DB.
  OPEN CURSOR WITH HOLD G_CURSOR FOR
SELECT * FROM ZTCO_SHOPCOST
WHERE BDATJ IN S_BDATJ
*AND ELEMT IN S_ELEMT
*AND FSC_MATNR IN S_FSC_MA
*AND KALNR IN S_KALNR
*AND KLVAR IN S_KLVAR
*AND KOKRS IN S_KOKRS
*AND KOSTL IN S_KOSTL
*AND KSTAR IN S_KSTAR
*AND LLV_MATNR IN S_LLV_MA
*AND LSTAR IN S_LSTAR
AND POPER IN S_POPER.
*AND RECORD_TYPE IN S_RECORD
*AND SHOP IN S_SHOP
*AND TYPPS IN S_TYPPS
*AND VERSN IN S_VERSN.
ENDFORM.
FORM MAKE_ARCHIVE_OBJECT_ID.



ENDFORM.
