*&-------------------------------------------------------------*
*& Report ZTPP_PMT06EA_W
*&-------------------------------------------------------------*
*System name         : HMI SYSTEM
*Sub system name     : ARCHIVE
*Program name        : Archiving : ZTPP_PMT06EA (Write)
*Program descrition  : Generated automatically by the ZHACR00800
*Created on   : 20130603          Created by   : T00302
*Changed on :                           Changed by    :
*Changed descrition :
*"-------------------------------------------------------------*
REPORT ZTPP_PMT06EA_W .

***** Include TOP
INCLUDE ZTPP_PMT06EA_T .

***** Selection screen.
SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME TITLE TEXT-001.
*SELECT-OPTIONS S_DIST FOR ZTPP_PMT06EA-DIST.
*SELECT-OPTIONS S_EXTC FOR ZTPP_PMT06EA-EXTC.
*SELECT-OPTIONS S_INTC FOR ZTPP_PMT06EA-INTC.
*SELECT-OPTIONS S_LINE FOR ZTPP_PMT06EA-LINE.
*SELECT-OPTIONS S_MODL FOR ZTPP_PMT06EA-MODL.
*SELECT-OPTIONS S_PACK FOR ZTPP_PMT06EA-PACK.
*SELECT-OPTIONS S_PLNT FOR ZTPP_PMT06EA-PLNT.
*SELECT-OPTIONS S_REGN FOR ZTPP_PMT06EA-REGN.
*SELECT-OPTIONS S_SERL FOR ZTPP_PMT06EA-SERL.
*SELECT-OPTIONS S_STDT FOR ZTPP_PMT06EA-STDT.
*SELECT-OPTIONS S_USEE FOR ZTPP_PMT06EA-USEE.
SELECT-OPTIONS S_STDT FOR ZTPP_PMT06EA-STDT.
SELECTION-SCREEN SKIP 1.
PARAMETERS: TESTRUN               AS CHECKBOX,
            CREATE    DEFAULT  'X' AS CHECKBOX,
            OBJECT    LIKE         ARCH_IDX-OBJECT
                      DEFAULT 'ZTPP_PMT06' NO-DISPLAY .
SELECTION-SCREEN SKIP 1.
PARAMETERS: COMMENT   LIKE ADMI_RUN-COMMENTS OBLIGATORY.
SELECTION-SCREEN END OF BLOCK B2.

***** Main login - common routine of include
PERFORM ARCHIVE_PROCESS.

***** Common routine
INCLUDE ZITARCW.

***** History for each object,
***** processing required for each part defined,
FORM OPEN_CURSOR_FOR_DB.
  OPEN CURSOR WITH HOLD G_CURSOR FOR
SELECT * FROM ZTPP_PMT06EA
*WHERE DIST IN S_DIST
*AND EXTC IN S_EXTC
*AND INTC IN S_INTC
*AND LINE IN S_LINE
*AND MODL IN S_MODL
*AND PACK IN S_PACK
*AND PLNT IN S_PLNT
*AND REGN IN S_REGN
*AND SERL IN S_SERL
*AND STDT IN S_STDT
*AND USEE IN S_USEE.
WHERE STDT IN S_STDT.
ENDFORM.
FORM MAKE_ARCHIVE_OBJECT_ID.



ENDFORM.
