REPORT ZRPM_DEL_TBL_ZTPM_MTTR_MTBF .
TABLES: ZTPM_MTBT,
        ZTPM_MTTR_MTBF_U,
        ZTPM_MTTR_MTBF.
PARAMETERS : ZSHOP LIKE ZTPM_MTTR_MTBF-SHOP,
             ZAJAHR LIKE ZTPM_MTTR_MTBF-AJAHR,
             ZZMONTH LIKE ZTPM_MTTR_MTBF-ZMONTH.


DATA : IT_ZTPM_MTBT LIKE ZTPM_MTBT OCCURS 0 WITH HEADER LINE,
       IT_ZTPM_MTTR_MTBF LIKE ZTPM_MTTR_MTBF OCCURS 0 WITH HEADER LINE,
*       IT_ZTPM_MTTR_MTBF1 LIKE ZTPM_MTTR_MTBF OCCURS 0 WITH HEADER LINE
       IT_ZTPM_MTTR_MTBF2 LIKE ZTPM_MTTR_MTBF OCCURS 0 WITH HEADER LINE.
DATA: ZMTTR_AVRATE LIKE ZTPM_MTTR_MTBF-ZMTTR_AVRATE ,
      ZMTBF_AVRATE LIKE ZTPM_MTTR_MTBF-ZMTBF_AVRATE.

DATA: WA_SHOP LIKE  IT_ZTPM_MTTR_MTBF-SHOP ,
wa_ajahr LIKE  IT_ZTPM_MTTR_MTBF-AJAHR ,
wa_zmonth LIKE IT_ZTPM_MTTR_MTBF-ZMONTH .

DATA: BEGIN OF IT_ZTPM_MTTR_MTBF1  OCCURS 0,
      MANDT LIKE ZTPM_MTTR_MTBF-MANDT,
      SHOP  LIKE ZTPM_MTTR_MTBF-SHOP,
      AJAHR LIKE ZTPM_MTTR_MTBF-AJAHR,
      ZMONTH LIKE ZTPM_MTTR_MTBF-ZMONTH,
      ZMTTR_AVRATE LIKE ZTPM_MTTR_MTBF-ZMTTR_AVRATE,
     ZMTBF_AVRATE LIKE  ZTPM_MTTR_MTBF-ZMTBF_AVRATE,
     END OF IT_ZTPM_MTTR_MTBF1 .

DELETE FROM ZTPM_MTTR_MTBF_U WHERE SHOP = ZSHOP AND
                                   AJAHR = ZAJAHR AND
                                   ZMONTH = ZZMONTH.
