*
*--Struktur für Ablage von CUA-Statusprofilen in MONI (ID = "CU")
DATA  SUMMCUA LIKE SAPWLFCODE OCCURS 0 WITH HEADER LINE.
*
DATA  BEGIN OF XUMMCUA OCCURS 0.
        INCLUDE STRUCTURE SUMMCUA.
DATA  END OF XUMMCUA.
*
DATA  READCUAFLAG.
