FUNCTION Z_HR_ESS_UPD_EMP_EMERGENCY_CON.
*"----------------------------------------------------------------------
*"*"Local interface:
*"  IMPORTING
*"     VALUE(EMPLOYEE_NUMBER) LIKE  BAPI7004-PERNR
*"     VALUE(FAMSA) TYPE  FAMSA DEFAULT 7
*"     VALUE(CREATE) TYPE  CHAR1 OPTIONAL
*"     VALUE(UPDATE) TYPE  CHAR1 OPTIONAL
*"     VALUE(DELETE) TYPE  CHAR1 OPTIONAL
*"  TABLES
*"      ZESS_EMP_EMERGENCY_CON STRUCTURE  ZESS_EMP_EMERGENCY_CONTACT
*"      RETURN STRUCTURE  BAPIRETURN
*"----------------------------------------------------------------------

* {

  DATA RETURN1 LIKE BAPIRETURN1 OCCURS 0 WITH HEADER LINE.

  CALL FUNCTION 'BAPI_EMPLOYEE_ENQUEUE'
       EXPORTING
            NUMBER = EMPLOYEE_NUMBER
       IMPORTING
            RETURN = RETURN1.

  IF RETURN1-TYPE EQ 'E'.
    RETURN-TYPE = 'I'.
    RETURN-MESSAGE = 'Record is locked. Please try again later.'.
    APPEND RETURN.
    EXIT.
  ENDIF.

  CALL FUNCTION 'BAPI_EMPLOYEE_DEQUEUE'
       EXPORTING
            NUMBER = EMPLOYEE_NUMBER
       IMPORTING
            RETURN = RETURN1.
* }

  IF CREATE IS INITIAL AND
     UPDATE IS INITIAL AND
     DELETE IS INITIAL.
    RETURN-TYPE = 'E'.
    RETURN-MESSAGE = 'Select Create or Update or Delete'.
    APPEND RETURN.
    EXIT.
  ENDIF.

  DATA $LINE TYPE I.
  DATA $OBJPS(2) TYPE N.
  DATA $SEQNR(2) TYPE N.
  DATA G_ERROR.
  DATA G_UPD.

  READ TABLE ZESS_EMP_EMERGENCY_CON INDEX 1.
  CHECK SY-SUBRC EQ 0.

  IF FAMSA IS INITIAL.
    FAMSA = '7'.
  ENDIF.

  DATA ITAB LIKE PA0021 OCCURS 10 WITH HEADER LINE.

  SELECT *
  INTO CORRESPONDING FIELDS OF TABLE ITAB
    FROM PA0021 WHERE PERNR EQ EMPLOYEE_NUMBER
                 AND FAMSA EQ FAMSA
                 AND ENDDA EQ '99991231'.

  IF SY-SUBRC NE 0 AND CREATE NE TRUE.
    RETURN-TYPE = 'E'.
    RETURN-MESSAGE = 'Invalid Employee Number'.
    APPEND RETURN.
    EXIT.
  ENDIF.

  LOOP AT ITAB.

    TRANSLATE ITAB-FAVOR TO UPPER CASE.
    TRANSLATE ZESS_EMP_EMERGENCY_CON-FIRST_NAME TO UPPER CASE.

    TRANSLATE ITAB-FANAM TO UPPER CASE.
    TRANSLATE ZESS_EMP_EMERGENCY_CON-LAST_NAME TO UPPER CASE.

    TRANSLATE ITAB-FINIT TO UPPER CASE.
    TRANSLATE ZESS_EMP_EMERGENCY_CON-INITIALS TO UPPER CASE.

    IF ZESS_EMP_EMERGENCY_CON-FIRST_NAME = ITAB-FAVOR AND
       ZESS_EMP_EMERGENCY_CON-LAST_NAME  = ITAB-FANAM AND
       ZESS_EMP_EMERGENCY_CON-INITIALS = ITAB-FINIT.

      G_UPD = TRUE.
      IF CREATE EQ TRUE.
        RETURN-TYPE = 'E'.
       RETURN-MESSAGE = 'Cannot create - Aready exists in contact list'.
        APPEND RETURN.
        G_ERROR = TRUE.
        EXIT.
      ENDIF.

      IF DELETE EQ TRUE.

        DELETE FROM PA0106 WHERE PERNR = ITAB-PERNR
          AND SUBTY = ITAB-SUBTY
          AND OBJPS = ITAB-OBJPS
          AND BEGDA = SY-DATUM.

        DELETE FROM PA0021 WHERE PERNR = ITAB-PERNR
          AND SUBTY = ITAB-SUBTY
          AND OBJPS = ITAB-OBJPS
          AND BEGDA = SY-DATUM.

        SELECT SINGLE * FROM PA0106
        WHERE PERNR = ITAB-PERNR
          AND SUBTY = ITAB-SUBTY
          AND OBJPS = ITAB-OBJPS
          AND ENDDA = '99991231'.

        IF SY-SUBRC EQ 0.

           *PA0106 = PA0106.
           *PA0106-ENDDA = SY-DATUM - 1.

          DELETE FROM PA0106 WHERE PERNR = ITAB-PERNR
            AND SUBTY = ITAB-SUBTY
            AND OBJPS = ITAB-OBJPS
            AND ENDDA = *PA0106-ENDDA.

          IF SY-SUBRC EQ 0.
             *PA0106-ENDDA = SY-DATUM.
            DELETE FROM PA0106 WHERE PERNR = ITAB-PERNR
              AND SUBTY = ITAB-SUBTY
              AND OBJPS = ITAB-OBJPS
              AND ENDDA = *PA0106-ENDDA.
          ENDIF.

          UPDATE PA0106 SET ENDDA = *PA0106-ENDDA
               WHERE PERNR EQ ITAB-PERNR
                 AND SUBTY EQ ITAB-SUBTY
                 AND OBJPS EQ ITAB-OBJPS
                 AND ENDDA EQ '99991231'.

          IF SY-SUBRC NE 0.
            ROLLBACK WORK.
            RETURN-TYPE = 'E'.
            RETURN-MESSAGE = 'Error Occured When Update'.
            APPEND RETURN.
            EXIT.

          ENDIF.

        ENDIF.

        SELECT SINGLE * FROM PA0021
        WHERE PERNR = ITAB-PERNR
          AND SUBTY = ITAB-SUBTY
          AND OBJPS = ITAB-OBJPS
          AND ENDDA = '99991231'.

        IF SY-SUBRC EQ 0.

           *PA0021 = PA0021.
           *PA0021-ENDDA = SY-DATUM - 1.

          DELETE FROM PA0021 WHERE PERNR = ITAB-PERNR
            AND SUBTY = ITAB-SUBTY
            AND OBJPS = ITAB-OBJPS
            AND ENDDA = *PA0021-ENDDA.

          IF SY-SUBRC EQ 0.
             *PA0021-ENDDA = SY-DATUM.
            DELETE FROM PA0021 WHERE PERNR = ITAB-PERNR
              AND SUBTY = ITAB-SUBTY
              AND OBJPS = ITAB-OBJPS
              AND ENDDA = *PA0021-ENDDA.
          ENDIF.

          UPDATE PA0021 SET ENDDA = *PA0021-ENDDA
               WHERE PERNR EQ ITAB-PERNR
                 AND SUBTY EQ ITAB-SUBTY
                 AND OBJPS EQ ITAB-OBJPS
                 AND ENDDA EQ '99991231'.

          IF SY-SUBRC NE 0.
            ROLLBACK WORK.
            RETURN-TYPE = 'E'.
            RETURN-MESSAGE = 'Error Occured When Update'.
            APPEND RETURN.
            EXIT.
          ENDIF.

          COMMIT WORK.

        ENDIF.
      ENDIF.

      IF UPDATE EQ TRUE.

        SELECT SINGLE * FROM PA0106
        WHERE PERNR = ITAB-PERNR
          AND SUBTY = ITAB-SUBTY
          AND OBJPS = ITAB-OBJPS
          AND ENDDA = '99991231'.

        IF SY-SUBRC EQ 0.

           *PA0106 = PA0106.
           *PA0106-ENDDA = SY-DATUM - 1.

          DELETE FROM PA0106 WHERE PERNR = ITAB-PERNR
            AND SUBTY = ITAB-SUBTY
            AND OBJPS = ITAB-OBJPS
            AND BEGDA = SY-DATUM.

          UPDATE PA0106 SET ENDDA = *PA0106-ENDDA
          WHERE PERNR = ITAB-PERNR
            AND SUBTY = ITAB-SUBTY
            AND OBJPS = ITAB-OBJPS
            AND ENDDA = '99991231'.

           *PA0106-TELNR = ZESS_EMP_EMERGENCY_CON-TELEPHONE.
           *PA0106-BEGDA =  SY-DATUM.
           *PA0106-ENDDA = '99991231'.

          INSERT PA0106 FROM *PA0106.

          IF SY-SUBRC NE 0.
            ROLLBACK WORK.
            RETURN-TYPE = 'E'.
            RETURN-MESSAGE = 'Error Occured When Update'.
            APPEND RETURN.
            EXIT.
          ENDIF.
          COMMIT WORK.

        ENDIF.

      ENDIF.

    ENDIF.

  ENDLOOP.

  IF G_ERROR EQ TRUE.
    EXIT.
  ENDIF.

  IF CREATE EQ TRUE.

    DESCRIBE TABLE ITAB LINES $LINE.
    $OBJPS = $LINE.
    SORT ITAB BY SEQNR DESCENDING.
    READ TABLE ITAB INDEX 1.
    IF SY-SUBRC EQ 0.
      $SEQNR = ITAB-SEQNR.
    ELSE.
      $SEQNR = '00'.
    ENDIF.

    LOOP AT ZESS_EMP_EMERGENCY_CON.

      ADD 1 TO $OBJPS.
      ADD 1 TO $SEQNR.

      PA0021-PERNR = EMPLOYEE_NUMBER.
      PA0021-SUBTY = '7'.
      PA0021-OBJPS = $OBJPS.
      PA0021-ENDDA = '99991231'.
      PA0021-BEGDA = SY-DATUM.
*      PA0021-SEQNR = $SEQNR.
      PA0021-FAVOR = ZESS_EMP_EMERGENCY_CON-FIRST_NAME.
      PA0021-FANAM = ZESS_EMP_EMERGENCY_CON-LAST_NAME.
      PA0021-FINIT = ZESS_EMP_EMERGENCY_CON-INITIALS.
      PA0021-FAMSA = FAMSA.
      PA0021-AEDTM = SY-DATUM.
      PA0021-UNAME = SY-UNAME.
      PA0021-FAMSA = FAMSA.
      INSERT PA0021.
      IF SY-SUBRC NE 0.
        ROLLBACK WORK.
        RETURN-TYPE = 'E'.
        RETURN-MESSAGE = 'Error Occured When Insert'.
        APPEND RETURN.
        EXIT.
      ENDIF.

      PA0106-PERNR = EMPLOYEE_NUMBER.
      PA0106-SUBTY = '7'.
      PA0106-OBJPS = $OBJPS.
      PA0106-ENDDA = '99991231'.
      PA0106-BEGDA = SY-DATUM.
*      PA0106-SEQNR = $SEQNR.
      PA0106-TELNR = ZESS_EMP_EMERGENCY_CON-TELEPHONE.
      PA0106-AEDTM = SY-DATUM.
      PA0106-UNAME = SY-UNAME.

      INSERT PA0106.
      IF SY-SUBRC NE 0.
        ROLLBACK WORK.
        RETURN-TYPE = 'E'.
        RETURN-MESSAGE = 'Error Occured when Insert'.
        APPEND RETURN.
        EXIT.

      ENDIF.

    ENDLOOP.

    COMMIT WORK.

  ENDIF.
  IF ( UPDATE EQ TRUE OR DELETE EQ TRUE ) AND  G_UPD EQ FALSE.
    RETURN-TYPE = 'E'.
    RETURN-MESSAGE = 'Could not find the name'.
    APPEND RETURN.
    EXIT.
  ENDIF.

  RETURN-TYPE = 'S'.
  RETURN-MESSAGE = 'Success!'.
  APPEND RETURN.

ENDFUNCTION.
