FUNCTION Z_HR_ESS_GET_PERSONAL_EMAIL.
*"----------------------------------------------------------------------
*"*"Local interface:
*"  IMPORTING
*"     VALUE(EMPLOYEE_NUMBER) LIKE  BAPI7004-PERNR
*"  EXPORTING
*"     VALUE(RETURN) LIKE  BAPIRETURN STRUCTURE  BAPIRETURN
*"  TABLES
*"      ZESS_PERSONAL_EMAIL STRUCTURE  ZESS_PERSONAL_EMAIL
*"  EXCEPTIONS
*"      INVALID_EMP_NUMBER
*"----------------------------------------------------------------------
*  SELECT SINGLE STEXT INTO ZESS_PERSONAL_EMAIL-STEXT
*        FROM T591S WHERE SPRSL eq SY-LANGU
*                     AND INFTY.
*  IF SY-SUBRC NE 0.
*    RAISE INVALID_EMP_NUMBER.
*  ENDIF.
*
*  REPLACE :
*      'Mr' WITH '' INTO ZESS_PERSONAL-NAME,
*      'Miss' WITH '' INTO ZESS_PERSONAL-NAME,
*      'Mrs' WITH '' INTO ZESS_PERSONAL-NAME,
*      'Ms' WITH '' INTO ZESS_PERSONAL-NAME,
*      'Dr' WITH '' INTO ZESS_PERSONAL-NAME.
*
*  SELECT SINGLE  * FROM PA0002 WHERE PERNR EQ EMPLOYEE_NUMBER
*                             AND BEGDA <= SY-DATUM
*                             AND ENDDA >= SY-DATUM.
*
*  IF SY-SUBRC EQ 0.
*    ZESS_PERSONAL-SSN = PA0002-PERID.
*    ZESS_PERSONAL-BIRTH_DATE = PA0002-GBDAT.
**    ZESS_PERSONAL-GENDER = PA0002-GESCH .
*
*    SELECT SINGLE SPTXT INTO ZESS_PERSONAL-COMM_LANG
*          FROM T002T WHERE SPRAS EQ 'E'
*                       AND SPRSL EQ PA0002-SPRSL.
*
*
*    SELECT SINGLE NATIO INTO ZESS_PERSONAL-NATIONALITY
*    FROM T005T WHERE LAND1 = PA0002-NATIO
*                 AND SPRAS = 'E'.
*
*    SELECT SINGLE FTEXT INTO ZESS_PERSONAL-MAR_STATUS
*    FROM T502T WHERE FAMST = PA0002-FAMST
*                 AND SPRSL = 'E'.
*
*    ZESS_PERSONAL-DEPENDENTS = PA0002-ANZKD.
*  ENDIF.
*
*  ZESS_PERSONAL-COMM_LANG_KEY = PA0002-SPRSL.
*  ZESS_PERSONAL-NATIONALITY_KEY = PA0002-NATIO.
*  ZESS_PERSONAL-MAR_STATUS_KEY = PA0002-FAMST.
*
*  APPEND ZESS_PERSONAL.
*
ENDFUNCTION.
