************************************************************************
* Program Name      : ZACO10R_SHOP
* Author            : Hyung Jin Youn
* Creation Date     : 31/04/2004
* Specifications By : Hae Sung Cho
* Pattern           : Report 1-1
* Development Request No:UD1K908459
* Add documentation :
* Description       : Report to display the result of SHOP data
*                     Standard / Business Plan
* the BDC structures for BATCH INPUT processing
*
* Modifications Log
* Date   Developer   Request ID    Description
*
************************************************************************
REPORT ZACO10R_SHOP
   LINE-SIZE 253 NO STANDARD PAGE HEADING LINE-COUNT 000(003).

*INCLUDE <SYMBOL>.
*INCLUDE <ICON>.
*SELECTION-SCREEN: BEGIN OF BLOCK PROG
*                           WITH FRAME TITLE TEXT-F58.
*
*TABLES ZTCO_SHOPCOST.
*DATA %COUNT-ZTCO_SHOPCOST(4) TYPE X.
*DATA %LINR-ZTCO_SHOPCOST(2).
*
*TABLES AQLDB.
*
*INCLUDE RSAQEXCD.
*
*DATA: BEGIN OF %ST_LISTE OCCURS 100,
*          HEAD(1),
*          TAB(3),
*          LINE(6) TYPE N,
*          CONT(1) TYPE N,
*          FINT(1),
*          FINV(1),
*          FCOL(1) TYPE N,
*          TEXT(0253),
*      END OF %ST_LISTE.
*
*DATA %DATA_SELECTED(1).
*DATA %GLFRAME(1)  VALUE 'X' .
*DATA %UFLAG(1).
*DATA %USTFLAG(1).
*DATA %GRST_TEXT(255).
*DATA %GLLINE TYPE I.
*DATA %TABIX LIKE SY-TABIX.
*DATA %PRFLAG(1) TYPE X VALUE '02'.
*
*
*DATA %PERC(4) TYPE P DECIMALS 3.
*DATA %P100(4) TYPE P DECIMALS 3 VALUE '100.000'.
*DATA %RANGCT TYPE I.
*DATA %RANGCC(8).
*DATA %SUBRC LIKE SY-SUBRC.
*
*DATA: BEGIN OF %WA010 OCCURS 10,
*            ZTCO_SHOPCOST-MENGE(16) TYPE P DECIMALS 03,
*            BEGIN OF ZTCO_SHOPCOST,
*                  ZTCO_SHOPCOST-MEEHT LIKE ZTCO_SHOPCOST-MEEHT,
*            END OF ZTCO_SHOPCOST,
*      END OF %WA010.
*
*DATA: BEGIN OF %WA020 OCCURS 10,
*            ZTCO_SHOPCOST-WERTN(16) TYPE P DECIMALS 02,
*            ZTCO_SHOPCOST-WDIFF(16) TYPE P DECIMALS 02,
*            ZTCO_SHOPCOST-WRTFX(16) TYPE P DECIMALS 02,
*            BEGIN OF ZTCO_SHOPCOST,
*                  ZTCO_SHOPCOST-HWAER LIKE ZTCO_SHOPCOST-HWAER,
*            END OF ZTCO_SHOPCOST,
*      END OF %WA020.
*
*DATA: BEGIN OF %W0100 OCCURS 20,
*            ZTCO_SHOPCOST-HWAER LIKE ZTCO_SHOPCOST-HWAER,
*            ZTCO_SHOPCOST-WERTN(16) TYPE P DECIMALS 02,
*            ZTCO_SHOPCOST-WDIFF(16) TYPE P DECIMALS 02,
*            ZTCO_SHOPCOST-WRTFX(16) TYPE P DECIMALS 02,
*      END OF %W0100.
*
*DATA: BEGIN OF %W0101 OCCURS 20,
*            ZTCO_SHOPCOST-HWAER LIKE ZTCO_SHOPCOST-HWAER,
*            ZTCO_SHOPCOST-WERTN(16) TYPE P DECIMALS 02,
*            ZTCO_SHOPCOST-WDIFF(16) TYPE P DECIMALS 02,
*            ZTCO_SHOPCOST-WRTFX(16) TYPE P DECIMALS 02,
*      END OF %W0101.
*
*DATA: BEGIN OF %W0102 OCCURS 20,
*            ZTCO_SHOPCOST-HWAER LIKE ZTCO_SHOPCOST-HWAER,
*            ZTCO_SHOPCOST-WERTN(16) TYPE P DECIMALS 02,
*            ZTCO_SHOPCOST-WDIFF(16) TYPE P DECIMALS 02,
*            ZTCO_SHOPCOST-WRTFX(16) TYPE P DECIMALS 02,
*      END OF %W0102.
*
*DATA: BEGIN OF %W0103 OCCURS 20,
*            ZTCO_SHOPCOST-HWAER LIKE ZTCO_SHOPCOST-HWAER,
*            ZTCO_SHOPCOST-WERTN(16) TYPE P DECIMALS 02,
*            ZTCO_SHOPCOST-WDIFF(16) TYPE P DECIMALS 02,
*            ZTCO_SHOPCOST-WRTFX(16) TYPE P DECIMALS 02,
*      END OF %W0103.
*
*DATA: BEGIN OF %W0104 OCCURS 20,
*            ZTCO_SHOPCOST-HWAER LIKE ZTCO_SHOPCOST-HWAER,
*            ZTCO_SHOPCOST-WERTN(16) TYPE P DECIMALS 02,
*            ZTCO_SHOPCOST-WDIFF(16) TYPE P DECIMALS 02,
*            ZTCO_SHOPCOST-WRTFX(16) TYPE P DECIMALS 02,
*      END OF %W0104.
*
*DATA: BEGIN OF %W0105 OCCURS 20,
*            ZTCO_SHOPCOST-HWAER LIKE ZTCO_SHOPCOST-HWAER,
*            ZTCO_SHOPCOST-WERTN(16) TYPE P DECIMALS 02,
*            ZTCO_SHOPCOST-WDIFF(16) TYPE P DECIMALS 02,
*            ZTCO_SHOPCOST-WRTFX(16) TYPE P DECIMALS 02,
*      END OF %W0105.
*
*DATA: BEGIN OF %W0106 OCCURS 20,
*            ZTCO_SHOPCOST-HWAER LIKE ZTCO_SHOPCOST-HWAER,
*            ZTCO_SHOPCOST-WERTN(16) TYPE P DECIMALS 02,
*            ZTCO_SHOPCOST-WDIFF(16) TYPE P DECIMALS 02,
*            ZTCO_SHOPCOST-WRTFX(16) TYPE P DECIMALS 02,
*      END OF %W0106.
*
*DATA: BEGIN OF %W0107 OCCURS 20,
*            ZTCO_SHOPCOST-HWAER LIKE ZTCO_SHOPCOST-HWAER,
*            ZTCO_SHOPCOST-WERTN(16) TYPE P DECIMALS 02,
*            ZTCO_SHOPCOST-WDIFF(16) TYPE P DECIMALS 02,
*            ZTCO_SHOPCOST-WRTFX(16) TYPE P DECIMALS 02,
*      END OF %W0107.
*
*DATA: BEGIN OF %W0108 OCCURS 20,
*            ZTCO_SHOPCOST-HWAER LIKE ZTCO_SHOPCOST-HWAER,
*            ZTCO_SHOPCOST-WERTN(16) TYPE P DECIMALS 02,
*            ZTCO_SHOPCOST-WDIFF(16) TYPE P DECIMALS 02,
*            ZTCO_SHOPCOST-WRTFX(16) TYPE P DECIMALS 02,
*      END OF %W0108.
*
*DATA: BEGIN OF %W0109 OCCURS 20,
*            ZTCO_SHOPCOST-HWAER LIKE ZTCO_SHOPCOST-HWAER,
*            ZTCO_SHOPCOST-WERTN(16) TYPE P DECIMALS 02,
*            ZTCO_SHOPCOST-WDIFF(16) TYPE P DECIMALS 02,
*            ZTCO_SHOPCOST-WRTFX(16) TYPE P DECIMALS 02,
*      END OF %W0109.
*
*DATA: BEGIN OF %W0110 OCCURS 20,
*            ZTCO_SHOPCOST-HWAER LIKE ZTCO_SHOPCOST-HWAER,
*            ZTCO_SHOPCOST-WERTN(16) TYPE P DECIMALS 02,
*            ZTCO_SHOPCOST-WDIFF(16) TYPE P DECIMALS 02,
*            ZTCO_SHOPCOST-WRTFX(16) TYPE P DECIMALS 02,
*      END OF %W0110.
*
*DATA: BEGIN OF %W0200 OCCURS 20,
*            ZTCO_SHOPCOST-MEEHT LIKE ZTCO_SHOPCOST-MEEHT,
*            ZTCO_SHOPCOST-MENGE(16) TYPE P DECIMALS 03,
*      END OF %W0200.
*
*DATA: BEGIN OF %W0201 OCCURS 20,
*            ZTCO_SHOPCOST-MEEHT LIKE ZTCO_SHOPCOST-MEEHT,
*            ZTCO_SHOPCOST-MENGE(16) TYPE P DECIMALS 03,
*      END OF %W0201.
*
*DATA: BEGIN OF %W0202 OCCURS 20,
*            ZTCO_SHOPCOST-MEEHT LIKE ZTCO_SHOPCOST-MEEHT,
*            ZTCO_SHOPCOST-MENGE(16) TYPE P DECIMALS 03,
*      END OF %W0202.
*
*DATA: BEGIN OF %W0203 OCCURS 20,
*            ZTCO_SHOPCOST-MEEHT LIKE ZTCO_SHOPCOST-MEEHT,
*            ZTCO_SHOPCOST-MENGE(16) TYPE P DECIMALS 03,
*      END OF %W0203.
*
*DATA: BEGIN OF %W0204 OCCURS 20,
*            ZTCO_SHOPCOST-MEEHT LIKE ZTCO_SHOPCOST-MEEHT,
*            ZTCO_SHOPCOST-MENGE(16) TYPE P DECIMALS 03,
*      END OF %W0204.
*
*DATA: BEGIN OF %W0205 OCCURS 20,
*            ZTCO_SHOPCOST-MEEHT LIKE ZTCO_SHOPCOST-MEEHT,
*            ZTCO_SHOPCOST-MENGE(16) TYPE P DECIMALS 03,
*      END OF %W0205.
*
*DATA: BEGIN OF %W0206 OCCURS 20,
*            ZTCO_SHOPCOST-MEEHT LIKE ZTCO_SHOPCOST-MEEHT,
*            ZTCO_SHOPCOST-MENGE(16) TYPE P DECIMALS 03,
*      END OF %W0206.
*
*DATA: BEGIN OF %W0207 OCCURS 20,
*            ZTCO_SHOPCOST-MEEHT LIKE ZTCO_SHOPCOST-MEEHT,
*            ZTCO_SHOPCOST-MENGE(16) TYPE P DECIMALS 03,
*      END OF %W0207.
*
*DATA: BEGIN OF %W0208 OCCURS 20,
*            ZTCO_SHOPCOST-MEEHT LIKE ZTCO_SHOPCOST-MEEHT,
*            ZTCO_SHOPCOST-MENGE(16) TYPE P DECIMALS 03,
*      END OF %W0208.
*
*DATA: BEGIN OF %W0209 OCCURS 20,
*            ZTCO_SHOPCOST-MEEHT LIKE ZTCO_SHOPCOST-MEEHT,
*            ZTCO_SHOPCOST-MENGE(16) TYPE P DECIMALS 03,
*      END OF %W0209.
*
*DATA: BEGIN OF %W0210 OCCURS 20,
*            ZTCO_SHOPCOST-MEEHT LIKE ZTCO_SHOPCOST-MEEHT,
*            ZTCO_SHOPCOST-MENGE(16) TYPE P DECIMALS 03,
*      END OF %W0210.
*SELECT-OPTIONS SP$00001 FOR ZTCO_SHOPCOST-KOKRS MEMORY ID CAC.
*SELECT-OPTIONS SP$00002 FOR ZTCO_SHOPCOST-BDATJ MEMORY ID BDTJ.
*SELECT-OPTIONS SP$00003 FOR ZTCO_SHOPCOST-POPER MEMORY ID POPR.
*SELECT-OPTIONS SP$00004 FOR ZTCO_SHOPCOST-KLVAR MEMORY ID KRT.
*SELECT-OPTIONS SP$00005 FOR ZTCO_SHOPCOST-VERSN MEMORY ID KVS.
*SELECT-OPTIONS SP$00006 FOR ZTCO_SHOPCOST-RECORD_TYPE.
*SELECT-OPTIONS SP$00007 FOR ZTCO_SHOPCOST-FSC_MATNR MEMORY ID MAT.
*SELECT-OPTIONS SP$00008 FOR ZTCO_SHOPCOST-SHOP.
*SELECT-OPTIONS SP$00009 FOR ZTCO_SHOPCOST-LLV_MATNR MEMORY ID MAT.
*SELECT-OPTIONS SP$00010 FOR ZTCO_SHOPCOST-TYPPS.
*SELECT-OPTIONS SP$00011 FOR ZTCO_SHOPCOST-KSTAR MEMORY ID KAT.
*SELECT-OPTIONS SP$00012 FOR ZTCO_SHOPCOST-ELEMT.
*SELECT-OPTIONS SP$00013 FOR ZTCO_SHOPCOST-KOSTL MEMORY ID KOS.
*SELECT-OPTIONS SP$00014 FOR ZTCO_SHOPCOST-LSTAR MEMORY ID LAR.
*SELECTION-SCREEN SKIP 1.
*SELECTION-SCREEN: BEGIN OF BLOCK DIRECT
*                  WITH FRAME TITLE TEXT-F59.
*SELECTION-SCREEN: BEGIN OF LINE.
*PARAMETERS:       %ALV RADIOBUTTON GROUP FUNC USER-COMMAND OUTBUT
*                         DEFAULT 'X' .
*SELECTION-SCREEN: COMMENT 4(26) TEXT-F72 FOR FIELD %ALV.
*PARAMETERS:       %ALVL TYPE SLIS_VARI.
*SELECTION-SCREEN: PUSHBUTTON 72(4) PB%EXCO USER-COMMAND EXPCOL.
*SELECTION-SCREEN: END OF LINE.
*SELECTION-SCREEN: BEGIN OF LINE.
*PARAMETERS:       %NOFUNC RADIOBUTTON GROUP FUNC MODIF ID OLD.
*SELECTION-SCREEN: COMMENT 4(26) TEXT-F66 FOR FIELD %NOFUNC
*                                         MODIF ID OLD.
*PARAMETERS:       %TVIEW RADIOBUTTON GROUP FUNC MODIF ID OLD.
*SELECTION-SCREEN: COMMENT 34(26) TEXT-F68 FOR FIELD %TVIEW
*                                          MODIF ID OLD,
*                  END OF LINE.
*SELECTION-SCREEN: BEGIN OF LINE.
*PARAMETERS:       %GRAPH RADIOBUTTON GROUP FUNC MODIF ID OLD.
*SELECTION-SCREEN: COMMENT 4(26) TEXT-F61 FOR FIELD %GRAPH
*                                         MODIF ID OLD.
*PARAMETERS:       %TEXT RADIOBUTTON GROUP FUNC MODIF ID OLD.
*SELECTION-SCREEN: COMMENT 34(26) TEXT-F69 FOR FIELD %TEXT
*                                          MODIF ID OLD,
*                  END OF LINE.
*SELECTION-SCREEN: BEGIN OF LINE.
*PARAMETERS:       %ABC RADIOBUTTON GROUP FUNC MODIF ID OLD.
*SELECTION-SCREEN: COMMENT 4(26) TEXT-F70 FOR FIELD %ABC
*                                         MODIF ID OLD.
*PARAMETERS:       %EXCEL RADIOBUTTON GROUP FUNC MODIF ID OLD.
*SELECTION-SCREEN: COMMENT 34(26) TEXT-F60 FOR FIELD %EXCEL
*                                         MODIF ID OLD,
*                  END OF LINE.
*SELECTION-SCREEN: BEGIN OF LINE.
*PARAMETERS:       %EIS RADIOBUTTON GROUP FUNC MODIF ID OLD.
*SELECTION-SCREEN: COMMENT 4(26) TEXT-F63 FOR FIELD %EIS
*                                         MODIF ID OLD.
*SELECTION-SCREEN: END OF LINE.
*SELECTION-SCREEN: BEGIN OF LINE.
*PARAMETERS:       %XINT RADIOBUTTON GROUP FUNC MODIF ID XIN.
*SELECTION-SCREEN: COMMENT 4(26) TEXT-F73 FOR FIELD %XINT
*                                         MODIF ID XIN.
*PARAMETERS:       %XINTK(30) LOWER CASE MODIF ID XIN.
*SELECTION-SCREEN: END OF LINE.
*SELECTION-SCREEN: BEGIN OF LINE.
*PARAMETERS:       %DOWN RADIOBUTTON GROUP FUNC MODIF ID OLD.
*SELECTION-SCREEN: COMMENT 4(26) TEXT-F64 FOR FIELD %DOWN
*                                         MODIF ID OLD.
*PARAMETERS:       %PATH(132) LOWER CASE MODIF ID OLD.
*SELECTION-SCREEN: END OF LINE.
*SELECTION-SCREEN: BEGIN OF LINE.
*PARAMETERS:       %SAVE RADIOBUTTON GROUP FUNC MODIF ID OLD.
*SELECTION-SCREEN: COMMENT 4(26) TEXT-F62 FOR FIELD %SAVE
*                                         MODIF ID OLD.
*PARAMETERS:       %LISTID(40) LOWER CASE MODIF ID OLD.
*SELECTION-SCREEN: END OF LINE.
*SELECTION-SCREEN: END OF BLOCK DIRECT.
*SELECTION-SCREEN: END OF BLOCK PROG.
*
*DATA: BEGIN OF %G00 OCCURS 100,
*            ZTCO_SHOPCOST-KOKRS LIKE ZTCO_SHOPCOST-KOKRS,
*            ZTCO_SHOPCOST-BDATJ LIKE ZTCO_SHOPCOST-BDATJ,
*            ZTCO_SHOPCOST-POPER LIKE ZTCO_SHOPCOST-POPER,
*            ZTCO_SHOPCOST-KLVAR LIKE ZTCO_SHOPCOST-KLVAR,
*            ZTCO_SHOPCOST-VERSN LIKE ZTCO_SHOPCOST-VERSN,
*            ZTCO_SHOPCOST-RECORD_TYPE LIKE ZTCO_SHOPCOST-RECORD_TYPE,
*            ZTCO_SHOPCOST-FSC_MATNR LIKE ZTCO_SHOPCOST-FSC_MATNR,
*            ZTCO_SHOPCOST-SHOP LIKE ZTCO_SHOPCOST-SHOP,
*            ZTCO_SHOPCOST-LLV_MATNR LIKE ZTCO_SHOPCOST-LLV_MATNR,
*            ZTCO_SHOPCOST-TYPPS LIKE ZTCO_SHOPCOST-TYPPS,
*            ZTCO_SHOPCOST-KSTAR LIKE ZTCO_SHOPCOST-KSTAR,
*            ZTCO_SHOPCOST-KALNR LIKE ZTCO_SHOPCOST-KALNR,
*            ZTCO_SHOPCOST-ELEMT LIKE ZTCO_SHOPCOST-ELEMT,
*            ZTCO_SHOPCOST-KOSTL LIKE ZTCO_SHOPCOST-KOSTL,
*            ZTCO_SHOPCOST-LSTAR LIKE ZTCO_SHOPCOST-LSTAR,
*            ZTCO_SHOPCOST-HWAER LIKE ZTCO_SHOPCOST-HWAER,
*            ZTCO_SHOPCOST-MENGE LIKE ZTCO_SHOPCOST-MENGE,
*            ZTCO_SHOPCOST-MEEHT-0117 LIKE ZTCO_SHOPCOST-MEEHT,
*            ZTCO_SHOPCOST-MEEHT LIKE ZTCO_SHOPCOST-MEEHT,
*            ZTCO_SHOPCOST-BESKZ LIKE ZTCO_SHOPCOST-BESKZ,
*            ZTCO_SHOPCOST-SOBSL LIKE ZTCO_SHOPCOST-SOBSL,
*            ZTCO_SHOPCOST-VSPVB LIKE ZTCO_SHOPCOST-VSPVB,
*            ZTCO_SHOPCOST-PAR_KALNR LIKE ZTCO_SHOPCOST-PAR_KALNR,
*            ZTCO_SHOPCOST-PAR_KADKY LIKE ZTCO_SHOPCOST-PAR_KADKY,
*            ZTCO_SHOPCOST-MTART LIKE ZTCO_SHOPCOST-MTART,
*            ZTCO_SHOPCOST-WERTN LIKE ZTCO_SHOPCOST-WERTN,
*            ZTCO_SHOPCOST-WRTFX LIKE ZTCO_SHOPCOST-WRTFX,
*            ZTCO_SHOPCOST-WDIFF LIKE ZTCO_SHOPCOST-WDIFF,
*            ZTCO_SHOPCOST-KADAT LIKE ZTCO_SHOPCOST-KADAT,
*            ZTCO_SHOPCOST-BIDAT LIKE ZTCO_SHOPCOST-BIDAT,
*            ZTCO_SHOPCOST-BZOBJ LIKE ZTCO_SHOPCOST-BZOBJ,
*            ZTCO_SHOPCOST-KALKA LIKE ZTCO_SHOPCOST-KALKA,
*            ZTCO_SHOPCOST-KADKY LIKE ZTCO_SHOPCOST-KADKY,
*            ZTCO_SHOPCOST-TVERS LIKE ZTCO_SHOPCOST-TVERS,
*            ZTCO_SHOPCOST-BWVAR LIKE ZTCO_SHOPCOST-BWVAR,
*            ZTCO_SHOPCOST-KKZMA LIKE ZTCO_SHOPCOST-KKZMA,
*            ZTCO_SHOPCOST-WERKS LIKE ZTCO_SHOPCOST-WERKS,
*            ZTCO_SHOPCOST-BWKEY LIKE ZTCO_SHOPCOST-BWKEY,
*            ZTCO_SHOPCOST-BWTAR LIKE ZTCO_SHOPCOST-BWTAR,
*            ZTCO_SHOPCOST-FROM_PER LIKE ZTCO_SHOPCOST-FROM_PER,
*            ZTCO_SHOPCOST-TO_PER LIKE ZTCO_SHOPCOST-TO_PER,
*            ZTCO_SHOPCOST-ERDAT LIKE ZTCO_SHOPCOST-ERDAT,
*            ZTCO_SHOPCOST-ERZET LIKE ZTCO_SHOPCOST-ERZET,
*            ZTCO_SHOPCOST-ERNAM LIKE ZTCO_SHOPCOST-ERNAM,
*            ZTCO_SHOPCOST-AEDAT LIKE ZTCO_SHOPCOST-AEDAT,
*            ZTCO_SHOPCOST-AEZET LIKE ZTCO_SHOPCOST-AEZET,
*            ZTCO_SHOPCOST-AENAM LIKE ZTCO_SHOPCOST-AENAM,
*      END OF %G00.
*DATA: BEGIN OF %%G00,
*            ZTCO_SHOPCOST-KOKRS(004),
*            ZTCO_SHOPCOST-BDATJ(004),
*            ZTCO_SHOPCOST-POPER(003),
*            ZTCO_SHOPCOST-KLVAR(004),
*            ZTCO_SHOPCOST-VERSN(003),
*            ZTCO_SHOPCOST-RECORD_TYPE(001),
*            ZTCO_SHOPCOST-FSC_MATNR(040),
*            ZTCO_SHOPCOST-SHOP(010),
*            ZTCO_SHOPCOST-LLV_MATNR(040),
*            ZTCO_SHOPCOST-TYPPS(001),
*            ZTCO_SHOPCOST-KSTAR(010),
*            ZTCO_SHOPCOST-KALNR(012),
*            ZTCO_SHOPCOST-ELEMT(003),
*            ZTCO_SHOPCOST-KOSTL(010),
*            ZTCO_SHOPCOST-LSTAR(006),
*            ZTCO_SHOPCOST-HWAER(005),
*            ZTCO_SHOPCOST-MENGE(020),
*            ZTCO_SHOPCOST-MEEHT-0117 LIKE ZTCO_SHOPCOST-MEEHT,
*            ZTCO_SHOPCOST-MEEHT(003),
*            ZTCO_SHOPCOST-BESKZ(001),
*            ZTCO_SHOPCOST-SOBSL(002),
*            ZTCO_SHOPCOST-VSPVB(010),
*            ZTCO_SHOPCOST-PAR_KALNR(012),
*            ZTCO_SHOPCOST-PAR_KADKY(010),
*            ZTCO_SHOPCOST-MTART(004),
*            ZTCO_SHOPCOST-WERTN(021),
*            ZTCO_SHOPCOST-WRTFX(021),
*            ZTCO_SHOPCOST-WDIFF(021),
*            ZTCO_SHOPCOST-KADAT(010),
*            ZTCO_SHOPCOST-BIDAT(010),
*            ZTCO_SHOPCOST-BZOBJ(001),
*            ZTCO_SHOPCOST-KALKA(002),
*            ZTCO_SHOPCOST-KADKY(010),
*            ZTCO_SHOPCOST-TVERS(002),
*            ZTCO_SHOPCOST-BWVAR(003),
*            ZTCO_SHOPCOST-KKZMA(001),
*            ZTCO_SHOPCOST-WERKS(004),
*            ZTCO_SHOPCOST-BWKEY(004),
*            ZTCO_SHOPCOST-BWTAR(010),
*            ZTCO_SHOPCOST-FROM_PER(003),
*            ZTCO_SHOPCOST-TO_PER(003),
*            ZTCO_SHOPCOST-ERDAT(010),
*            ZTCO_SHOPCOST-ERZET(008),
*            ZTCO_SHOPCOST-ERNAM(012),
*            ZTCO_SHOPCOST-AEDAT(010),
*            ZTCO_SHOPCOST-AEZET(008),
*            ZTCO_SHOPCOST-AENAM(012),
*      END OF %%G00.
*DATA %ZNR TYPE I.
*DATA %LZNR TYPE I VALUE 99999.
*FIELD-GROUPS HEADER.
*DATA %GROUP01.
*DATA %%ZTCO_SHOPCOST-KOKRS LIKE ZTCO_SHOPCOST-KOKRS.
*DATA %%%ZTCO_SHOPCOST-KOKRS(1).
*DATA %GROUP0101.
*DATA %GROUP0201.
*DATA %GROUP02.
*DATA %%ZTCO_SHOPCOST-BDATJ LIKE ZTCO_SHOPCOST-BDATJ.
*DATA %%%ZTCO_SHOPCOST-BDATJ(1).
*DATA %GROUP0102.
*DATA %GROUP0202.
*DATA %GROUP03.
*DATA %%ZTCO_SHOPCOST-POPER LIKE ZTCO_SHOPCOST-POPER.
*DATA %%%ZTCO_SHOPCOST-POPER(1).
*DATA %GROUP0103.
*DATA %GROUP0203.
*DATA %GROUP04.
*DATA %%ZTCO_SHOPCOST-KLVAR LIKE ZTCO_SHOPCOST-KLVAR.
*DATA %%%ZTCO_SHOPCOST-KLVAR(1).
*DATA %GROUP0104.
*DATA %GROUP0204.
*DATA %GROUP05.
*DATA %%ZTCO_SHOPCOST-VERSN LIKE ZTCO_SHOPCOST-VERSN.
*DATA %%%ZTCO_SHOPCOST-VERSN(1).
*DATA %GROUP0105.
*DATA %GROUP0205.
*DATA %GROUP06.
*DATA %%ZTCO_SHOPCOST-RECORD_TYPE LIKE ZTCO_SHOPCOST-RECORD_TYPE.
*DATA %%%ZTCO_SHOPCOST-RECORD_TYPE(1).
*DATA %GROUP0106.
*DATA %GROUP0206.
*DATA %GROUP07.
*DATA %%ZTCO_SHOPCOST-FSC_MATNR LIKE ZTCO_SHOPCOST-FSC_MATNR.
*DATA %%%ZTCO_SHOPCOST-FSC_MATNR(1).
*DATA %GROUP0107.
*DATA %GROUP0207.
*DATA %GROUP08.
*DATA %%ZTCO_SHOPCOST-SHOP LIKE ZTCO_SHOPCOST-SHOP.
*DATA %%%ZTCO_SHOPCOST-SHOP(1).
*DATA %GROUP0108.
*DATA %GROUP0208.
*DATA %GROUP09.
*DATA %%ZTCO_SHOPCOST-TYPPS LIKE ZTCO_SHOPCOST-TYPPS.
*DATA %%%ZTCO_SHOPCOST-TYPPS(1).
*DATA %GROUP0109.
*DATA %GROUP0209.
*DATA %GROUP10.
*DATA %%ZTCO_SHOPCOST-ELEMT LIKE ZTCO_SHOPCOST-ELEMT.
*DATA %%%ZTCO_SHOPCOST-ELEMT(1).
*DATA %GROUP0110.
*DATA %GROUP0210.
*FIELD-GROUPS %FG01.
*DATA %ANY-01.
*DATA %EXT-ZTCO_SHOPCOST01.
*FIELD-GROUPS %FG02.
*DATA %ANY-02.
*DATA %EXT-ZTCO_SHOPCOST02.
*FIELD-GROUPS %FGWRZTCO_SHOPCOST02.
*FIELD-GROUPS %FGWRZTCO_SHOPCOST01.
*
*CONTROLS TVIEW100 TYPE TABLEVIEW USING SCREEN 100.
*
*AT SELECTION-SCREEN .
*PERFORM ALVL_CHECK(RSAQEXCE) USING %ALVL 'G00'.
*PERFORM TESTMODE(RSAQEXCE).
*PERFORM CHECK_EXPCOL(RSAQEXCE) USING %ALV.
*
*
*AT SELECTION-SCREEN ON VALUE-REQUEST FOR %ALVL .
*PERFORM ALVL_VALUE_REQUEST(RSAQEXCE) USING %ALVL 'G00'.
*
*AT SELECTION-SCREEN ON VALUE-REQUEST FOR %XINTK .
*PERFORM XINT_VALUE_REQUEST(RSAQEXCE).
*
*AT SELECTION-SCREEN OUTPUT .
*
*PERFORM RINIT(RSAQBRST).
*PERFORM SET_EXPCOL(RSAQEXCE) USING %ALV PB%EXCO.
*PERFORM ALVL_SET_INVISIBLE(RSAQEXCE).
*PERFORM SET_XINT_PARAMS(RSAQEXCE).
*
*INITIALIZATION.
*PERFORM INIT_XINT(RSAQEXCE).
*PERFORM SET_WWW_FLAGS(RSAQEXCE).
*PERFORM INIT_PRINT_PARAMS(RSAQEXCE).
*
*START-OF-SELECTION.
*INSERT ZTCO_SHOPCOST-HWAER INTO %FGWRZTCO_SHOPCOST02.
*INSERT ZTCO_SHOPCOST-WERTN INTO %FGWRZTCO_SHOPCOST02.
*INSERT ZTCO_SHOPCOST-WDIFF INTO %FGWRZTCO_SHOPCOST02.
*INSERT ZTCO_SHOPCOST-WRTFX INTO %FGWRZTCO_SHOPCOST02.
*INSERT ZTCO_SHOPCOST-MEEHT INTO %FGWRZTCO_SHOPCOST01.
*INSERT ZTCO_SHOPCOST-MENGE INTO %FGWRZTCO_SHOPCOST01.
*INSERT ZTCO_SHOPCOST-KOKRS INTO HEADER.
*INSERT ZTCO_SHOPCOST-BDATJ INTO HEADER.
*INSERT ZTCO_SHOPCOST-POPER INTO HEADER.
*INSERT ZTCO_SHOPCOST-KLVAR INTO HEADER.
*INSERT ZTCO_SHOPCOST-VERSN INTO HEADER.
*INSERT ZTCO_SHOPCOST-RECORD_TYPE INTO HEADER.
*INSERT ZTCO_SHOPCOST-FSC_MATNR INTO HEADER.
*INSERT ZTCO_SHOPCOST-SHOP INTO HEADER.
*INSERT ZTCO_SHOPCOST-TYPPS INTO HEADER.
*INSERT ZTCO_SHOPCOST-ELEMT INTO HEADER.
*INSERT %COUNT-ZTCO_SHOPCOST INTO HEADER.
*INSERT %LINR-ZTCO_SHOPCOST INTO HEADER.
*INSERT ZTCO_SHOPCOST-LLV_MATNR INTO %FG01.
*INSERT ZTCO_SHOPCOST-KSTAR INTO %FG01.
*INSERT ZTCO_SHOPCOST-KALNR INTO %FG01.
*INSERT ZTCO_SHOPCOST-KOSTL INTO %FG01.
*INSERT ZTCO_SHOPCOST-LSTAR INTO %FG01.
*INSERT ZTCO_SHOPCOST-HWAER INTO %FG01.
*INSERT ZTCO_SHOPCOST-MENGE INTO %FG01.
*INSERT ZTCO_SHOPCOST-MEEHT INTO %FG01.
*INSERT ZTCO_SHOPCOST-MEEHT INTO %FG01.
*INSERT ZTCO_SHOPCOST-BESKZ INTO %FG01.
*INSERT ZTCO_SHOPCOST-SOBSL INTO %FG01.
*INSERT ZTCO_SHOPCOST-VSPVB INTO %FG01.
*INSERT ZTCO_SHOPCOST-PAR_KALNR INTO %FG01.
*INSERT ZTCO_SHOPCOST-PAR_KADKY INTO %FG01.
*INSERT ZTCO_SHOPCOST-MTART INTO %FG01.
*INSERT ZTCO_SHOPCOST-WERTN INTO %FG02.
*INSERT ZTCO_SHOPCOST-HWAER INTO %FG02.
*INSERT ZTCO_SHOPCOST-WRTFX INTO %FG02.
*INSERT ZTCO_SHOPCOST-HWAER INTO %FG02.
*INSERT ZTCO_SHOPCOST-WDIFF INTO %FG02.
*INSERT ZTCO_SHOPCOST-HWAER INTO %FG02.
*INSERT ZTCO_SHOPCOST-KADAT INTO %FG02.
*INSERT ZTCO_SHOPCOST-BIDAT INTO %FG02.
*INSERT ZTCO_SHOPCOST-BZOBJ INTO %FG02.
*INSERT ZTCO_SHOPCOST-KALKA INTO %FG02.
*INSERT ZTCO_SHOPCOST-KADKY INTO %FG02.
*INSERT ZTCO_SHOPCOST-TVERS INTO %FG02.
*INSERT ZTCO_SHOPCOST-BWVAR INTO %FG02.
*INSERT ZTCO_SHOPCOST-KKZMA INTO %FG02.
*INSERT ZTCO_SHOPCOST-WERKS INTO %FG02.
*INSERT ZTCO_SHOPCOST-BWKEY INTO %FG02.
*INSERT ZTCO_SHOPCOST-BWTAR INTO %FG02.
*INSERT ZTCO_SHOPCOST-FROM_PER INTO %FG02.
*INSERT ZTCO_SHOPCOST-TO_PER INTO %FG02.
*INSERT ZTCO_SHOPCOST-ERDAT INTO %FG02.
*INSERT ZTCO_SHOPCOST-ERZET INTO %FG02.
*INSERT ZTCO_SHOPCOST-ERNAM INTO %FG02.
*INSERT ZTCO_SHOPCOST-AEDAT INTO %FG02.
*INSERT ZTCO_SHOPCOST-AEZET INTO %FG02.
*INSERT ZTCO_SHOPCOST-AENAM INTO %FG02.
*PERFORM INIT_TEXTHANDLING(RSAQEXCE) USING 'CL_TEXT_IDENTIFIER' ' '
*        'SYSTQV000000000000000017'.
*PERFORM AUTHORITY_BEGIN(RSAQEXCE).
*PERFORM AUTHORITY(RSAQEXCE) USING 'ZTCO_SHOPCOST'.
*PERFORM AUTHORITY_END(RSAQEXCE).
*PERFORM %COMP_LDESC.
*SELECT AEDAT AENAM AEZET BDATJ BESKZ BIDAT BWKEY BWTAR BWVAR BZOBJ
*       ELEMT ERDAT ERNAM ERZET FROM_PER FSC_MATNR HWAER KADAT KADKY
*       KALKA KALNR KKZMA KLVAR KOKRS KOSTL KSTAR LLV_MATNR LSTAR MEEHT
*       MENGE MTART PAR_KADKY PAR_KALNR POPER RECORD_TYPE SHOP SOBSL
*       TO_PER TVERS TYPPS VERSN VSPVB WDIFF WERKS WERTN WRTFX
*       INTO CORRESPONDING FIELDS OF ZTCO_SHOPCOST
*       FROM ZTCO_SHOPCOST
*       WHERE BDATJ IN SP$00002
*         AND ELEMT IN SP$00012
*         AND FSC_MATNR IN SP$00007
*         AND KLVAR IN SP$00004
*         AND KOKRS IN SP$00001
*         AND KOSTL IN SP$00013
*         AND KSTAR IN SP$00011
*         AND LLV_MATNR IN SP$00009
*         AND LSTAR IN SP$00014
*         AND POPER IN SP$00003
*         AND RECORD_TYPE IN SP$00006
*         AND SHOP IN SP$00008
*         AND TYPPS IN SP$00010
*         AND VERSN IN SP$00005.
*  %DBACC = %DBACC - 1.
*  IF %DBACC = 0.
*    STOP.
*  ENDIF.
*  ADD 1 TO %COUNT-ZTCO_SHOPCOST.
*  %LINR-ZTCO_SHOPCOST = '01'.
*  EXTRACT %FG01.
*  %EXT-ZTCO_SHOPCOST01 = 'X'.
*    EXTRACT %FGWRZTCO_SHOPCOST01.
*  %LINR-ZTCO_SHOPCOST = '02'.
*  EXTRACT %FG02.
*  %EXT-ZTCO_SHOPCOST02 = 'X'.
*    EXTRACT %FGWRZTCO_SHOPCOST02.
*ENDSELECT.
*
*END-OF-SELECTION.
*SORT AS TEXT BY
*        ZTCO_SHOPCOST-KOKRS
*        ZTCO_SHOPCOST-BDATJ
*        ZTCO_SHOPCOST-POPER
*        ZTCO_SHOPCOST-KLVAR
*        ZTCO_SHOPCOST-VERSN
*        ZTCO_SHOPCOST-RECORD_TYPE
*        ZTCO_SHOPCOST-FSC_MATNR
*        ZTCO_SHOPCOST-SHOP
*        ZTCO_SHOPCOST-TYPPS
*        ZTCO_SHOPCOST-ELEMT
*        %COUNT-ZTCO_SHOPCOST
*        %LINR-ZTCO_SHOPCOST.
*%DIACT = SPACE.
*%BATCH = SY-BATCH.
*IF %BATCH <> SPACE.
*  IF %EIS <> SPACE.
*    %DIACT = 'E'.
*    IF %EISPROTOCOL = SPACE.
*      NEW-PAGE PRINT ON DESTINATION 'NULL' NO DIALOG
*               LINE-SIZE 0253 LINE-COUNT 0065.
*    ELSE.
*      NEW-PAGE PRINT ON NO DIALOG
*               PARAMETERS %INIT_PRI_PARAMS.
*    ENDIF.
*  ENDIF.
*  IF %ALV <> SPACE.
*    %DIACT = 'V'.
*    %ALV_LAYOUT = %ALVL.
*    NEW-PAGE PRINT ON DESTINATION 'NULL' NO DIALOG
*             LINE-SIZE 0253 LINE-COUNT 0065.
*  ENDIF.
*  IF %SAVE <> SPACE.
*    %DIACT = 'S'.
*    NEW-PAGE PRINT ON DESTINATION 'NULL' NO DIALOG
*             LINE-SIZE 0253 LINE-COUNT 0065.
*  ENDIF.
*ELSEIF %CALLED_BY_WWW <> SPACE.
*  %DIACT = SPACE.
*ELSEIF %CALLED_BY_WWW_ALV <> SPACE.
*  %DIACT = 'V'.
*ELSE.
*  PERFORM INIT_PRINT_PARAMS(RSAQEXCE).
*  IF %SAVE  <> SPACE. %DIACT = 'S'. ENDIF.
*  IF %XINT  <> SPACE. %DIACT = 'I'. ENDIF.
*  IF %TVIEW <> SPACE. %DIACT = 'T'. ENDIF.
*  IF %ALV   <> SPACE. %DIACT = 'V'. ENDIF.
*  IF %DOWN  <> SPACE. %DIACT = 'D'. ENDIF.
*  IF %EIS   <> SPACE. %DIACT = 'E'. ENDIF.
*  IF %GRAPH <> SPACE. %DIACT = 'G'. ENDIF.
*  IF %EXCEL <> SPACE. %DIACT = 'X'. ENDIF.
*  IF %TEXT  <> SPACE. %DIACT = 'W'. ENDIF.
*  IF %ABC   <> SPACE. %DIACT = 'A'. ENDIF.
*  IF %DIACT <> SPACE AND %DIACT <> 'S' AND %DIACT <> 'W'.
*    NEW-PAGE PRINT ON DESTINATION 'NULL' NO DIALOG
*             LINE-SIZE 0253 LINE-COUNT 0065.
*  ENDIF.
*  %PATHNAME = %PATH.
*  IF %DIACT = 'I'.
*    %FUNCTIONKEY = %XINTK.
*  ENDIF.
*  IF %DIACT = 'V'.
*    %ALV_LAYOUT = %ALVL.
*  ENDIF.
*ENDIF.
*FREE MEMORY ID 'AQLISTDATA'.
*IF %MEMMODE <> SPACE.
*  IF %BATCH <> SPACE.
*    NEW-PAGE PRINT ON DESTINATION 'NULL' NO DIALOG
*             LINE-SIZE 0253 LINE-COUNT 0065.
*  ENDIF.
*  %DIACT = '1'.
*ENDIF.
*%TITEL = ' '.
*IF SY-SUBTY O %PRFLAG AND %TITEL = SPACE.
*  NEW-PAGE WITH-TITLE.
*ENDIF.
*%TVSIZE = 0200.
*%PLINE = 1.
*%PZGR  = 1.
*%FIRST = 'X'.
*PERFORM %OUTPUT.
*%FIRST = SPACE.
*IF %DIACT <> SPACE AND %DIACT <> 'S'.
*  IF %BATCH = SPACE.
*    NEW-PAGE PRINT OFF.
*    IF NOT ( %DIACT = 'V' AND %UCOMM = 'PRIN' ).
*      NEW-PAGE NO-HEADING NO-TITLE.
*      WRITE SPACE.
*    ENDIF.
*  ENDIF.
*ELSE.
*  PERFORM PF-STATUS(RSAQEXCE) USING 'XXX X '.
*ENDIF.
*CLEAR: %TAB, %LINE, %CONT.
*IF %DATA_SELECTED = SPACE.
*  IF %DIACT = '1'.
*    EXPORT EMPTY FROM %EMPTY TO MEMORY ID 'AQLISTDATA'.
*    LEAVE.
*  ELSE.
*    IF %BATCH = SPACE AND
*       %CALLED_BY_WWW = SPACE AND
*       %CALLED_BY_WWW_ALV = SPACE.
*      MESSAGE S260(AQ).
*      LEAVE LIST-PROCESSING.
*    ELSE.
*      IF %CALLED_BY_WWW_ALV = SPACE.
*        %DIACT = SPACE.
*      ENDIF.
*    ENDIF.
*  ENDIF.
*ENDIF.
*IF %DIACT = 'S'.
*  PERFORM %SAVE_LIST.
*  LEAVE LIST-PROCESSING.
*ENDIF.
*IF %DIACT = 'V' AND %BATCH <> SPACE.
*  NEW-PAGE PRINT OFF.
*  PERFORM SET_PRINT_PARAMS(RSAQEXCE).
*  PERFORM %DOWNLOAD USING 'ALV'.
*  LEAVE.
*ENDIF.
*IF %DIACT = 'V' AND %CALLED_BY_WWW_ALV <> SPACE.
*  PERFORM %DOWNLOAD USING 'ALV'.
*  LEAVE.
*ENDIF.
*IF %DIACT = 'V' AND %UCOMM = 'PRIN'.
*  NEW-PAGE PRINT OFF.
*  PERFORM SET_PRINT_PARAMS(RSAQEXCE).
*  PERFORM %DOWNLOAD USING 'ALV'.
*  LEAVE LIST-PROCESSING.
*ENDIF.
*IF %DIACT = 'P' AND %BATCH <> SPACE.
*  PERFORM %DOWNLOAD USING '+DAT'.
*  LEAVE LIST-PROCESSING.
*ENDIF.
*IF %DIACT = 'E' AND %BATCH <> SPACE.
*  PERFORM %DOWNLOAD USING 'EIS'.
*  LEAVE LIST-PROCESSING.
*ENDIF.
*IF %DIACT = '1'.
*  PERFORM %DOWNLOAD USING '+MEM'.
*  LEAVE.
*ENDIF.
*IF %DIACT = 'X'.
*  SET USER-COMMAND 'XXL'.
*ELSEIF %DIACT = 'W'.
*  SET USER-COMMAND 'TEXT'.
*ELSEIF %DIACT = 'V'.
*  SET USER-COMMAND 'ALV'.
*ELSEIF %DIACT = 'T'.
*  SET USER-COMMAND 'VIEW'.
*ELSEIF %DIACT = 'G'.
*  SET USER-COMMAND 'GRAF'.
*ELSEIF %DIACT = 'A'.
*  SET USER-COMMAND 'ABCA'.
*ELSEIF %DIACT = 'E'.
*  SET USER-COMMAND 'EIS'.
*ELSEIF %DIACT = 'D'.
*  SET USER-COMMAND 'DOWN'.
*ELSEIF %DIACT = 'I'.
*  SET USER-COMMAND 'XINT'.
*ELSEIF %DIACT = 'P'.
*  SET USER-COMMAND '+DAT'.
*ENDIF.
*
*TOP-OF-PAGE.
*PERFORM %TOP-OF-PAGE.
*
*END-OF-PAGE.
*PERFORM PAGE_FOOT(RSAQEXCE).
*PERFORM %SAVE_PAGE.
*
*TOP-OF-PAGE DURING LINE-SELECTION.
*PERFORM %TOP-OF-PAGE.
*
*AT USER-COMMAND.
*CASE SY-UCOMM.
*WHEN 'EXIT'.
*  LEAVE PROGRAM.
*WHEN 'RETN'.
*  PERFORM RETURN(RSAQEXCE).
*WHEN 'CANC'.
*  PERFORM RETURN(RSAQEXCE).
*WHEN 'WEIT'.
*  PERFORM RETURN(RSAQEXCE).
*WHEN 'INHA'.
*  PERFORM CATALOGUE(RSAQEXCE).
*WHEN 'AUSL'.
*  PERFORM PICKUP(RSAQEXCE).
*WHEN 'AUSW'.
*  PERFORM PICKUP(RSAQEXCE).
*WHEN 'RCAA'.
*  PERFORM RCHAIN(RSAQBRST).
*WHEN 'RCAL'.
*  PERFORM RCALL(RSAQBRST).
*WHEN 'VGLI'.
*  PERFORM CHANGE(RSAQEXCE).
*WHEN 'VGLE'.
*  PERFORM CHANGE(RSAQEXCE).
*WHEN 'TOTO'.
*  PERFORM CHANGE(RSAQEXCE).
*WHEN 'VSTA'.
*  PERFORM CHANGE(RSAQEXCE).
*WHEN 'VSTE'.
*  PERFORM RETURN(RSAQEXCE).
*WHEN 'SAVL'.
*  PERFORM %SAVE_LIST.
*WHEN 'ODRU'.
*  PERFORM PRINT_LIST(RSAQEXCE).
*WHEN 'COPA'.
*  PERFORM PRINT_COVER_PAGE(RSAQEXCE).
*WHEN 'TEXT'.
*  PERFORM %DOWNLOAD USING 'TEXT'.
*WHEN 'ALV'.
*  PERFORM %DOWNLOAD USING 'ALV'.
*WHEN 'VIEW'.
*  PERFORM %VIEW.
*WHEN 'XXL'.
*  PERFORM %DOWNLOAD USING 'XXL'.
*WHEN 'GRAF'.
*  PERFORM %DOWNLOAD USING 'GRAF'.
*WHEN 'ABCA'.
*  PERFORM %DOWNLOAD USING 'ABCA'.
*WHEN 'EIS'.
*  PERFORM %DOWNLOAD USING 'EIS'.
*WHEN 'DOWN'.
*  PERFORM %DOWNLOAD USING 'DOWN'.
*WHEN 'XINT'.
*  PERFORM %DOWNLOAD USING 'XINT'.
*ENDCASE.
*CLEAR: %CLINE, %ZGR.
*CLEAR: %TAB, %LINE, %CONT.
*IF %DIACT <> SPACE.
*  LEAVE LIST-PROCESSING.
*ENDIF.
*
*
*FORM %COMP_LDESC.
*
*  REFRESH %LDESC.
*  REFRESH %GDESC.
*  PERFORM LDESC(RSAQEXCE) USING 'G00010000X004       01  98'
*    TEXT-A00 TEXT-B00 TEXT-H00 'ZTCO_SHOPCOST-KOKRS'
*    ZTCO_SHOPCOST-KOKRS 'ZTCO_SHOPCOST-KOKRS'.
*  PERFORM LDESC(RSAQEXCE) USING 'G00020000X004       02  98'
*    TEXT-A01 TEXT-B01 TEXT-H00 'ZTCO_SHOPCOST-BDATJ'
*    ZTCO_SHOPCOST-BDATJ 'ZTCO_SHOPCOST-BDATJ'.
*  PERFORM LDESC(RSAQEXCE) USING 'G00030000X003       03  98'
*    TEXT-A02 TEXT-B02 TEXT-H00 'ZTCO_SHOPCOST-POPER'
*    ZTCO_SHOPCOST-POPER 'ZTCO_SHOPCOST-POPER'.
*  PERFORM LDESC(RSAQEXCE) USING 'G00040000X004       04  98'
*    TEXT-A03 TEXT-B03 TEXT-H00 'ZTCO_SHOPCOST-KLVAR'
*    ZTCO_SHOPCOST-KLVAR 'ZTCO_SHOPCOST-KLVAR'.
*  PERFORM LDESC(RSAQEXCE) USING 'G00050000X003       05  98'
*    TEXT-A04 TEXT-B04 TEXT-H00 'ZTCO_SHOPCOST-VERSN'
*    ZTCO_SHOPCOST-VERSN 'ZTCO_SHOPCOST-VERSN'.
*  PERFORM LDESC(RSAQEXCE) USING 'G00060000X001       06  98'
*    TEXT-A05 TEXT-B05 TEXT-H00 'ZTCO_SHOPCOST-RECORD_TYPE'
*    ZTCO_SHOPCOST-RECORD_TYPE 'ZTCO_SHOPCOST-RECORD_TYPE'.
*  PERFORM LDESC(RSAQEXCE) USING 'G00070000X040       07  98'
*    TEXT-A06 TEXT-B06 TEXT-H00 'ZTCO_SHOPCOST-FSC_MATNR'
*    ZTCO_SHOPCOST-FSC_MATNR 'ZTCO_SHOPCOST-FSC_MATNR'.
*  PERFORM LDESC(RSAQEXCE) USING 'G00080000X010       08  98'
*    TEXT-A07 TEXT-B07 TEXT-H00 'ZTCO_SHOPCOST-SHOP' ZTCO_SHOPCOST-SHOP
*    'ZTCO_SHOPCOST-SHOP'.
*  PERFORM LDESC(RSAQEXCE) USING 'G00090000X040       00  98'
*    TEXT-A08 TEXT-B08 TEXT-H00 'ZTCO_SHOPCOST-LLV_MATNR'
*    ZTCO_SHOPCOST-LLV_MATNR 'ZTCO_SHOPCOST-LLV_MATNR'.
*  PERFORM LDESC(RSAQEXCE) USING 'G00100000X001       09  98'
*    TEXT-A09 TEXT-B09 TEXT-H00 'ZTCO_SHOPCOST-TYPPS'
*    ZTCO_SHOPCOST-TYPPS 'ZTCO_SHOPCOST-TYPPS'.
*  PERFORM LDESC(RSAQEXCE) USING 'G00110000X010       00  98'
*    TEXT-A10 TEXT-B10 TEXT-H00 'ZTCO_SHOPCOST-KSTAR'
*    ZTCO_SHOPCOST-KSTAR 'ZTCO_SHOPCOST-KSTAR'.
*  PERFORM LDESC(RSAQEXCE) USING 'G00120000X012       00  98'
*    TEXT-A11 TEXT-B11 TEXT-H00 'ZTCO_SHOPCOST-KALNR'
*    ZTCO_SHOPCOST-KALNR 'ZTCO_SHOPCOST-KALNR'.
*  PERFORM LDESC(RSAQEXCE) USING 'G00130000X003       10  98'
*    TEXT-A12 TEXT-B12 TEXT-H00 'ZTCO_SHOPCOST-ELEMT'
*    ZTCO_SHOPCOST-ELEMT 'ZTCO_SHOPCOST-ELEMT'.
*  PERFORM LDESC(RSAQEXCE) USING 'G00140000X010       00  98'
*    TEXT-A13 TEXT-B13 TEXT-H00 'ZTCO_SHOPCOST-KOSTL'
*    ZTCO_SHOPCOST-KOSTL 'ZTCO_SHOPCOST-KOSTL'.
*  PERFORM LDESC(RSAQEXCE) USING 'G00150000X006       00  98'
*    TEXT-A14 TEXT-B14 TEXT-H00 'ZTCO_SHOPCOST-LSTAR'
*    ZTCO_SHOPCOST-LSTAR 'ZTCO_SHOPCOST-LSTAR'.
*  PERFORM LDESC(RSAQEXCE) USING 'G00160000X005       00  98'
*    TEXT-A15 TEXT-B15 TEXT-H00 'ZTCO_SHOPCOST-HWAER'
*    ZTCO_SHOPCOST-HWAER 'ZTCO_SHOPCOST-HWAER'.
*  PERFORM LDESC(RSAQEXCE) USING 'G00170174 020M    X 00  98'
*    TEXT-A16 TEXT-B16 TEXT-H00 'ZTCO_SHOPCOST-MENGE'
*    ZTCO_SHOPCOST-MENGE 'ZTCO_SHOPCOST-MENGE'.
*  PERFORM LDESC(RSAQEXCE) USING 'G00180000 003E      00  98'
*    TEXT-A17 TEXT-B17 TEXT-H00 'ZTCO_SHOPCOST-MEEHT'
*    ZTCO_SHOPCOST-MEEHT 'ZTCO_SHOPCOST-MEEHT-0117'.
*  PERFORM LDESC(RSAQEXCE) USING 'G00190000X003       00  98'
*    TEXT-A18 TEXT-B18 TEXT-H00 'ZTCO_SHOPCOST-MEEHT'
*    ZTCO_SHOPCOST-MEEHT 'ZTCO_SHOPCOST-MEEHT'.
*  PERFORM LDESC(RSAQEXCE) USING 'G00200000X001       00  98'
*    TEXT-A19 TEXT-B19 TEXT-H00 'ZTCO_SHOPCOST-BESKZ'
*    ZTCO_SHOPCOST-BESKZ 'ZTCO_SHOPCOST-BESKZ'.
*  PERFORM LDESC(RSAQEXCE) USING 'G00210000X002       00  98'
*    TEXT-A20 TEXT-B20 TEXT-H00 'ZTCO_SHOPCOST-SOBSL'
*    ZTCO_SHOPCOST-SOBSL 'ZTCO_SHOPCOST-SOBSL'.
*  PERFORM LDESC(RSAQEXCE) USING 'G00220000X010       00  98'
*    TEXT-A21 TEXT-B21 TEXT-H00 'ZTCO_SHOPCOST-VSPVB'
*    ZTCO_SHOPCOST-VSPVB 'ZTCO_SHOPCOST-VSPVB'.
*  PERFORM LDESC(RSAQEXCE) USING 'G00230000X012       00  98'
*    TEXT-A22 TEXT-B22 TEXT-H00 'ZTCO_SHOPCOST-PAR_KALNR'
*    ZTCO_SHOPCOST-PAR_KALNR 'ZTCO_SHOPCOST-PAR_KALNR'.
*  PERFORM LDESC(RSAQEXCE) USING 'G00240000X010       00  98'
*    TEXT-A23 TEXT-B23 TEXT-H00 'ZTCO_SHOPCOST-PAR_KADKY'
*    ZTCO_SHOPCOST-PAR_KADKY 'ZTCO_SHOPCOST-PAR_KADKY'.
*  PERFORM LDESC(RSAQEXCE) USING 'G00250000X004       00  98'
*    TEXT-A24 TEXT-B24 TEXT-H00 'ZTCO_SHOPCOST-MTART'
*    ZTCO_SHOPCOST-MTART 'ZTCO_SHOPCOST-MTART'.
*  PERFORM LDESC(RSAQEXCE) USING 'G00261002 021     X 00  98'
*    TEXT-A25 TEXT-B25 TEXT-H00 'ZTCO_SHOPCOST-WERTN'
*    ZTCO_SHOPCOST-WERTN 'ZTCO_SHOPCOST-WERTN'.
*  PERFORM LDESC(RSAQEXCE) USING 'G00271030 021     X 00  98'
*    TEXT-A26 TEXT-B26 TEXT-H00 'ZTCO_SHOPCOST-WRTFX'
*    ZTCO_SHOPCOST-WRTFX 'ZTCO_SHOPCOST-WRTFX'.
*  PERFORM LDESC(RSAQEXCE) USING 'G00281058 021     X 00  98'
*    TEXT-A27 TEXT-B27 TEXT-H00 'ZTCO_SHOPCOST-WDIFF'
*    ZTCO_SHOPCOST-WDIFF 'ZTCO_SHOPCOST-WDIFF'.
*  PERFORM LDESC(RSAQEXCE) USING 'G00291000X010       00  98'
*    TEXT-A28 TEXT-B28 TEXT-H00 'ZTCO_SHOPCOST-KADAT'
*    ZTCO_SHOPCOST-KADAT 'ZTCO_SHOPCOST-KADAT'.
*  PERFORM LDESC(RSAQEXCE) USING 'G00301000X010       00  98'
*    TEXT-A29 TEXT-B29 TEXT-H00 'ZTCO_SHOPCOST-BIDAT'
*    ZTCO_SHOPCOST-BIDAT 'ZTCO_SHOPCOST-BIDAT'.
*  PERFORM LDESC(RSAQEXCE) USING 'G00311000X001       00  98'
*    TEXT-A30 TEXT-B30 TEXT-H00 'ZTCO_SHOPCOST-BZOBJ'
*    ZTCO_SHOPCOST-BZOBJ 'ZTCO_SHOPCOST-BZOBJ'.
*  PERFORM LDESC(RSAQEXCE) USING 'G00321000X002       00  98'
*    TEXT-A31 TEXT-B31 TEXT-H00 'ZTCO_SHOPCOST-KALKA'
*    ZTCO_SHOPCOST-KALKA 'ZTCO_SHOPCOST-KALKA'.
*  PERFORM LDESC(RSAQEXCE) USING 'G00331000X010       00  98'
*    TEXT-A32 TEXT-B32 TEXT-H00 'ZTCO_SHOPCOST-KADKY'
*    ZTCO_SHOPCOST-KADKY 'ZTCO_SHOPCOST-KADKY'.
*  PERFORM LDESC(RSAQEXCE) USING 'G00341000X002       00  98'
*    TEXT-A33 TEXT-B33 TEXT-H00 'ZTCO_SHOPCOST-TVERS'
*    ZTCO_SHOPCOST-TVERS 'ZTCO_SHOPCOST-TVERS'.
*  PERFORM LDESC(RSAQEXCE) USING 'G00351000X003       00  98'
*    TEXT-A34 TEXT-B34 TEXT-H00 'ZTCO_SHOPCOST-BWVAR'
*    ZTCO_SHOPCOST-BWVAR 'ZTCO_SHOPCOST-BWVAR'.
*  PERFORM LDESC(RSAQEXCE) USING 'G00361000X001       00  98'
*    TEXT-A35 TEXT-B35 TEXT-H00 'ZTCO_SHOPCOST-KKZMA'
*    ZTCO_SHOPCOST-KKZMA 'ZTCO_SHOPCOST-KKZMA'.
*  PERFORM LDESC(RSAQEXCE) USING 'G00371000X004       00  98'
*    TEXT-A36 TEXT-B36 TEXT-H00 'ZTCO_SHOPCOST-WERKS'
*    ZTCO_SHOPCOST-WERKS 'ZTCO_SHOPCOST-WERKS'.
*  PERFORM LDESC(RSAQEXCE) USING 'G00381000X004       00  98'
*    TEXT-A37 TEXT-B37 TEXT-H00 'ZTCO_SHOPCOST-BWKEY'
*    ZTCO_SHOPCOST-BWKEY 'ZTCO_SHOPCOST-BWKEY'.
*  PERFORM LDESC(RSAQEXCE) USING 'G00391000X010       00  98'
*    TEXT-A38 TEXT-B38 TEXT-H00 'ZTCO_SHOPCOST-BWTAR'
*    ZTCO_SHOPCOST-BWTAR 'ZTCO_SHOPCOST-BWTAR'.
*  PERFORM LDESC(RSAQEXCE) USING 'G00401000X003       00  98'
*    TEXT-A39 TEXT-B39 TEXT-H00 'ZTCO_SHOPCOST-FROM_PER'
*    ZTCO_SHOPCOST-FROM_PER 'ZTCO_SHOPCOST-FROM_PER'.
*  PERFORM LDESC(RSAQEXCE) USING 'G00411000X003       00  98'
*    TEXT-A40 TEXT-B40 TEXT-H00 'ZTCO_SHOPCOST-TO_PER'
*    ZTCO_SHOPCOST-TO_PER 'ZTCO_SHOPCOST-TO_PER'.
*  PERFORM LDESC(RSAQEXCE) USING 'G00421000X010       00  98'
*    TEXT-A41 TEXT-B41 TEXT-H00 'ZTCO_SHOPCOST-ERDAT'
*    ZTCO_SHOPCOST-ERDAT 'ZTCO_SHOPCOST-ERDAT'.
*  PERFORM LDESC(RSAQEXCE) USING 'G00431000X008       00  98'
*    TEXT-A42 TEXT-B42 TEXT-H00 'ZTCO_SHOPCOST-ERZET'
*    ZTCO_SHOPCOST-ERZET 'ZTCO_SHOPCOST-ERZET'.
*  PERFORM LDESC(RSAQEXCE) USING 'G00441000X012       00  98'
*    TEXT-A43 TEXT-B43 TEXT-H00 'ZTCO_SHOPCOST-ERNAM'
*    ZTCO_SHOPCOST-ERNAM 'ZTCO_SHOPCOST-ERNAM'.
*  PERFORM LDESC(RSAQEXCE) USING 'G00451000X010       00  98'
*    TEXT-A44 TEXT-B44 TEXT-H00 'ZTCO_SHOPCOST-AEDAT'
*    ZTCO_SHOPCOST-AEDAT 'ZTCO_SHOPCOST-AEDAT'.
*  PERFORM LDESC(RSAQEXCE) USING 'G00461000X008       00  98'
*    TEXT-A45 TEXT-B45 TEXT-H00 'ZTCO_SHOPCOST-AEZET'
*    ZTCO_SHOPCOST-AEZET 'ZTCO_SHOPCOST-AEZET'.
*  PERFORM LDESC(RSAQEXCE) USING 'G00471000X012       00  98'
*    TEXT-A46 TEXT-B46 TEXT-H00 'ZTCO_SHOPCOST-AENAM'
*    ZTCO_SHOPCOST-AENAM 'ZTCO_SHOPCOST-AENAM'.
*  PERFORM GDESC(RSAQEXCE) USING 'G00' 5 20 ' ' ' ' 'X'.
*  PERFORM COMPLETE_LDESC(RSAQEXCE) TABLES %LDESC.
*
*ENDFORM.
*
*FORM %OUTPUT.
*
*DESCRIBE TABLE %PRLIST LINES %MAX_PRLIST.
*%HEAD = 'AAA'.
*%KEYEMPTY = SPACE.
*NEW-PAGE.
*PERFORM %OUTPUT_GL.
*PERFORM COMPLETE_PAGE(RSAQEXCE).
*%HEAD = 'ZZZ'.
*PERFORM LAST_PTAB_ENTRY(RSAQEXCE).
*NEW-PAGE.
*IF %KEYEMPTY <> SPACE.
*  MESSAGE S894(AQ).
*ENDIF.
*
*ENDFORM.
*
*
*FORM %TOP-OF-PAGE.
*
*IF SY-UCOMM = 'INHA'. EXIT. ENDIF.
*IF SY-UCOMM = 'COPA'. EXIT. ENDIF.
*IF %HEAD    = SPACE.  EXIT. ENDIF.
*IF %HEAD = 'DDD'.
*  PERFORM TVIEWPAGE(RSAQEXCE).
*  EXIT.
*ENDIF.
*IF %HEAD = 'GGG'.
*  PERFORM PAGE(RSAQEXCE) USING 'G00' TEXT-GRL 252 %GLFRAME 003.
*  SET LEFT SCROLL-BOUNDARY COLUMN 002.
*  PERFORM SET_SCROLL_BOUNDARY(RSAQEXCE) USING 002.
*  IF %TOTO <> SPACE. EXIT. ENDIF.
*ELSE.
*  CASE %HEAD.
*  ENDCASE.
*ENDIF.
*
*ENDFORM.
*
*
*FORM %NEWLINE.
*
*  %UFLAG = SPACE.
*  NEW-LINE.
*  WRITE: '|', 252 '|'.
*  POSITION 2.
*
*ENDFORM.
*
*FORM %SKIP USING COUNT.
*
*  IF SY-LINNO > 1.
*    %UFLAG = SPACE.
*    DO COUNT TIMES.
*      NEW-LINE.
*      FORMAT RESET.
*      WRITE: '|', 252 '|'.
*    ENDDO.
*  ENDIF.
*
*ENDFORM.
*
*FORM %ULINE.
*
*  IF %UFLAG = SPACE.
*    IF SY-LINNO > 1.
*      ULINE /1(252).
*    ENDIF.
*    %UFLAG = 'X'.
*  ENDIF.
*
*ENDFORM.
*
*FORM %HIDE.
*
*  IF %BATCH <> SPACE AND %DIACT = 'S'.
*    PERFORM HIDE(RSAQEXCE).
*  ELSE.
*    HIDE: %TAB, %LINE, %CONT.
*  ENDIF.
*
*ENDFORM.
*
*FORM %HIDE_COLOR.
*
*  IF %BATCH <> SPACE AND %DIACT = 'S'.
*    PERFORM HIDE_COLOR(RSAQEXCE).
*  ELSE.
*    HIDE: %FINT, %FCOL.
*  ENDIF.
*
*ENDFORM.
*
*FORM %RCALL USING NAME VALUE.
*
*FIELD-SYMBOLS <FIELD>.
*
*  ASSIGN (NAME) TO <FIELD>.
*  READ CURRENT LINE FIELD VALUE <FIELD> INTO VALUE.
*  IF SY-SUBRC <> 0.
*    VALUE = SPACE.
*    EXIT.
*  ENDIF.
*  IF VALUE = SPACE AND %TAB = 'G00' AND %LDESC-FCUR NA 'FM'.
*    READ TABLE %G00 INDEX %LINE.
*    IF SY-SUBRC = 0.
*      ASSIGN COMPONENT %LDESC-FNAMEINT OF STRUCTURE %G00
*                                       TO <FIELD>.
*      IF SY-SUBRC = 0.
*        WRITE <FIELD> TO VALUE(%LDESC-FOLEN).
*      ENDIF.
*    ENDIF.
*  ENDIF.
*
*ENDFORM.
*
*FORM %SAVE_PAGE.
*
*  IF %BATCH <> SPACE AND %DIACT = 'S'.
*    PERFORM SAVE_PAGE(RSAQEXCE) TABLES %ST_LISTE.
*  ENDIF.
*
*ENDFORM.
*
*FORM %REPLACE_VAR USING TEXT.
*
*FIELD-SYMBOLS <VAR>.
*
*  ASSIGN TEXT+1(*) TO <VAR>.
*
*ENDFORM.
*
*FORM %SAVE_LIST.
*
*DATA: %SFLAG,
*      QREPORT LIKE SY-REPID.
*
*  IF %DIACT = 'S'. %SFLAG = 'X'. ENDIF.
*  QREPORT = SY-REPID.
*  PERFORM SAVE_LIST(RSAQEXCE) TABLES %ST_LISTE
*                              USING QREPORT %SFLAG %LISTID.
*  IF %QL_ID <> SPACE.
*    %DLFLAG = 'X'.
*    %LISTSIZE = 0253.
*    PERFORM COMP_SELECTION_SCREEN(RSAQEXCE).
*    EXPORT %ST_LISTE %PTAB %LDESC %GDESC %DLFLAG %LISTSIZE
*           %SELECTIONS
*           %G00
*           TO DATABASE AQLDB(AQ) ID %QL_ID.
*  ENDIF.
*
*ENDFORM.
*
*FORM %REFRESH.
*
*  CASE %TAB.
*  WHEN 'G00'.
*    IMPORT %G00 FROM DATABASE AQLDB(AQ) ID %QL_ID.
*  ENDCASE.
*
*ENDFORM.
*
*FORM %DOWNLOAD USING CODE.
*
*DATA: QREPORT LIKE SY-REPID.
*
*  PERFORM INIT_DOWNLOAD(RSAQEXCE).
*  QREPORT = SY-REPID.
*  CASE %TAB.
*  WHEN 'G00'.
*    PERFORM DOWNLOAD(RSAQEXCE)
*            TABLES %G00 USING CODE QREPORT TEXT-GRL.
*  WHEN OTHERS.
*    MESSAGE S860(AQ).
*  ENDCASE.
*
*ENDFORM.
*
*FORM %SET_DATA CHANGING L_LINES TYPE I.
*
*  IMPORT LDATA TO %G00 FROM MEMORY ID 'AQLISTDATA'.
*  DESCRIBE TABLE %G00 LINES L_LINES.
*  FREE MEMORY ID 'AQLISTDATA'.
*
*ENDFORM.
*
*FORM %GET_DATA TABLES DATATAB STRUCTURE %G00
*               USING  FIRST TYPE I
*                      LAST  TYPE I.
*
*  APPEND LINES OF %G00 FROM FIRST TO LAST TO DATATAB.
*
*ENDFORM.
*
*FORM %GET_REF_TO_TABLE USING LID         LIKE RSAQLDESC-LID
*                             REF_TO_ITAB TYPE REF TO DATA
*                             SUBRC       LIKE SY-SUBRC.
*
*  SUBRC = 0.
*  CASE LID.
*  WHEN 'G00'.
*    CREATE DATA REF_TO_ITAB LIKE %G00[].
*  WHEN OTHERS.
*    SUBRC = 4.
*    MESSAGE S860(AQ).
*  ENDCASE.
*
*ENDFORM.
*
*FORM %VIEW.
*
*DATA: RET TYPE I.
*
*  PERFORM CHECK_WINGUI(RSAQSYST) USING RET.
*  IF RET <> 0.
*    MESSAGE S841(AQ).
*    PERFORM %DOWNLOAD USING 'ALV'.
*    EXIT.
*  ENDIF.
*
*DATA: ANZ TYPE I,
*      PROG LIKE SY-REPID.
*
*  PROG = SY-REPID.
*  PERFORM INIT_DOWNLOAD(RSAQEXCE).
*  CASE %TAB.
*  WHEN 'G00'.
*    PERFORM GENERATE_VIEW_DYNPRO(RSAQEXCE)
*            USING PROG TEXT-GRL.
*    DESCRIBE TABLE %G00 LINES ANZ.
*    TVIEW100-LINES = ANZ.
*    PERFORM INIT_VIEW(RSAQEXCE) TABLES %G00 USING TVIEW100.
*    CALL SCREEN 100.
*    PERFORM RESET_VIEW_DYNPRO(RSAQEXCE).
*  WHEN OTHERS.
*    MESSAGE S860(AQ).
*  ENDCASE.
*
*ENDFORM.
*
*
*FORM %CLEAR02.
*
*  CLEAR %G00-ZTCO_SHOPCOST-WERTN.
*  CLEAR %G00-ZTCO_SHOPCOST-WRTFX.
*  CLEAR %G00-ZTCO_SHOPCOST-WDIFF.
*  CLEAR %G00-ZTCO_SHOPCOST-KADAT.
*  CLEAR %G00-ZTCO_SHOPCOST-BIDAT.
*  CLEAR %G00-ZTCO_SHOPCOST-BZOBJ.
*  CLEAR %G00-ZTCO_SHOPCOST-KALKA.
*  CLEAR %G00-ZTCO_SHOPCOST-KADKY.
*  CLEAR %G00-ZTCO_SHOPCOST-TVERS.
*  CLEAR %G00-ZTCO_SHOPCOST-BWVAR.
*  CLEAR %G00-ZTCO_SHOPCOST-KKZMA.
*  CLEAR %G00-ZTCO_SHOPCOST-WERKS.
*  CLEAR %G00-ZTCO_SHOPCOST-BWKEY.
*  CLEAR %G00-ZTCO_SHOPCOST-BWTAR.
*  CLEAR %G00-ZTCO_SHOPCOST-FROM_PER.
*  CLEAR %G00-ZTCO_SHOPCOST-TO_PER.
*  CLEAR %G00-ZTCO_SHOPCOST-ERDAT.
*  CLEAR %G00-ZTCO_SHOPCOST-ERZET.
*  CLEAR %G00-ZTCO_SHOPCOST-ERNAM.
*  CLEAR %G00-ZTCO_SHOPCOST-AEDAT.
*  CLEAR %G00-ZTCO_SHOPCOST-AEZET.
*  CLEAR %G00-ZTCO_SHOPCOST-AENAM.
*
*ENDFORM.
*
*
*FORM %OUTPUT_GL.
*
*IF %MAX_PRLIST <> 0.
*  READ TABLE %PRLIST WITH KEY TAB = 'GGG'.
*  IF SY-SUBRC <> 0.
*    EXIT.
*  ENDIF.
*ENDIF.
*SET MARGIN 00.
*PERFORM COMPLETE_PAGE(RSAQEXCE).
*%NOCHANGE = SPACE.
*NEW-PAGE.
*REFRESH %WA010.
*REFRESH %WA020.
*REFRESH %W0100.
*REFRESH %W0100.
*REFRESH %W0100.
*REFRESH %W0102.
*REFRESH %W0102.
*REFRESH %W0102.
*REFRESH %W0110.
*REFRESH %W0110.
*REFRESH %W0110.
*REFRESH %W0107.
*REFRESH %W0107.
*REFRESH %W0107.
*REFRESH %W0104.
*REFRESH %W0104.
*REFRESH %W0104.
*REFRESH %W0101.
*REFRESH %W0101.
*REFRESH %W0101.
*REFRESH %W0103.
*REFRESH %W0103.
*REFRESH %W0103.
*REFRESH %W0106.
*REFRESH %W0106.
*REFRESH %W0106.
*REFRESH %W0108.
*REFRESH %W0108.
*REFRESH %W0108.
*REFRESH %W0109.
*REFRESH %W0109.
*REFRESH %W0109.
*REFRESH %W0105.
*REFRESH %W0105.
*REFRESH %W0105.
*REFRESH %W0200.
*REFRESH %W0202.
*REFRESH %W0210.
*REFRESH %W0207.
*REFRESH %W0204.
*REFRESH %W0201.
*REFRESH %W0203.
*REFRESH %W0206.
*REFRESH %W0208.
*REFRESH %W0209.
*REFRESH %W0205.
*%GLLINE   = 0.
*%TAB      = 'G00'.
*%LINE     = 0.
*%CONT     = '0'.
*%FINT     = SPACE.
*%FCOL     = '0'.
*%HEAD     = 'GGG'.
*%CLINE    = 0.
*%OUTFLAG  = SPACE.
*%OUTCOMP  = SPACE.
*%OUTTOTAL = SPACE.
*%RFLAG    = 'AA'.
*IF %DIACT <> SPACE AND %DIACT NA 'SWE'. WRITE SPACE. ENDIF.
*FORMAT RESET.
*LOOP.
*  %DATA_SELECTED = 'X'.
*  AT %FG01.
*    %ZNR = '01'.
*    %ZGR = '01'.
*    %CLINE = %CLINE + 1.
*    PERFORM %CLEAR02.
*    %G00-ZTCO_SHOPCOST-KOKRS = ZTCO_SHOPCOST-KOKRS.
*    %G00-ZTCO_SHOPCOST-BDATJ = ZTCO_SHOPCOST-BDATJ.
*    %G00-ZTCO_SHOPCOST-POPER = ZTCO_SHOPCOST-POPER.
*    %G00-ZTCO_SHOPCOST-KLVAR = ZTCO_SHOPCOST-KLVAR.
*    %G00-ZTCO_SHOPCOST-VERSN = ZTCO_SHOPCOST-VERSN.
*    %G00-ZTCO_SHOPCOST-RECORD_TYPE = ZTCO_SHOPCOST-RECORD_TYPE.
*    %G00-ZTCO_SHOPCOST-FSC_MATNR = ZTCO_SHOPCOST-FSC_MATNR.
*    %G00-ZTCO_SHOPCOST-SHOP = ZTCO_SHOPCOST-SHOP.
*    %G00-ZTCO_SHOPCOST-LLV_MATNR = ZTCO_SHOPCOST-LLV_MATNR.
*    %G00-ZTCO_SHOPCOST-TYPPS = ZTCO_SHOPCOST-TYPPS.
*    %G00-ZTCO_SHOPCOST-KSTAR = ZTCO_SHOPCOST-KSTAR.
*    %G00-ZTCO_SHOPCOST-KALNR = ZTCO_SHOPCOST-KALNR.
*    %G00-ZTCO_SHOPCOST-ELEMT = ZTCO_SHOPCOST-ELEMT.
*    %G00-ZTCO_SHOPCOST-KOSTL = ZTCO_SHOPCOST-KOSTL.
*    %G00-ZTCO_SHOPCOST-LSTAR = ZTCO_SHOPCOST-LSTAR.
*    %G00-ZTCO_SHOPCOST-HWAER = ZTCO_SHOPCOST-HWAER.
*    %G00-ZTCO_SHOPCOST-MENGE = ZTCO_SHOPCOST-MENGE.
*    %G00-ZTCO_SHOPCOST-MEEHT-0117 = ZTCO_SHOPCOST-MEEHT.
*    %G00-ZTCO_SHOPCOST-MEEHT = ZTCO_SHOPCOST-MEEHT.
*    %G00-ZTCO_SHOPCOST-BESKZ = ZTCO_SHOPCOST-BESKZ.
*    %G00-ZTCO_SHOPCOST-SOBSL = ZTCO_SHOPCOST-SOBSL.
*    %G00-ZTCO_SHOPCOST-VSPVB = ZTCO_SHOPCOST-VSPVB.
*    %G00-ZTCO_SHOPCOST-PAR_KALNR = ZTCO_SHOPCOST-PAR_KALNR.
*    %G00-ZTCO_SHOPCOST-PAR_KADKY = ZTCO_SHOPCOST-PAR_KADKY.
*    %G00-ZTCO_SHOPCOST-MTART = ZTCO_SHOPCOST-MTART.
*    IF %FIRST <> SPACE. APPEND %G00. ENDIF.
*    %GLLINE = %GLLINE + 1.
*    %LZNR = %ZNR.
*    IF %DIACT <> SPACE AND %DIACT NA 'SWE'. CONTINUE. ENDIF.
*    PERFORM CHECK(RSAQEXCE) USING ' '.
*    IF %RFLAG = 'E'. EXIT. ENDIF.
*    IF %RFLAG = 'AA'.
*      PERFORM RESERVE(RSAQEXCE) USING 002.
*    ENDIF.
*IF ZTCO_SHOPCOST-KOKRS <> %%ZTCO_SHOPCOST-KOKRS OR
*%%%ZTCO_SHOPCOST-KOKRS = SPACE.
*      %%ZTCO_SHOPCOST-KOKRS = ZTCO_SHOPCOST-KOKRS.
*      %%%ZTCO_SHOPCOST-KOKRS ='X'.
*      CLEAR %%ZTCO_SHOPCOST-BDATJ.
*      CLEAR %%%ZTCO_SHOPCOST-BDATJ.
*      CLEAR %%ZTCO_SHOPCOST-POPER.
*      CLEAR %%%ZTCO_SHOPCOST-POPER.
*      CLEAR %%ZTCO_SHOPCOST-KLVAR.
*      CLEAR %%%ZTCO_SHOPCOST-KLVAR.
*      CLEAR %%ZTCO_SHOPCOST-VERSN.
*      CLEAR %%%ZTCO_SHOPCOST-VERSN.
*      CLEAR %%ZTCO_SHOPCOST-RECORD_TYPE.
*      CLEAR %%%ZTCO_SHOPCOST-RECORD_TYPE.
*      CLEAR %%ZTCO_SHOPCOST-FSC_MATNR.
*      CLEAR %%%ZTCO_SHOPCOST-FSC_MATNR.
*      CLEAR %%ZTCO_SHOPCOST-SHOP.
*      CLEAR %%%ZTCO_SHOPCOST-SHOP.
*      CLEAR %%ZTCO_SHOPCOST-TYPPS.
*      CLEAR %%%ZTCO_SHOPCOST-TYPPS.
*      CLEAR %%ZTCO_SHOPCOST-ELEMT.
*      CLEAR %%%ZTCO_SHOPCOST-ELEMT.
*    ENDIF.
*IF ZTCO_SHOPCOST-BDATJ <> %%ZTCO_SHOPCOST-BDATJ OR
*%%%ZTCO_SHOPCOST-BDATJ = SPACE.
*      %%ZTCO_SHOPCOST-BDATJ = ZTCO_SHOPCOST-BDATJ.
*      %%%ZTCO_SHOPCOST-BDATJ ='X'.
*      CLEAR %%ZTCO_SHOPCOST-POPER.
*      CLEAR %%%ZTCO_SHOPCOST-POPER.
*      CLEAR %%ZTCO_SHOPCOST-KLVAR.
*      CLEAR %%%ZTCO_SHOPCOST-KLVAR.
*      CLEAR %%ZTCO_SHOPCOST-VERSN.
*      CLEAR %%%ZTCO_SHOPCOST-VERSN.
*      CLEAR %%ZTCO_SHOPCOST-RECORD_TYPE.
*      CLEAR %%%ZTCO_SHOPCOST-RECORD_TYPE.
*      CLEAR %%ZTCO_SHOPCOST-FSC_MATNR.
*      CLEAR %%%ZTCO_SHOPCOST-FSC_MATNR.
*      CLEAR %%ZTCO_SHOPCOST-SHOP.
*      CLEAR %%%ZTCO_SHOPCOST-SHOP.
*      CLEAR %%ZTCO_SHOPCOST-TYPPS.
*      CLEAR %%%ZTCO_SHOPCOST-TYPPS.
*      CLEAR %%ZTCO_SHOPCOST-ELEMT.
*      CLEAR %%%ZTCO_SHOPCOST-ELEMT.
*    ENDIF.
*IF ZTCO_SHOPCOST-POPER <> %%ZTCO_SHOPCOST-POPER OR
*%%%ZTCO_SHOPCOST-POPER = SPACE.
*      %%ZTCO_SHOPCOST-POPER = ZTCO_SHOPCOST-POPER.
*      %%%ZTCO_SHOPCOST-POPER ='X'.
*      CLEAR %%ZTCO_SHOPCOST-KLVAR.
*      CLEAR %%%ZTCO_SHOPCOST-KLVAR.
*      CLEAR %%ZTCO_SHOPCOST-VERSN.
*      CLEAR %%%ZTCO_SHOPCOST-VERSN.
*      CLEAR %%ZTCO_SHOPCOST-RECORD_TYPE.
*      CLEAR %%%ZTCO_SHOPCOST-RECORD_TYPE.
*      CLEAR %%ZTCO_SHOPCOST-FSC_MATNR.
*      CLEAR %%%ZTCO_SHOPCOST-FSC_MATNR.
*      CLEAR %%ZTCO_SHOPCOST-SHOP.
*      CLEAR %%%ZTCO_SHOPCOST-SHOP.
*      CLEAR %%ZTCO_SHOPCOST-TYPPS.
*      CLEAR %%%ZTCO_SHOPCOST-TYPPS.
*      CLEAR %%ZTCO_SHOPCOST-ELEMT.
*      CLEAR %%%ZTCO_SHOPCOST-ELEMT.
*    ENDIF.
*IF ZTCO_SHOPCOST-KLVAR <> %%ZTCO_SHOPCOST-KLVAR OR
*%%%ZTCO_SHOPCOST-KLVAR = SPACE.
*      %%ZTCO_SHOPCOST-KLVAR = ZTCO_SHOPCOST-KLVAR.
*      %%%ZTCO_SHOPCOST-KLVAR ='X'.
*      CLEAR %%ZTCO_SHOPCOST-VERSN.
*      CLEAR %%%ZTCO_SHOPCOST-VERSN.
*      CLEAR %%ZTCO_SHOPCOST-RECORD_TYPE.
*      CLEAR %%%ZTCO_SHOPCOST-RECORD_TYPE.
*      CLEAR %%ZTCO_SHOPCOST-FSC_MATNR.
*      CLEAR %%%ZTCO_SHOPCOST-FSC_MATNR.
*      CLEAR %%ZTCO_SHOPCOST-SHOP.
*      CLEAR %%%ZTCO_SHOPCOST-SHOP.
*      CLEAR %%ZTCO_SHOPCOST-TYPPS.
*      CLEAR %%%ZTCO_SHOPCOST-TYPPS.
*      CLEAR %%ZTCO_SHOPCOST-ELEMT.
*      CLEAR %%%ZTCO_SHOPCOST-ELEMT.
*    ENDIF.
*IF ZTCO_SHOPCOST-VERSN <> %%ZTCO_SHOPCOST-VERSN OR
*%%%ZTCO_SHOPCOST-VERSN = SPACE.
*      %%ZTCO_SHOPCOST-VERSN = ZTCO_SHOPCOST-VERSN.
*      %%%ZTCO_SHOPCOST-VERSN ='X'.
*      CLEAR %%ZTCO_SHOPCOST-RECORD_TYPE.
*      CLEAR %%%ZTCO_SHOPCOST-RECORD_TYPE.
*      CLEAR %%ZTCO_SHOPCOST-FSC_MATNR.
*      CLEAR %%%ZTCO_SHOPCOST-FSC_MATNR.
*      CLEAR %%ZTCO_SHOPCOST-SHOP.
*      CLEAR %%%ZTCO_SHOPCOST-SHOP.
*      CLEAR %%ZTCO_SHOPCOST-TYPPS.
*      CLEAR %%%ZTCO_SHOPCOST-TYPPS.
*      CLEAR %%ZTCO_SHOPCOST-ELEMT.
*      CLEAR %%%ZTCO_SHOPCOST-ELEMT.
*    ENDIF.
*IF ZTCO_SHOPCOST-RECORD_TYPE <> %%ZTCO_SHOPCOST-RECORD_TYPE OR
*%%%ZTCO_SHOPCOST-RECORD_TYPE = SPACE.
*      %%ZTCO_SHOPCOST-RECORD_TYPE = ZTCO_SHOPCOST-RECORD_TYPE.
*      %%%ZTCO_SHOPCOST-RECORD_TYPE ='X'.
*      CLEAR %%ZTCO_SHOPCOST-FSC_MATNR.
*      CLEAR %%%ZTCO_SHOPCOST-FSC_MATNR.
*      CLEAR %%ZTCO_SHOPCOST-SHOP.
*      CLEAR %%%ZTCO_SHOPCOST-SHOP.
*      CLEAR %%ZTCO_SHOPCOST-TYPPS.
*      CLEAR %%%ZTCO_SHOPCOST-TYPPS.
*      CLEAR %%ZTCO_SHOPCOST-ELEMT.
*      CLEAR %%%ZTCO_SHOPCOST-ELEMT.
*    ENDIF.
*IF ZTCO_SHOPCOST-FSC_MATNR <> %%ZTCO_SHOPCOST-FSC_MATNR OR
*%%%ZTCO_SHOPCOST-FSC_MATNR = SPACE.
*      %%ZTCO_SHOPCOST-FSC_MATNR = ZTCO_SHOPCOST-FSC_MATNR.
*      %%%ZTCO_SHOPCOST-FSC_MATNR ='X'.
*      CLEAR %%ZTCO_SHOPCOST-SHOP.
*      CLEAR %%%ZTCO_SHOPCOST-SHOP.
*      CLEAR %%ZTCO_SHOPCOST-TYPPS.
*      CLEAR %%%ZTCO_SHOPCOST-TYPPS.
*      CLEAR %%ZTCO_SHOPCOST-ELEMT.
*      CLEAR %%%ZTCO_SHOPCOST-ELEMT.
*    ENDIF.
*IF ZTCO_SHOPCOST-SHOP <> %%ZTCO_SHOPCOST-SHOP OR %%%ZTCO_SHOPCOST-SHOP
*=
*SPACE.
*      %%ZTCO_SHOPCOST-SHOP = ZTCO_SHOPCOST-SHOP.
*      %%%ZTCO_SHOPCOST-SHOP ='X'.
*      CLEAR %%ZTCO_SHOPCOST-TYPPS.
*      CLEAR %%%ZTCO_SHOPCOST-TYPPS.
*      CLEAR %%ZTCO_SHOPCOST-ELEMT.
*      CLEAR %%%ZTCO_SHOPCOST-ELEMT.
*    ENDIF.
*IF ZTCO_SHOPCOST-TYPPS <> %%ZTCO_SHOPCOST-TYPPS OR
*%%%ZTCO_SHOPCOST-TYPPS = SPACE.
*      %%ZTCO_SHOPCOST-TYPPS = ZTCO_SHOPCOST-TYPPS.
*      %%%ZTCO_SHOPCOST-TYPPS ='X'.
*      CLEAR %%ZTCO_SHOPCOST-ELEMT.
*      CLEAR %%%ZTCO_SHOPCOST-ELEMT.
*    ENDIF.
*IF ZTCO_SHOPCOST-ELEMT <> %%ZTCO_SHOPCOST-ELEMT OR
*%%%ZTCO_SHOPCOST-ELEMT = SPACE.
*      %%ZTCO_SHOPCOST-ELEMT = ZTCO_SHOPCOST-ELEMT.
*      %%%ZTCO_SHOPCOST-ELEMT ='X'.
*    ENDIF.
*    IF %RFLAG(1) = 'A'.
*    FORMAT RESET.
*    %FINT = 'F'. %FCOL = '0'.
*    FORMAT COLOR 2. %FCOL = '2'.
*    PERFORM %NEWLINE.
*    WRITE 002(004) ZTCO_SHOPCOST-KOKRS.
*    %LINE = %GLLINE.
*    PERFORM %HIDE.
*    %LINE = 0.
*    IF %RFLAG = 'AA'. HIDE %CLINE. ENDIF. HIDE %ZGR.
*    PERFORM %HIDE_COLOR.
*    WRITE 007(004) ZTCO_SHOPCOST-BDATJ.
*    WRITE 012(003) ZTCO_SHOPCOST-POPER.
*    WRITE 016(004) ZTCO_SHOPCOST-KLVAR.
*    WRITE 021(003) ZTCO_SHOPCOST-VERSN.
*    WRITE 025(001) ZTCO_SHOPCOST-RECORD_TYPE.
*    WRITE 027(040) ZTCO_SHOPCOST-FSC_MATNR.
*    WRITE 068(010) ZTCO_SHOPCOST-SHOP.
*    WRITE 079(040) ZTCO_SHOPCOST-LLV_MATNR.
*    WRITE 120(001) ZTCO_SHOPCOST-TYPPS.
*    WRITE 122(010) ZTCO_SHOPCOST-KSTAR.
*    WRITE 133(012) ZTCO_SHOPCOST-KALNR.
*    WRITE 146(003) ZTCO_SHOPCOST-ELEMT.
*    WRITE 150(010) ZTCO_SHOPCOST-KOSTL.
*    WRITE 161(006) ZTCO_SHOPCOST-LSTAR.
*    WRITE 168(005) ZTCO_SHOPCOST-HWAER.
*    WRITE 174(020) ZTCO_SHOPCOST-MENGE
*      UNIT ZTCO_SHOPCOST-MEEHT.
*    WRITE 195(003) ZTCO_SHOPCOST-MEEHT.
*    WRITE 199(003) ZTCO_SHOPCOST-MEEHT.
*    WRITE 203(001) ZTCO_SHOPCOST-BESKZ.
*    WRITE 205(002) ZTCO_SHOPCOST-SOBSL.
*    WRITE 208(010) ZTCO_SHOPCOST-VSPVB.
*    WRITE 219(012) ZTCO_SHOPCOST-PAR_KALNR.
*    WRITE 232(010) ZTCO_SHOPCOST-PAR_KADKY.
*    WRITE 243(004) ZTCO_SHOPCOST-MTART.
*    ENDIF.
*  ENDAT.
*  AT %FG02.
*    %ZNR = '02'.
*    %ZGR = '01'.
*    IF %ZNR > %LZNR.
*      READ TABLE %G00 INDEX %GLLINE.
*    ENDIF.
*    %G00-ZTCO_SHOPCOST-WERTN = ZTCO_SHOPCOST-WERTN.
*    %G00-ZTCO_SHOPCOST-WRTFX = ZTCO_SHOPCOST-WRTFX.
*    %G00-ZTCO_SHOPCOST-WDIFF = ZTCO_SHOPCOST-WDIFF.
*    %G00-ZTCO_SHOPCOST-KADAT = ZTCO_SHOPCOST-KADAT.
*    %G00-ZTCO_SHOPCOST-BIDAT = ZTCO_SHOPCOST-BIDAT.
*    %G00-ZTCO_SHOPCOST-BZOBJ = ZTCO_SHOPCOST-BZOBJ.
*    %G00-ZTCO_SHOPCOST-KALKA = ZTCO_SHOPCOST-KALKA.
*    %G00-ZTCO_SHOPCOST-KADKY = ZTCO_SHOPCOST-KADKY.
*    %G00-ZTCO_SHOPCOST-TVERS = ZTCO_SHOPCOST-TVERS.
*    %G00-ZTCO_SHOPCOST-BWVAR = ZTCO_SHOPCOST-BWVAR.
*    %G00-ZTCO_SHOPCOST-KKZMA = ZTCO_SHOPCOST-KKZMA.
*    %G00-ZTCO_SHOPCOST-WERKS = ZTCO_SHOPCOST-WERKS.
*    %G00-ZTCO_SHOPCOST-BWKEY = ZTCO_SHOPCOST-BWKEY.
*    %G00-ZTCO_SHOPCOST-BWTAR = ZTCO_SHOPCOST-BWTAR.
*    %G00-ZTCO_SHOPCOST-FROM_PER = ZTCO_SHOPCOST-FROM_PER.
*    %G00-ZTCO_SHOPCOST-TO_PER = ZTCO_SHOPCOST-TO_PER.
*    %G00-ZTCO_SHOPCOST-ERDAT = ZTCO_SHOPCOST-ERDAT.
*    %G00-ZTCO_SHOPCOST-ERZET = ZTCO_SHOPCOST-ERZET.
*    %G00-ZTCO_SHOPCOST-ERNAM = ZTCO_SHOPCOST-ERNAM.
*    %G00-ZTCO_SHOPCOST-AEDAT = ZTCO_SHOPCOST-AEDAT.
*    %G00-ZTCO_SHOPCOST-AEZET = ZTCO_SHOPCOST-AEZET.
*    %G00-ZTCO_SHOPCOST-AENAM = ZTCO_SHOPCOST-AENAM.
*    IF %ZNR > %LZNR.
*      IF %FIRST <> SPACE. MODIFY %G00 INDEX %GLLINE. ENDIF.
*    ELSE.
*      IF %FIRST <> SPACE. APPEND %G00. ENDIF.
*      %GLLINE = %GLLINE + 1.
*    ENDIF.
*    %LZNR = %ZNR.
*    IF %DIACT <> SPACE AND %DIACT NA 'SWE'. CONTINUE. ENDIF.
*    PERFORM CHECK(RSAQEXCE) USING ' '.
*    IF %RFLAG = 'E'. EXIT. ENDIF.
*    IF %RFLAG(1) = 'A'.
*    FORMAT RESET.
*    %FINT = 'F'. %FCOL = '0'.
*    FORMAT COLOR 2. %FCOL = '2'.
*    PERFORM %NEWLINE.
*    WRITE 002(021) ZTCO_SHOPCOST-WERTN
*      CURRENCY ZTCO_SHOPCOST-HWAER.
*    %LINE = %GLLINE.  %CONT = '1'.
*    PERFORM %HIDE.
*    %LINE = 0.  %CONT = '0'.
*    IF %RFLAG = 'AA'. HIDE %CLINE. ENDIF. HIDE %ZGR.
*    PERFORM %HIDE_COLOR.
*    WRITE 030(021) ZTCO_SHOPCOST-WRTFX
*      CURRENCY ZTCO_SHOPCOST-HWAER.
*    WRITE 058(021) ZTCO_SHOPCOST-WDIFF
*      CURRENCY ZTCO_SHOPCOST-HWAER.
*    WRITE 086(010) ZTCO_SHOPCOST-KADAT.
*    WRITE 097(010) ZTCO_SHOPCOST-BIDAT.
*    WRITE 108(001) ZTCO_SHOPCOST-BZOBJ.
*    WRITE 110(002) ZTCO_SHOPCOST-KALKA.
*    WRITE 113(010) ZTCO_SHOPCOST-KADKY.
*    WRITE 124(002) ZTCO_SHOPCOST-TVERS.
*    WRITE 127(003) ZTCO_SHOPCOST-BWVAR.
*    WRITE 131(001) ZTCO_SHOPCOST-KKZMA.
*    WRITE 133(004) ZTCO_SHOPCOST-WERKS.
*    WRITE 138(004) ZTCO_SHOPCOST-BWKEY.
*    WRITE 143(010) ZTCO_SHOPCOST-BWTAR.
*    WRITE 154(003) ZTCO_SHOPCOST-FROM_PER.
*    WRITE 158(003) ZTCO_SHOPCOST-TO_PER.
*    WRITE 162(010) ZTCO_SHOPCOST-ERDAT.
*    WRITE 173(008) ZTCO_SHOPCOST-ERZET.
*    WRITE 182(012) ZTCO_SHOPCOST-ERNAM.
*    WRITE 195(010) ZTCO_SHOPCOST-AEDAT.
*    WRITE 206(008) ZTCO_SHOPCOST-AEZET.
*    WRITE 215(012) ZTCO_SHOPCOST-AENAM.
*    ENDIF.
*  ENDAT.
*  AT %FGWRZTCO_SHOPCOST02.
*    CLEAR %W0110.
*    %W0110-ZTCO_SHOPCOST-HWAER = ZTCO_SHOPCOST-HWAER.
*    %W0110-ZTCO_SHOPCOST-WERTN = ZTCO_SHOPCOST-WERTN.
*    %W0110-ZTCO_SHOPCOST-WDIFF = ZTCO_SHOPCOST-WDIFF.
*    %W0110-ZTCO_SHOPCOST-WRTFX = ZTCO_SHOPCOST-WRTFX.
*    COLLECT %W0110.
*  ENDAT.
*  AT %FGWRZTCO_SHOPCOST01.
*    CLEAR %W0210.
*    %W0210-ZTCO_SHOPCOST-MEEHT = ZTCO_SHOPCOST-MEEHT.
*    %W0210-ZTCO_SHOPCOST-MENGE = ZTCO_SHOPCOST-MENGE.
*    COLLECT %W0210.
*  ENDAT.
*  AT END OF ZTCO_SHOPCOST-ELEMT.
*    %ZGR = '01'.
*    PERFORM CHECK(RSAQEXCE) USING 'X'.
*    IF %RFLAG = 'E'. EXIT. ENDIF.
*    LOOP AT %W0110.
*      %W0109 = %W0110.
*      COLLECT %W0109.
*    ENDLOOP.
*    REFRESH %W0110.
*    LOOP AT %W0210.
*      %W0209 = %W0210.
*      COLLECT %W0209.
*    ENDLOOP.
*    REFRESH %W0210.
*  ENDAT.
*  AT END OF ZTCO_SHOPCOST-TYPPS.
*    %ZGR = '01'.
*    PERFORM CHECK(RSAQEXCE) USING 'X'.
*    IF %RFLAG = 'E'. EXIT. ENDIF.
*    LOOP AT %W0109.
*      %W0108 = %W0109.
*      COLLECT %W0108.
*    ENDLOOP.
*    REFRESH %W0109.
*    LOOP AT %W0209.
*      %W0208 = %W0209.
*      COLLECT %W0208.
*    ENDLOOP.
*    REFRESH %W0209.
*  ENDAT.
*  AT END OF ZTCO_SHOPCOST-SHOP.
*    %ZGR = '01'.
*    PERFORM CHECK(RSAQEXCE) USING 'X'.
*    IF %RFLAG = 'E'. EXIT. ENDIF.
*    LOOP AT %W0108.
*      %W0107 = %W0108.
*      COLLECT %W0107.
*    ENDLOOP.
*    REFRESH %W0108.
*    LOOP AT %W0208.
*      %W0207 = %W0208.
*      COLLECT %W0207.
*    ENDLOOP.
*    REFRESH %W0208.
*  ENDAT.
*  AT END OF ZTCO_SHOPCOST-FSC_MATNR.
*    %ZGR = '01'.
*    PERFORM CHECK(RSAQEXCE) USING 'X'.
*    IF %RFLAG = 'E'. EXIT. ENDIF.
*    LOOP AT %W0107.
*      %W0106 = %W0107.
*      COLLECT %W0106.
*    ENDLOOP.
*    REFRESH %W0107.
*    LOOP AT %W0207.
*      %W0206 = %W0207.
*      COLLECT %W0206.
*    ENDLOOP.
*    REFRESH %W0207.
*  ENDAT.
*  AT END OF ZTCO_SHOPCOST-RECORD_TYPE.
*    %ZGR = '01'.
*    PERFORM CHECK(RSAQEXCE) USING 'X'.
*    IF %RFLAG = 'E'. EXIT. ENDIF.
*    LOOP AT %W0106.
*      %W0105 = %W0106.
*      COLLECT %W0105.
*    ENDLOOP.
*    REFRESH %W0106.
*    LOOP AT %W0206.
*      %W0205 = %W0206.
*      COLLECT %W0205.
*    ENDLOOP.
*    REFRESH %W0206.
*  ENDAT.
*  AT END OF ZTCO_SHOPCOST-VERSN.
*    %ZGR = '01'.
*    PERFORM CHECK(RSAQEXCE) USING 'X'.
*    IF %RFLAG = 'E'. EXIT. ENDIF.
*    LOOP AT %W0105.
*      %W0104 = %W0105.
*      COLLECT %W0104.
*    ENDLOOP.
*    REFRESH %W0105.
*    LOOP AT %W0205.
*      %W0204 = %W0205.
*      COLLECT %W0204.
*    ENDLOOP.
*    REFRESH %W0205.
*  ENDAT.
*  AT END OF ZTCO_SHOPCOST-KLVAR.
*    %ZGR = '01'.
*    PERFORM CHECK(RSAQEXCE) USING 'X'.
*    IF %RFLAG = 'E'. EXIT. ENDIF.
*    LOOP AT %W0104.
*      %W0103 = %W0104.
*      COLLECT %W0103.
*    ENDLOOP.
*    REFRESH %W0104.
*    LOOP AT %W0204.
*      %W0203 = %W0204.
*      COLLECT %W0203.
*    ENDLOOP.
*    REFRESH %W0204.
*  ENDAT.
*  AT END OF ZTCO_SHOPCOST-POPER.
*    %ZGR = '01'.
*    PERFORM CHECK(RSAQEXCE) USING 'X'.
*    IF %RFLAG = 'E'. EXIT. ENDIF.
*    LOOP AT %W0103.
*      %W0102 = %W0103.
*      COLLECT %W0102.
*    ENDLOOP.
*    REFRESH %W0103.
*    LOOP AT %W0203.
*      %W0202 = %W0203.
*      COLLECT %W0202.
*    ENDLOOP.
*    REFRESH %W0203.
*  ENDAT.
*  AT END OF ZTCO_SHOPCOST-BDATJ.
*    %ZGR = '01'.
*    PERFORM CHECK(RSAQEXCE) USING 'X'.
*    IF %RFLAG = 'E'. EXIT. ENDIF.
*    LOOP AT %W0102.
*      %W0101 = %W0102.
*      COLLECT %W0101.
*    ENDLOOP.
*    REFRESH %W0102.
*    LOOP AT %W0202.
*      %W0201 = %W0202.
*      COLLECT %W0201.
*    ENDLOOP.
*    REFRESH %W0202.
*  ENDAT.
*  AT END OF ZTCO_SHOPCOST-KOKRS.
*    %ZGR = '01'.
*    PERFORM CHECK(RSAQEXCE) USING 'X'.
*    IF %RFLAG = 'E'. EXIT. ENDIF.
*    LOOP AT %W0101.
*      %W0100 = %W0101.
*      COLLECT %W0100.
*    ENDLOOP.
*    REFRESH %W0101.
*    LOOP AT %W0201.
*      %W0200 = %W0201.
*      COLLECT %W0200.
*    ENDLOOP.
*    REFRESH %W0201.
*  ENDAT.
*  AT LAST.
*    %ZNR = 0.
*    %RFLAG = 'AA'.
*    %OUTTOTAL = 'X'.
*    PERFORM RESERVE(RSAQEXCE) USING 2.
*    PERFORM %ULINE.
*    FORMAT RESET.
*    FORMAT INTENSIFIED ON COLOR 3.
*    %FINT = 'N'. %FCOL = '3'.
*    %NOCHANGE = 'X'.
*    PERFORM %NEWLINE.
*    %NOCHANGE = SPACE.
*    WRITE (13) TEXT-F02.
*    PERFORM %HIDE.
*    PERFORM %HIDE_COLOR.
*    SORT %W0100 BY ZTCO_SHOPCOST-HWAER.
*    SORT %W0200 BY ZTCO_SHOPCOST-MEEHT.
*      PERFORM %NEWLINE.
*      WRITE 199 '*'.
*      REFRESH %WA010.
*      DO.
*        %SUBRC = 4.
*        CLEAR %WA010.
*        READ TABLE %W0200 INDEX SY-INDEX.
*        IF SY-SUBRC = 0.
*          %SUBRC = 0.
*          %WA010-ZTCO_SHOPCOST-ZTCO_SHOPCOST-MEEHT =
*          %W0200-ZTCO_SHOPCOST-MEEHT.
*          %WA010-ZTCO_SHOPCOST-MENGE = %W0200-ZTCO_SHOPCOST-MENGE.
*        ENDIF.
*        IF %SUBRC = 4.
*          EXIT.
*        ENDIF.
*        APPEND %WA010.
*      ENDDO.
*      LOOP AT %WA010.
*        IF SY-TABIX <> 1.
*          PERFORM %NEWLINE.
*        ENDIF.
*        IF %WA010-ZTCO_SHOPCOST-ZTCO_SHOPCOST-MEEHT = SPACE.
*          WRITE 174(020) %WA010-ZTCO_SHOPCOST-MENGE
*                UNIT %WA010-ZTCO_SHOPCOST-ZTCO_SHOPCOST-MEEHT NO-ZERO.
*          IF NOT %WA010-ZTCO_SHOPCOST-MENGE IS INITIAL.
*            %KEYEMPTY = 'X'.
*          ENDIF.
*        ELSE.
*          WRITE 174(020) %WA010-ZTCO_SHOPCOST-MENGE
*                UNIT %WA010-ZTCO_SHOPCOST-ZTCO_SHOPCOST-MEEHT.
*        ENDIF.
*        WRITE 195(003) %WA010-ZTCO_SHOPCOST-ZTCO_SHOPCOST-MEEHT.
*        PERFORM %HIDE.
*        PERFORM %HIDE_COLOR.
*      ENDLOOP.
*      PERFORM %NEWLINE.
*      WRITE 199 '*'.
*      REFRESH %WA020.
*      DO.
*        %SUBRC = 4.
*        CLEAR %WA020.
*        READ TABLE %W0100 INDEX SY-INDEX.
*        IF SY-SUBRC = 0.
*          %SUBRC = 0.
*          %WA020-ZTCO_SHOPCOST-ZTCO_SHOPCOST-HWAER =
*          %W0100-ZTCO_SHOPCOST-HWAER.
*          %WA020-ZTCO_SHOPCOST-WERTN = %W0100-ZTCO_SHOPCOST-WERTN.
*          %WA020-ZTCO_SHOPCOST-WDIFF = %W0100-ZTCO_SHOPCOST-WDIFF.
*          %WA020-ZTCO_SHOPCOST-WRTFX = %W0100-ZTCO_SHOPCOST-WRTFX.
*        ENDIF.
*        IF %SUBRC = 4.
*          EXIT.
*        ENDIF.
*        APPEND %WA020.
*      ENDDO.
*      LOOP AT %WA020.
*        IF SY-TABIX <> 1.
*          PERFORM %NEWLINE.
*        ENDIF.
*        IF %WA020-ZTCO_SHOPCOST-ZTCO_SHOPCOST-HWAER = SPACE.
*          WRITE 002(021) %WA020-ZTCO_SHOPCOST-WERTN
*CURRENCY %WA020-ZTCO_SHOPCOST-ZTCO_SHOPCOST-HWAER NO-ZERO.
*          IF NOT %WA020-ZTCO_SHOPCOST-WERTN IS INITIAL.
*            %KEYEMPTY = 'X'.
*          ENDIF.
*        ELSE.
*          WRITE 002(021) %WA020-ZTCO_SHOPCOST-WERTN
*                CURRENCY %WA020-ZTCO_SHOPCOST-ZTCO_SHOPCOST-HWAER.
*        ENDIF.
*        IF %WA020-ZTCO_SHOPCOST-ZTCO_SHOPCOST-HWAER = SPACE.
*          WRITE 030(021) %WA020-ZTCO_SHOPCOST-WRTFX
*CURRENCY %WA020-ZTCO_SHOPCOST-ZTCO_SHOPCOST-HWAER NO-ZERO.
*          IF NOT %WA020-ZTCO_SHOPCOST-WRTFX IS INITIAL.
*            %KEYEMPTY = 'X'.
*          ENDIF.
*        ELSE.
*          WRITE 030(021) %WA020-ZTCO_SHOPCOST-WRTFX
*                CURRENCY %WA020-ZTCO_SHOPCOST-ZTCO_SHOPCOST-HWAER.
*        ENDIF.
*        IF %WA020-ZTCO_SHOPCOST-ZTCO_SHOPCOST-HWAER = SPACE.
*          WRITE 058(021) %WA020-ZTCO_SHOPCOST-WDIFF
*CURRENCY %WA020-ZTCO_SHOPCOST-ZTCO_SHOPCOST-HWAER NO-ZERO.
*          IF NOT %WA020-ZTCO_SHOPCOST-WDIFF IS INITIAL.
*            %KEYEMPTY = 'X'.
*          ENDIF.
*        ELSE.
*          WRITE 058(021) %WA020-ZTCO_SHOPCOST-WDIFF
*                CURRENCY %WA020-ZTCO_SHOPCOST-ZTCO_SHOPCOST-HWAER.
*        ENDIF.
*        PERFORM %HIDE.
*        PERFORM %HIDE_COLOR.
*      ENDLOOP.
*    IF %RFLAG = 'AA'. PERFORM %ULINE. ENDIF.
*  ENDAT.
*ENDLOOP.
*%RFLAG = 'AA'.
*PERFORM %ULINE.
*CLEAR: %CLINE, %ZGR.
*
*ENDFORM.
*
*
*
*MODULE %INIT_VIEW OUTPUT.
*
*  CASE %TAB.
*  WHEN 'G00'.
*    PERFORM INIT_PBO(RSAQEXCE) TABLES %G00 USING TVIEW100 'X'.
*  WHEN OTHERS.
*    MESSAGE S860(AQ).
*  ENDCASE.
*
*ENDMODULE.
*
*MODULE %PBO_VIEW OUTPUT.
*
*  CASE %TAB.
*  WHEN 'G00'.
*    PERFORM LOOP_PBO(RSAQEXCE) TABLES %G00 USING %%G00 TVIEW100.
*  ENDCASE.
*
*ENDMODULE.
*
*MODULE %PAI_VIEW INPUT.
*
*  CASE %TAB.
*  WHEN 'G00'.
*    PERFORM LOOP_PAI(RSAQEXCE) TABLES %G00 USING %%G00 TVIEW100.
*  ENDCASE.
*
*ENDMODULE.
*
*MODULE %OKCODE_VIEW INPUT.
*
*  CASE %TAB.
*  WHEN 'G00'.
*    PERFORM OKCODE(RSAQEXCE) TABLES %G00 USING TVIEW100.
*  ENDCASE.
*
*ENDMODULE.
