*----------------------------------------------------------------------*
*   INCLUDE ZACO18L_1TOP                                               *
*----------------------------------------------------------------------*

*----------------------------------------------------------------------*
*   Include Program
*----------------------------------------------------------------------*
* For Global Value in CO
INCLUDE ZLZGCO_GLOBAL_FORMTO1.

*----------------------------------------------------------------------*
*   Data Definition
*----------------------------------------------------------------------*
** type-pools
TYPE-POOLS: SLIS.
TYPE-POOLS: ICON.

** Tables
TABLES : COSP, COSS, CSSL, CSKS.
TABLES : ZSCO_COSP_AMT01, "Fix + Key
         ZSCO_COSP_AMT03, "Total
         ZSCO_COSP_AMT02, "Var
         ZSCO_COSP_AMT04. "FIx

** Main Table
* For Cal. Factor
DATA : BEGIN OF IT_QUAN_PLAN OCCURS 1000.
        INCLUDE STRUCTURE ZSCO_COSS_KEY01.
        INCLUDE STRUCTURE ZSCO_COSS_MEG01.
DATA : END OF   IT_QUAN_PLAN.
DATA : IT_QUAN_STD LIKE STANDARD TABLE OF IT_QUAN_PLAN
                   WITH HEADER LINE .
DATA : BEGIN OF IT_RATE OCCURS 100.
        INCLUDE STRUCTURE ZSCO_COSS_KEY01.
        INCLUDE STRUCTURE ZSCO_COSS_RAT01.
DATA : END OF   IT_RATE.

* For report and Posting
DATA : BEGIN OF IT_COSP OCCURS 1000,
        KOSTL       LIKE  CSKS-KOSTL,
        LSTAR       LIKE  CSLA-LSTAR.
*        RATE        LIKE  ZSCO_COSS_RAT01-RAT001.
        INCLUDE STRUCTURE ZSCO_COSP_AMT01. "Fix + Key
        INCLUDE STRUCTURE ZSCO_COSP_AMT03. "Total
        INCLUDE STRUCTURE ZSCO_COSP_AMT02. "Var.
DATA : END OF   IT_COSP.
DATA : BEGIN OF IT_POST OCCURS 1000,
        KOSTL       LIKE  CSKS-KOSTL,
        LSTAR       LIKE  CSLA-LSTAR,
        KSTAR       LIKE  COSP-KSTAR,
        OBJNR       LIKE  COSP-OBJNR.
        INCLUDE STRUCTURE ZSCO_COSP_AMT04. "Fix
        INCLUDE STRUCTURE ZSCO_COSP_AMT02. "Var.
DATA : END OF   IT_POST.
DATA : BEGIN OF IT_REPORT OCCURS 0,
        PERIOD      LIKE  COSP-PERBL,
        KOSTL       LIKE  CSKS-KOSTL,
        LSTAR       LIKE  CSLA-LSTAR,
        OBJNR       LIKE  COSP-OBJNR,
        FIX_AMT     LIKE  COSP-WKF001,
        VAR_AMT     LIKE  COSP-WKF001,
        RATE        LIKE  ZSCO_COSS_RAT01-RAT001,
        CH_VAR_AMT  LIKE  COSP-WKF001,
        WAERS       LIKE  TKA01-WAERS,  "CO area Currency
       END OF  IT_REPORT.

** For BAPI
DATA : IT_COSTCENTERLIST LIKE STANDARD TABLE OF BAPI0012_CCLIST
                         WITH HEADER LINE.
DATA : IT_COSTELEMENTLIST LIKE STANDARD TABLE OF BAPI1030_CELIST
                         WITH HEADER LINE.
DATA : IT_RETURN         LIKE STANDARD TABLE OF BAPIRET2
                         WITH HEADER LINE.
DATA : WA_HEADERINFO     LIKE BAPIPLNHDR.
DATA : IT_INDEXSTRUCTURE LIKE STANDARD TABLE OF BAPIACPSTRU
                         WITH HEADER LINE.
DATA : IT_COOBJECT       LIKE STANDARD TABLE OF BAPIPCPOBJ
                         WITH HEADER LINE.
DATA : IT_PERVALUE       LIKE STANDARD TABLE OF BAPIPCPVAL
                         WITH HEADER LINE.
DATA : IT_TOTVALUE       LIKE STANDARD TABLE OF BAPIPCPTOT
                         WITH HEADER LINE.

** For OBJECT KEY
DATA : BEGIN OF WA_OBJ ,
        OBJNR  LIKE  COSS-OBJNR,
        KOSTL  LIKE  CSKS-KOSTL,
        LSTAR  LIKE  CSLA-LSTAR,
       END OF WA_OBJ.
DATA : IT_OBJ_CCTR      LIKE STANDARD TABLE OF WA_OBJ
                        WITH HEADER LINE .
DATA : IT_OBJ_CCTR_AT   LIKE STANDARD TABLE OF WA_OBJ
                        WITH HEADER LINE .
DATA : IT_OBJ_ALL       LIKE STANDARD TABLE OF WA_OBJ
                        WITH HEADER LINE .

** Work Area / Global Fields
* For Fields Group
DATA : GV_FIELDGROUP_RAT(3) VALUE 'RAT'.
DATA : GV_FIELDGROUP_MEG(3) VALUE 'MEG'.
DATA : GV_FIELDGROUP_WKF(3) VALUE 'WKF'.
DATA : GV_FIELDGROUP_WKG(3) VALUE 'WKG'.
DATA : GV_FIELDGROUP_VAR(3) VALUE 'VAR'.
* For DATA retrieval
DATA : GV_CI_TABNAME TYPE  DDOBJNAME .
DATA : GV_PERCOUNT LIKE COSP-PERBL. "Period Counter
* For DD data
DATA : IT_ET_FIELDLIST LIKE TABLE OF RFVICP_DDIC_TABL_FIELDNAME
                       WITH HEADER LINE.

** For ALV
DATA : GV_REPID LIKE SY-REPID.
DATA : GV_STATUS       TYPE SLIS_FORMNAME VALUE 'PF_STATUS_VAR'.
DATA : GV_USER_COMMAND TYPE SLIS_FORMNAME VALUE 'USER_COMMAND'.
DATA : IT_SORT         TYPE SLIS_T_SORTINFO_ALV WITH HEADER LINE .
DATA : GV_COL_POS TYPE I.
DATA : IT_FIELDCAT          TYPE SLIS_T_FIELDCAT_ALV,
       WA_FIELDCAT           LIKE LINE OF IT_FIELDCAT,
       IT_EVENTCAT          TYPE SLIS_T_EVENT,
       WA_EVENTCAT           LIKE LINE OF IT_EVENTCAT.
DATA : IT_EVENTS	          TYPE SLIS_T_EVENT,
       IT_EVENT_EXIT	    TYPE SLIS_T_EVENT_EXIT.


*----------------------------------------------------------------------*
*  Macro
*----------------------------------------------------------------------*
* Macro for defining FIELDCATs
DEFINE BULID_FIELDCAT.
  ADD 1 TO GV_COL_POS.
  WA_FIELDCAT-TABNAME     = &1.
  WA_FIELDCAT-FIELDNAME   = &2.
  WA_FIELDCAT-KEY         = &3.
  WA_FIELDCAT-DO_SUM      = &4.
  WA_FIELDCAT-CFIELDNAME  = &5.
  WA_FIELDCAT-CTABNAME    = &6.
  WA_FIELDCAT-OUTPUTLEN   = &7.
  WA_FIELDCAT-SELTEXT_L   = &8.
  WA_FIELDCAT-DATATYPE    = &9.
  WA_FIELDCAT-COL_POS     = GV_COL_POS.
*  WA_FIELDCAT-REF_FIELDNAME  = &5.
*  WA_FIELDCAT-REF_TABNAME = &6.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.
END-OF-DEFINITION.
* Macro For Transferring value in BAPI
DEFINE TRANS_VALUE.
  IT_PERVALUE-FIX_VAL_PER&1  =  IT_POST-WKF0&1.
  IT_PERVALUE-VAR_VAL_PER&1  =  IT_POST-VAR0&1.
END-OF-DEFINITION.
* For Minus value
DEFINE Minus_VALUE.
  IT_TMP_L_COSS-MEG&1 = IT_TMP_L_COSS-MEG&1 * ( -1 ).
END-OF-DEFINITION.


*----------------------------------------------------------------------*
*   Selection Condition                                                *
*----------------------------------------------------------------------*
SELECTION-SCREEN BEGIN OF BLOCK BL1 WITH FRAME TITLE TEXT-001.
PARAMETERS : P_KOKRS LIKE CSKS-KOKRS MEMORY ID CAC OBLIGATORY,
             P_GJAHR LIKE COBK-GJAHR MEMORY ID GJR OBLIGATORY,
             P_FRPER LIKE COSP-PERBL MEMORY ID BPE OBLIGATORY,
             P_TOPER LIKE COSP-PERBL MEMORY ID BPE OBLIGATORY,
             P_FRVER LIKE COBK-VERSN MEMORY ID KVT OBLIGATORY,
             P_TOVER LIKE COBK-VERSN MEMORY ID KVT OBLIGATORY,
             P_CURRT LIKE PLNHDR-PLNCT DEFAULT 'C' OBLIGATORY,
             P_TRUN(1).
SELECTION-SCREEN SKIP 1.

SELECTION-SCREEN BEGIN OF BLOCK BL3 WITH FRAME TITLE TEXT-003.

SELECT-OPTIONS : S_KOSTL  FOR CSKS-KOSTL.
PARAMETERS:      P_NCOAL LIKE GRPDYNP-NAME_COALL
                                     DEFAULT GV_CCGR_SETID_ALL.
SELECTION-SCREEN END OF BLOCK BL3.

SELECTION-SCREEN BEGIN OF BLOCK BL2 WITH FRAME TITLE TEXT-002.
SELECT-OPTIONS : S_KSTAR  FOR COSP-KSTAR.
PARAMETERS :     P_CEGRP  LIKE GRPDYNP-NAME_COALL.
SELECTION-SCREEN END OF BLOCK BL2.

SELECTION-SCREEN END OF BLOCK BL1.
