*&---------------------------------------------------------------------*
*&  Include           ZGHRR00100TOP
*&---------------------------------------------------------------------*

REPORT   ZGHRR00100.

CONSTANTS: GC_RED       TYPE ICON-ID VALUE '@0A@',
                      GC_YELLOW   TYPE ICON-ID VALUE '@09@'.

TABLES: PA0001.

DATA: BEGIN OF GS_DATA,
  ICONNAME  TYPE ICONNAME,
BUKRS           TYPE BUKRS,
PERNR           TYPE PERNR_D,
ENAME         TYPE EMNAM,
PERSG           TYPE PERSG,
PGTXT           TYPE PGTXT,
PERSK           TYPE PERSK,
PKTXT           TYPE PKTXT,
ORGEH           TYPE ORGEH,
ORGTX             TYPE ORGTX,
BEGDA           TYPE DATUM,
ENDDA           TYPE DATUM,
ZZCGSJBGRP    TYPE ZCGSJBGRP,
ZZCGSJIKUN    TYPE ZCGSJIKUN,
ZZCGSJIKUB    TYPE ZCGSJIKUB,
ZZCGSAGREE   TYPE ZCGSAGREE,
 MODE,
  END OF GS_DATA.

DATA:
      OK_CODE       LIKE SY-UCOMM,
      G_R_CONT      TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
      G_R_GRID      TYPE REF TO CL_GUI_ALV_GRID,

      GT_EX_TOOL    TYPE UI_FUNCTIONS,
      GT_FCAT       TYPE TABLE OF LVC_S_FCAT WITH HEADER LINE,
      GT_DATA       LIKE TABLE OF GS_DATA WITH HEADER LINE,
      GS_VARIANT    TYPE DISVARIANT,
      GS_LAYOUT     TYPE LVC_S_LAYO,

      G_MSG         TYPE TEXT100,
      G_SELIDX        TYPE I,
      G_FVAL(100).



SELECTION-SCREEN BEGIN OF BLOCK BLOCK WITH FRAME TITLE TEXT-T01.

SELECTION-SCREEN: BEGIN OF LINE,
  COMMENT 1(12) TEXT-T02 FOR FIELD P_BUKRS,
                  POSITION 14.
PARAMETERS: P_BUKRS TYPE BUKRS DEFAULT 'H201'.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN: BEGIN OF LINE,
  COMMENT 1(12) TEXT-T03 FOR FIELD P_PERNR,
                  POSITION 11.
SELECT-OPTIONS P_PERNR FOR PA0001-PERNR   MATCHCODE OBJECT PREM NO INTERVALS.

SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN: BEGIN OF LINE,
    COMMENT 1(12) TEXT-T04 FOR FIELD P_BEGDA,
                  POSITION 14.
PARAMETERS: P_BEGDA TYPE DATUM OBLIGATORY.
SELECTION-SCREEN: COMMENT 26(2) TEXT-T05 FOR FIELD P_ENDDA,
                POSITION 28.
PARAMETERS: P_ENDDA TYPE DATUM OBLIGATORY.

SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN: BEGIN OF LINE,
COMMENT 1(12) TEXT-T06 FOR FIELD P_INFO,
                  POSITION 14.
PARAMETERS: P_INFO TYPE FLAG  RADIOBUTTON GROUP RDO1 DEFAULT 'X'.
SELECTION-SCREEN: COMMENT 26(11) TEXT-T07 FOR FIELD P_AGREE,
                POSITION 38.
PARAMETERS: P_AGREE TYPE FLAG RADIOBUTTON GROUP RDO1.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN END OF BLOCK BLOCK .
