 FUNCTION ZIM_APPCIP_EDI_SEND.
*"----------------------------------------------------------------------
*"*"Local interface:
*"  IMPORTING
*"     VALUE(W_ZFREQNO) LIKE  ZTINS-ZFREQNO
*"     VALUE(W_ZFINSEQ) LIKE  ZTINS-ZFINSEQ
*"     VALUE(W_ZFAMDNO) LIKE  ZTINS-ZFAMDNO
*"     VALUE(W_ZFDHENO) LIKE  ZTDHF1-ZFDHENO
*"  EXCEPTIONS
*"      DB_ERROR
*"----------------------------------------------------------------------

 CALL  FUNCTION 'ZIM_GET_INSURANCE_DOC'
    EXPORTING
       ZFREQNO             =          W_ZFREQNO
       ZFINSEQ             =          W_ZFINSEQ
       ZFAMDNO             =          W_ZFAMDNO
    IMPORTING
       W_ZTINS             =          ZTINS
       W_ZTINSRSP          =          ZTINSRSP
       W_ZTINSSG3          =          ZTINSSG3
    TABLES
        IT_ZSINSAGR        =          IT_ZSINSAGR
        IT_ZSINSAGR_ORG    =          IT_ZSINSAGR_ORG
        IT_ZSINSSG2        =          IT_ZSINSSG2
        IT_ZSINSSG2_ORG    =          IT_ZSINSSG2_ORG
        IT_ZSINSSG5        =          IT_ZSINSSG5
        IT_ZSINSSG5_ORG    =          IT_ZSINSSG5_ORG
     EXCEPTIONS
        NOT_FOUND         =    4
        NOT_INPUT         =    8.

 CASE SY-SUBRC.
    WHEN 4.
       IF SY-TCODE NE 'ZIM41'.
          MESSAGE E169 WITH ZTINS-ZFREQNO.
       ENDIF.
    WHEN 8.
       MESSAGE E173.
 ENDCASE.
*-----------------------------------------------------------------------
* internal Table Append
*-----------------------------------------------------------------------
   REFRESH : IT_ZTDDF1.
   CLEAR : IT_ZTDDF1.
   IT_ZTDDF1-ZFDDENO = W_ZFDHENO.
*>>> 전자문서 시작
   IT_ZTDDF1-ZFDDFDA = '{10'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '4AA'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = W_ZFDHENO.        APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '' .              APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ''.               APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}10'.            APPEND IT_ZTDDF1.
*>>> 위험개시일
   IT_ZTDDF1-ZFDDFDA = '{11'.               APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '92'.                APPEND IT_ZTDDF1.
   IF ZTINS-ZFINSDT+2(2) GE '10'.
      IT_ZTDDF1-ZFDDFDA = ZTINS-ZFINSDT+2(4).  APPEND IT_ZTDDF1.
   ELSE.
      IT_ZTDDF1-ZFDDFDA = ZTINS-ZFINSDT+3(3).  APPEND IT_ZTDDF1.
   ENDIF.
   IT_ZTDDF1-ZFDDFDA = '6TA'.               APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}11'.            APPEND IT_ZTDDF1.
*>>> 포괄보험증권번호
   IT_ZTDDF1-ZFDDFDA = '{12'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '4AB'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTINS-ZFOPNO.     APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}12'.            APPEND IT_ZTDDF1.
*>>> L/C 문구
   IF NOT ( ZTINS-ZFFTX1 IS INITIAL AND ZTINS-ZFFTX2 IS INITIAL AND
            ZTINS-ZFFTX3 IS INITIAL AND ZTINS-ZFFTX4 IS INITIAL AND
            ZTINS-ZFFTX5 IS INITIAL ).
      IT_ZTDDF1-ZFDDFDA = '{13'.                APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = 'IIN'.                APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTINS-ZFFTX1.         APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTINS-ZFFTX2.         APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTINS-ZFFTX3.         APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTINS-ZFFTX4.         APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTINS-ZFFTX5.         APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '}13'.                APPEND IT_ZTDDF1.
   ENDIF.
*>>> 기타지시사항
   IF NOT ( ZTINS-ZFETC1 IS INITIAL AND ZTINS-ZFETC2 IS INITIAL AND
            ZTINS-ZFETC3 IS INITIAL AND ZTINS-ZFETC4 IS INITIAL AND
            ZTINS-ZFETC5 IS INITIAL ).
      IT_ZTDDF1-ZFDDFDA = '{13'.                APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '2AE'.                APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTINS-ZFETC1.         APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTINS-ZFETC2.         APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTINS-ZFETC3.         APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTINS-ZFETC4.         APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTINS-ZFETC5.         APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '}13'.                APPEND IT_ZTDDF1.
   ENDIF.
*>>> 피보험자 상호
   IT_ZTDDF1-ZFDDFDA = '{14'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = 'BM'..            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ''.               APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ''.               APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTINS-ZFINSU1.    APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTINS-ZFINSU2.    APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ''.               APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ''.               APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ''.               APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}14'.            APPEND IT_ZTDDF1.
* 보험계약자
   IT_ZTDDF1-ZFDDFDA = '{14'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '4AA'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTINS-ZFELTXN.    APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '1AB'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ''.               APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ''.               APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTINS-ZFELENM.    APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTINS-ZFREPRE.    APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTINS-ZFELEID.    APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}14'.            APPEND IT_ZTDDF1.
* 손보사 영업담당자 코드
   IF NOT ( ZTINS-ZFCONID IS INITIAL AND ZTINS-ZFCONNM IS INITIAL ).
      IT_ZTDDF1-ZFDDFDA = '{15'.            APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = 'IC'.             APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTINS-ZFCONID.    APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTINS-ZFCONNM.    APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '}15'.            APPEND IT_ZTDDF1.
   ENDIF.
* 질권기관
   IF NOT ( ZTINS-ZFOPBNCD IS INITIAL AND ZTINS-ZFEINM IS INITIAL AND
            ZTINS-ZFEIBR   IS INITIAL ).
      IT_ZTDDF1-ZFDDFDA = '{16'.            APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = 'AZ'.             APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTINS-ZFOPBNCD.   APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '25'.             APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = 'BOK'.            APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTINS-ZFEINM.     APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTINS-ZFEIBR.     APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '}16'.            APPEND IT_ZTDDF1.
   ENDIF.
* 대표 H/S CODE
   IT_ZTDDF1-ZFDDFDA = '{17'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '1'.              APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTINS-ZFRSTAW.    APPEND IT_ZTDDF1.
* 서류번호 1 ~ 3 ( 최대 3회 반복 )
   IF NOT ( ZTINS-ZFREDOC1 IS INITIAL AND ZTINS-ZFREDON1 IS INITIAL ).
      IT_ZTDDF1-ZFDDFDA = '{20'.            APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTINS-ZFREDOC1.   APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTINS-ZFREDON1.   APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '}20'.            APPEND IT_ZTDDF1.
   ENDIF.
   IF NOT ( ZTINS-ZFREDOC2 IS INITIAL AND ZTINS-ZFREDON2 IS INITIAL ).
      IT_ZTDDF1-ZFDDFDA = '{20'.            APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTINS-ZFREDOC2.   APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTINS-ZFREDON2.   APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '}20'.            APPEND IT_ZTDDF1.
   ENDIF.
   IF NOT ( ZTINS-ZFREDOC3 IS INITIAL AND ZTINS-ZFREDON3 IS INITIAL ).
      IT_ZTDDF1-ZFDDFDA = '{20'.            APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTINS-ZFREDOC3.   APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTINS-ZFREDON3.   APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '}20'.            APPEND IT_ZTDDF1.
   ENDIF.
* 상품명세
   LOOP AT IT_ZSINSSG2.
      IT_ZTDDF1-ZFDDFDA = '{21'.               APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = 'AAA'.               APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = IT_ZSINSSG2-ZFDSOG1. APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = IT_ZSINSSG2-ZFDSOG2. APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = IT_ZSINSSG2-ZFDSOG3. APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = IT_ZSINSSG2-ZFDSOG4. APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = IT_ZSINSSG2-ZFDSOG5. APPEND IT_ZTDDF1.
* 상품수량 및 단위
      IF NOT ( IT_ZSINSSG2-ZFPKCN  IS INITIAL AND
               IT_ZSINSSG2-ZFPKCNM IS INITIAL ).
         IT_ZTDDF1-ZFDDFDA = '{30'.               APPEND IT_ZTDDF1.

         WRITE   IT_ZSINSSG2-ZFPKCN    TO   W_TEXT_AMOUNT
                                       UNIT IT_ZSINSSG2-ZFPKCNM.
         PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.
         IT_ZTDDF1-ZFDDFDA = W_TEXT_AMOUNT.       APPEND IT_ZTDDF1.
*>>> UNIT ISO CODE <=== 내부코드로 변환( PKG    단위 )
         PERFORM    SET_UNIT_CONV_TO_EXTERNAL
                             CHANGING IT_ZSINSSG2-ZFPKCNM.
         IT_ZTDDF1-ZFDDFDA = IT_ZSINSSG2-ZFPKCNM. APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '}30'.               APPEND IT_ZTDDF1.
      ENDIF.
      IT_ZTDDF1-ZFDDFDA = '}21'.               APPEND IT_ZTDDF1.
   ENDLOOP.
* 항차 / 선명
   IT_ZTDDF1-ZFDDFDA = '{22'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '20'.             APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTINSSG3-ZFCARNU. APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTINSSG3-ZFCARNM. APPEND IT_ZTDDF1.
* 선적국가
   IF NOT ( ZTINSSG3-ZFSHCU    IS INITIAL AND
            ZTINSSG3-ZFSHCUNM  IS INITIAL ).
      IT_ZTDDF1-ZFDDFDA = '{31'.               APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '9'.                 APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTINSSG3-ZFSHCU.     APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTINSSG3-ZFSHCUNM.   APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '}31'.               APPEND IT_ZTDDF1.
   ENDIF.
* 도착국가
   IF NOT ( ZTINSSG3-ZFARCU    IS INITIAL AND
            ZTINSSG3-ZFARCUNM  IS INITIAL ).
      IT_ZTDDF1-ZFDDFDA = '{31'.               APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '12'.                APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTINSSG3-ZFARCU.     APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTINSSG3-ZFARCUNM.   APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '}31'.               APPEND IT_ZTDDF1.
   ENDIF.
* 최종도착국가
   IF NOT ( ZTINSSG3-ZFLACU    IS INITIAL AND
            ZTINSSG3-ZFLACUNM  IS INITIAL ).
      IT_ZTDDF1-ZFDDFDA = '{31'.               APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '20'.                APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTINSSG3-ZFLACU.     APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTINSSG3-ZFLACUNM.   APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '}31'.               APPEND IT_ZTDDF1.
   ENDIF.
* 환적지  국가
   IF NOT ( ZTINSSG3-ZFTRCU    IS INITIAL AND
            ZTINSSG3-ZFTRCUNM  IS INITIAL ).
      IT_ZTDDF1-ZFDDFDA = '{31'.               APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '13'.                APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTINSSG3-ZFTRCU.     APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTINSSG3-ZFTRCUNM.   APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '}31'.               APPEND IT_ZTDDF1.
   ENDIF.
* 출항일
   IF NOT ZTINSSG3-ZFDPDT IS INITIAL.
      IT_ZTDDF1-ZFDDFDA = '{32'.              APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '136'.              APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTINSSG3-ZFDPDT+2.  APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '101'.              APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '}32'.              APPEND IT_ZTDDF1.
   ENDIF.
   IT_ZTDDF1-ZFDDFDA = '}22'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}17'.            APPEND IT_ZTDDF1.

*-----------------------------------------------------------------------
* 사본 / 원본 발급회수
*-----------------------------------------------------------------------
   IT_ZTDDF1-ZFDDFDA = '{18'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '530'.            APPEND IT_ZTDDF1.
* 사본
   IF ZTINS-ZFNUCD GE 10.
      IT_ZTDDF1-ZFDDFDA = ZTINS-ZFNUCD.       APPEND IT_ZTDDF1.
   ELSE.
      IT_ZTDDF1-ZFDDFDA = ZTINS-ZFNUCD+1(1).  APPEND IT_ZTDDF1.
   ENDIF.
* 원본
   IF ZTINS-ZFNUOD GE 10.
      IT_ZTDDF1-ZFDDFDA = ZTINS-ZFNUOD.       APPEND IT_ZTDDF1.
   ELSE.
      IT_ZTDDF1-ZFDDFDA = ZTINS-ZFNUOD+1(1).  APPEND IT_ZTDDF1.
   ENDIF.
   IT_ZTDDF1-ZFDDFDA = '}18'.            APPEND IT_ZTDDF1.

*-----------------------------------------------------------------------
* SEGMENT GROUP - 4
*-----------------------------------------------------------------------
* INVOICE AMOUNT
   IT_ZTDDF1-ZFDDFDA = '{19'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '77'.             APPEND IT_ZTDDF1.
   WRITE   ZTINS-ZFIVAMT         TO   W_TEXT_AMOUNT
                       CURRENCY       ZTINS-WAERS.
   PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.
   IT_ZTDDF1-ZFDDFDA = W_TEXT_AMOUNT.        APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTINS-WAERS.          APPEND IT_ZTDDF1.
* 희망이익율
   IF NOT ZTINS-ZFPEIV IS INITIAL.
      WRITE  ZTINS-ZFPEIV       TO    W_TEXT_AMOUNT.
      PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.

      IT_ZTDDF1-ZFDDFDA = '{23'.            APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '7'.              APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = W_TEXT_AMOUNT.    APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '}23'.            APPEND IT_ZTDDF1.
   ENDIF.
* 관세율
   IF NOT ZTINS-ZFPEDU IS INITIAL.
      WRITE  ZTINS-ZFPEDU   TO    W_TEXT_AMOUNT.
      PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.
      IT_ZTDDF1-ZFDDFDA = '{23'.            APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '4AD'.            APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = W_TEXT_AMOUNT.    APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '}23'.            APPEND IT_ZTDDF1.
   ENDIF.
   IT_ZTDDF1-ZFDDFDA = '}19'.            APPEND IT_ZTDDF1.
* 관세가액
   IF NOT ( ZTINS-ZFDUAMT IS INITIAL AND ZTINS-ZFDUAMC IS INITIAL ).
      IT_ZTDDF1-ZFDDFDA = '{19'.            APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '43'.             APPEND IT_ZTDDF1.
      WRITE   ZTINS-ZFDUAMT         TO   W_TEXT_AMOUNT
                          CURRENCY       ZTINS-ZFDUAMC.
      PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.
      IT_ZTDDF1-ZFDDFDA = W_TEXT_AMOUNT.    APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTINS-ZFDUAMC.    APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '}19'.            APPEND IT_ZTDDF1.
   ENDIF.
* 기본 및 부가조건 코드
   SORT IT_ZSINSAGR BY ZFBCNYN DESCENDING.
   LOOP AT IT_ZSINSAGR.
      IT_ZTDDF1-ZFDDFDA = '{1A'.               APPEND IT_ZTDDF1.
* 기본 조건인지 부가 조건인지 구분
      IF IT_ZSINSAGR-ZFBCNYN EQ 'X'.
         IT_ZTDDF1-ZFDDFDA = '4AA'.            APPEND IT_ZTDDF1.
      ELSE.
         IT_ZTDDF1-ZFDDFDA = '4AB'.            APPEND IT_ZTDDF1.
      ENDIF.
      IT_ZTDDF1-ZFDDFDA = IT_ZSINSAGR-ZFCNCD.   APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '4AA'.                APPEND IT_ZTDDF1.
*----------------------------------------------------------------------*
* 현대해상의 요청으로 앞으 두자리는 SPACE
      CLEAR : IT_ZTDDF1-ZFDDFDA.
      IT_ZTDDF1-ZFDDFDA+2(68) = IT_ZSINSAGR-ZFCNCDNM.
      APPEND IT_ZTDDF1.
*----------------------------------------------------------------------*
      IT_ZTDDF1-ZFDDFDA = '}1A'.               APPEND IT_ZTDDF1.
   ENDLOOP.
* 공동인수비율 / 손보사
   LOOP AT IT_ZSINSSG5.
      IT_ZTDDF1-ZFDDFDA = '{1B'.                APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = 'IO'.                 APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = IT_ZSINSSG5-ZFINSC.   APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '160'.                APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '4AA'.                APPEND IT_ZTDDF1.
      IF NOT IT_ZSINSSG5-ZFINSRT IS INITIAL.
         WRITE  IT_ZSINSSG5-ZFINSRT TO  W_TEXT_AMOUNT.
         PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.
         IT_ZTDDF1-ZFDDFDA = '{24'.                APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '4AC'.                APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = W_TEXT_AMOUNT.        APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '}24'.                APPEND IT_ZTDDF1.
      ENDIF.
      IT_ZTDDF1-ZFDDFDA = '}1B'.               APPEND IT_ZTDDF1.
   ENDLOOP.
*
   CALL FUNCTION 'ZIM_EDI_FLAT_ITEM_INSERT'
        EXPORTING
              W_ZFDHENO         =        W_ZFDHENO
        TABLES
              IT_ZTDDF1         =        IT_ZTDDF1
        EXCEPTIONS
              DB_ERROR         =         4.

   IF SY-SUBRC NE 0.
      MESSAGE E118 WITH W_ZFDHENO.
   ENDIF.

ENDFUNCTION.
