FUNCTION ZIM_GET_LOCAL_LC_DATA.
*"----------------------------------------------------------------------
*"*"Local interface:
*"  IMPORTING
*"     VALUE(ZFREQNO) LIKE  ZTREQHD-ZFREQNO
*"  EXPORTING
*"     VALUE(W_ZTLLCHD) LIKE  ZTLLCHD STRUCTURE  ZTLLCHD
*"     VALUE(W_ZTLLCSG23) LIKE  ZTLLCSG23 STRUCTURE  ZTLLCSG23
*"  TABLES
*"      IT_ZSLLCOF STRUCTURE  ZSLLCOF
*"      IT_ZSLLCOF_ORG STRUCTURE  ZSLLCOF
*"  EXCEPTIONS
*"      NOT_FOUND
*"      NOT_INPUT
*"----------------------------------------------------------------------

  REFRESH : IT_ZSLLCOF, IT_ZSLLCOF_ORG.

  CLEAR : W_ZTLLCHD, W_ZTLLCSG23.

  IF ZFREQNO IS INITIAL.
     RAISE NOT_INPUT.
  ENDIF.

  SELECT SINGLE * INTO   W_ZTLLCHD FROM ZTLLCHD
                  WHERE  ZFREQNO   EQ   ZFREQNO.

  IF SY-SUBRC NE 0.
     RAISE NOT_FOUND.
  ENDIF.

  SELECT SINGLE * INTO   W_ZTLLCSG23 FROM ZTLLCSG23
                  WHERE  ZFREQNO     EQ   ZFREQNO.

  SELECT *  INTO CORRESPONDING FIELDS OF TABLE IT_ZSLLCOF
            FROM   ZTLLCOF
            WHERE  ZFREQNO      EQ   ZFREQNO
            ORDER BY  ZFLSGOF.

  LOOP AT IT_ZSLLCOF.

     MOVE-CORRESPONDING   IT_ZSLLCOF    TO   IT_ZSLLCOF_ORG.
     APPEND IT_ZSLLCOF_ORG.
  ENDLOOP.


ENDFUNCTION.
