FUNCTION ZIM_DOMOFR_EDI_SEND.
*"----------------------------------------------------------------------
*"*"Local interface:
*"  IMPORTING
*"     VALUE(W_ZFREQNO) LIKE  ZTOFF-ZFREQNO
*"     VALUE(W_ZFDHENO) LIKE  ZTDHF1-ZFDHENO
*"  EXCEPTIONS
*"      DB_ERROR
*"----------------------------------------------------------------------
  CALL  FUNCTION 'ZIM_GET_OFFER_SHEET_DOC'
     EXPORTING
        ZFREQNO             =          W_ZFREQNO
     IMPORTING
        W_ZTOFF             =          ZTOFF
        W_ZTOFFFTX          =          ZTOFFFTX
     TABLES
        IT_ZSOFFO          =          IT_ZSOFFO
        IT_ZSOFFO_ORG      =          IT_ZSOFFO_ORG
        IT_ZSOFFSDE        =          IT_ZSOFFSDE
        IT_ZSOFFSDE_ORG    =          IT_ZSOFFSDE_ORG
        IT_ZSOFFSG6        =          IT_ZSOFFSG6
        IT_ZSOFFSG6_ORG    =          IT_ZSOFFSG6_ORG
        IT_ZSOFFSG6G       =          IT_ZSOFFSG6G
        IT_ZSOFFSG6G_ORG   =          IT_ZSOFFSG6G_ORG
     EXCEPTIONS
        NOT_FOUND         =    4
        NOT_INPUT         =    8.


     CASE SY-SUBRC.
        WHEN 4.
           MESSAGE E018 WITH W_ZFREQNO.
        WHEN 8.
           MESSAGE E019.
     ENDCASE.

*-----------------------------------------------------------------------
* internal Table Append
*-----------------------------------------------------------------------
   REFRESH : IT_ZTDDF1.
   CLEAR : IT_ZTDDF1.
   IT_ZTDDF1-ZFDDENO = W_ZFDHENO.
*>>> 전자문서 시작
   IT_ZTDDF1-ZFDDFDA = '{10'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '1BL'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = W_ZFDHENO.        APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '9'.              APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = 'AB'.             APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}10'.            APPEND IT_ZTDDF1.
*>>> 원산지 국가
   LOOP AT IT_ZSOFFO.
      IT_ZTDDF1-ZFDDFDA = '{11'.            APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '27'.             APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = IT_ZSOFFO-ZFORIG. APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '162'.            APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '5'.              APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = IT_ZSOFFO-ZFORNM. APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '}11'.            APPEND IT_ZTDDF1.
   ENDLOOP.
*>>> 오퍼유효기간 평문
   IF NOT ( ZTOFFFTX-ZFED1 IS INITIAL AND ZTOFFFTX-ZFED2 IS INITIAL AND
            ZTOFFFTX-ZFED3 IS INITIAL AND ZTOFFFTX-ZFED4 IS INITIAL AND
            ZTOFFFTX-ZFED5 IS INITIAL ).
      IT_ZTDDF1-ZFDDFDA = '{12'.                APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '1AB'.                APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTOFFFTX-ZFED1.       APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTOFFFTX-ZFED2.       APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTOFFFTX-ZFED3.       APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTOFFFTX-ZFED4.       APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTOFFFTX-ZFED5.       APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '}12'.                APPEND IT_ZTDDF1.
   ENDIF.
*>>> 검사방법
   IF NOT ( ZTOFFFTX-ZFISM1 IS INITIAL AND ZTOFFFTX-ZFISM2 IS INITIAL
      AND ZTOFFFTX-ZFISM3 IS INITIAL AND ZTOFFFTX-ZFISM4 IS INITIAL AND
          ZTOFFFTX-ZFISM5 IS INITIAL ).
      IT_ZTDDF1-ZFDDFDA = '{12'.                APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = 'ITS'.                APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTOFFFTX-ZFISM1.      APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTOFFFTX-ZFISM2.      APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTOFFFTX-ZFISM3.      APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTOFFFTX-ZFISM4.      APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTOFFFTX-ZFISM5.      APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '}12'.                APPEND IT_ZTDDF1.
   ENDIF.
*>>> 대금결제방법
   IF NOT ( ZTOFFFTX-ZFPAM1 IS INITIAL AND ZTOFFFTX-ZFPAM2 IS INITIAL
      AND ZTOFFFTX-ZFPAM3 IS INITIAL AND ZTOFFFTX-ZFPAM4 IS INITIAL AND
          ZTOFFFTX-ZFPAM5 IS INITIAL ).
      IT_ZTDDF1-ZFDDFDA = '{12'.                APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = 'AAB'.                APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTOFFFTX-ZFPAM1.      APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTOFFFTX-ZFPAM2.      APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTOFFFTX-ZFPAM3.      APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTOFFFTX-ZFPAM4.      APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTOFFFTX-ZFPAM5.      APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '}12'.                APPEND IT_ZTDDF1.
   ENDIF.
*>>> 포장방법
   IF NOT ( ZTOFFFTX-ZFPKM1 IS INITIAL AND ZTOFFFTX-ZFPKM2 IS INITIAL
      AND ZTOFFFTX-ZFPKM3 IS INITIAL AND ZTOFFFTX-ZFPKM4 IS INITIAL AND
          ZTOFFFTX-ZFPKM5 IS INITIAL ).
      IT_ZTDDF1-ZFDDFDA = '{12'.                APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = 'PKG'.                APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTOFFFTX-ZFPKM1.      APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTOFFFTX-ZFPKM2.      APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTOFFFTX-ZFPKM3.      APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTOFFFTX-ZFPKM4.      APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTOFFFTX-ZFPKM5.      APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '}12'.                APPEND IT_ZTDDF1.
   ENDIF.
*>>> 발행번호
   IT_ZTDDF1-ZFDDFDA = '{13'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = 'AAG'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTOFF-ZFISSNO.    APPEND IT_ZTDDF1.
* >>>>>>>>>발행일자
   IT_ZTDDF1-ZFDDFDA = '{20'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '182'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTOFF-ZFISSDT.    APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '101'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}20'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}13'.            APPEND IT_ZTDDF1.
*>>> 수혜업자
   IT_ZTDDF1-ZFDDFDA = '{14'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = 'SE'.             APPEND IT_ZTDDF1.
   IF NOT ( ZTOFF-ZFELNO IS INITIAL ).
      IT_ZTDDF1-ZFDDFDA = ZTOFF-ZFELNO.  APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '1AD'.         APPEND IT_ZTDDF1.
   ELSE.
      IT_ZTDDF1-ZFDDFDA = ''.            APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ''.            APPEND IT_ZTDDF1.
   ENDIF.
   IT_ZTDDF1-ZFDDFDA = ZTOFF-ZFELENM.    APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTOFF-ZFREPRE.    APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTOFF-ZFELEID.    APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTOFF-ZFAPPAD1.   APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTOFF-ZFAPPAD2.   APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTOFF-ZFAPPAD3.   APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}14'.            APPEND IT_ZTDDF1.
*>>> 개설업체
   IT_ZTDDF1-ZFDDFDA = '{14'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = 'BY'.             APPEND IT_ZTDDF1.
   IF NOT ( ZTOFF-ZFVETXN IS INITIAL ).
      IT_ZTDDF1-ZFDDFDA = ZTOFF-ZFVETXN. APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '1AB'.         APPEND IT_ZTDDF1.
   ELSE.
      IT_ZTDDF1-ZFDDFDA = ''.            APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ''.            APPEND IT_ZTDDF1.
   ENDIF.
   IT_ZTDDF1-ZFDDFDA = ZTOFF-ZFVENNM.    APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTOFF-ZFVENRE.    APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTOFF-ZFVENID.    APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTOFF-ZFVENAD1.   APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTOFF-ZFVENAD2.   APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTOFF-ZFVENAD3.   APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}14'.            APPEND IT_ZTDDF1.
*>>> 운송유형 코드
   IT_ZTDDF1-ZFDDFDA = '{15'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '20'.             APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTOFF-ZFTRME.     APPEND IT_ZTDDF1.
*-------> 선적국가
   IF NOT ZTOFF-ZFSHCU IS INITIAL.
      IT_ZTDDF1-ZFDDFDA = '{21'.            APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '27'.             APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTOFF-ZFSHCU.     APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '162'.            APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '5'.              APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTOFF-ZFSHCUNM.   APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '}21'.            APPEND IT_ZTDDF1.
   ENDIF.
*-------> 도착국가
   IF NOT ZTOFF-ZFARCU IS INITIAL.
      IT_ZTDDF1-ZFDDFDA = '{21'.            APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '8'..             APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTOFF-ZFARCU.     APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '162'.            APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '5'.              APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTOFF-ZFARCUNM.   APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '}21'.            APPEND IT_ZTDDF1.
   ENDIF.
*-------> 선적시기
   IF NOT ( ZTOFF-ZFSHDT1 IS INITIAL AND ZTOFF-ZFSHDT2 IS INITIAL AND
            ZTOFF-ZFSHDT3 IS INITIAL AND ZTOFF-ZFSHDT4 IS INITIAL AND
            ZTOFF-ZFSHDT5 IS INITIAL ).
      IT_ZTDDF1-ZFDDFDA = '{22'.            APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '1AC'.            APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTOFF-ZFSHDT1.    APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTOFF-ZFSHDT2.    APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTOFF-ZFSHDT3.    APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTOFF-ZFSHDT4.    APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTOFF-ZFSHDT5.    APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '}22'.            APPEND IT_ZTDDF1.
   ENDIF.
*-------> 도착시기
   IF NOT ( ZTOFF-ZFGADT1 IS INITIAL AND ZTOFF-ZFGADT2 IS INITIAL AND
            ZTOFF-ZFGADT3 IS INITIAL AND ZTOFF-ZFGADT4 IS INITIAL AND
            ZTOFF-ZFGADT5 IS INITIAL ).
      IT_ZTDDF1-ZFDDFDA = '{22'.            APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '1AD'.            APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTOFF-ZFGADT1.    APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTOFF-ZFGADT2.    APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTOFF-ZFGADT3.    APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTOFF-ZFGADT4.    APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTOFF-ZFGADT5.    APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '}22'.            APPEND IT_ZTDDF1.
   ENDIF.
   IT_ZTDDF1-ZFDDFDA = '}15'.            APPEND IT_ZTDDF1.
*>>> Seg 6 ( 상품명세 )
   LOOP AT IT_ZSOFFSG6.
      IT_ZTDDF1-ZFDDFDA = '{16'.                APPEND IT_ZTDDF1.
* -----------> 일련번호
      IT_ZTDDF1-ZFDDFDA = IT_ZSOFFSG6-ZFLSG6.   APPEND IT_ZTDDF1.
* -----------> H/S CODE
      IF NOT IT_ZSOFFSG6-STAWN IS INITIAL.
         IT_ZTDDF1-ZFDDFDA = '{23'.                APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = IT_ZSOFFSG6-STAWN.    APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '}23'.                APPEND IT_ZTDDF1.
      ENDIF.
* -----------> 품목명
      IF NOT IT_ZSOFFSG6-ZFGD1 IS INITIAL.
         IT_ZTDDF1-ZFDDFDA = '{24'.                APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '1AA'.                APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = IT_ZSOFFSG6-ZFGD1.    APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '}24'.                APPEND IT_ZTDDF1.
      ENDIF.
* -----------> 물품수량
      IF NOT IT_ZSOFFSG6-MENGE IS INITIAL.
         WRITE   IT_ZSOFFSG6-MENGE  TO      W_TEXT_AMOUNT
                               UNIT         IT_ZSOFFSG6-MEINS.
         PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.
         IT_ZTDDF1-ZFDDFDA = '{25'.                APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '1'.                  APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = W_TEXT_AMOUNT.        APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = IT_ZSOFFSG6-MEINS.    APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '}25'.                APPEND IT_ZTDDF1.
      ENDIF.
* -----------> 물품수량 소계
      IF NOT IT_ZSOFFSG6-ZFMENGES IS INITIAL.
         WRITE   IT_ZSOFFSG6-ZFMENGES  TO   W_TEXT_AMOUNT
                               UNIT         IT_ZSOFFSG6-MEINS.
         PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.
         IT_ZTDDF1-ZFDDFDA = '{25'.                APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '3'.                  APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = W_TEXT_AMOUNT.        APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = IT_ZSOFFSG6-MEINS.    APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '}25'.                APPEND IT_ZTDDF1.
      ENDIF.
* -----------> 물품금액
      IF NOT IT_ZSOFFSG6-ZFGOAMT  IS INITIAL.
         WRITE   IT_ZSOFFSG6-ZFGOAMT   TO   W_TEXT_AMOUNT
                               CURRENCY     IT_ZSOFFSG6-WAERS.
         PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.
         IT_ZTDDF1-ZFDDFDA = '{26'.                APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '203'.                APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = W_TEXT_AMOUNT.        APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = IT_ZSOFFSG6-WAERS.    APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '}26'.                APPEND IT_ZTDDF1.
      ENDIF.
* -----------> 물품금액 소계
      IF NOT IT_ZSOFFSG6-ZFGOAMTS IS INITIAL.
         WRITE   IT_ZSOFFSG6-ZFGOAMTS  TO   W_TEXT_AMOUNT
                               CURRENCY     IT_ZSOFFSG6-WAERS.
         PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.
         IT_ZTDDF1-ZFDDFDA = '{26'.                APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '17'.                 APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = W_TEXT_AMOUNT.        APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = IT_ZSOFFSG6-WAERS.    APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '}26'.                APPEND IT_ZTDDF1.
      ENDIF.
* -----------> 선적시기 평문 및 품목규격 ( 생략 )

* -----------> 단가
      IF NOT IT_ZSOFFSG6-NETPR    IS INITIAL.
         WRITE   IT_ZSOFFSG6-NETPR     TO   W_TEXT_AMOUNT
                             CURRENCY       IT_ZSOFFSG6-WAERS.
         PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.
         IT_ZTDDF1-ZFDDFDA = '{28'.                APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = 'CAL'.                APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = W_TEXT_AMOUNT.        APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = 'PE'.                 APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = 'CUP'.                APPEND IT_ZTDDF1.
         WRITE   IT_ZSOFFSG6-PEINH     TO   W_TEXT_AMOUNT.
         PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.
         IT_ZTDDF1-ZFDDFDA = W_TEXT_AMOUNT.        APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = IT_ZSOFFSG6-BPRME.    APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '}28'.                APPEND IT_ZTDDF1.
      ENDIF.
      IT_ZTDDF1-ZFDDFDA = '}16'.                APPEND IT_ZTDDF1.
   ENDLOOP.
*>>> 발행자의 BGM상 전자문서
   IT_ZTDDF1-ZFDDFDA = '{17'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = 'DM'.             APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = W_ZFDHENO.        APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}17'.            APPEND IT_ZTDDF1.
*>>> 참조사항 평문
*===> 참조사항 평문 생략
*>>> 물품 총금액
   WRITE   ZTOFF-ZFTOAM          TO   W_TEXT_AMOUNT
                       CURRENCY       ZTOFF-ZFTOAMC.
   PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.
   IT_ZTDDF1-ZFDDFDA = '{19'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '128'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = W_TEXT_AMOUNT.    APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTOFF-ZFTOAMC.    APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}19'.            APPEND IT_ZTDDF1.
* -----------> 물품수량 소계
   IF NOT ZTOFF-ZFTOCN         IS INITIAL.
      WRITE   ZTOFF-ZFTOCN          TO   W_TEXT_AMOUNT
                            UNIT         ZTOFF-ZFTOCNM.
      PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.
      IT_ZTDDF1-ZFDDFDA = '{1A'.                APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '1AA'.                APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = W_TEXT_AMOUNT.        APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTOFF-ZFTOCNM.        APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '}1A'.                APPEND IT_ZTDDF1.
   ENDIF.
*
   CALL FUNCTION 'ZIM_EDI_FLAT_ITEM_INSERT'
        EXPORTING
              W_ZFDHENO         =        W_ZFDHENO
        TABLES
              IT_ZTDDF1         =        IT_ZTDDF1
        EXCEPTIONS
              DB_ERROR         =         4.

   IF SY-SUBRC NE 0.
      MESSAGE E118 WITH W_ZFDHENO.
   ENDIF.

ENDFUNCTION.
