FUNCTION ZIM_GET_INSURANCE_BL_DOC.
*"----------------------------------------------------------------------
*"*"Local interface:
*"  IMPORTING
*"     VALUE(ZFBLNO) LIKE  ZTINSB-ZFBLNO
*"     VALUE(ZFINSEQ) LIKE  ZTINSB-ZFINSEQ
*"  EXPORTING
*"     VALUE(W_ZTINSB) LIKE  ZTINSB STRUCTURE  ZTINSB
*"     VALUE(W_ZTINSBRSP) LIKE  ZTINSBRSP STRUCTURE  ZTINSBRSP
*"     VALUE(W_ZTINSBSG3) LIKE  ZTINSBSG3 STRUCTURE  ZTINSBSG3
*"  TABLES
*"      IT_ZSINSBAGR STRUCTURE  ZSINSBAGR
*"      IT_ZSINSBSG2 STRUCTURE  ZSINSBSG2
*"      IT_ZSINSBSG5 STRUCTURE  ZSINSBSG5
*"      IT_ZSINSBAGR_ORG STRUCTURE  ZSINSBAGR OPTIONAL
*"      IT_ZSINSBSG2_ORG STRUCTURE  ZSINSBSG2 OPTIONAL
*"      IT_ZSINSBSG5_ORG STRUCTURE  ZSINSBSG5 OPTIONAL
*"  EXCEPTIONS
*"      NOT_FOUND
*"      NOT_INPUT
*"----------------------------------------------------------------------
  REFRESH : IT_ZSINSBAGR,     IT_ZSINSBSG2,     IT_ZSINSBSG5.
  REFRESH : IT_ZSINSBAGR_ORG, IT_ZSINSBSG2_ORG, IT_ZSINSBSG5_ORG.
  CLEAR :   W_ZTINSB,         W_ZTINSBRSP,      W_ZTINSBSG3.

  IF ZFBLNO IS INITIAL.
     RAISE NOT_INPUT.
  ENDIF.
* insurance Header Table
  SELECT SINGLE * INTO   W_ZTINSB  FROM ZTINSB
                  WHERE  ZFBLNO    EQ   ZFBLNO
                  AND    ZFINSEQ   EQ   ZFINSEQ.

  IF SY-SUBRC NE 0.
     RAISE NOT_FOUND.
  ENDIF.
* insurance Response Table
  SELECT SINGLE * INTO   W_ZTINSBRSP FROM ZTINSBRSP
                  WHERE  ZFBLNO    EQ   ZFBLNO
                  AND    ZFINSEQ   EQ   ZFINSEQ.
* insurance Seg. 3 Table
  SELECT SINGLE * INTO   W_ZTINSBSG3 FROM ZTINSBSG3
                  WHERE  ZFBLNO    EQ   ZFBLNO
                  AND    ZFINSEQ   EQ   ZFINSEQ.
* insurance Seg. AGR Table
  SELECT *  INTO   CORRESPONDING FIELDS OF TABLE IT_ZSINSBAGR
            FROM   ZTINSBAGR
            WHERE  ZFBLNO    EQ   ZFBLNO
            AND    ZFINSEQ   EQ   ZFINSEQ
            ORDER BY  ZFLAGR.

  IT_ZSINSBAGR_ORG[] = IT_ZSINSBAGR[].

* insurance Seg. 2 Table
  SELECT *  INTO   CORRESPONDING FIELDS OF TABLE IT_ZSINSBSG2
            FROM   ZTINSBSG2
            WHERE  ZFBLNO    EQ   ZFBLNO
            AND    ZFINSEQ   EQ   ZFINSEQ
            ORDER BY  ZFLSG2.

  IT_ZSINSBSG2_ORG[] = IT_ZSINSBSG2[].

* insurance Seg. 5 Table
  SELECT *  INTO   CORRESPONDING FIELDS OF TABLE IT_ZSINSBSG5
            FROM   ZTINSBSG5
            WHERE  ZFBLNO    EQ   ZFBLNO
            AND    ZFINSEQ   EQ   ZFINSEQ
            ORDER BY  ZFLSG5.

  IT_ZSINSBSG5_ORG[] = IT_ZSINSBSG5[].

ENDFUNCTION.
