FUNCTION ZIM_GET_OFFER_SHEET_DOC.
*"----------------------------------------------------------------------
*"*"Local interface:
*"  IMPORTING
*"     VALUE(ZFREQNO) LIKE  ZTOFF-ZFREQNO
*"  EXPORTING
*"     VALUE(W_ZTOFF) LIKE  ZTOFF STRUCTURE  ZTOFF
*"     VALUE(W_ZTOFFFTX) LIKE  ZTOFFFTX STRUCTURE  ZTOFFFTX
*"  TABLES
*"      IT_ZSOFFO STRUCTURE  ZSOFFO
*"      IT_ZSOFFSDE STRUCTURE  ZSOFFSDE
*"      IT_ZSOFFSG6 STRUCTURE  ZSOFFSG6
*"      IT_ZSOFFSG6G STRUCTURE  ZSOFFSG6G
*"      IT_ZSOFFO_ORG STRUCTURE  ZSOFFO
*"      IT_ZSOFFSDE_ORG STRUCTURE  ZSOFFSDE
*"      IT_ZSOFFSG6_ORG STRUCTURE  ZSOFFSG6
*"      IT_ZSOFFSG6G_ORG STRUCTURE  ZSOFFSG6G
*"  EXCEPTIONS
*"      NOT_FOUND
*"      NOT_INPUT
*"----------------------------------------------------------------------
  REFRESH : IT_ZSOFFO, IT_ZSOFFSDE, IT_ZSOFFSG6, IT_ZSOFFSG6G.
  REFRESH : IT_ZSOFFO_ORG, IT_ZSOFFSDE_ORG, IT_ZSOFFSG6_ORG,
            IT_ZSOFFSG6G_ORG.
  CLEAR : W_ZTOFF, W_ZTOFFFTX.

  IF ZFREQNO IS INITIAL.
     RAISE NOT_INPUT.
  ENDIF.
* OFFER SHEET HEADER
  SELECT SINGLE * INTO   W_ZTOFF   FROM ZTOFF
                  WHERE  ZFREQNO   EQ   ZFREQNO.

  IF SY-SUBRC NE 0.
     RAISE NOT_FOUND.
  ENDIF.
* TEXT
  SELECT SINGLE * INTO   W_ZTOFFFTX   FROM ZTOFFFTX
                  WHERE  ZFREQNO   EQ   ZFREQNO.
* Offer 원산지
  SELECT *  INTO CORRESPONDING FIELDS OF TABLE IT_ZSOFFO
            FROM ZTOFFO
            WHERE  ZFREQNO      EQ   ZFREQNO
            ORDER BY  ZFLO.

  LOOP AT IT_ZSOFFO.
     W_TABIX = SY-TABIX.
     SELECT SINGLE * FROM T005T WHERE SPRAS EQ SY-LANGU
                                AND   LAND1 EQ IT_ZSOFFO-ZFORIG.
*     TRANSLATE   T005T  TO UPPER CASE.
     IT_ZSOFFO-ZFORNM = T005T-LANDX.

     W_TEXT70 = IT_ZSOFFO-ZFORNM.
     TRANSLATE  W_TEXT70   TO UPPER CASE.
     IT_ZSOFFO-ZFORNM = W_TEXT70.

     MODIFY IT_ZSOFFO INDEX W_TABIX.
     MOVE-CORRESPONDING   IT_ZSOFFO     TO   IT_ZSOFFO_ORG.
     APPEND IT_ZSOFFO_ORG.
  ENDLOOP.
* Offer 기타참조사항
  SELECT *  INTO CORRESPONDING FIELDS OF TABLE IT_ZSOFFSDE
            FROM ZTOFFSDE
            WHERE  ZFREQNO      EQ   ZFREQNO
            ORDER BY  ZFFLSDE.

  LOOP AT IT_ZSOFFSDE.
     MOVE-CORRESPONDING   IT_ZSOFFSDE   TO   IT_ZSOFFSDE_ORG.
     APPEND IT_ZSOFFSDE_ORG.
  ENDLOOP.
* Offer Sg 6
  SELECT *  INTO CORRESPONDING FIELDS OF TABLE IT_ZSOFFSG6
            FROM ZTOFFSG6
            WHERE  ZFREQNO      EQ   ZFREQNO
            ORDER BY  ZFLSG6.

  LOOP AT IT_ZSOFFSG6.
     MOVE-CORRESPONDING   IT_ZSOFFSG6   TO   IT_ZSOFFSG6_ORG.
     APPEND IT_ZSOFFSG6_ORG.
  ENDLOOP.
* Offer Sg 6 GOD
  SELECT *  INTO CORRESPONDING FIELDS OF TABLE IT_ZSOFFSG6G
            FROM ZTOFFSG6G
            WHERE  ZFREQNO      EQ   ZFREQNO
            ORDER BY  ZFLSG6 ZFLSG6G.

  LOOP AT IT_ZSOFFSG6G.
     MOVE-CORRESPONDING   IT_ZSOFFSG6G     TO   IT_ZSOFFSG6G_ORG.
     APPEND IT_ZSOFFSG6G_ORG.
  ENDLOOP.

ENDFUNCTION.
