FUNCTION ZIM_GET_CARGO_WORK_DOCUMENT.
*"----------------------------------------------------------------------
*"*"Local interface:
*"  IMPORTING
*"     VALUE(ZFCGNO) LIKE  ZTCGHD-ZFCGNO
*"  EXPORTING
*"     VALUE(W_ZTCGHD) LIKE  ZTCGHD STRUCTURE  ZTCGHD
*"  TABLES
*"      IT_ZSCGCST STRUCTURE  ZSCGCST
*"      IT_ZSCGCST_ORG STRUCTURE  ZSCGCST OPTIONAL
*"      IT_ZSCGIT STRUCTURE  ZSCGIT
*"      IT_ZSCGIT_ORG STRUCTURE  ZSCGIT OPTIONAL
*"  EXCEPTIONS
*"      NOT_FOUND
*"      NOT_INPUT
*"----------------------------------------------------------------------
REFRESH : IT_ZSCGCST, IT_ZSCGIT, IT_ZSCGCST_ORG, IT_ZSCGIT_ORG.

  CLEAR : W_ZTCGHD.

  IF ZFCGNO IS INITIAL.   RAISE NOT_INPUT.   ENDIF.

  SELECT SINGLE * INTO W_ZTCGHD
                  FROM ZTCGHD
                  WHERE ZFCGNO EQ ZFCGNO.
  IF SY-SUBRC NE 0.    RAISE NOT_FOUND.   ENDIF.

* 하역비용...
  REFRESH : IT_ZSCGCST.
  SELECT * INTO CORRESPONDING FIELDS OF TABLE IT_ZSCGCST
                FROM ZTCGCST
                WHERE ZFCGNO EQ ZFCGNO.

  LOOP AT IT_ZSCGCST.
     W_TABIX = SY-TABIX.
     SELECT SINGLE ZFCDNM INTO IT_ZSCGCST-ZFCDNM FROM ZTIMIMG08
                          WHERE ZFCDTY EQ '007'
                          AND   ZFCD   EQ IT_ZSCGCST-ZFCSCD.
     MODIFY IT_ZSCGCST INDEX W_TABIX.
  ENDLOOP.
  IT_ZSCGCST_ORG[] = IT_ZSCGCST[].

* 하역 자재내역.
  SELECT * INTO CORRESPONDING FIELDS OF TABLE IT_ZSCGIT
                              FROM ZTCGIT
                              WHERE ZFCGNO EQ ZFCGNO.
  SORT IT_ZSCGIT BY ZFCGIT.

  LOOP AT IT_ZSCGIT.
     W_TABIX =  SY-TABIX.
*++++> P/O DATA 조회.
     SELECT SINGLE MENGE UEBTO UEBTK WEPOS ELIKZ LOEKZ UNTTO
                   BPUMN BPUMZ
            INTO (IT_ZSCGIT-MENGE_PO, IT_ZSCGIT-UEBTO,
                  IT_ZSCGIT-UEBTK,    IT_ZSCGIT-WEPOS,
                  IT_ZSCGIT-ELIKZ,    IT_ZSCGIT-LOEKZ,
                  IT_ZSCGIT-UNTTO,
                  IT_ZSCGIT-BPUMN,    IT_ZSCGIT-BPUMZ)
            FROM   EKPO
            WHERE  EBELN   EQ   IT_ZSCGIT-EBELN
            AND    EBELP   EQ   IT_ZSCGIT-EBELP.

*+++++> 수입의뢰 수량.
     SELECT SINGLE MENGE KBETR KWERT KPEIN KMEIN
            INTO (IT_ZSCGIT-MENGE, IT_ZSCGIT-KBETR,
                  IT_ZSCGIT-KWERT, IT_ZSCGIT-KPEIN,
                  IT_ZSCGIT-KMEIN)
            FROM  ZTREQIT
            WHERE ZFREQNO EQ IT_ZSCGIT-ZFREQNO
            AND   ZFITMNO EQ IT_ZSCGIT-ZFITMNO.

*>>>>> B/L TOTAL 수량(수입의뢰별).
     SELECT SUM( BLMENGE ) INTO IT_ZSCGIT-MENGE_BL
            FROM  ZTBLIT
            WHERE ZFBLNO  EQ IT_ZSCGIT-ZFBLNO
            AND   ZFBLIT  EQ IT_ZSCGIT-ZFBLIT
            AND   BLOEKZ  NE 'X'.
*>> B/L 관련 PLANT, LGORT, MATKL.
     SELECT SINGLE WERKS LGORT MATKL
            INTO  (IT_ZSCGIT-WERKS, IT_ZSCGIT-LGORT,
                   IT_ZSCGIT-MATKL)
            FROM  ZTBLIT
            WHERE ZFBLNO   EQ IT_ZSCGIT-ZFBLNO
            AND   ZFBLIT   EQ IT_ZSCGIT-ZFBLIT.


*>>>>> 하역 TOTAL 수량(B/L 별).
     SELECT SUM( CGMENGE ) INTO IT_ZSCGIT-ZFCGTOT
            FROM  ZTCGIT
            WHERE ZFBLNO   EQ IT_ZSCGIT-ZFBLNO
            AND   ZFBLIT   EQ IT_ZSCGIT-ZFBLIT
            AND   CGLOEKZ  NE 'X'.

*>>>>> 하역 TOTAL 수량(B/L 아이템별, 하역 헤더별).
     SELECT SUM( CGMENGE ) INTO IT_ZSCGIT-CGITTOT
            FROM  ZTCGIT
            WHERE ZFCGNO   EQ IT_ZSCGIT-ZFCGNO
            AND   ZFBLNO   EQ IT_ZSCGIT-ZFBLNO
            AND   ZFBLIT   EQ IT_ZSCGIT-ZFBLIT
            AND   CGLOEKZ  NE 'X'.

*>> 통관요청 수량.
     SELECT SUM( CCMENGE ) SUM( GRMENGE )
            INTO (IT_ZSCGIT-CCMENGE, IT_ZSCGIT-GRMENGE)
            FROM ZTIVIT
            WHERE ZFCGNO   EQ IT_ZSCGIT-ZFCGNO
            AND   ZFCGIT   EQ IT_ZSCGIT-ZFCGIT.

*>> 선사 B/L No.
     IF NOT IT_ZSCGIT-ZFBLNO IS INITIAL.
        SELECT SINGLE ZFCGHNO INTO IT_ZSCGIT-ZFCGHNO
               FROM ZTBL
               WHERE ZFBLNO  EQ  IT_ZSCGIT-ZFBLNO.
     ENDIF.

*>>   수입승인번호.
     SELECT SINGLE ZFOPNNO INTO IT_ZSCGIT-ZFOPNNO
            FROM   ZTREQHD
            WHERE  ZFREQNO EQ IT_ZSCGIT-ZFREQNO.

*>>>  보세구역 코드...
     SELECT ZFBNARM  INTO IT_ZSCGIT-ZFBNARM UP TO 1 ROWS
                     FROM  ZTIMIMG03
                     WHERE ZFBNARCD EQ IT_ZSCGIT-ZFBNARCD.
     ENDSELECT.

     MODIFY  IT_ZSCGIT   INDEX  W_TABIX.

  ENDLOOP.

  IT_ZSCGIT_ORG[] = IT_ZSCGIT[].

ENDFUNCTION.
