FUNCTION ZIM_GET_COMPANY_DATA.
*"----------------------------------------------------------------------
*"*"Local interface:
*"  IMPORTING
*"     VALUE(BUKRS) LIKE  ZTREQHD-BUKRS
*"     VALUE(IMTRD) LIKE  ZTREQHD-IMTRD DEFAULT 'S'
*"  EXPORTING
*"     VALUE(XT001) TYPE  T001
*"     VALUE(XZTIMIMG00) TYPE  ZTIMIMG00
*"     VALUE(XZTIMIMGTX) TYPE  ZTIMIMGTX
*"     VALUE(XZTIMIMG11) TYPE  ZTIMIMG11
*"     VALUE(OZTIMIMGTX) TYPE  ZTIMIMGTX
*"  EXCEPTIONS
*"      NOT_FOUND
*"----------------------------------------------------------------------
DATA : W_BUKRS   LIKE  T001-BUKRS.

   CLEAR : XT001, XZTIMIMG00, XZTIMIMGTX, XZTIMIMG11, OZTIMIMGTX.

   IF BUKRS IS INITIAL.
      MESSAGE E167 WITH '회사코드'
              RAISING NOT_FOUND.
   ELSE.
      SELECT SINGLE * INTO XT001 FROM T001
                      WHERE BUKRS EQ BUKRS.
      IF SY-SUBRC NE 0.
         MESSAGE E594 WITH BUKRS
              RAISING NOT_FOUND.
      ENDIF.
   ENDIF.

*> BASIC CONFIG.
   SELECT SINGLE * INTO XZTIMIMG00 FROM ZTIMIMG00.
   IF SY-SUBRC NE 0.
      MESSAGE E963 RAISING NOT_FOUND.
   ENDIF.
*> 자사 TEXT.
   SELECT SINGLE * INTO  OZTIMIMGTX FROM ZTIMIMGTX
                   WHERE BUKRS EQ BUKRS.
   IF SY-SUBRC NE 0.
      MESSAGE E949 WITH BUKRS
              RAISING NOT_FOUND.
   ENDIF.

   IF IMTRD EQ 'F'.
      W_BUKRS = OZTIMIMGTX-ZFCORP.
      SELECT SINGLE * INTO  XT001  FROM T001
                      WHERE BUKRS   EQ   W_BUKRS.
      IF SY-SUBRC NE 0.
         MESSAGE E594 WITH W_BUKRS
                 RAISING NOT_FOUND.
      ENDIF.
      SELECT SINGLE * INTO  XZTIMIMGTX FROM ZTIMIMGTX
                      WHERE BUKRS   EQ   W_BUKRS.
      IF SY-SUBRC NE 0.
         MESSAGE E949 WITH W_BUKRS
                 RAISING NOT_FOUND.
      ENDIF.
   ELSE.
      MOVE-CORRESPONDING  OZTIMIMGTX   TO    XZTIMIMGTX.
   ENDIF.

   SELECT SINGLE * INTO  XZTIMIMG11 FROM ZTIMIMG11
                   WHERE BUKRS  EQ  BUKRS.
   IF SY-SUBRC NE 0.
      MESSAGE E987 WITH BUKRS
              RAISING NOT_FOUND.
   ENDIF.

ENDFUNCTION.
