FUNCTION ZIM_GET_MASTER_LC_DATA.
*"----------------------------------------------------------------------
*"*"Local interface:
*"  IMPORTING
*"     VALUE(ZFREQNO) LIKE  ZTREQHD-ZFREQNO
*"  EXPORTING
*"     VALUE(W_ZTMLCHD) LIKE  ZTMLCHD STRUCTURE  ZTMLCHD
*"     VALUE(W_ZTMLCSG2) LIKE  ZTMLCSG2 STRUCTURE  ZTMLCSG2
*"     VALUE(W_ZTMLCSG910) LIKE  ZTMLCSG910 STRUCTURE  ZTMLCSG910
*"  TABLES
*"      IT_ZSMLCSG7G STRUCTURE  ZSMLCSG7G
*"      IT_ZSMLCSG7O STRUCTURE  ZSMLCSG7O
*"      IT_ZSMLCSG8E STRUCTURE  ZSMLCSG8E
*"      IT_ZSMLCSG9O STRUCTURE  ZSMLCSG9O
*"      IT_ZSMLCSG7G_ORG STRUCTURE  ZSMLCSG7G
*"      IT_ZSMLCSG7O_ORG STRUCTURE  ZSMLCSG7O
*"      IT_ZSMLCSG8E_ORG STRUCTURE  ZSMLCSG8E
*"      IT_ZSMLCSG9O_ORG STRUCTURE  ZSMLCSG9O
*"  EXCEPTIONS
*"      NOT_FOUND
*"      NOT_INPUT
*"----------------------------------------------------------------------
  REFRESH : IT_ZSMLCSG7G, IT_ZSMLCSG7O, IT_ZSMLCSG8E,
            IT_ZSMLCSG9O.
  REFRESH : IT_ZSMLCSG7G_ORG, IT_ZSMLCSG7O_ORG, IT_ZSMLCSG8E_ORG,
            IT_ZSMLCSG9O_ORG.

  CLEAR : W_ZTMLCHD, W_ZTMLCSG2, W_ZTMLCSG910.

  IF ZFREQNO IS INITIAL.
     RAISE NOT_INPUT.
  ENDIF.

  SELECT SINGLE * INTO   W_ZTMLCHD FROM ZTMLCHD
                  WHERE  ZFREQNO   EQ   ZFREQNO.

  IF SY-SUBRC NE 0.
     RAISE NOT_FOUND.
  ENDIF.

  SELECT SINGLE * INTO   W_ZTMLCSG2 FROM ZTMLCSG2
                  WHERE  ZFREQNO    EQ   ZFREQNO.

  SELECT SINGLE * INTO   W_ZTMLCSG910 FROM ZTMLCSG910
                  WHERE  ZFREQNO      EQ   ZFREQNO.

  SELECT *  INTO CORRESPONDING FIELDS OF TABLE IT_ZSMLCSG7G
            FROM ZTMLCSG7G
            WHERE  ZFREQNO      EQ   ZFREQNO
            ORDER BY  ZFLSG7G.

  SELECT * INTO CORRESPONDING FIELDS OF TABLE IT_ZSMLCSG7O
           FROM ZTMLCSG7O
           WHERE  ZFREQNO      EQ   ZFREQNO
           ORDER BY  ZFLSG7O.

  LOOP AT IT_ZSMLCSG7O.
     W_TABIX = SY-TABIX.
     SELECT SINGLE LANDX INTO   IT_ZSMLCSG7O-ZFORNM FROM T005T
                                 WHERE SPRAS  EQ SY-LANGU
                                 AND   LAND1  EQ IT_ZSMLCSG7O-ZFORIG.

     MODIFY IT_ZSMLCSG7O INDEX W_TABIX.
     MOVE-CORRESPONDING   IT_ZSMLCSG7O  TO  IT_ZSMLCSG7O_ORG.
     APPEND IT_ZSMLCSG7O_ORG.
  ENDLOOP.

  SELECT * INTO CORRESPONDING FIELDS OF TABLE IT_ZSMLCSG8E
           FROM ZTMLCSG8E
           WHERE  ZFREQNO      EQ   ZFREQNO
           ORDER BY  ZFLSG8E.

  LOOP AT IT_ZSMLCSG8E.
     MOVE-CORRESPONDING   IT_ZSMLCSG8E  TO  IT_ZSMLCSG8E_ORG.
     APPEND IT_ZSMLCSG8E_ORG.
  ENDLOOP.

  SELECT * INTO CORRESPONDING FIELDS OF TABLE IT_ZSMLCSG9O
           FROM ZTMLCSG9O
           WHERE  ZFREQNO      EQ   ZFREQNO
           ORDER BY  ZFLSG9O.

  LOOP AT IT_ZSMLCSG9O.
     MOVE-CORRESPONDING   IT_ZSMLCSG9O  TO  IT_ZSMLCSG9O_ORG.
     APPEND IT_ZSMLCSG9O_ORG.
  ENDLOOP.

ENDFUNCTION.
