FUNCTION ZIM_LOCAMR_EDI_SEND.
*"----------------------------------------------------------------------
*"*"Local interface:
*"       IMPORTING
*"             VALUE(W_ZFREQNO) LIKE  ZTREQHD-ZFREQNO
*"             VALUE(W_ZFAMDNO) LIKE  ZTREQST-ZFAMDNO
*"             VALUE(W_ZFDHENO) LIKE  ZTDHF1-ZFDHENO
*"       EXCEPTIONS
*"              DB_ERROR
*"----------------------------------------------------------------------

   CALL FUNCTION 'ZIM_GET_LOCAL_LC_DATA'
        EXPORTING
              ZFREQNO        =       W_ZFREQNO
        IMPORTING
              W_ZTLLCHD      =       ZTLLCHD
              W_ZTLLCSG23    =       ZTLLCSG23
        TABLES
              IT_ZSLLCOF     =       IT_ZSLLCOF
              IT_ZSLLCOF_ORG =       IT_ZSLLCOF_ORG
        EXCEPTIONS
              NOT_FOUND      =       4
              NOT_INPUT      =       8.

     CASE SY-SUBRC.
        WHEN 4.
           MESSAGE E018 WITH W_ZFREQNO.
        WHEN 8.
           MESSAGE E019.
     ENDCASE.

* AMEND DOCUMENT SELECT
   CALL FUNCTION 'ZIM_GET_LOCAL_LC_AMEND_DATA'
        EXPORTING
              ZFREQNO            =       W_ZFREQNO
              ZFAMDNO            =       W_ZFAMDNO
        IMPORTING
              W_ZTLLCAMHD        =       ZTLLCAMHD
        TABLES
              IT_ZSLLCAMSGOF     =       IT_ZSLLCAMSGOF
              IT_ZSLLCAMSGOF_ORG =       IT_ZSLLCAMSGOF_ORG
        EXCEPTIONS
              NOT_FOUND      =       4
              NOT_INPUT      =       8.

     CASE SY-SUBRC.
        WHEN 4.
           MESSAGE E194 WITH W_ZFREQNO W_ZFAMDNO.
        WHEN 8.
           MESSAGE E195.
     ENDCASE.

*-----------------------------------------------------------------------
* internal Table Append
*-----------------------------------------------------------------------
   REFRESH : IT_ZTDDF1.
   CLEAR : IT_ZTDDF1.
   IT_ZTDDF1-ZFDDENO = W_ZFDHENO.
*>>> 전자문서 시작
   IT_ZTDDF1-ZFDDFDA = '{10'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '2AE'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = W_ZFDHENO.        APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '9'.              APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = 'AB'.             APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}10'.            APPEND IT_ZTDDF1.
*>>> 내국신용장 번호
   IT_ZTDDF1-ZFDDFDA = '{11'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = 'LC'.             APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTREQST-ZFOPNNO.  APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}11'.            APPEND IT_ZTDDF1.
*>>> 물품매도확약서 번호
   LOOP AT IT_ZSLLCOF.
     IT_ZTDDF1-ZFDDFDA = '{11'.                APPEND IT_ZTDDF1.
     IT_ZTDDF1-ZFDDFDA = 'AAG'.                APPEND IT_ZTDDF1.
     IT_ZTDDF1-ZFDDFDA = IT_ZSLLCOF-ZFOFFER.   APPEND IT_ZTDDF1.
     IT_ZTDDF1-ZFDDFDA = '}11'.                APPEND IT_ZTDDF1.
   ENDLOOP.

*>>> 조건변경신청일자
   IT_ZTDDF1-ZFDDFDA = '{12'.              APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '2AA'.              APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTREQST-ZFAPPDT+2.  APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '101'.              APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}12'.              APPEND IT_ZTDDF1.
*>>> 개설일자
   SELECT SINGLE ZFOPNDT INTO W_ZFOPNDT FROM ZTREQST
                        WHERE ZFREQNO  EQ W_ZFREQNO
                        AND   ZFAMDNO  EQ '00000'.
   IT_ZTDDF1-ZFDDFDA = '{12'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '182'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = W_ZFOPNDT+2.      APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '101'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}12'.            APPEND IT_ZTDDF1.
*>>> 기타 정보
   IF NOT ZTLLCHD-ZFETC1 IS INITIAL OR
      NOT ZTLLCHD-ZFETC2 IS INITIAL OR
      NOT ZTLLCHD-ZFETC3 IS INITIAL OR
      NOT ZTLLCHD-ZFETC4 IS INITIAL OR
      NOT ZTLLCHD-ZFETC5 IS INITIAL.
      IT_ZTDDF1-ZFDDFDA = '{13'.            APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = 'ACB'.            APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTLLCHD-ZFGDSC1.  APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTLLCHD-ZFGDSC2.  APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTLLCHD-ZFGDSC3.  APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTLLCHD-ZFGDSC4.  APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTLLCHD-ZFGDSC5.  APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '}13'.            APPEND IT_ZTDDF1.
   ENDIF.
*>>> 개설은행
   IT_ZTDDF1-ZFDDFDA = '{14'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = 'AZ'.             APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTLLCHD-ZFOPBNCD. APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '25'.             APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = 'BOK'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTLLCHD-ZFOBNM.   APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTLLCHD-ZFOBBR.   APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}14'.            APPEND IT_ZTDDF1.
*>>> 개설의뢰인
   IT_ZTDDF1-ZFDDFDA = '{15'.              APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = 'DF'.               APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTLLCSG23-ZFAPPNM1. APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTLLCSG23-ZFAPPNM2. APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTLLCSG23-ZFAPPNM3. APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}15'.              APPEND IT_ZTDDF1.
*>>> 수혜자
   IT_ZTDDF1-ZFDDFDA = '{15'.              APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = 'DG'.               APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTLLCSG23-ZFBENI1.  APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTLLCSG23-ZFBENI2.  APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTLLCSG23-ZFBENI3.  APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}15'.              APPEND IT_ZTDDF1.
*>>> 전자서명
   IT_ZTDDF1-ZFDDFDA = '{15'.              APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = 'AX'.               APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTLLCSG23-ZFELENM.  APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTLLCSG23-ZFREPRE.  APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTLLCSG23-ZFELEID.  APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}15'.              APPEND IT_ZTDDF1.
*>>> 조건변경횟수
   WRITE : ZTREQST-ZFAMDNO   TO   W_TEXT02.
   PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT02.
   IT_ZTDDF1-ZFDDFDA = '{16'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '2AB'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = W_TEXT02.         APPEND IT_ZTDDF1.
*>>> 물품인도기일
   IF ZTLLCAMHD-ZFNGDDT IS INITIAL.
      IT_ZTDDF1-ZFDDFDA = '{20'.                APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '2'.                  APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTLLCAMHD-ZFNGDDT+2.  APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '101'.                APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '}20'.                APPEND IT_ZTDDF1.
   ENDIF.
*>>> 유효기일
   IF ZTLLCAMHD-ZFNEXDT IS INITIAL.
      IT_ZTDDF1-ZFDDFDA = '{20'.                APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '123'.                APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTLLCAMHD-ZFNEXDT+2.  APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '101'.                APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '}20'.                APPEND IT_ZTDDF1.
   ENDIF.
*>>> 기타 정보
   IF NOT ZTLLCAMHD-ZFECON1 IS INITIAL OR
      NOT ZTLLCAMHD-ZFECON2 IS INITIAL OR
      NOT ZTLLCAMHD-ZFECON3 IS INITIAL OR
      NOT ZTLLCAMHD-ZFECON4 IS INITIAL OR
      NOT ZTLLCAMHD-ZFECON5 IS INITIAL.
      IT_ZTDDF1-ZFDDFDA = '{21'.              APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = 'CHG'.              APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTLLCAMHD-ZFECON1.  APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTLLCAMHD-ZFECON2.  APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTLLCAMHD-ZFECON3.  APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTLLCAMHD-ZFECON4.  APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTLLCAMHD-ZFECON5.  APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '}21'.              APPEND IT_ZTDDF1.
   ENDIF.
   IT_ZTDDF1-ZFDDFDA = '}16'.            APPEND IT_ZTDDF1.

* 내국신용장 종류
   IT_ZTDDF1-ZFDDFDA = '{17'.              APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTLLCAMHD-ZFNLLCTY. APPEND IT_ZTDDF1.
*>>>>>>>>>>> 개설금액
      IF NOT ZTLLCAMHD-ZFNOAMT IS INITIAL.
         WRITE   ZTLLCAMHD-ZFNOAMT  TO      W_TEXT_AMOUNT
                               CURRENCY     ZTLLCAMHD-WAERS.
         PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.
         IT_ZTDDF1-ZFDDFDA = '{22'.              APPEND IT_ZTDDF1.
         IF ZTLLCAMHD-WAERS EQ 'KRW'.
            IT_ZTDDF1-ZFDDFDA = '2AD'.           APPEND IT_ZTDDF1.
         ELSE.
            IT_ZTDDF1-ZFDDFDA = '2AE'.           APPEND IT_ZTDDF1.
         ENDIF.
         IT_ZTDDF1-ZFDDFDA = W_TEXT_AMOUNT.      APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = ZTLLCAMHD-WAERS.    APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '}22'.              APPEND IT_ZTDDF1.
      ENDIF.
   IT_ZTDDF1-ZFDDFDA = '}17'.              APPEND IT_ZTDDF1.
*
   CALL FUNCTION 'ZIM_EDI_FLAT_ITEM_INSERT'
        EXPORTING
              W_ZFDHENO         =        W_ZFDHENO
        TABLES
              IT_ZTDDF1         =        IT_ZTDDF1
        EXCEPTIONS
              DB_ERROR         =         4.

   IF SY-SUBRC NE 0.
      MESSAGE E118 WITH W_ZFDHENO.
   ENDIF.

ENDFUNCTION.
