FUNCTION ZIM_GET_MASTER_LC_AMEND_DATA.
*"----------------------------------------------------------------------
*"*"Local interface:
*"  IMPORTING
*"     VALUE(ZFREQNO) LIKE  ZTREQHD-ZFREQNO
*"     VALUE(ZFAMDNO) LIKE  ZTREQST-ZFAMDNO
*"  EXPORTING
*"     VALUE(W_ZTMLCAMHD) LIKE  ZTMLCAMHD STRUCTURE  ZTMLCAMHD
*"  TABLES
*"      IT_ZSMLCAMNARR STRUCTURE  ZSMLCAMNARR
*"      IT_ZSMLCAMNARR_ORG STRUCTURE  ZSMLCAMNARR
*"  EXCEPTIONS
*"      NOT_FOUND
*"      NOT_INPUT
*"----------------------------------------------------------------------
  REFRESH : IT_ZSMLCAMNARR, IT_ZSMLCAMNARR_ORG.

  CLEAR : W_ZTMLCAMHD.

  IF ZFREQNO IS INITIAL OR ZFAMDNO IS INITIAL.
     RAISE NOT_INPUT.
  ENDIF.

  SELECT SINGLE * INTO   W_ZTMLCAMHD FROM ZTMLCAMHD
                  WHERE  ZFREQNO     EQ   ZFREQNO
                  AND    ZFAMDNO     EQ   ZFAMDNO.

  IF SY-SUBRC NE 0.
     RAISE NOT_FOUND.
  ENDIF.

  SELECT * INTO CORRESPONDING FIELDS OF TABLE IT_ZSMLCAMNARR
           FROM ZTMLCAMNARR
           WHERE  ZFREQNO      EQ   ZFREQNO
           AND    ZFAMDNO      EQ   ZFAMDNO
           ORDER BY  ZFLNARR.

  SELECT * INTO CORRESPONDING FIELDS OF TABLE IT_ZSMLCAMNARR_ORG
           FROM ZTMLCAMNARR
           WHERE  ZFREQNO      EQ   ZFREQNO
           AND    ZFAMDNO      EQ   ZFAMDNO
           ORDER BY  ZFLNARR.

ENDFUNCTION.
