FUNCTION ZIM_MAT_PAYORD_EDI_DOC.
*"----------------------------------------------------------------------
*"*"Local interface:
*"  IMPORTING
*"     REFERENCE(W_ZFCIVRN) LIKE  ZTCIVHD-ZFCIVRN
*"     REFERENCE(W_ZFDHENO) LIKE  ZTDHF1-ZFDHENO
*"     REFERENCE(W_BAHNS) LIKE  LFA1-BAHNS
*"  EXPORTING
*"     REFERENCE(W_EDI_RECORD)
*"  EXCEPTIONS
*"      CREATE_ERROR
*"----------------------------------------------------------------------
  DATA : L_TEXT         LIKE     DD07T-DDTEXT,
         L_TEXT280(280) TYPE     C,
         L_TEXT350(350) TYPE     C,
         L_BOOLEAN      TYPE     C,
         L_TYPE(002)    TYPE     C,
         L_TYPE_TEMP    LIKE     L_TYPE,
         L_CODE(003)    TYPE     C,
         L_ZFDSOG1      LIKE     IT_ZSMLCSG7G-ZFDSOG1,
         L_ZFDSOG2      LIKE     IT_ZSMLCSG7G-ZFDSOG1,
         L_ZFDSOG3      LIKE     IT_ZSMLCSG7G-ZFDSOG1,
         L_ZFDSOG4      LIKE     IT_ZSMLCSG7G-ZFDSOG1,
         L_ZFDSOG5      LIKE     IT_ZSMLCSG7G-ZFDSOG1.
  DATA : W_STRLEN       TYPE     I.
  DATA : CR_LF          TYPE     X     VALUE   '0A'.
  DATA : L_LINENO       TYPE     I.

*> PAYORD READ.
  CALL FUNCTION 'ZIM_GET_PAYORD_DOC_DATA'
       EXPORTING
            ZFCIVRN          = W_ZFCIVRN
       IMPORTING
            W_ZTTTHD         = ZTTTHD
       TABLES
            IT_ZSTTSG5       = IT_ZSTTSG5
            IT_ZSTTSG5_ORG   = IT_ZSTTSG5_ORG
       EXCEPTIONS
            NOT_FOUND        = 4
            NOT_INPUT        = 8.

  CASE SY-SUBRC.
    WHEN 4.
      MESSAGE E018 WITH W_ZFREQNO RAISING  CREATE_ERROR.
    WHEN 8.
      MESSAGE E019 RAISING  CREATE_ERROR.
  ENDCASE.

  SELECT SINGLE * FROM ZTCIVHD
         WHERE    ZFCIVRN  EQ   W_ZFCIVRN.

  SELECT SINGLE * FROM ZTIMIMGTX
         WHERE    BUKRS   EQ    ZTCIVHD-BUKRS.

*-----------------------------------------------------------------------
* FLAT-FILE RECORD CREATE
*-----------------------------------------------------------------------
* 001 문서명.
  CLEAR W_EDI_RECORD.

  PERFORM P3000_DOCNAME_MAKE USING    'PAYORD'
                             CHANGING W_EDI_RECORD.

* 002 인터페이스 일자.
  PERFORM P3000_DOCDATE_MAKE USING SY-DATUM
                             CHANGING W_EDI_RECORD.

* 003 데이터 처리형태.
  BUFFER_POINTER = STRLEN( W_EDI_RECORD ).
  PARA_LENG = 1.
  MOVE 'A' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ADD PARA_LENG TO BUFFER_POINTER.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 004 Member ID.
  PARA_LENG = 4.
  MOVE '0001' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ADD PARA_LENG TO BUFFER_POINTER.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 005 관리번호.
  PARA_LENG = STRLEN( W_ZFDHENO ).
  MOVE W_ZFDHENO TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ADD PARA_LENG TO BUFFER_POINTER.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 006 사용자 ID.
  PARA_LENG = STRLEN( SY-UNAME(10) ).
  MOVE SY-UNAME(10) TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ADD PARA_LENG TO BUFFER_POINTER.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 007 등록일자.
  PARA_LENG = 8.
  MOVE SY-DATUM TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ADD PARA_LENG TO BUFFER_POINTER.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 008 기능 표시.
  PARA_LENG = 1.
  MOVE '9' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ADD PARA_LENG TO BUFFER_POINTER.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 009 응답유형. --> 일단은 'NA'로 보낸다.
  PARA_LENG = 2.
  MOVE 'NA' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ADD PARA_LENG TO BUFFER_POINTER.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 010 신고일자.
  PARA_LENG = 8.
  MOVE SY-DATUM TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ADD PARA_LENG TO BUFFER_POINTER.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 011 기타 참조번호.
  IF NOT ZTTTHD-ZFETCNO IS INITIAL.
    PARA_LENG = STRLEN( ZTTTHD-ZFETCNO ).
    MOVE ZTTTHD-ZFETCNO TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 012 지급지시서 용도.
  IF NOT ZTTTHD-ZFBUSFUN IS INITIAL.
    PARA_LENG = 3.
    MOVE ZTTTHD-ZFBUSFUN TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 013 납부수수료 유형.
  IF NOT ZTTTHD-ZFCOMMTY IS INITIAL.
    PARA_LENG = STRLEN( ZTTTHD-ZFCOMMTY ).
    MOVE ZTTTHD-ZFCOMMTY TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 014 송금내역 1.
  IF NOT ZTTTHD-ZFSEND1 IS INITIAL.
    PARA_LENG = STRLEN( ZTTTHD-ZFSEND1(35) ).
    MOVE ZTTTHD-ZFSEND1 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 015 송금내역 2.
  IF NOT ZTTTHD-ZFSEND2 IS INITIAL.
    PARA_LENG = STRLEN( ZTTTHD-ZFSEND2(35) ).
    MOVE ZTTTHD-ZFSEND2 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 016 송금내역 3.
  IF NOT ZTTTHD-ZFSEND3 IS INITIAL.
    PARA_LENG = STRLEN( ZTTTHD-ZFSEND3(35) ).
    MOVE ZTTTHD-ZFSEND3 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 017 송금내역 4.
  IF NOT ZTTTHD-ZFSEND4 IS INITIAL.
    PARA_LENG = STRLEN( ZTTTHD-ZFSEND4(35) ).
    MOVE ZTTTHD-ZFSEND4 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 018 송금내역 5.
  IF NOT ZTTTHD-ZFSEND5 IS INITIAL.
    PARA_LENG = STRLEN( ZTTTHD-ZFSEND5(35) ).
    MOVE ZTTTHD-ZFSEND5 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 019 송금방법.
  IF NOT ZTTTHD-ZFSENDTY IS INITIAL.
    PARA_LENG = STRLEN( ZTTTHD-ZFSENDTY ).
    MOVE ZTTTHD-ZFSENDTY TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 020 수수료 부담자..
  IF NOT ZTTTHD-ZFCFRG IS INITIAL.
    PARA_LENG = STRLEN( ZTTTHD-ZFCFRG ).
    MOVE ZTTTHD-ZFCFRG TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 021 지급금액 & 022 지급금액 단위.
  PERFORM P3000_AMTR_MAKE USING   ZTTTHD-ZFAMT
                                  ZTTTHD-WAERS
                         CHANGING W_EDI_RECORD.

  IF ZTTTHD-ZFAMT IS INITIAL OR ZTTTHD-WAERS IS INITIAL.
    MESSAGE E977 WITH '지급금액을 확인하십시오.'.
  ENDIF.

* 023 지급의뢰인은행 계좌번호.
  IF NOT ZTTTHD-ZFOBAK IS INITIAL.
    PARA_LENG = STRLEN( ZTTTHD-ZFOBAK ).
    MOVE ZTTTHD-ZFOBAK TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 024 사용무.
  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 025 지급의뢰인 은행.
  IF NOT ZTTTHD-ZFOPBNCD IS INITIAL.
    PARA_LENG = STRLEN( ZTTTHD-ZFOPBNCD(6) ).
    MOVE ZTTTHD-ZFOPBNCD TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ELSE.
    MESSAGE E977 WITH '지급의뢰인 은행코드를 확인하십시오.'.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 026 지급의뢰인 은행명 1.
  IF NOT ZTTTHD-ZFOBNM(35) IS INITIAL.
    PARA_LENG = STRLEN( ZTTTHD-ZFOBNM(35) ).
    MOVE ZTTTHD-ZFOBNM(35) TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ELSE.
    MESSAGE E977 WITH '지급의뢰인 은행명을 확인하십시오.'.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 027 지급의뢰인 은행명 2.
  IF NOT ZTTTHD-ZFOBNM+35(35) IS INITIAL.
    PARA_LENG = STRLEN( ZTTTHD-ZFOBNM+35(35) ).
    MOVE ZTTTHD-ZFOBNM+35(35) TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 028 지급의뢰인 은행명 3.
  IF NOT ZTTTHD-ZFOBBR(35) IS INITIAL.
    PARA_LENG = STRLEN( ZTTTHD-ZFOBBR(35) ).
    MOVE ZTTTHD-ZFOBBR(35) TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 029 지급의뢰인 은행명 4.
  IF NOT ZTTTHD-ZFOBBR+35(35) IS INITIAL.
    PARA_LENG = STRLEN( ZTTTHD-ZFOBBR+35(35) ).
    MOVE ZTTTHD-ZFOBBR+35(35) TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 030 수익자은행 계좌번호.
  IF NOT ZTTTHD-ZFOBAK1 IS INITIAL.
    PARA_LENG = STRLEN( ZTTTHD-ZFOBAK1(17) ).
    MOVE ZTTTHD-ZFOBAK1(17) TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 031 수익자은행 은행코드.
  IF NOT ZTTTHD-ZFBENCD IS INITIAL.
    PARA_LENG = STRLEN( ZTTTHD-ZFBENCD(6) ).
    MOVE ZTTTHD-ZFBENCD TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 032 수익자 은행명 1.
  IF NOT ZTTTHD-ZFBENM(35) IS INITIAL.
    PARA_LENG = STRLEN( ZTTTHD-ZFBENM(35) ).
    MOVE ZTTTHD-ZFBENM(35) TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ELSE.
    MESSAGE E977 WITH '수익자 은행명을 확인하십시오.'.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 033 수익자 은행명 2.
  IF NOT ZTTTHD-ZFBENM+35(35) IS INITIAL.
    PARA_LENG = STRLEN( ZTTTHD-ZFBENM+35(35) ).
    MOVE ZTTTHD-ZFBENM+35(35) TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 034 수익자 은행명 3.
  IF NOT ZTTTHD-ZFBEBR(35) IS INITIAL.
    PARA_LENG = STRLEN( ZTTTHD-ZFBEBR(35) ).
    MOVE ZTTTHD-ZFBEBR(35) TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 035 수익자 은행명 4.
  IF NOT ZTTTHD-ZFBEBR+35(35) IS INITIAL.
    PARA_LENG = STRLEN( ZTTTHD-ZFBEBR+35(35) ).
    MOVE ZTTTHD-ZFBEBR+35(35) TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 036 중간경유은행 계좌번호.
  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.
* 037 중간경유은행 은행코드.
  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.
* 038 중간경유은행 은행명 1.
  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.
* 039 중간경유은행 은행명 2.
  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.
* 040 중간경유은행 은행명 3.
  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.
* 041 중간경유은행 은행명 4.
  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.
* 042 비밀번호.
  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.
* 043 EDI 비밀번호.
  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.
* 044 지급의뢰인 내부관리코드.
  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 045 지급의뢰인 1.
  IF NOT ZTTTHD-ZFAPPNM IS INITIAL.
    PARA_LENG = STRLEN( ZTTTHD-ZFAPPNM ).
    MOVE ZTTTHD-ZFAPPNM TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 046 지급의뢰인 2.
  IF NOT ZTTTHD-ZFAPPAD1 IS INITIAL.
    PARA_LENG = STRLEN( ZTTTHD-ZFAPPAD1 ).
    MOVE ZTTTHD-ZFAPPAD1 TO W_EDI_RECORD+BUFFER_POINTER.
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 047 지급의뢰인 3.
  IF NOT ZTTTHD-ZFAPPAD2 IS INITIAL.
    PARA_LENG = STRLEN( ZTTTHD-ZFAPPAD2 ).
    MOVE ZTTTHD-ZFAPPAD2 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 048 지급의뢰인 4(전화번호).
  IF NOT ZTTTHD-ZFTELNO IS INITIAL.
    PARA_LENG = STRLEN( ZTTTHD-ZFTELNO ).
    MOVE ZTTTHD-ZFTELNO TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 049 지급의뢰인 5.
  IF NOT ZTTTHD-ZFAPPAD3 IS INITIAL.
    PARA_LENG = STRLEN( ZTTTHD-ZFAPPAD3 ).
    MOVE ZTTTHD-ZFAPPAD3 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 050 수익자 내부관리코드.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 051 수익자 1.
  IF NOT ZTTTHD-ZFBENI1 IS INITIAL.
    PARA_LENG = STRLEN( ZTTTHD-ZFBENI1 ).
    MOVE ZTTTHD-ZFBENI1 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 052 수익자 2.
  IF NOT ZTTTHD-ZFBENI2 IS INITIAL.
    PARA_LENG = STRLEN( ZTTTHD-ZFBENI2 ).
    MOVE ZTTTHD-ZFBENI2 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 053 수익자 3.
  IF NOT ZTTTHD-ZFBENI3 IS INITIAL.
    PARA_LENG = STRLEN( ZTTTHD-ZFBENI3 ).
    MOVE ZTTTHD-ZFBENI3 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 054 수익자.
  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.
* 055 수익자.
  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 056 신청업체 내부관리번호.
  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 057 신청업체.
  IF NOT ZTTTHD-ZFELENM IS INITIAL.
    PARA_LENG = STRLEN( ZTTTHD-ZFELENM ).
    MOVE ZTTTHD-ZFELENM TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 058 신청업체.
  IF NOT ZTTTHD-ZFREPRE IS INITIAL.
    PARA_LENG = STRLEN( ZTTTHD-ZFREPRE ).
    MOVE ZTTTHD-ZFREPRE TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 059 전자서명.
  IF NOT ZTTTHD-ZFELEID IS INITIAL.
    PARA_LENG = STRLEN( ZTTTHD-ZFELEID ).
    MOVE ZTTTHD-ZFELEID TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 060 지급의뢰인 은행 → 지급의뢰인 은행 계좌번호를 말하는 것 같다.
  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 061 기타정보 입력여부.
  PERFORM P3000_ZTTTHD_ZFETC_MAKE USING L_LINENO.
  PARA_LENG = 1.

  IF NOT L_LINENO IS INITIAL.
    MOVE L_LINENO TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ELSE.
    MOVE '0' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ENDIF.
  ADD PARA_LENG TO BUFFER_POINTER.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 062 기타정보(5행 70열).
  PERFORM P3000_ZTTTHD_ZFETCD_MAKE USING L_TEXT350.

  IF NOT L_LINENO IS INITIAL.
    PARA_LENG = L_LINENO * 70.
    MOVE L_TEXT350 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 063 입금관련서류구분.
  READ TABLE IT_ZSTTSG5 INDEX 1.
  IF NOT IT_ZSTTSG5-ZFDOCCD IS INITIAL.
    PARA_LENG = STRLEN( IT_ZSTTSG5-ZFDOCCD ).
    MOVE IT_ZSTTSG5-ZFDOCCD TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 064 서류 번호.
  IF NOT IT_ZSTTSG5-ZFDOCNO IS INITIAL.
    PARA_LENG = STRLEN( IT_ZSTTSG5-ZFDOCNO ).
    MOVE IT_ZSTTSG5-ZFDOCNO TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 065 서류발행일자.
  IF NOT IT_ZSTTSG5-ZFISSDT IS INITIAL.
    PARA_LENG = STRLEN( IT_ZSTTSG5-ZFISSDT ).
    MOVE IT_ZSTTSG5-ZFISSDT TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 066 문서현황.
  PARA_LENG = 1.
  MOVE '1' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ADD PARA_LENG TO BUFFER_POINTER.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 067 송수신상태. → Not I/F.

* 068 출력횟수.
  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.
* 069 지급의뢰인 은행 계좌주 또는 계좌번호1.
  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.
* 070 지급의뢰인 은행 계좌주 또는 계좌번호2.
  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.
* 071 수익자 은행 계좌주 또는 계좌번호1.
  IF NOT ZTTTHD-ZFOBAK1 IS INITIAL.
    PARA_LENG = 35.
    MOVE ZTTTHD-ZFOBAK1 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.
* 072 수익자 은행 계좌주 또는 계좌번호2.
  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.
* 073 중간경유 은행 계좌주 또는 계좌번호1.
  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.
* 074 중간경유 은행 계좌주 또는 계좌번호2.
  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.
* 075 수발신식별자 부호.
  PARA_LENG = STRLEN( W_BAHNS ).
  MOVE W_BAHNS TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ADD PARA_LENG TO BUFFER_POINTER.

  PARA_LENG = 7.
  MOVE '@@@}}~~' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ADD PARA_LENG TO BUFFER_POINTER.

ENDFUNCTION.
