FUNCTION ZIM_GET_REQ_DOC_HEADER.
*"----------------------------------------------------------------------
*"*"Local interface:
*"  IMPORTING
*"     VALUE(ZFREQNO) LIKE  ZSREQHD-ZFREQNO
*"     VALUE(ZFAMDNO) LIKE  ZTREQST-ZFAMDNO OPTIONAL
*"  EXPORTING
*"     VALUE(W_ZTREQHD) LIKE  ZTREQHD STRUCTURE  ZTREQHD
*"     VALUE(W_ZTREQST) LIKE  ZTREQST STRUCTURE  ZTREQST
*"  TABLES
*"      IT_ZTREQORJ STRUCTURE  ZSMLCSG7O OPTIONAL
*"      IT_ZTREQORJ_ORG STRUCTURE  ZSMLCSG7O OPTIONAL
*"      IT_ZSREQIL STRUCTURE  ZSREQIL OPTIONAL
*"      IT_ZSREQIL_ORG STRUCTURE  ZSREQIL OPTIONAL
*"  EXCEPTIONS
*"      NOT_FOUND
*"      NOT_INPUT
*"----------------------------------------------------------------------
  CLEAR : W_ZTREQHD, W_ZTREQST.
  REFRESH : IT_ZTREQORJ, IT_ZTREQORJ_ORG.
  REFRESH : IT_ZSREQIL, IT_ZSREQIL_ORG.

  IF ZFREQNO IS INITIAL.
     RAISE NOT_INPUT.
  ENDIF.

  IF ZFAMDNO IS INITIAL.
     CLEAR : ZFAMDNO.
  ENDIF.

  SELECT SINGLE * INTO W_ZTREQHD FROM   ZTREQHD
                                 WHERE  ZFREQNO  EQ  ZFREQNO.
  IF SY-SUBRC NE 0.
     RAISE NOT_FOUND.
  ENDIF.

  IF ZTREQHD-ZFCLOSE EQ 'X'.
     MESSAGE E735 WITH ZFREQNO.
  ENDIF.
*>>>
  SELECT SINGLE * INTO W_ZTREQST FROM   ZTREQST
                                 WHERE  ZFREQNO  EQ  ZFREQNO
                                 AND    ZFAMDNO  EQ  ZFAMDNO.

  IF SY-SUBRC NE 0.
     RAISE NOT_FOUND.
  ENDIF.

* ORIJIN
  SELECT * INTO CORRESPONDING FIELDS OF TABLE IT_ZTREQORJ
           FROM ZTREQORJ
           WHERE  ZFREQNO      EQ   ZFREQNO
           ORDER BY  ZFLSG7O.

  LOOP AT IT_ZTREQORJ.
     W_TABIX = SY-TABIX.
     SELECT SINGLE LANDX INTO    IT_ZTREQORJ-ZFORNM FROM T005T
*                                WHERE SPRAS  EQ SY-LANGU
                                 WHERE SPRAS  EQ 'E'
                                 AND   LAND1  EQ IT_ZTREQORJ-ZFORIG.

     W_TEXT70 = IT_ZTREQORJ-ZFORNM.
     TRANSLATE W_TEXT70 TO UPPER CASE.
     IT_ZTREQORJ-ZFORNM = W_TEXT70.

     MODIFY IT_ZTREQORJ  INDEX W_TABIX.
     MOVE-CORRESPONDING   IT_ZTREQORJ   TO   IT_ZTREQORJ_ORG.
     APPEND IT_ZTREQORJ_ORG.
  ENDLOOP.

* 수입추천
  SELECT * INTO CORRESPONDING FIELDS OF TABLE IT_ZSREQIL
           FROM ZTREQIL
           WHERE  ZFREQNO      EQ   ZFREQNO
           ORDER BY  ZFILSEQ.

   IT_ZSREQIL_ORG[] = IT_ZSREQIL[].

ENDFUNCTION.
