FUNCTION ZIM_EDI_SAMFILE_WRITE.
*"----------------------------------------------------------------------
*"*"Local interface:
*"  IMPORTING
*"     REFERENCE(ZFCDDOC) LIKE  ZTCDF1-ZFCDDOC
*"     REFERENCE(BUKRS) LIKE  ZTIMIMGTX-BUKRS DEFAULT 'KHNP'
*"  EXPORTING
*"     REFERENCE(W_FILENAME) LIKE  ZTDHF1-FILENAME
*"  TABLES
*"      EDIFILE
*"----------------------------------------------------------------------
DATA : UNIXFILE(300) TYPE C.
DATA : L_SEQ         LIKE ZTREQST-ZFAMDNO VALUE  '00001'.
DATA : BEGIN OF IT_ZTDHF1 OCCURS 0.
       INCLUDE STRUCTURE  ZTDHF1.
DATA : END   OF IT_ZTDHF1.

  SELECT SINGLE * FROM  ZTIMIMGTX
                  WHERE BUKRS EQ BUKRS.
  IF SY-SUBRC EQ 0.
     IF ZTIMIMGTX-ZFPATH IS INITIAL.
        MESSAGE E978.
     ENDIF.
  ELSE.
     MESSAGE E961.
  ENDIF.

  CONCATENATE   ZTIMIMGTX-ZFPATH '/' ZFCDDOC
                SY-DATUM SY-UZEIT L_SEQ '.ITF'
                INTO   UNIXFILE.

  OPEN DATASET UNIXFILE.
  DO.
     IF SY-SUBRC EQ 0.
        CLOSE DATASET UNIXFILE.
     ELSE.
        EXIT.
     ENDIF.
     L_SEQ = L_SEQ + 1.
     CONCATENATE   ZTIMIMGTX-ZFPATH '/' ZFCDDOC
                   SY-DATUM SY-UZEIT L_SEQ '.ITF'
                   INTO   UNIXFILE.
     OPEN DATASET UNIXFILE.
  ENDDO.

  CONCATENATE  ZFCDDOC SY-DATUM SY-UZEIT L_SEQ '.ITF'  INTO  W_FILENAME.

  OPEN DATASET UNIXFILE FOR OUTPUT IN TEXT MODE.
  IF SY-SUBRC NE 0.
     MESSAGE E910 WITH UNIXFILE.
     EXIT.
  ENDIF.

  LOOP AT EDIFILE.

     PERFORM    P3000_CHAR_TO_SPACE  CHANGING  EDIFILE.

     TRANSFER   EDIFILE  TO     UNIXFILE.
     SELECT SINGLE * INTO IT_ZTDHF1 FROM ZTDHF1
                     WHERE ZFDHENO EQ EDIFILE+23(17).
     IF SY-SUBRC EQ 0.
        MOVE: UNIXFILE    TO   IT_ZTDHF1-FILENAME.
        APPEND IT_ZTDHF1.
     ENDIF.
  ENDLOOP.

  CLOSE DATASET    UNIXFILE.

  MODIFY ZTDHF1  FROM TABLE IT_ZTDHF1.

ENDFUNCTION.
