FUNCTION ZIM_EDI_SAMFILE_LOCAL_WRITE.
*"----------------------------------------------------------------------
*"*"Local interface:
*"  IMPORTING
*"     REFERENCE(ZFCDDOC) LIKE  ZTCDF1-ZFCDDOC
*"     REFERENCE(BUKRS) LIKE  ZTIMIMGTX-BUKRS DEFAULT 'KHNP'
*"  EXPORTING
*"     REFERENCE(W_FILENAME) LIKE  RLGRAP-FILENAME
*"  TABLES
*"      EDIFILE
*"----------------------------------------------------------------------
DATA : UNIXFILE LIKE RLGRAP-FILENAME.
DATA : L_SEQ         LIKE ZTREQST-ZFAMDNO VALUE  '00001'.
DATA : BEGIN OF IT_ZTDHF1 OCCURS 0.
       INCLUDE STRUCTURE  ZTDHF1.
DATA : END   OF IT_ZTDHF1.

  CONCATENATE  ZFCDDOC SY-DATUM
               SY-UZEIT L_SEQ '.ITF'  INTO  W_FILENAME.

  CONCATENATE 'C:\' W_FILENAME  INTO  UNIXFILE.

  LOOP AT EDIFILE.

     PERFORM    P3000_CHAR_TO_SPACE  CHANGING  EDIFILE.

     CALL FUNCTION 'DOWNLOAD'
          EXPORTING
               FILENAME = UNIXFILE
               FILETYPE = 'ASC'
          TABLES
               DATA_TAB = EDIFILE.

     SELECT SINGLE * INTO IT_ZTDHF1 FROM ZTDHF1
                     WHERE ZFDHENO EQ EDIFILE+23(17).
     IF SY-SUBRC EQ 0.
        MOVE: EDIFILE+23(17)    TO   IT_ZTDHF1-FILENAME.
        APPEND IT_ZTDHF1.
     ENDIF.
  ENDLOOP.

  MODIFY ZTDHF1  FROM TABLE IT_ZTDHF1.

ENDFUNCTION.
