*&---------------------------------------------------------------------*
*&  Function Module 명: APP700 EDI Send                                *
*&              작성자: 나신호 INFOLINK Ltd.                           *
*&              작성일: 2002.05.14                                     *
*&---------------------------------------------------------------------*
*&   DESC.     :
*&---------------------------------------------------------------------*
*& [변경내용]
*&---------------------------------------------------------------------*
FUNCTION ZIM_MAT_APP700_EDI_DOC .
*"----------------------------------------------------------------------
*"*"Local interface:
*"  IMPORTING
*"     VALUE(W_ZFREQNO) LIKE  ZTREQHD-ZFREQNO
*"     VALUE(W_ZFDHENO) LIKE  ZTDHF1-ZFDHENO
*"     VALUE(W_BAHNS) LIKE  LFA1-BAHNS
*"  EXPORTING
*"     REFERENCE(W_EDI_RECORD)
*"  EXCEPTIONS
*"      CREATE_ERROR
*"----------------------------------------------------------------------
  DATA : L_TEXT         LIKE     DD07T-DDTEXT,
         L_TEXT280(280) TYPE     C,
         L_TEXT350(350) TYPE     C,
         L_BOOLEAN      TYPE     C,
         L_TYPE(002)    TYPE     C,
         L_TYPE_TEMP    LIKE     L_TYPE,
         L_CODE(003)    TYPE     C,
         L_ZFDSOG1      LIKE     IT_ZSMLCSG7G-ZFDSOG1,
         L_ZFDSOG2      LIKE     IT_ZSMLCSG7G-ZFDSOG1,
         L_ZFDSOG3      LIKE     IT_ZSMLCSG7G-ZFDSOG1,
         L_ZFDSOG4      LIKE     IT_ZSMLCSG7G-ZFDSOG1,
         L_ZFDSOG5      LIKE     IT_ZSMLCSG7G-ZFDSOG1,
         L_LINENO       TYPE     I.
  DATA : W_STRLEN       TYPE     I.
  DATA : CR_LF          TYPE     X     VALUE   '0A'.

*> MASTER L/C READ.
  CALL FUNCTION 'ZIM_GET_MASTER_LC_DATA'
       EXPORTING
            ZFREQNO          = W_ZFREQNO
       IMPORTING
            W_ZTMLCHD        = ZTMLCHD
            W_ZTMLCSG2       = ZTMLCSG2
            W_ZTMLCSG910     = ZTMLCSG910
       TABLES
            IT_ZSMLCSG7G     = IT_ZSMLCSG7G
            IT_ZSMLCSG7O     = IT_ZSMLCSG7O
            IT_ZSMLCSG8E     = IT_ZSMLCSG8E
            IT_ZSMLCSG9O     = IT_ZSMLCSG9O
            IT_ZSMLCSG7G_ORG = IT_ZSMLCSG7G_ORG
            IT_ZSMLCSG7O_ORG = IT_ZSMLCSG7O_ORG
            IT_ZSMLCSG8E_ORG = IT_ZSMLCSG8E_ORG
            IT_ZSMLCSG9O_ORG = IT_ZSMLCSG9O_ORG
       EXCEPTIONS
            NOT_FOUND        = 4
            NOT_INPUT        = 8.

  CASE SY-SUBRC.
    WHEN 4.
      MESSAGE E018 WITH W_ZFREQNO RAISING  CREATE_ERROR.
    WHEN 8.
      MESSAGE E019 RAISING  CREATE_ERROR.
  ENDCASE.

  SELECT SINGLE * FROM ZTREQHD
         WHERE    ZFREQNO  EQ   W_ZFREQNO.

  SELECT SINGLE * FROM ZTREQST
         WHERE    ZFREQNO  EQ    W_ZFREQNO
         AND      ZFAMDNO  EQ    '00000'.

  SELECT SINGLE * FROM ZTIMIMGTX
         WHERE    BUKRS   EQ    ZTIMIMGTX-BUKRS.

*-----------------------------------------------------------------------
* FLAT-FILE RECORD CREATE
*-----------------------------------------------------------------------
* 001 문서명.
  CLEAR W_EDI_RECORD.

  PERFORM P3000_DOCNAME_MAKE USING    'APP700'
                             CHANGING W_EDI_RECORD.

* 002 인터페이스 일자.
*  BUFFER_POINTER = STRLEN( W_EDI_RECORD ).
*  CLEAR  REC_DOC.
  PERFORM P3000_DOCDATE_MAKE USING SY-DATUM
                             CHANGING W_EDI_RECORD.

* 003 데이터 처리형태.
  BUFFER_POINTER = STRLEN( W_EDI_RECORD ).
  PARA_LENG = 1.
  MOVE 'A' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
*  IF ZTMLCHD-ZFEDFN IS INITIAL.
*    MOVE 'I' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
*  ELSE.
*    MOVE 'U' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
*  ENDIF.
  ADD PARA_LENG TO BUFFER_POINTER.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 004 Member ID.
  PARA_LENG = 4.
  MOVE '0001' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ADD PARA_LENG TO BUFFER_POINTER.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 005 관리번호.
  PARA_LENG = STRLEN( W_ZFDHENO ).
  MOVE W_ZFDHENO TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ADD PARA_LENG TO BUFFER_POINTER.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 006 사용자 ID.
  PARA_LENG = STRLEN( SY-UNAME(10) ).
  MOVE SY-UNAME(10) TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ADD PARA_LENG TO BUFFER_POINTER.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 007 전자문서기능.
  PARA_LENG = 1.
  MOVE '9' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ADD PARA_LENG TO BUFFER_POINTER.
*  IF NOT ZTMLCHD-ZFEDFN IS INITIAL.
*    PARA_LENG = 1.
*    MOVE ZTMLCHD-ZFEDFN TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
*    ADD PARA_LENG TO BUFFER_POINTER.
*  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 008 응답유형.
  PARA_LENG = 2.
  MOVE 'AB' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ADD PARA_LENG TO BUFFER_POINTER.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 009 등록일자. --> 일단 Blank Data를 보낸다.
  PARA_LENG = 8.
  MOVE SY-DATUM TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ADD PARA_LENG TO BUFFER_POINTER.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 010 신청일자.
  IF NOT ZTREQST-ZFAPPDT IS INITIAL.
    PARA_LENG = 8.
    MOVE ZTREQST-ZFAPPDT TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 011 개설방법.
  IF NOT ZTMLCHD-ZFOPME IS INITIAL.
    PARA_LENG = 2.
    MOVE ZTMLCHD-ZFOPME TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 012 개설의뢰은행코드.
  IF NOT ZTMLCHD-ZFOPBNCD IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCHD-ZFOPBNCD(4) ).
    MOVE ZTMLCHD-ZFOPBNCD(4) TO W_EDI_RECORD+BUFFER_POINTER(4).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 013 개설은행명1.
  IF NOT ZTMLCHD-ZFOBNM IS INITIAL.
    PARA_LENG = 35.
    PARA_LENG = STRLEN( ZTMLCHD-ZFOBNM(35) ).
    MOVE ZTMLCHD-ZFOBNM(35) TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 014 개설은행명2.
  IF NOT ZTMLCHD-ZFOBNM+35(35) IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCHD-ZFOBNM+35(35) ).
    MOVE ZTMLCHD-ZFOBNM+35(35)
      TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 015 개설은행지점명1.
  IF NOT ZTMLCHD-ZFOBBR(35) IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCHD-ZFOBBR(35) ).
    MOVE ZTMLCHD-ZFOBBR(35) TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 016 개설은행지점명2.
  IF NOT ZTMLCHD-ZFOBBR+35(35) IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCHD-ZFOBBR+35(35) ).
    MOVE ZTMLCHD-ZFOBBR+35(35)
      TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 017 개설은행 전화번호.
  IF NOT ZTMLCHD-ZFOBPH IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCHD-ZFOBPH ).
    MOVE ZTMLCHD-ZFOBPH TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 018 통지은행 코드. --> 일단 Blank Data를 보낸다.
  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 019 통지은행명1.
  IF NOT ZTMLCHD-ZFABNM(35) IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCHD-ZFABNM(35) ).
    MOVE ZTMLCHD-ZFABNM(35) TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 020 통지은행명2.
  IF NOT ZTMLCHD-ZFABNM+35(35) IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCHD-ZFABNM+35(35) ).
    MOVE ZTMLCHD-ZFABNM+35(35)
      TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 021 통지은행 지점명1.
  IF NOT ZTMLCHD-ZFABBR(35) IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCHD-ZFABBR(35) ).
    MOVE ZTMLCHD-ZFABBR(35) TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 022 통지은행 지점명2.
  IF NOT ZTMLCHD-ZFABBR+35(35) IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCHD-ZFABBR+35(35) ).
    MOVE ZTMLCHD-ZFABBR+35(35)
      TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 023 신용공여.
  IF NOT ZTMLCHD-ZFPAGR IS INITIAL.
    PARA_LENG = 3.
    MOVE ZTMLCHD-ZFPAGR TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 024 기타정보1.
  IF NOT ZTMLCHD-ZFETC1 IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCHD-ZFETC1 ).
    MOVE ZTMLCHD-ZFETC1 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 025 기타정보2.
  IF NOT ZTMLCHD-ZFETC2 IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCHD-ZFETC2 ).
    MOVE ZTMLCHD-ZFETC2 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 026 기타정보3.
  IF NOT ZTMLCHD-ZFETC3 IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCHD-ZFETC3 ).
    MOVE ZTMLCHD-ZFETC3 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 027 기타정보4.
  IF NOT ZTMLCHD-ZFETC4 IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCHD-ZFETC4 ).
    MOVE ZTMLCHD-ZFETC4 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 028 기타정보5.
  IF NOT ZTMLCHD-ZFETC5 IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCHD-ZFETC5 ).
    MOVE ZTMLCHD-ZFETC5 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 029 Form of Documentary Credit.
  IF NOT ZTMLCHD-ZFLCTY IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCHD-ZFLCTY ).
    MOVE ZTMLCHD-ZFLCTY TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 030 Date and Place of Expiry:.
  IF NOT ZTMLCHD-ZFEXDT IS INITIAL.
    PARA_LENG = 8.
    MOVE ZTMLCHD-ZFEXDT TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 031 Date and Place of Expiry:장소.
  IF NOT ZTMLCHD-ZFEXPL IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCHD-ZFEXPL ).
    MOVE ZTMLCHD-ZFEXPL TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 032 문서현황.
  PARA_LENG = 1.
  MOVE '1' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ADD PARA_LENG TO BUFFER_POINTER.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 034 수발신인 식별자.. → 신규로 들어간 부분.
  PARA_LENG = STRLEN( W_BAHNS ).
  MOVE W_BAHNS TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ADD PARA_LENG TO BUFFER_POINTER.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 035 Applicant1.
  IF NOT ZTMLCSG2-ZFAPPNM IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCSG2-ZFAPPNM ).
    MOVE ZTMLCSG2-ZFAPPNM TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 036 Applicant2.
  IF NOT ZTMLCSG2-ZFAPPAD1 IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCSG2-ZFAPPAD1 ).
    MOVE ZTMLCSG2-ZFAPPAD1 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 037 Applicant3.
  IF NOT ZTMLCSG2-ZFAPPAD2 IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCSG2-ZFAPPAD2 ).
    MOVE ZTMLCSG2-ZFAPPAD2 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 038 Applicant4.
  IF NOT ZTMLCSG2-ZFAPPAD3 IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCSG2-ZFAPPAD3 ).
    MOVE ZTMLCSG2-ZFAPPAD3 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 039 TEL.
  IF NOT ZTMLCSG2-ZFTELNO IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCSG2-ZFTELNO ).
    MOVE ZTMLCSG2-ZFTELNO TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 040 Beneficiary CODE.
  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 041 Beneficiary1.
  IF NOT ZTMLCSG2-ZFBENI1 IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCSG2-ZFBENI1 ).
    MOVE ZTMLCSG2-ZFBENI1 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 042 Beneficiary2.
  IF NOT ZTMLCSG2-ZFBENI2 IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCSG2-ZFBENI2 ).
    MOVE ZTMLCSG2-ZFBENI2 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 043 Beneficiary3.
  IF NOT ZTMLCSG2-ZFBENI3 IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCSG2-ZFBENI3 ).
    MOVE ZTMLCSG2-ZFBENI3 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 044 Beneficiary4.
  IF NOT ZTMLCSG2-ZFBENI4 IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCSG2-ZFBENI4 ).
    MOVE ZTMLCSG2-ZFBENI4 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 045 계좌번호.
  IF NOT ZTMLCSG2-ZFBENIA IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCSG2-ZFBENIA ).
    MOVE ZTMLCSG2-ZFBENIA TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 046 ~ 047. 개설금액 & 통화.
  IF NOT ZTREQHD-ZFLASTAM IS INITIAL.
    PERFORM P3000_AMTR_MAKE USING ZTREQHD-ZFLASTAM
                                  ZTREQHD-WAERS
                         CHANGING W_EDI_RECORD.
  ENDIF.

* 048 Percentage Credit Amount Toler(Plus).
  IF NOT ZTMLCHD-ZFALCP IS INITIAL.
    PARA_LENG = 2.
    MOVE ZTMLCHD-ZFALCP TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ELSE.
    PARA_LENG = 1.
    MOVE '0' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 049 Percentage Credit Amount Toler(Minus).
  IF NOT ZTMLCHD-ZFALCM IS INITIAL.
    PARA_LENG = 2.
    MOVE ZTMLCHD-ZFALCM TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ELSE.
    PARA_LENG = 1.
    MOVE '0' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 050 Maximum Credit Amount. --> 일단은 Blank Data를 내보낸다.
  IF NOT ZTMLCHD-ZFALCQ IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCHD-ZFALCQ ).
    MOVE ZTMLCHD-ZFALCQ TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.
  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 051 Additional Amounts Covered1.
  IF NOT ZTMLCHD-ZFAAMT1 IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCHD-ZFAAMT1 ).
    MOVE ZTMLCHD-ZFAAMT1 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 052 Additional Amounts Covered2.
  IF NOT ZTMLCHD-ZFAAMT2 IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCHD-ZFAAMT2 ).
    MOVE ZTMLCHD-ZFAAMT2 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 053 Additional Amounts Covered3.
  IF NOT ZTMLCHD-ZFAAMT3 IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCHD-ZFAAMT3 ).
    MOVE ZTMLCHD-ZFAAMT3 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 054 Additional Amounts Covered4.
  IF NOT ZTMLCHD-ZFAAMT4 IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCHD-ZFAAMT4 ).
    MOVE ZTMLCHD-ZFAAMT4 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

*----------------------------------------------------------------------*
* 지급조건..
*----------------------------------------------------------------------*
  CASE ZTMLCHD-ZFTRMB.
    WHEN '2AO'.                        " Drafts at..
      IF NOT ZTMLCHD-ZFTRTX1 IS INITIAL.                    " 054.
        PARA_LENG = STRLEN( ZTMLCHD-ZFTRTX1 ).
        MOVE ZTMLCHD-ZFTRTX1
          TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
        ADD PARA_LENG TO BUFFER_POINTER.
      ENDIF.
      PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

      IF NOT ZTMLCHD-ZFTRTX2 IS INITIAL.                    " 055.
        PARA_LENG = STRLEN( ZTMLCHD-ZFTRTX2 ).
        MOVE ZTMLCHD-ZFTRTX2
          TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
        ADD PARA_LENG TO BUFFER_POINTER.
      ENDIF.
* [Drafts at..2] 구분자 넣기.
      PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

      IF NOT ZTMLCHD-ZFTRTX3 IS INITIAL.                    " 056.
        PARA_LENG = STRLEN( ZTMLCHD-ZFTRTX3 ).
        MOVE ZTMLCHD-ZFTRTX3
          TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
        ADD PARA_LENG TO BUFFER_POINTER.
      ENDIF.

* [Drafts at..3] 구분자 넣기.
      PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.


* 'Mixed Payment Detail..', 'Deferred Payment Details..' Space.
      PARA_LENG = 8.
      MOVE '||||||||' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
      ADD PARA_LENG TO BUFFER_POINTER.

    WHEN '2AM'.                        " Mixed Payment Detail..
* 'Drafts at..' Space.
      PARA_LENG = 3.
      MOVE '|||' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
      ADD PARA_LENG TO BUFFER_POINTER.

      IF NOT ZTMLCHD-ZFTRTX1 IS INITIAL.                    " 057.
        PARA_LENG = STRLEN( ZTMLCHD-ZFTRTX1 ).
        MOVE ZTMLCHD-ZFTRTX1
          TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
        ADD PARA_LENG TO BUFFER_POINTER.
      ENDIF.
      PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

      IF NOT ZTMLCHD-ZFTRTX2 IS INITIAL.                    " 058.
        PARA_LENG = STRLEN( ZTMLCHD-ZFTRTX2 ).
        MOVE ZTMLCHD-ZFTRTX2
          TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
        ADD PARA_LENG TO BUFFER_POINTER.
      ENDIF.
* [Mixed Payment Detail2] 구분자 넣기.
      PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

      IF NOT ZTMLCHD-ZFTRTX3 IS INITIAL.                    " 059.
        PARA_LENG = STRLEN( ZTMLCHD-ZFTRTX3 ).
        MOVE ZTMLCHD-ZFTRTX3
          TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
        ADD PARA_LENG TO BUFFER_POINTER.
      ENDIF.
* [Mixed Payment Detail3] 구분자 넣기.
      PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

      IF NOT ZTMLCHD-ZFTRTX4 IS INITIAL.                    " 060.
        PARA_LENG = STRLEN( ZTMLCHD-ZFTRTX4 ).
        MOVE ZTMLCHD-ZFTRTX4
          TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
        ADD PARA_LENG TO BUFFER_POINTER.
      ENDIF.
* [Mixed Payment Detail4] 구분자 넣기.
      PERFORM P3000_1BYTE_DELIMETER_INSERT
              CHANGING W_EDI_RECORD.
* 'Deferred Payment Details..' Space.
      PARA_LENG = 4.
      MOVE '||||' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
      ADD PARA_LENG TO BUFFER_POINTER.

    WHEN '2AN'.                        " Deferred Payment Details..
      PARA_LENG = 7.
      MOVE '|||||||' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
      ADD PARA_LENG TO BUFFER_POINTER.

      IF NOT ZTMLCHD-ZFTRTX1 IS INITIAL.                    " 061.
        PARA_LENG = STRLEN( ZTMLCHD-ZFTRTX1 ).
        MOVE ZTMLCHD-ZFTRTX1
          TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
        ADD PARA_LENG TO BUFFER_POINTER.
      ENDIF.
      PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

      IF NOT ZTMLCHD-ZFTRTX2 IS INITIAL.                    " 062.
        PARA_LENG = STRLEN( ZTMLCHD-ZFTRTX2 ).
        MOVE ZTMLCHD-ZFTRTX2
          TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
        ADD PARA_LENG TO BUFFER_POINTER.
      ENDIF.
      PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

      IF NOT ZTMLCHD-ZFTRTX3 IS INITIAL.                    " 063.
        PARA_LENG = STRLEN( ZTMLCHD-ZFTRTX3 ).
        MOVE ZTMLCHD-ZFTRTX3
          TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
        ADD PARA_LENG TO BUFFER_POINTER.
      ENDIF.
      PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

      IF NOT ZTMLCHD-ZFTRTX4 IS INITIAL.                    " 064.
        PARA_LENG = STRLEN( ZTMLCHD-ZFTRTX4 ).
        MOVE ZTMLCHD-ZFTRTX4
          TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
        ADD PARA_LENG TO BUFFER_POINTER.
      ENDIF.
      PERFORM P3000_1BYTE_DELIMETER_INSERT
              CHANGING W_EDI_RECORD.
    WHEN OTHERS.
  ENDCASE.

* 066 Partial Shipments.
  IF NOT ZTMLCHD-ZFPRMT IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCHD-ZFPRMT ).
    MOVE ZTMLCHD-ZFPRMT TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 067 Transhipment.
  IF NOT ZTMLCHD-ZFTRMT IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCHD-ZFTRMT ).
    MOVE ZTMLCHD-ZFTRMT TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 068 Loading on Board/Dispatch/Taking (선적항).
  IF NOT ZTMLCHD-ZFSPRT IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCHD-ZFSPRT ).
    MOVE ZTMLCHD-ZFSPRT TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 069 For Transporttation to ....
  IF NOT ZTMLCHD-ZFAPRT IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCHD-ZFAPRT ).
    MOVE ZTMLCHD-ZFAPRT TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 070 Latest Date of Shipment.
  IF NOT ZTMLCHD-ZFLTSD IS INITIAL.
    PARA_LENG = 8.
    MOVE ZTMLCHD-ZFLTSD TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 071 Shipment Period1.
  IF NOT ZTMLCHD-ZFSHPR1 IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCHD-ZFSHPR1 ).
    MOVE ZTMLCHD-ZFSHPR1 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 072 Shipment Period2.
  IF NOT ZTMLCHD-ZFSHPR2 IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCHD-ZFSHPR2 ).
    MOVE ZTMLCHD-ZFSHPR2 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 073 Shipment Period3.
  IF NOT ZTMLCHD-ZFSHPR3 IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCHD-ZFSHPR3 ).
    MOVE ZTMLCHD-ZFSHPR3 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 074 ~ 076 Shipment Period4 & 5 & 6.  --> 일단은 Blank Data를 내보낸다.
  PARA_LENG = 3.
  MOVE '|||' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ADD PARA_LENG TO BUFFER_POINTER.

*----------------------------------------------------------------------*
* Start of Description of Goods.
*----------------------------------------------------------------------*
* 077 Description of Goods and/or Se(입력여부).
  PARA_LENG = 3.
  PERFORM P3000_MLCSG_MAKE USING L_LINENO.
  IF L_LINENO GE 10. PARA_LENG = 2. ELSE. PARA_LENG = 1. ENDIF.

  IF NOT L_LINENO IS INITIAL.
    MOVE L_LINENO TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ELSE.
    MOVE '0' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 078 Description of Goods.
  IF L_LINENO GT 0.
    LOOP AT IT_ZSMLCSG7G.
      W_MOD = SY-TABIX MOD 5.
      CASE W_MOD.
        WHEN 1.
          CLEAR:L_ZFDSOG1, L_ZFDSOG2, L_ZFDSOG3,
                L_ZFDSOG4, L_ZFDSOG5.

          MOVE  IT_ZSMLCSG7G-ZFDSOG1 TO L_ZFDSOG1.
        WHEN 2.
          MOVE  IT_ZSMLCSG7G-ZFDSOG1 TO L_ZFDSOG2.
        WHEN 3.
          MOVE  IT_ZSMLCSG7G-ZFDSOG1 TO L_ZFDSOG3.
        WHEN 4.
          MOVE  IT_ZSMLCSG7G-ZFDSOG1 TO L_ZFDSOG4.
        WHEN 0.
          MOVE  IT_ZSMLCSG7G-ZFDSOG1 TO L_ZFDSOG5.

          IF NOT L_ZFDSOG1 IS INITIAL.
            PARA_LENG = 65.
            MOVE L_ZFDSOG1 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
            ADD PARA_LENG TO BUFFER_POINTER.
          ENDIF.

          IF NOT L_ZFDSOG2 IS INITIAL.
            PARA_LENG = 65.
            MOVE L_ZFDSOG2 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
            ADD PARA_LENG TO BUFFER_POINTER.
          ENDIF.

          IF NOT L_ZFDSOG3 IS INITIAL.
            PARA_LENG = 65.
            MOVE L_ZFDSOG3 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
            ADD PARA_LENG TO BUFFER_POINTER.
          ENDIF.

          IF NOT L_ZFDSOG4 IS INITIAL.
            PARA_LENG = 65.
            MOVE L_ZFDSOG4 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
            ADD PARA_LENG TO BUFFER_POINTER.
          ENDIF.

          IF NOT L_ZFDSOG5 IS INITIAL.
            PARA_LENG = 65.
            MOVE L_ZFDSOG5 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
            ADD PARA_LENG TO BUFFER_POINTER.
          ENDIF.

      ENDCASE.
    ENDLOOP.
    IF W_MOD NE 0.
      IF NOT L_ZFDSOG1 IS INITIAL.
        PARA_LENG = 65.
        MOVE L_ZFDSOG1 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
        ADD PARA_LENG TO BUFFER_POINTER.
      ENDIF.

      IF NOT L_ZFDSOG2 IS INITIAL.
        PARA_LENG = 65.
        MOVE L_ZFDSOG2 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
        ADD PARA_LENG TO BUFFER_POINTER.
      ENDIF.

      IF NOT L_ZFDSOG3 IS INITIAL.
        PARA_LENG = 65.
        MOVE L_ZFDSOG3 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
        ADD PARA_LENG TO BUFFER_POINTER.
      ENDIF.

      IF NOT L_ZFDSOG4 IS INITIAL.
        PARA_LENG = 65.
        MOVE L_ZFDSOG4 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
        ADD PARA_LENG TO BUFFER_POINTER.
      ENDIF.

      IF NOT L_ZFDSOG5 IS INITIAL.
        PARA_LENG = 65.
        MOVE L_ZFDSOG5 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
        ADD PARA_LENG TO BUFFER_POINTER.
      ENDIF.
    ENDIF.
  ENDIF.
  CLEAR: L_ZFDSOG1, L_ZFDSOG2, L_ZFDSOG3, L_ZFDSOG4, L_ZFDSOG5.
  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

*----------------------------------------------------------------------*
* End of Description of Goods.
*----------------------------------------------------------------------*
* 079 Assigned Commercial Invoice in.
  PARA_LENG = 1.
  IF ZTMLCSG910-ZFCOMYN EQ 'X'.        " 할당된 송장사본이 있는 경우.
    MOVE '1' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ELSE.                                " 할당된 송장사본이 없는 경우.
    MOVE '0' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ENDIF.
  ADD PARA_LENG TO BUFFER_POINTER.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 080 COPIES. --> ZTMLCSG910-ZFCOMYN이 'X'인 경우 필수항목.
  IF ZTMLCSG910-ZFCOMYN EQ 'X'.
    IF NOT ZTMLCSG910-ZFNOCOM IS INITIAL.
      PARA_LENG = STRLEN( ZTMLCSG910-ZFNOCOM ).
      MOVE ZTMLCSG910-ZFNOCOM
        TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
      ADD PARA_LENG TO BUFFER_POINTER.
    ELSE.
      MESSAGE E996 WITH W_ZFDHENO 'Commercial Invoice 통수'.
    ENDIF.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 081 FULL SET OF CLEAN ON BOARD OCEAN.
  PARA_LENG = 1.
  IF ZTMLCSG910-ZFOCEYN EQ 'X'.
    MOVE '1' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ELSE.
    MOVE '0' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ENDIF.
  ADD PARA_LENG TO BUFFER_POINTER.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 082 THE ORDER OF .
  IF ZTMLCSG910-ZFOCEYN EQ 'X'.
    IF NOT ZTMLCSG910-ZFOCEC1 IS INITIAL.
      PARA_LENG = STRLEN( ZTMLCSG910-ZFOCEC1 ).
      MOVE ZTMLCSG910-ZFOCEC1 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
      ADD PARA_LENG TO BUFFER_POINTER.
    ELSE.
      MESSAGE E996 WITH W_ZFDHENO 'Ocean Bill 하수인 1'.
    ENDIF.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 083 THE ORDER OF .
  IF NOT ZTMLCSG910-ZFOCEC2 IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCSG910-ZFOCEC2 ).
    MOVE ZTMLCSG910-ZFOCEC2 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 084 MARKED FREIGHT.
  IF ZTMLCSG910-ZFOCEYN EQ 'X'.
    IF NOT ZTMLCSG910-ZFOCEAC IS INITIAL.
      PARA_LENG = 2.
      MOVE ZTMLCSG910-ZFOCEAC TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
      ADD PARA_LENG TO BUFFER_POINTER.
    ELSE.
      MESSAGE E996 WITH W_ZFDHENO 'Ocean Bill 운임지불여부'.
    ENDIF.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 085 NOTIFY.
  IF ZTMLCSG910-ZFOCEYN EQ 'X'.
    IF NOT ZTMLCSG910-ZFOCEAN IS INITIAL.
      PARA_LENG = STRLEN( ZTMLCSG910-ZFOCEAN ).
      MOVE ZTMLCSG910-ZFOCEAN TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
      ADD PARA_LENG TO BUFFER_POINTER.
    ELSE.
      MESSAGE E996 WITH W_ZFDHENO 'Ocean Bill 통지처'.
    ENDIF.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 086 AIRWAY BILL CONSIGNED TO1.
  PARA_LENG = 1.
  IF ZTMLCSG910-ZFAIRYN EQ 'X'.
    MOVE '1' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ELSE.
    MOVE '0' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ENDIF.
  ADD PARA_LENG TO BUFFER_POINTER.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 087 AIRWAY BILL CONSIGNED TO2.
  IF ZTMLCSG910-ZFAIRYN EQ 'X'.
    IF NOT ZTMLCSG910-ZFAIRC1 IS INITIAL.
      PARA_LENG = STRLEN( ZTMLCSG910-ZFAIRC1 ).
      MOVE ZTMLCSG910-ZFAIRC1 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
      ADD PARA_LENG TO BUFFER_POINTER.
    ELSE.
      MESSAGE E996 WITH W_ZFDHENO 'Air Bill 하수인 1'.
    ENDIF.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 088 AIRWAY BILL CONSIGNED TO3.
  IF ZTMLCSG910-ZFAIRYN EQ 'X'.
    IF NOT ZTMLCSG910-ZFAIRC2 IS INITIAL.
      PARA_LENG = STRLEN( ZTMLCSG910-ZFAIRC2 ).
      MOVE ZTMLCSG910-ZFAIRC2 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
      ADD PARA_LENG TO BUFFER_POINTER.
    ENDIF.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 089 MARKED FREIGHT .
  IF ZTMLCSG910-ZFAIRYN EQ 'X'.
    IF NOT ZTMLCSG910-ZFAIRAC IS INITIAL.
      PARA_LENG = 2.
      MOVE ZTMLCSG910-ZFAIRAC TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
      ADD PARA_LENG TO BUFFER_POINTER.
    ELSE.
      MESSAGE E996 WITH W_ZFDHENO 'Air Bill 운임지불여부'.
    ENDIF.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 090 NOTIFY.
  IF ZTMLCSG910-ZFAIRYN EQ 'X'.
    IF NOT ZTMLCSG910-ZFAIRAN IS INITIAL.
      PARA_LENG = STRLEN( ZTMLCSG910-ZFAIRAN ).
      MOVE ZTMLCSG910-ZFAIRAN TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
      ADD PARA_LENG TO BUFFER_POINTER.
    ELSE.
      MESSAGE E996 WITH W_ZFDHENO 'Air Bill 통지처'.
    ENDIF.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 091 FULL SET OF INSURANCE POLICIES.
  PARA_LENG = 1.
  IF ZTMLCSG910-ZFINYN EQ 'X'.
    MOVE '1' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ELSE.
    MOVE '0' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ENDIF.
  ADD PARA_LENG TO BUFFER_POINTER.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 092 EXPRESSLY STIPULATING THAT CLAIMS.
  IF ZTMLCSG910-ZFINYN EQ 'X'.
    IF NOT ZTMLCSG910-ZFINCO1 IS INITIAL.
      PARA_LENG = STRLEN( ZTMLCSG910-ZFINCO1 ).
      MOVE ZTMLCSG910-ZFINCO1 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
      ADD PARA_LENG TO BUFFER_POINTER.
    ELSE.
      MESSAGE E996 WITH W_ZFDHENO '부보조건 1'.
    ENDIF.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 093 EXPRESSLY STIPULATING THAT CLAIMS.
  IF NOT ZTMLCSG910-ZFINCO2 IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCSG910-ZFINCO2 ).
    MOVE ZTMLCSG910-ZFINCO2 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 094 PACKING LIST IN.
  PARA_LENG = 1.
  IF ZTMLCSG910-ZFPACYN EQ 'X'.
    MOVE '1' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ELSE.
    MOVE '0' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ENDIF.
  ADD PARA_LENG TO BUFFER_POINTER.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 095 COPIES.
  IF ZTMLCSG910-ZFPACYN EQ 'X'.
    IF NOT ZTMLCSG910-ZFNOPAC IS INITIAL.
      PARA_LENG = STRLEN( ZTMLCSG910-ZFNOPAC ).
      MOVE ZTMLCSG910-ZFNOPAC TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
      ADD PARA_LENG TO BUFFER_POINTER.
    ELSE.
      MESSAGE E996 WITH W_ZFDHENO 'Packing List 통수'.
    ENDIF.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 096 CERTIFICATE OF ORIGIN.
  PARA_LENG = 1.
  IF ZTMLCSG910-ZFCEOYN EQ 'X'.
    MOVE '1' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ELSE.
    MOVE '0' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ENDIF.
  ADD PARA_LENG TO BUFFER_POINTER.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

*----------------------------------------------------------------------*
* Start of Other Documents.
*----------------------------------------------------------------------*
* 097 Other Documents.
  CLEAR: L_LINENO.
  IF ZTMLCSG910-ZFOTDYN EQ 'X'.
    PERFORM P3000_MLCSG8E_MAKE USING L_LINENO.
    IF L_LINENO GE 10. PARA_LENG = 2. ELSE. PARA_LENG = 1. ENDIF.

    IF NOT L_LINENO IS INITIAL.
      MOVE L_LINENO TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ELSE.
      MOVE '0' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ENDIF.
    ADD PARA_LENG TO BUFFER_POINTER.
  ELSE.
    PARA_LENG = 1.
    MOVE '0' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 098 OTHER DOCUMENT(S)  (if any)(65*5)*10.
  IF L_LINENO GT 0.
    LOOP AT IT_ZSMLCSG8E.
      W_MOD = SY-TABIX MOD 5.
      CASE W_MOD.
        WHEN 1.
          CLEAR:L_ZFDSOG1, L_ZFDSOG2, L_ZFDSOG3,
                L_ZFDSOG4, L_ZFDSOG5.

          MOVE  IT_ZSMLCSG8E-ZFOACD1 TO L_ZFDSOG1.
        WHEN 2.
          MOVE  IT_ZSMLCSG8E-ZFOACD1 TO L_ZFDSOG2.
        WHEN 3.
          MOVE  IT_ZSMLCSG8E-ZFOACD1 TO L_ZFDSOG3.
        WHEN 4.
          MOVE  IT_ZSMLCSG8E-ZFOACD1 TO L_ZFDSOG4.
        WHEN 0.
          MOVE  IT_ZSMLCSG8E-ZFOACD1 TO L_ZFDSOG5.

          IF NOT L_ZFDSOG1 IS INITIAL.
            PARA_LENG = 65.
            MOVE L_ZFDSOG1 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
            ADD PARA_LENG TO BUFFER_POINTER.
          ENDIF.

          IF NOT L_ZFDSOG2 IS INITIAL.
            PARA_LENG = 65.
            MOVE L_ZFDSOG2 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
            ADD PARA_LENG TO BUFFER_POINTER.
          ENDIF.

          IF NOT L_ZFDSOG3 IS INITIAL.
            PARA_LENG = 65.
            MOVE L_ZFDSOG3 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
            ADD PARA_LENG TO BUFFER_POINTER.
          ENDIF.

          IF NOT L_ZFDSOG4 IS INITIAL.
            PARA_LENG = 65.
            MOVE L_ZFDSOG4 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
            ADD PARA_LENG TO BUFFER_POINTER.
          ENDIF.

          IF NOT L_ZFDSOG5 IS INITIAL.
            PARA_LENG = 65.
            MOVE L_ZFDSOG5 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
            ADD PARA_LENG TO BUFFER_POINTER.
          ENDIF.

      ENDCASE.
    ENDLOOP.
    IF W_MOD NE 0.
      IF NOT L_ZFDSOG1 IS INITIAL.
        PARA_LENG = 65.
        MOVE L_ZFDSOG1 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
        ADD PARA_LENG TO BUFFER_POINTER.
      ENDIF.

      IF NOT L_ZFDSOG2 IS INITIAL.
        PARA_LENG = 65.
        MOVE L_ZFDSOG2 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
        ADD PARA_LENG TO BUFFER_POINTER.
      ENDIF.

      IF NOT L_ZFDSOG3 IS INITIAL.
        PARA_LENG = 65.
        MOVE L_ZFDSOG3 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
        ADD PARA_LENG TO BUFFER_POINTER.
      ENDIF.

      IF NOT L_ZFDSOG4 IS INITIAL.
        PARA_LENG = 65.
        MOVE L_ZFDSOG4 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
        ADD PARA_LENG TO BUFFER_POINTER.
      ENDIF.

      IF NOT L_ZFDSOG5 IS INITIAL.
        PARA_LENG = 65.
        MOVE L_ZFDSOG5 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
        ADD PARA_LENG TO BUFFER_POINTER.
      ENDIF.
    ENDIF.
    PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.
  ELSE.
    PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.
  ENDIF.
  CLEAR: L_ZFDSOG1, L_ZFDSOG2, L_ZFDSOG3, L_ZFDSOG4, L_ZFDSOG5.
*----------------------------------------------------------------------*
* End of Other Documents.
*----------------------------------------------------------------------*
* 099 SHIPMENT BY.
  PARA_LENG = 1.
  IF ZTMLCHD-ZFADCD1 EQ 'X'.
    MOVE '1' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ELSE.
    MOVE '0' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ENDIF.
  ADD PARA_LENG TO BUFFER_POINTER.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 100 SHIPMENT BY1.
  IF ZTMLCHD-ZFADCD1 EQ 'X'.
    IF NOT ZTMLCHD-ZFCARR IS INITIAL.
      PARA_LENG = STRLEN( ZTMLCHD-ZFCARR ).
      MOVE ZTMLCHD-ZFCARR TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
      ADD PARA_LENG TO BUFFER_POINTER.
    ELSE.
      MESSAGE E996 WITH W_ZFDHENO '선박회사/선박명'.
    ENDIF.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 101 ACCEPTANCE COMMISSION  DISCOUN.
  PARA_LENG = 1.
  IF ZTMLCHD-ZFADCD2 EQ 'X'.
    MOVE '1' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ELSE.
    MOVE '0' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ENDIF.
  ADD PARA_LENG TO BUFFER_POINTER.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 102 ALL DOCUMENTS MUST BEAR OUR CR.
  PARA_LENG = 1.
  IF ZTMLCHD-ZFADCD3 EQ 'X'.
    MOVE '1' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ELSE.
    MOVE '0' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ENDIF.
  ADD PARA_LENG TO BUFFER_POINTER.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 103 LATE PRESENTATION B/L ACCEPTAB.
  PARA_LENG = 1.
  IF ZTMLCHD-ZFADCD4 EQ 'X'.
    MOVE '1' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ELSE.
    MOVE '0' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ENDIF.
  ADD PARA_LENG TO BUFFER_POINTER.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

*----------------------------------------------------------------------*
* Start of Other Additional Conditions.
*----------------------------------------------------------------------*
* 104 Other Condition(s)(입력여부)
  CLEAR: L_LINENO.
  IF ZTMLCHD-ZFADCD5 EQ 'X'.
    PERFORM P3000_MLCSG9O_MAKE USING L_LINENO.
    IF L_LINENO GE 10. PARA_LENG = 2. ELSE. PARA_LENG = 1. ENDIF.

    IF NOT L_LINENO IS INITIAL.
      MOVE L_LINENO TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ELSE.
      MOVE '0' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ENDIF.
    ADD PARA_LENG TO BUFFER_POINTER.
  ELSE.
    PARA_LENG = 1.
    MOVE '0' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.
  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 105 Other Condition(s) if any(65*10).
  IF L_LINENO GT 0.
    LOOP AT IT_ZSMLCSG9O.
      W_MOD = SY-TABIX MOD 5.
      CASE W_MOD.
        WHEN 1.
          CLEAR:L_ZFDSOG1, L_ZFDSOG2, L_ZFDSOG3,
                L_ZFDSOG4, L_ZFDSOG5.

          MOVE  IT_ZSMLCSG9O-ZFODOC1 TO L_ZFDSOG1.
        WHEN 2.
          MOVE  IT_ZSMLCSG9O-ZFODOC1 TO L_ZFDSOG2.
        WHEN 3.
          MOVE  IT_ZSMLCSG9O-ZFODOC1 TO L_ZFDSOG3.
        WHEN 4.
          MOVE  IT_ZSMLCSG9O-ZFODOC1 TO L_ZFDSOG4.
        WHEN 0.
          MOVE  IT_ZSMLCSG9O-ZFODOC1 TO L_ZFDSOG5.

          IF NOT L_ZFDSOG1 IS INITIAL.
            PARA_LENG = 65.
            MOVE L_ZFDSOG1 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
            ADD PARA_LENG TO BUFFER_POINTER.
          ENDIF.

          IF NOT L_ZFDSOG2 IS INITIAL.
            PARA_LENG = 65.
            MOVE L_ZFDSOG2 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
            ADD PARA_LENG TO BUFFER_POINTER.
          ENDIF.

          IF NOT L_ZFDSOG3 IS INITIAL.
            PARA_LENG = 65.
            MOVE L_ZFDSOG3 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
            ADD PARA_LENG TO BUFFER_POINTER.
          ENDIF.

          IF NOT L_ZFDSOG4 IS INITIAL.
            PARA_LENG = 65.
            MOVE L_ZFDSOG4 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
            ADD PARA_LENG TO BUFFER_POINTER.
          ENDIF.

          IF NOT L_ZFDSOG5 IS INITIAL.
            PARA_LENG = 65.
            MOVE L_ZFDSOG5 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
            ADD PARA_LENG TO BUFFER_POINTER.
          ENDIF.
      ENDCASE.
    ENDLOOP.
    IF W_MOD NE 0.
      IF NOT L_ZFDSOG1 IS INITIAL.
        PARA_LENG = 65.
        MOVE L_ZFDSOG1 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
        ADD PARA_LENG TO BUFFER_POINTER.
      ENDIF.

      IF NOT L_ZFDSOG2 IS INITIAL.
        PARA_LENG = 65.
        MOVE L_ZFDSOG2 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
        ADD PARA_LENG TO BUFFER_POINTER.
      ENDIF.

      IF NOT L_ZFDSOG3 IS INITIAL.
        PARA_LENG = 65.
        MOVE L_ZFDSOG3 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
        ADD PARA_LENG TO BUFFER_POINTER.
      ENDIF.

      IF NOT L_ZFDSOG4 IS INITIAL.
        PARA_LENG = 65.
        MOVE L_ZFDSOG4 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
        ADD PARA_LENG TO BUFFER_POINTER.
      ENDIF.

      IF NOT L_ZFDSOG5 IS INITIAL.
        PARA_LENG = 65.
        MOVE L_ZFDSOG5 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
        ADD PARA_LENG TO BUFFER_POINTER.
      ENDIF.
    ENDIF.

    PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

  ELSE.
    PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.
  ENDIF.
  CLEAR: L_ZFDSOG1, L_ZFDSOG2, L_ZFDSOG3, L_ZFDSOG4, L_ZFDSOG5.
*----------------------------------------------------------------------*
* End of Other Additional Conditions.
*----------------------------------------------------------------------*
* 106 Charge (수수료 부담자).
  PARA_LENG = 2.
  MOVE ZTMLCHD-ZFCHG TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ADD PARA_LENG TO BUFFER_POINTER.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 107 DOCUMENTS TO BE PRESENTED WITH.
  IF NOT ZTMLCHD-ZFPFPR IS INITIAL.
    PARA_LENG = 2.
    MOVE ZTMLCHD-ZFPFPR TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ELSE.
    PARA_LENG = 1.
    MOVE '0' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 108 확언지시문언.
  PARA_LENG = 2.
  MOVE ZTMLCHD-ZFCNIS TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ADD PARA_LENG TO BUFFER_POINTER.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 109 명 의 인.
  IF NOT ZTMLCSG2-ZFAPPNM IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCSG2-ZFAPPNM ).
    MOVE ZTMLCSG2-ZFAPPNM TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ELSE.
    MESSAGE E996 WITH W_ZFDHENO 'Applicant 상호/성명'.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 110 명 의 인.
  IF NOT ZTMLCSG2-ZFREPRE IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCSG2-ZFREPRE ).
    MOVE ZTMLCSG2-ZFREPRE TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ELSE.
    MESSAGE E996 WITH W_ZFDHENO 'Applicant 전자서명 대표자'.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 111 식별부호(전자서명값10자리).
  IF NOT ZTMLCSG2-ZFELEID IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCSG2-ZFELEID ).
    MOVE ZTMLCSG2-ZFELEID TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ELSE.
    MESSAGE E996 WITH W_ZFDHENO 'Applicant 식별자'.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 112 주소.
  IF NOT ZTMLCSG2-ZFELEAD1 IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCSG2-ZFELEAD1 ).
    MOVE ZTMLCSG2-ZFELEAD1 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ELSE.
    MESSAGE E996 WITH W_ZFDHENO 'Applicant 전자서명 주소 1'.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 113 주소.
  IF NOT ZTMLCSG2-ZFELEAD1 IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCSG2-ZFELEAD1 ).
    MOVE ZTMLCSG2-ZFELEAD2 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 114 Country of Origin.
  IF NOT IT_ZSMLCSG7O-ZFORIG IS INITIAL.
    PARA_LENG = STRLEN( IT_ZSMLCSG7O-ZFORIG ).
    MOVE IT_ZSMLCSG7O-ZFORIG TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 115 Country of Origin.
  IF NOT IT_ZSMLCSG7O-ZFORNM IS INITIAL.
    PARA_LENG = STRLEN( IT_ZSMLCSG7O-ZFORNM ).
    MOVE IT_ZSMLCSG7O-ZFORNM TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 116 Place of Terms of Price.
  IF NOT ZTMLCHD-ZFINCP IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCHD-ZFINCP ).
    MOVE ZTMLCHD-ZFINCP TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 117 Terms of Price.
  IF NOT ZTMLCHD-INCO1 IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCHD-INCO1 ).
    MOVE ZTMLCHD-INCO1 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ELSE.
    MESSAGE E996 WITH W_ZFDHENO '인도조건 (파트 1)'.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 118 Terms of Price.
  IF NOT ZTMLCHD-ZFINCN IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCHD-ZFINCN ).
    MOVE ZTMLCHD-ZFINCN TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PARA_LENG = 7.
  MOVE '@@@}}~~' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ADD PARA_LENG TO BUFFER_POINTER.

*>> 마지막 New Line Char. Cut.
* NHJ 막음.
*  PERFORM P3000_EDI_RECORD_ADJUST  CHANGING W_EDI_RECORD.

ENDFUNCTION.
