FUNCTION ZIM_IMPORT_EDI_APP700 .
*"----------------------------------------------------------------------
*"*"Local interface:
*"  IMPORTING
*"     VALUE(W_ZFREQNO) LIKE  ZTREQHD-ZFREQNO
*"     VALUE(W_ZFDHENO) LIKE  ZTDHF1-ZFDHENO
*"     VALUE(W_BAHNS) LIKE  LFA1-BAHNS
*"  EXPORTING
*"     REFERENCE(W_EDI_RECORD)
*"  EXCEPTIONS
*"      DB_ERROR
*"----------------------------------------------------------------------
DATA : L_TEXT         LIKE     DD07T-DDTEXT,
       L_TEXT280(280) TYPE     C,
       L_TEXT350(350) TYPE     C,
       L_BOOLEAN      TYPE     C.

   CALL FUNCTION 'ZIM_GET_MASTER_LC_DATA'
        EXPORTING
              ZFREQNO           =       W_ZFREQNO
        IMPORTING
              W_ZTMLCHD         =       ZTMLCHD
              W_ZTMLCSG2        =       ZTMLCSG2
              W_ZTMLCSG910      =       ZTMLCSG910
        TABLES
              IT_ZSMLCSG7G      =       IT_ZSMLCSG7G
              IT_ZSMLCSG7O      =       IT_ZSMLCSG7O
              IT_ZSMLCSG8E      =       IT_ZSMLCSG8E
              IT_ZSMLCSG9O      =       IT_ZSMLCSG9O
              IT_ZSMLCSG7G_ORG  =       IT_ZSMLCSG7G_ORG
              IT_ZSMLCSG7O_ORG  =       IT_ZSMLCSG7O_ORG
              IT_ZSMLCSG8E_ORG  =       IT_ZSMLCSG8E_ORG
              IT_ZSMLCSG9O_ORG  =       IT_ZSMLCSG9O_ORG
        EXCEPTIONS
              NOT_FOUND     =       4
              NOT_INPUT     =       8.

   CASE SY-SUBRC.
      WHEN 4.
         MESSAGE E018 WITH W_ZFREQNO.
      WHEN 8.
         MESSAGE E019.
   ENDCASE.

*-----------------------------------------------------------------------
* SAM-FILE RECORD CREATE
*-----------------------------------------------------------------------
   CLEAR : W_EDI_RECORD.
*>> 관리번호.(01)
   MOVE : W_ZFDHENO           TO         W_EDI_RECORD.
*>> 기능코드.(02)
   CONCATENATE W_EDI_RECORD '^' ZTMLCHD-ZFEDFN INTO W_EDI_RECORD.
*>> 기능의미.(03)
   CONCATENATE W_EDI_RECORD '^'                INTO W_EDI_RECORD.
*>> 응답유형코드.(04)
   CONCATENATE W_EDI_RECORD '^' 'AB'           INTO W_EDI_RECORD.
*>> 응답유형의미.(05)
   CONCATENATE W_EDI_RECORD '^'                INTO W_EDI_RECORD.
*>> 신용장종류.(06)
   CONCATENATE W_EDI_RECORD '^' ZTMLCHD-ZFLCTY INTO W_EDI_RECORD.
*>> 종류내역(TEXT).(07)
   PERFORM   P1000_GET_DD07T_TEXT      USING     'ZDLCTY'
                                                  ZTMLCHD-ZFLCTY
                                       CHANGING   L_TEXT.
   CONCATENATE W_EDI_RECORD '^' L_TEXT         INTO W_EDI_RECORD.
*>> 개설방법.(08)
   CONCATENATE W_EDI_RECORD '^' ZTMLCHD-ZFOPME INTO W_EDI_RECORD.
*>> 방법 내역.(09)
   PERFORM   P1000_GET_DD07T_TEXT      USING     'ZDOPME'
                                                  ZTMLCHD-ZFOPME
                                       CHANGING   L_TEXT.
   CONCATENATE W_EDI_RECORD '^' L_TEXT         INTO W_EDI_RECORD.
*>> 확인지시.(10)
   CONCATENATE W_EDI_RECORD '^' ZTMLCHD-ZFCNIS INTO W_EDI_RECORD.
*>> 지시내역.(11)
   PERFORM   P1000_GET_DD07T_TEXT      USING     'ZDCNIS'
                                                  ZTMLCHD-ZFCNIS
                                       CHANGING   L_TEXT.
   CONCATENATE W_EDI_RECORD '^' L_TEXT         INTO W_EDI_RECORD.
*>>> 수수료 부담자(12).
   CONCATENATE W_EDI_RECORD '^' ZTMLCHD-ZFCHG  INTO W_EDI_RECORD.
*>> 부담자 내역(13).
   PERFORM   P1000_GET_DD07T_TEXT      USING     'ZDCHG'
                                                  ZTMLCHD-ZFCHG
                                       CHANGING   L_TEXT.
   CONCATENATE W_EDI_RECORD '^' L_TEXT         INTO W_EDI_RECORD.

*>>> 신청일자.(14)
   CONCATENATE W_EDI_RECORD '^' ZTREQST-ZFAPPDT INTO W_EDI_RECORD.
*>>> 서류제시기간(15).
   CONCATENATE W_EDI_RECORD '^' ZTMLCHD-ZFPFPR  INTO W_EDI_RECORD.
*>>> 환적 허용여부(16).
   CONCATENATE W_EDI_RECORD '^' ZTMLCHD-ZFTRMT  INTO W_EDI_RECORD.
*>> 환적 내역(17).
   PERFORM   P1000_GET_DD07T_TEXT      USING     'ZDTRMT'
                                                  ZTMLCHD-ZFTRMT
                                       CHANGING   L_TEXT.
   CONCATENATE W_EDI_RECORD '^' L_TEXT         INTO W_EDI_RECORD.
*>> 분할선적 허용여부(18).
   CONCATENATE W_EDI_RECORD '^' ZTMLCHD-ZFTRMT  INTO W_EDI_RECORD.
*>> 분할선적 내역(19).
   PERFORM   P1000_GET_DD07T_TEXT      USING     'ZDTRPR'
                                                  ZTMLCHD-ZFPRMT
                                       CHANGING   L_TEXT.
   CONCATENATE W_EDI_RECORD '^' L_TEXT         INTO W_EDI_RECORD.
*>> 신용공여주체(20).
   CONCATENATE W_EDI_RECORD '^' ZTMLCHD-ZFPAGR  INTO W_EDI_RECORD.
*>> 주체 내역(21).
   PERFORM   P1000_GET_DD07T_TEXT      USING     'ZDPAGR'
                                                  ZTMLCHD-ZFPAGR
                                       CHANGING   L_TEXT.
   CONCATENATE W_EDI_RECORD '^' L_TEXT         INTO W_EDI_RECORD.
*>>> 지급조건(22).
   CASE ZTMLCHD-ZFTRMB.
      WHEN '2AO'.
         CONCATENATE W_EDI_RECORD '^' '2AB' INTO W_EDI_RECORD.
      WHEN '2AM'.
         CONCATENATE W_EDI_RECORD '^' '6'   INTO W_EDI_RECORD.
      WHEN '2AN'.
         CONCATENATE W_EDI_RECORD '^' '4'   INTO W_EDI_RECORD.
      WHEN OTHERS.
         CONCATENATE W_EDI_RECORD '^'       INTO W_EDI_RECORD.
   ENDCASE.
*>> 지급조건내역 (23).
   PERFORM   P1000_GET_DD07T_TEXT      USING     'ZDTRMB'
                                                  ZTMLCHD-ZFTRMB
                                       CHANGING   L_TEXT.
   CONCATENATE W_EDI_RECORD '^' L_TEXT          INTO W_EDI_RECORD.
*>> 지급조건1(24).
   PERFORM  P2000_SPACE_AND_CHANGE_SYMBOL CHANGING ZTMLCHD-ZFTRTX1.
   CONCATENATE W_EDI_RECORD '^' ZTMLCHD-ZFTRTX1 INTO W_EDI_RECORD.
*>> 지급조건2(25).
   PERFORM  P2000_SPACE_AND_CHANGE_SYMBOL CHANGING ZTMLCHD-ZFTRTX2.
   CONCATENATE W_EDI_RECORD '^' ZTMLCHD-ZFTRTX2 INTO W_EDI_RECORD.
*>> 지급조건3(26).
   PERFORM  P2000_SPACE_AND_CHANGE_SYMBOL CHANGING ZTMLCHD-ZFTRTX3.
   CONCATENATE W_EDI_RECORD '^' ZTMLCHD-ZFTRTX3 INTO W_EDI_RECORD.
*>> 지급조건4(27).
   PERFORM  P2000_SPACE_AND_CHANGE_SYMBOL CHANGING ZTMLCHD-ZFTRTX4.
   CONCATENATE W_EDI_RECORD '^' ZTMLCHD-ZFTRTX4 INTO W_EDI_RECORD.

*>>> 기타정보(28).
   CLEAR L_TEXT280.
   PERFORM  P2000_SPACE_AND_CHANGE_SYMBOL CHANGING ZTMLCHD-ZFETC1.
   PERFORM  P2000_SPACE_AND_CHANGE_SYMBOL CHANGING ZTMLCHD-ZFETC2.
   PERFORM  P2000_SPACE_AND_CHANGE_SYMBOL CHANGING ZTMLCHD-ZFETC3.
   PERFORM  P2000_SPACE_AND_CHANGE_SYMBOL CHANGING ZTMLCHD-ZFETC4.
   PERFORM  P2000_SPACE_AND_CHANGE_SYMBOL CHANGING ZTMLCHD-ZFETC5.

   CONCATENATE ZTMLCHD-ZFETC1 ZTMLCHD-ZFETC2
               ZTMLCHD-ZFETC3 ZTMLCHD-ZFETC4
*              ZTMLCHD-ZFETC5                INTO L_TEXT280
                                             INTO L_TEXT280
                                             SEPARATED BY SPACE.

   CONCATENATE W_EDI_RECORD '^' L_TEXT280        INTO W_EDI_RECORD.

*>>> 개설은행코드(29).
   PERFORM  P2000_SPACE_AND_CHANGE_SYMBOL CHANGING ZTMLCHD-ZFOPBNCD.
   CONCATENATE W_EDI_RECORD '^' ZTMLCHD-ZFOPBNCD INTO W_EDI_RECORD.
*>>> 개설은행명(30).
   PERFORM  P2000_SPACE_AND_CHANGE_SYMBOL CHANGING ZTMLCHD-ZFOBNM.
   CONCATENATE W_EDI_RECORD '^' ZTMLCHD-ZFOBNM   INTO W_EDI_RECORD.
*>>> 개설은행지점명(31).
   PERFORM  P2000_SPACE_AND_CHANGE_SYMBOL CHANGING ZTMLCHD-ZFOBBR.
   CONCATENATE W_EDI_RECORD '^' ZTMLCHD-ZFOBBR   INTO W_EDI_RECORD.
*>>> 개설은행전화번호(32).
   PERFORM  P2000_SPACE_AND_CHANGE_SYMBOL CHANGING ZTMLCHD-ZFOBPH.
   CONCATENATE W_EDI_RECORD '^' ZTMLCHD-ZFOBPH   INTO W_EDI_RECORD.
*>>> 통지은행명(33).
   PERFORM  P2000_SPACE_AND_CHANGE_SYMBOL CHANGING ZTMLCHD-ZFABNM.
   CONCATENATE W_EDI_RECORD '^' ZTMLCHD-ZFABNM   INTO W_EDI_RECORD.
*>>> 통지은행 지점명(34).
   PERFORM  P2000_SPACE_AND_CHANGE_SYMBOL CHANGING ZTMLCHD-ZFABBR.
   CONCATENATE W_EDI_RECORD '^' ZTMLCHD-ZFABBR   INTO W_EDI_RECORD.

*>>> 개설의뢰인 성명(35).
   PERFORM  P2000_SPACE_AND_CHANGE_SYMBOL CHANGING ZTMLCSG2-ZFAPPNM.
   CONCATENATE W_EDI_RECORD '^' ZTMLCSG2-ZFAPPNM  INTO W_EDI_RECORD.
*>>> 개설의뢰인 상호(36).
   PERFORM  P2000_SPACE_AND_CHANGE_SYMBOL CHANGING ZTMLCSG2-ZFAPPAD1.
   CONCATENATE W_EDI_RECORD '^' ZTMLCSG2-ZFAPPAD1 INTO W_EDI_RECORD.
*>>> 개설의뢰인 주소(37).
   PERFORM  P2000_SPACE_AND_CHANGE_SYMBOL CHANGING ZTMLCSG2-ZFAPPAD2.
   CONCATENATE W_EDI_RECORD '^' ZTMLCSG2-ZFAPPAD2 INTO W_EDI_RECORD.
*>>> 개설의뢰인 주소2(38).
   PERFORM  P2000_SPACE_AND_CHANGE_SYMBOL CHANGING ZTMLCSG2-ZFAPPAD3.
   CONCATENATE W_EDI_RECORD '^' ZTMLCSG2-ZFAPPAD3 INTO W_EDI_RECORD.
*>>> 개설의뢰인 전화번호(39).
   PERFORM  P2000_SPACE_AND_CHANGE_SYMBOL CHANGING ZTMLCSG2-ZFTELNO.
   CONCATENATE W_EDI_RECORD '^' ZTMLCSG2-ZFTELNO  INTO W_EDI_RECORD.

*>>> 수익자 성명(40).
   PERFORM  P2000_SPACE_AND_CHANGE_SYMBOL CHANGING ZTMLCSG2-ZFBENI1.
   CONCATENATE W_EDI_RECORD '^' ZTMLCSG2-ZFBENI1  INTO W_EDI_RECORD.
*>>> 수익자 상호(41).
   PERFORM  P2000_SPACE_AND_CHANGE_SYMBOL CHANGING ZTMLCSG2-ZFBENI2.
   CONCATENATE W_EDI_RECORD '^' ZTMLCSG2-ZFBENI2  INTO W_EDI_RECORD.
*>>> 수익자 주소(42).
   PERFORM  P2000_SPACE_AND_CHANGE_SYMBOL CHANGING ZTMLCSG2-ZFBENI3.
   CONCATENATE W_EDI_RECORD '^' ZTMLCSG2-ZFBENI3  INTO W_EDI_RECORD.
*>>> 수익자 주소(43).
   PERFORM  P2000_SPACE_AND_CHANGE_SYMBOL CHANGING ZTMLCSG2-ZFBENI4.
   CONCATENATE W_EDI_RECORD '^' ZTMLCSG2-ZFBENI4  INTO W_EDI_RECORD.
*>>> 수익자 계좌(44).
   PERFORM  P2000_SPACE_AND_CHANGE_SYMBOL CHANGING ZTMLCSG2-ZFBENIA.
   CONCATENATE W_EDI_RECORD '^' ZTMLCSG2-ZFBENIA  INTO W_EDI_RECORD.

*>> 의뢰상호(45).
   PERFORM  P2000_SPACE_AND_CHANGE_SYMBOL CHANGING ZTMLCSG2-ZFELENM.
   CONCATENATE W_EDI_RECORD '^' ZTMLCSG2-ZFELENM  INTO W_EDI_RECORD.
*>> 의뢰상호(46).
   PERFORM  P2000_SPACE_AND_CHANGE_SYMBOL CHANGING ZTMLCSG2-ZFREPRE.
   CONCATENATE W_EDI_RECORD '^' ZTMLCSG2-ZFREPRE  INTO W_EDI_RECORD.
*>> 의뢰상호(47).
   PERFORM  P2000_SPACE_AND_CHANGE_SYMBOL CHANGING ZTMLCSG2-ZFELEID.
   CONCATENATE W_EDI_RECORD '^' ZTMLCSG2-ZFELEID  INTO W_EDI_RECORD.
*>> 의뢰상호(48).
   PERFORM  P2000_SPACE_AND_CHANGE_SYMBOL CHANGING ZTMLCSG2-ZFELEAD1.
   CONCATENATE W_EDI_RECORD '^' ZTMLCSG2-ZFELEAD1 INTO W_EDI_RECORD.
*>> 의뢰상호(49).
   PERFORM  P2000_SPACE_AND_CHANGE_SYMBOL CHANGING ZTMLCSG2-ZFELEAD2.
   CONCATENATE W_EDI_RECORD '^' ZTMLCSG2-ZFELEAD2 INTO W_EDI_RECORD.

*>>> 유효기일(50)yyyymmdd.
   CONCATENATE W_EDI_RECORD '^' ZTMLCHD-ZFEXDT    INTO W_EDI_RECORD.
*>>> 유효장소(51).
   PERFORM  P2000_SPACE_AND_CHANGE_SYMBOL CHANGING ZTMLCHD-ZFEXPL.
   CONCATENATE W_EDI_RECORD '^' ZTMLCHD-ZFEXPL    INTO W_EDI_RECORD.

*>>> 개설금액(52)
   WRITE   ZTMLCHD-ZFOPAMT    TO      W_TEXT_AMOUNT
                         CURRENCY     ZTMLCHD-WAERS.
   PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.
   CONCATENATE W_EDI_RECORD '^' W_TEXT_AMOUNT     INTO W_EDI_RECORD.
*>>> 개설금액통화(53)
   CONCATENATE W_EDI_RECORD '^' ZTMLCHD-WAERS     INTO W_EDI_RECORD.

*>>> 부가금액부담(54)
   CLEAR L_TEXT280.
   PERFORM  P2000_SPACE_AND_CHANGE_SYMBOL CHANGING ZTMLCHD-ZFAAMT1.
   PERFORM  P2000_SPACE_AND_CHANGE_SYMBOL CHANGING ZTMLCHD-ZFAAMT2.
   PERFORM  P2000_SPACE_AND_CHANGE_SYMBOL CHANGING ZTMLCHD-ZFAAMT3.
   PERFORM  P2000_SPACE_AND_CHANGE_SYMBOL CHANGING ZTMLCHD-ZFAAMT4.
   CONCATENATE ZTMLCHD-ZFAAMT1 ZTMLCHD-ZFAAMT2
               ZTMLCHD-ZFAAMT3 ZTMLCHD-ZFAAMT4
               INTO L_TEXT280 SEPARATED BY SPACE.
   CONCATENATE W_EDI_RECORD '^' L_TEXT280        INTO W_EDI_RECORD.

*>>> 과부족사용(55)
   CONCATENATE W_EDI_RECORD '^' ZTMLCHD-ZFALCQ   INTO W_EDI_RECORD.
*>>> 과부족내역(56)
   PERFORM   P1000_GET_DD07T_TEXT      USING     'ZDALCQ'
                                                  ZTMLCHD-ZFALCQ
                                       CHANGING   L_TEXT.
   CONCATENATE W_EDI_RECORD '^' L_TEXT         INTO W_EDI_RECORD.
*>>> 과부족허용율(57)
   WRITE   ZTMLCHD-ZFALCP     TO      W_TEXT_AMOUNT.
   PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.
   CONCATENATE W_EDI_RECORD '^' W_TEXT_AMOUNT     INTO W_EDI_RECORD.
*>>> 초과허용율(58)
   CONCATENATE W_EDI_RECORD '^' '0'               INTO W_EDI_RECORD.
*>>> 부족허용율(59)
   CONCATENATE W_EDI_RECORD '^' '0'               INTO W_EDI_RECORD.

*>>> 선적항(60).
   PERFORM  P2000_SPACE_AND_CHANGE_SYMBOL CHANGING ZTMLCHD-ZFSPRT.
   CONCATENATE W_EDI_RECORD '^' ZTMLCHD-ZFSPRT    INTO W_EDI_RECORD.
*>>> 선적일자(61)YYYYMMDD.
   CONCATENATE W_EDI_RECORD '^' ZTMLCHD-ZFLTSD    INTO W_EDI_RECORD.
*>>> 선적기간(62).
   CLEAR L_TEXT280.
   PERFORM  P2000_SPACE_AND_CHANGE_SYMBOL CHANGING ZTMLCHD-ZFSHPR1.
   PERFORM  P2000_SPACE_AND_CHANGE_SYMBOL CHANGING ZTMLCHD-ZFSHPR2.
   PERFORM  P2000_SPACE_AND_CHANGE_SYMBOL CHANGING ZTMLCHD-ZFSHPR3.
   CONCATENATE ZTMLCHD-ZFSHPR1 ZTMLCHD-ZFSHPR2
               ZTMLCHD-ZFSHPR3
               INTO L_TEXT280 SEPARATED BY SPACE.
   CONCATENATE W_EDI_RECORD '^' L_TEXT280        INTO W_EDI_RECORD.
*>>> 도착항(63).
   PERFORM  P2000_SPACE_AND_CHANGE_SYMBOL CHANGING ZTMLCHD-ZFAPRT.
   CONCATENATE W_EDI_RECORD '^' ZTMLCHD-ZFAPRT    INTO W_EDI_RECORD.
*>>> 가격조건 코드(64).
   CONCATENATE W_EDI_RECORD '^' ZTMLCHD-INCO1     INTO W_EDI_RECORD.
*>>> 가격조건 내역(65).  ===> ????
   PERFORM  P2000_SPACE_AND_CHANGE_SYMBOL CHANGING ZTMLCHD-ZFAPRT.
   CONCATENATE W_EDI_RECORD '^' ZTMLCHD-INCO1     INTO W_EDI_RECORD.
*>>> 가격조건 평문(66).
   PERFORM  P2000_SPACE_AND_CHANGE_SYMBOL CHANGING ZTMLCHD-ZFINCN.
   CONCATENATE W_EDI_RECORD '^' ZTMLCHD-ZFINCN    INTO W_EDI_RECORD.
*>>> 가격조건 장소(67).
   PERFORM  P2000_SPACE_AND_CHANGE_SYMBOL CHANGING ZTMLCHD-ZFINCP.
   CONCATENATE W_EDI_RECORD '^' ZTMLCHD-ZFINCP    INTO W_EDI_RECORD.

*>>> 원산지 코드(68).
   READ TABLE IT_ZSMLCSG7O INDEX 1.
   CONCATENATE W_EDI_RECORD '^' IT_ZSMLCSG7O-ZFLSG7O INTO W_EDI_RECORD.
*>>> 원산지 내역(69).
   PERFORM  P2000_SPACE_AND_CHANGE_SYMBOL CHANGING IT_ZSMLCSG7O-ZFORIG.
   CONCATENATE W_EDI_RECORD '^' IT_ZSMLCSG7O-ZFORIG  INTO W_EDI_RECORD.
*>>> 원산지 장소(70). ----> SKIP
   CONCATENATE W_EDI_RECORD '^'                      INTO W_EDI_RECORD.

*>>> 상품명세(71). ---> ????
   LOOP AT IT_ZSMLCSG7G.
      PERFORM  P2000_SPACE_AND_CHANGE_SYMBOL
               CHANGING IT_ZSMLCSG7G-ZFDSOG1.
      W_MOD = SY-TABIX MOD 5.
      CASE W_MOD.
         WHEN 1.
            CLEAR L_TEXT350.
            CONCATENATE L_TEXT350 IT_ZSMLCSG7G-ZFDSOG1
                        INTO L_TEXT350 SEPARATED BY SPACE.
         WHEN 0.
            CONCATENATE L_TEXT350 IT_ZSMLCSG7G-ZFDSOG1
                        INTO L_TEXT350 SEPARATED BY SPACE.
            CONCATENATE W_EDI_RECORD '^' L_TEXT350
                                         INTO W_EDI_RECORD.
         WHEN OTHERS.
            CONCATENATE L_TEXT350 IT_ZSMLCSG7G-ZFDSOG1
                        INTO L_TEXT350 SEPARATED BY SPACE.
      ENDCASE.
   ENDLOOP.
   IF W_MOD NE 0.
      CONCATENATE W_EDI_RECORD '^' L_TEXT350
                                   INTO W_EDI_RECORD.
   ENDIF.
*>>> 주요부가1(72). ---> Shipment by
   L_BOOLEAN = 'F'.
   IF NOT ZTMLCHD-ZFADCD1 IS INITIAL.
      L_BOOLEAN = 'T'.
   ENDIF.
   CONCATENATE W_EDI_RECORD '^' L_BOOLEAN         INTO W_EDI_RECORD.
*>>> 주요부가2(73). ---> Acceptance Commission
   L_BOOLEAN = 'F'.
   IF NOT ZTMLCHD-ZFADCD2 IS INITIAL.
      L_BOOLEAN = 'T'.
   ENDIF.
   CONCATENATE W_EDI_RECORD '^' L_BOOLEAN         INTO W_EDI_RECORD.
*>>> 주요부가3(74). ---> credit number
   L_BOOLEAN = 'F'.
   IF NOT ZTMLCHD-ZFADCD3 IS INITIAL.
      L_BOOLEAN = 'T'.
   ENDIF.
   CONCATENATE W_EDI_RECORD '^' L_BOOLEAN         INTO W_EDI_RECORD.
*>>> 주요부가4(75). ---> B/L Acceptance
   L_BOOLEAN = 'F'.
   IF NOT ZTMLCHD-ZFADCD4 IS INITIAL.
      L_BOOLEAN = 'T'.
   ENDIF.
   CONCATENATE W_EDI_RECORD '^' L_BOOLEAN         INTO W_EDI_RECORD.
*>>> 주요부가코드(76). ---> ????
   CONCATENATE W_EDI_RECORD '^'                   INTO W_EDI_RECORD.
*>>> 주요부가내역(77). ---> ????
   CONCATENATE W_EDI_RECORD '^'                   INTO W_EDI_RECORD.
*>>> 선박회사(78).
   PERFORM  P2000_SPACE_AND_CHANGE_SYMBOL CHANGING ZTMLCHD-ZFCARR.
   CONCATENATE W_EDI_RECORD '^' ZTMLCHD-ZFCARR    INTO W_EDI_RECORD.
*>>> 부가조건(79).
   CLEAR L_TEXT280.
   LOOP AT IT_ZSMLCSG9O.
      CHECK SY-TABIX LE 4.
      PERFORM  P2000_SPACE_AND_CHANGE_SYMBOL
                           CHANGING IT_ZSMLCSG9O-ZFODOC1.
      CONCATENATE L_TEXT280 IT_ZSMLCSG9O-ZFODOC1
                  INTO L_TEXT280 SEPARATED BY SPACE.
   ENDLOOP.
   CONCATENATE W_EDI_RECORD '^' L_TEXT280         INTO W_EDI_RECORD.

*>>> 승인번호(수입추천)
   DO 5 TIMES.
      READ TABLE IT_ZSREQIL INDEX SY-INDEX.
      IF SY-SUBRC EQ 0.
         PERFORM  P2000_SPACE_AND_CHANGE_SYMBOL
                           CHANGING IT_ZSREQIL-ZFRECNO.
*>>> 승인번호
         CONCATENATE W_EDI_RECORD '^' IT_ZSREQIL-ZFRECNO
                                      INTO W_EDI_RECORD.
*>>> 승인금액
         WRITE   IT_ZSREQIL-ZFRECAM TO      W_TEXT_AMOUNT
                                    CURRENCY     IT_ZSREQIL-ZFRECCU.
         PERFORM    P2000_WRITE_NO_MASK
                                    CHANGING  W_TEXT_AMOUNT.
         CONCATENATE W_EDI_RECORD '^' W_TEXT_AMOUNT
                                      INTO W_EDI_RECORD.
*>>> 승인금액통화
         CONCATENATE W_EDI_RECORD '^' IT_ZSREQIL-ZFRECCU
                                      INTO W_EDI_RECORD.
      ELSE.
         CONCATENATE W_EDI_RECORD '^^0^' INTO W_EDI_RECORD.
      ENDIF.
   ENDDO.

*>>> 송장통수(95)
   CONCATENATE W_EDI_RECORD '^' ZTMLCSG910-ZFNOCOM INTO W_EDI_RECORD.
*>>> 팩킹통수(96)
   CONCATENATE W_EDI_RECORD '^' ZTMLCSG910-ZFNOPAC INTO W_EDI_RECORD.
*>>> 원산지증명서(97)
   L_BOOLEAN = 'F'.
   IF NOT ZTMLCSG910-ZFPACYN IS INITIAL.
      L_BOOLEAN = 'T'.
   ENDIF.
   CONCATENATE W_EDI_RECORD '^' L_BOOLEAN         INTO W_EDI_RECORD.
*>>> 기타서류(98)
   CLEAR L_TEXT280.
   LOOP AT IT_ZSMLCSG8E.
      CHECK SY-TABIX LE 4.
      PERFORM  P2000_SPACE_AND_CHANGE_SYMBOL
                           CHANGING IT_ZSMLCSG8E-ZFOACD1.
      CONCATENATE L_TEXT280 IT_ZSMLCSG8E-ZFOACD1
                  INTO L_TEXT280 SEPARATED BY SPACE.
   ENDLOOP.
   CONCATENATE W_EDI_RECORD '^' L_TEXT280        INTO W_EDI_RECORD.
*>>> 증권부보1(99)
   PERFORM  P2000_SPACE_AND_CHANGE_SYMBOL
            CHANGING ZTMLCSG910-ZFINCO1.
   CONCATENATE W_EDI_RECORD '^' ZTMLCSG910-ZFINCO1 INTO W_EDI_RECORD.
*>>> 증권부보2(100)
   PERFORM  P2000_SPACE_AND_CHANGE_SYMBOL
            CHANGING ZTMLCSG910-ZFINCO2.
   CONCATENATE W_EDI_RECORD '^' ZTMLCSG910-ZFINCO2 INTO W_EDI_RECORD.

   IF NOT ZTMLCSG910-ZFOCEYN IS INITIAL.
*>>> B운임지불(101)
      CONCATENATE W_EDI_RECORD '^' ZTMLCSG910-ZFOCEAC INTO W_EDI_RECORD.
*>>> B운임내역(102)
      PERFORM   P1000_GET_DD07T_TEXT      USING     'ZDOCEAC'
                                                     ZTMLCSG910-ZFOCEAC
                                          CHANGING   L_TEXT.
      CONCATENATE W_EDI_RECORD '^' L_TEXT         INTO W_EDI_RECORD.
*>>> B하수인(103)
      PERFORM  P2000_SPACE_AND_CHANGE_SYMBOL
               CHANGING ZTMLCSG910-ZFOCEC1.
      CONCATENATE W_EDI_RECORD '^' ZTMLCSG910-ZFOCEC1 INTO W_EDI_RECORD.
*>>> B하수인1(104)
      PERFORM  P2000_SPACE_AND_CHANGE_SYMBOL
               CHANGING ZTMLCSG910-ZFOCEC2.
      CONCATENATE W_EDI_RECORD '^' ZTMLCSG910-ZFOCEC2 INTO W_EDI_RECORD.
*>>> B통지처(105)
      PERFORM  P2000_SPACE_AND_CHANGE_SYMBOL
               CHANGING ZTMLCSG910-ZFOCEAN.
      CONCATENATE W_EDI_RECORD '^' ZTMLCSG910-ZFOCEAN INTO W_EDI_RECORD.
   ELSE.
      CONCATENATE W_EDI_RECORD '^^^^^'  INTO W_EDI_RECORD.
   ENDIF.

   IF NOT ZTMLCSG910-ZFINYN IS INITIAL.
*>>> A운임지불(106)
      CONCATENATE W_EDI_RECORD '^' ZTMLCSG910-ZFAIRAC INTO W_EDI_RECORD.
*>>> A운임내역(107)
      PERFORM   P1000_GET_DD07T_TEXT      USING     'ZDAIRAC'
                                                     ZTMLCSG910-ZFAIRAC
                                          CHANGING   L_TEXT.
      CONCATENATE W_EDI_RECORD '^' L_TEXT         INTO W_EDI_RECORD.
*>>> A하수인(108)
      PERFORM  P2000_SPACE_AND_CHANGE_SYMBOL
               CHANGING ZTMLCSG910-ZFAIRC1.
      CONCATENATE W_EDI_RECORD '^' ZTMLCSG910-ZFAIRC1 INTO W_EDI_RECORD.
*>>> A하수인1(109)
      PERFORM  P2000_SPACE_AND_CHANGE_SYMBOL
               CHANGING ZTMLCSG910-ZFAIRC2.
      CONCATENATE W_EDI_RECORD '^' ZTMLCSG910-ZFAIRC2 INTO W_EDI_RECORD.
*>>> A통지처(110)
      PERFORM  P2000_SPACE_AND_CHANGE_SYMBOL
               CHANGING ZTMLCSG910-ZFAIRAN.
      CONCATENATE W_EDI_RECORD '^' ZTMLCSG910-ZFAIRAN INTO W_EDI_RECORD.
   ELSE.
      CONCATENATE W_EDI_RECORD '^^^^^'  INTO W_EDI_RECORD.
   ENDIF.

*>>> 오류(111)
   CONCATENATE W_EDI_RECORD '^'                    INTO W_EDI_RECORD.
*>>> 송신(111)
   CONCATENATE W_EDI_RECORD '^'                    INTO W_EDI_RECORD.
*>>> 수신처(113)
   CONCATENATE W_EDI_RECORD '^' W_BAHNS            INTO W_EDI_RECORD.
*>>> 상태(114)
   CONCATENATE W_EDI_RECORD '^'                    INTO W_EDI_RECORD.
*>>> 입력일(115)
   CONCATENATE W_EDI_RECORD '^' SY-DATUM           INTO W_EDI_RECORD.

*   CALL FUNCTION 'ZIM_EDI_FLAT_ITEM_INSERT'
*        EXPORTING
*              W_ZFDHENO         =        W_ZFDHENO
*        TABLES
*              IT_ZTDDF1         =        IT_ZTDDF1
*        EXCEPTIONS
*              DB_ERROR         =         4.
*
*   IF SY-SUBRC NE 0.
*      MESSAGE E118 WITH W_ZFDHENO.
*   ENDIF.

ENDFUNCTION.























