*&---------------------------------------------------------------------*
*&  Function Module 명: APP707 EDI Send                                *
*&              작성자: 나신호 INFOLINK Ltd.                           *
*&              작성일: 2002.06.04                                     *
*&---------------------------------------------------------------------*
*&   DESC.     :
*&---------------------------------------------------------------------*
*& [변경내용]
*&---------------------------------------------------------------------*
FUNCTION ZIM_MAT_APP707_EDI_DOC.
*"----------------------------------------------------------------------
*"*"Local interface:
*"  IMPORTING
*"     VALUE(W_ZFREQNO) LIKE  ZTREQHD-ZFREQNO
*"     VALUE(W_ZFAMDNO) LIKE  ZTREQST-ZFAMDNO
*"     REFERENCE(W_ZFDHENO) LIKE  ZTDHF1-ZFDHENO
*"     REFERENCE(W_BAHNS) LIKE  LFA1-BAHNS
*"  EXPORTING
*"     REFERENCE(W_EDI_RECORD)
*"  EXCEPTIONS
*"      CREATE_ERROR
*"----------------------------------------------------------------------
  DATA : L_TEXT           LIKE     DD07T-DDTEXT,
         L_TEXT280(280)   TYPE     C,
         L_TEXT350(350)   TYPE     C,
         L_TEXT1750(1750) TYPE     C,
         L_BOOLEAN        TYPE     C,
         L_TYPE(002)      TYPE     C,
         L_TYPE_TEMP      LIKE     L_TYPE,
         L_CODE(003)      TYPE     C,
         L_ZFDSOG1        LIKE     IT_ZSMLCSG7G-ZFDSOG1,
         L_ZFDSOG2        LIKE     IT_ZSMLCSG7G-ZFDSOG1,
         L_ZFDSOG3        LIKE     IT_ZSMLCSG7G-ZFDSOG1,
         L_ZFDSOG4        LIKE     IT_ZSMLCSG7G-ZFDSOG1,
         L_ZFDSOG5        LIKE     IT_ZSMLCSG7G-ZFDSOG1,
         L_ZFAMDNO        LIKE     ZTREQST-ZFAMDNO,
         L_ZFOPNDT        LIKE     ZTREQST-ZFOPNDT,
         W_OPNDT          LIKE     ZTREQST-ZFOPNDT.
  DATA : L_SEQ(005)       TYPE     C.
  DATA : W_STRLEN         TYPE     I.
  DATA : L_LINENO         TYPE     I.

*> MASTER L/C AMEND DATA READ.
  CALL FUNCTION 'ZIM_GET_MASTER_LC_AMEND_DATA'
       EXPORTING
            ZFREQNO            = W_ZFREQNO
            ZFAMDNO            = W_ZFAMDNO
       IMPORTING
            W_ZTMLCAMHD        = ZTMLCAMHD
       TABLES
            IT_ZSMLCAMNARR     = IT_ZSMLCAMNARR
            IT_ZSMLCAMNARR_ORG = IT_ZSMLCAMNARR_ORG
       EXCEPTIONS
            NOT_FOUND          = 4
            NOT_INPUT          = 8.

  CASE SY-SUBRC.
    WHEN 4.
      MESSAGE E018 WITH W_ZFREQNO RAISING  CREATE_ERROR.
    WHEN 8.
      MESSAGE E019 RAISING  CREATE_ERROR.
  ENDCASE.

  SELECT SINGLE * FROM ZTREQHD
         WHERE    ZFREQNO  EQ   W_ZFREQNO.

  SELECT SINGLE * FROM ZTREQST
         WHERE    ZFREQNO  EQ    W_ZFREQNO
         AND      ZFAMDNO  EQ    W_ZFAMDNO.

  SELECT SINGLE * FROM  ZTIMIMGTX
         WHERE    BUKRS    EQ   ZTREQHD-BUKRS.

*>> LC HEADER TABLE
  SELECT SINGLE * FROM ZTMLCHD
         WHERE    ZFREQNO   EQ   W_ZFREQNO.

  L_SEQ = 1.

*>> [수입] Master L/C Seg 2.
  SELECT SINGLE * FROM ZTMLCSG2
         WHERE    ZFREQNO   EQ   W_ZFREQNO.

  SELECT SINGLE * FROM ZTIMIMGTX
         WHERE    BUKRS    EQ    ZTREQHD-BUKRS.
*-----------------------------------------------------------------------
* FLAT-FILE RECORD CREATE
*-----------------------------------------------------------------------
* 001 문서명.
  CLEAR W_EDI_RECORD.

  PERFORM P3000_DOCNAME_MAKE USING    'APP707'
                             CHANGING W_EDI_RECORD.

* 002 인터페이스 일자.
  PERFORM P3000_DOCDATE_MAKE USING SY-DATUM
                             CHANGING W_EDI_RECORD.

* 003 데이터 처리형태.
  BUFFER_POINTER = STRLEN( W_EDI_RECORD ).
  PARA_LENG = 1.
  MOVE 'A' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
*  IF ZTREQST-ZFDOCNO IS INITIAL.
*    MOVE 'I' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
*  ELSE.
*    MOVE 'U' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
*  ENDIF.
  ADD PARA_LENG TO BUFFER_POINTER.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 004 Member ID.
  PARA_LENG = 4.
  MOVE '0001' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ADD PARA_LENG TO BUFFER_POINTER.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 005 관리번호.
  PARA_LENG = STRLEN( W_ZFDHENO ).
  MOVE W_ZFDHENO TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ADD PARA_LENG TO BUFFER_POINTER.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 006 Sub 관리번호.
  PARA_LENG = STRLEN( L_SEQ ).
  MOVE L_SEQ TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ADD PARA_LENG TO BUFFER_POINTER.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 007 Number of Amendment.
  PARA_LENG       =  STRLEN( L_SEQ ).
  MOVE L_SEQ TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ADD PARA_LENG TO BUFFER_POINTER.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 008 사용자 ID.
  PARA_LENG = STRLEN( SY-UNAME(10) ).
  MOVE SY-UNAME(10) TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ADD PARA_LENG TO BUFFER_POINTER.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 009 문서기능.--> 로직이 필요!!

  PARA_LENG = 1.
  MOVE '9' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
*  MOVE ZTMLCAMHD-ZFEDFN TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ADD PARA_LENG TO BUFFER_POINTER.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 010 응답유형. --> 로직이 필요.
  PARA_LENG = 2.
  MOVE 'AB' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ADD PARA_LENG TO BUFFER_POINTER.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 011 등록일자.
  PARA_LENG = 8.
  MOVE SY-DATUM TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ADD PARA_LENG TO BUFFER_POINTER.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 012 신청일자.
  IF NOT ZTREQST-ZFAPPDT IS INITIAL.
    PARA_LENG = 8.
    MOVE ZTREQST-ZFAPPDT TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ELSE.
    MESSAGE E996 WITH W_ZFDHENO '신청일(개설예정일)'.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 013 개설방법.
  IF NOT ZTMLCAMHD-ZFOPME IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCAMHD-ZFOPME ).
    MOVE ZTMLCAMHD-ZFOPME TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ELSE.
    MESSAGE E996 WITH W_ZFDHENO '개설방법'.
  ENDIF.
  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 014 개설은행코드.
  IF NOT ZTMLCHD-ZFOPBNCD IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCHD-ZFOPBNCD ).
    MOVE ZTMLCHD-ZFOPBNCD TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ELSE.
    MESSAGE E996 WITH W_ZFDHENO '개설은행코드'.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 015 개설의뢰은행2.
  IF NOT ZTMLCHD-ZFOBNM(35) IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCHD-ZFOBNM(35) ).
    MOVE ZTMLCHD-ZFOBNM(35)
      TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ELSE.
    MESSAGE E996 WITH W_ZFDHENO '개설의뢰은행명'.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 016 개설의뢰은행3.
  IF NOT ZTMLCHD-ZFOBNM+35(35) IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCHD-ZFOBNM+35(35) ).
    MOVE ZTMLCHD-ZFOBNM+35(35)
      TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 017 개설의뢰은행4.
  IF NOT ZTMLCHD-ZFOBBR(35) IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCHD-ZFOBBR(35) ).
    MOVE ZTMLCHD-ZFOBBR(35)
      TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 018 개설의뢰은행5.
  IF NOT ZTMLCHD-ZFOBBR+35(35) IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCHD-ZFOBBR+35(35) ).
    MOVE ZTMLCHD-ZFOBBR+35(35)
      TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 019 Telephone Number.
  IF NOT ZTMLCHD-ZFOBPH IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCHD-ZFOBPH ).
    MOVE ZTMLCHD-ZFOBPH
      TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 020 통지은행1. → MATRIX2B 내부관리용 FIELD.
  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 021 통지은행2.
  IF NOT ZTMLCHD-ZFABNM(35) IS INITIAL.
    PARA_LENG  = STRLEN( ZTMLCHD-ZFABNM(35) ).
    MOVE ZTMLCHD-ZFABNM(35) TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ELSE.
    MESSAGE E996 WITH W_ZFDHENO '통지은행명'.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 022 통지은행3.
  IF NOT ZTMLCHD-ZFABNM+35(35) IS INITIAL.
    PARA_LENG  =  STRLEN( ZTMLCHD-ZFABNM+35(35) ).
    MOVE ZTMLCHD-ZFABNM+35(35)
      TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 023 통지은행4.
  IF NOT ZTMLCHD-ZFABBR(35) IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCHD-ZFABBR(35) ).
    MOVE ZTMLCHD-ZFABBR(35)
      TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 024 통지은행5.
  IF NOT ZTMLCHD-ZFABBR+35(35) IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCHD-ZFABBR+35(35) ).
    MOVE ZTMLCHD-ZFABBR+35(35)
      TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 025 신용공여. --> 무엇을 보내냐? → 보내지 말자..
  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 026 기타정보 1.
  IF NOT ZTMLCAMHD-ZFETC1 IS INITIAL.
    PARA_LENG = 35.
    MOVE ZTMLCAMHD-ZFETC1(35) TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 027 기타정보 2.
  IF NOT ZTMLCAMHD-ZFETC2 IS INITIAL.
    PARA_LENG = 70.
    MOVE ZTMLCAMHD-ZFETC2 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 028 기타정보 3.
  IF NOT ZTMLCAMHD-ZFETC3 IS INITIAL.
    PARA_LENG = 70.
    MOVE ZTMLCAMHD-ZFETC3 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 029 기타정보 4.
  IF NOT ZTMLCAMHD-ZFETC4 IS INITIAL.
    PARA_LENG = 70.
    MOVE ZTMLCAMHD-ZFETC4 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 030 기타정보 5.
  IF NOT ZTMLCAMHD-ZFETC5 IS INITIAL.
    PARA_LENG = 70.
    MOVE ZTMLCAMHD-ZFETC5 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 031 L/C No.
  IF NOT ZTREQHD-ZFOPNNO IS INITIAL.
    PARA_LENG = STRLEN( ZTREQHD-ZFOPNNO ).
    MOVE ZTREQHD-ZFOPNNO TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ELSE.
    MESSAGE E996 WITH W_ZFDHENO 'L/C No.'.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 032 통지일자. → 잘 이해가 안가는 부분.
  PARA_LENG = 8.
  SELECT SINGLE ZFOPNDT INTO W_OPNDT FROM   ZTREQST
         WHERE ZFREQNO EQ W_ZFREQNO
         AND   ZFAMDNO EQ '00000'.

  MOVE W_OPNDT TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ADD PARA_LENG TO BUFFER_POINTER.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 033 유효기일.
  IF NOT ZTMLCAMHD-ZFNEXDT IS INITIAL.
    PARA_LENG = 8.
    MOVE ZTMLCAMHD-ZFNEXDT
      TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 034 문서현황.
  PARA_LENG = 1.
  MOVE '1' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ADD PARA_LENG TO BUFFER_POINTER.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 036 수발신인식별자 → 신규삽입구문..
  IF NOT W_BAHNS IS INITIAL.
    PARA_LENG = STRLEN( W_BAHNS ).
    MOVE W_BAHNS TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ELSE.
    MESSAGE E996 WITH W_ZFDHENO '개설은행 수발신인식별자'.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 037 Applicant1.
  IF NOT ZTMLCSG2-ZFAPPNM IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCSG2-ZFAPPNM ).
    MOVE ZTMLCSG2-ZFAPPNM TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ELSE.
    MESSAGE E996 WITH W_ZFDHENO '개설의뢰인 상호'.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 038 Applicant2.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 039 Applicant3.
  IF NOT ZTMLCSG2-ZFELEAD1 IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCSG2-ZFELEAD1 ).
    MOVE ZTMLCSG2-ZFELEAD1
      TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 040 Applicant4.
  IF NOT ZTMLCSG2-ZFELEAD2 IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCSG2-ZFELEAD2 ).
    MOVE ZTMLCSG2-ZFELEAD2
      TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 041 Telephone Number.
  IF NOT ZTMLCSG2-ZFTELNO IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCSG2-ZFTELNO ).
    MOVE ZTMLCSG2-ZFTELNO TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 042 Beneficiary Code --> MATRIX2B 내부관리용..
  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 043 Beneficiary1.
  IF NOT ZTMLCAMHD-ZFBENI1 IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCAMHD-ZFBENI1 ).
    MOVE ZTMLCAMHD-ZFBENI1 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ELSE.
    MESSAGE E996 WITH W_ZFDHENO '수익자 상호'.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 044 Beneficiary2.
  IF NOT ZTMLCAMHD-ZFBENI2 IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCAMHD-ZFBENI2 ).
    MOVE ZTMLCAMHD-ZFBENI2 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 045 Beneficiary3.
  IF NOT ZTMLCAMHD-ZFBENI3 IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCAMHD-ZFBENI3 ).
    MOVE ZTMLCAMHD-ZFBENI3 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 046 Beneficiary4.
  IF NOT ZTMLCAMHD-ZFBENI4 IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCAMHD-ZFBENI4 ).
    MOVE ZTMLCAMHD-ZFBENI4 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 047 계좌번호.
  IF NOT ZTMLCAMHD-ZFBENIA IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCAMHD-ZFBENIA ).
    MOVE ZTMLCAMHD-ZFBENIA TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 048 Increase of Documentary Credit(Currency).
  CASE ZTMLCAMHD-ZFIDCD.
    WHEN '+'.
      PERFORM P3000_AMT_MAKE USING    ZTMLCAMHD-ZFIDAM
                                      ZTMLCAMHD-WAERS
                             CHANGING W_EDI_RECORD.
      PARA_LENG = 2.
      MOVE '||' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
      ADD PARA_LENG TO BUFFER_POINTER.
    WHEN '-'.
      PARA_LENG = 2.
      MOVE '||' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
      ADD PARA_LENG TO BUFFER_POINTER.
      PERFORM P3000_AMT_MAKE USING    ZTMLCAMHD-ZFIDAM
                                      ZTMLCAMHD-WAERS
                             CHANGING W_EDI_RECORD.
    WHEN OTHERS.
      PARA_LENG = 4.
      MOVE '||||' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
      ADD PARA_LENG TO BUFFER_POINTER.
  ENDCASE.

* 052 ~ 053 New Documentary Credit Amount(Currency).
  IF NOT ZTMLCAMHD-ZFNDAMT IS INITIAL.
    PERFORM P3000_AMT_MAKE     USING ZTMLCAMHD-ZFNDAMT
                                     ZTMLCAMHD-WAERS
                            CHANGING W_EDI_RECORD.
  ELSE.
    PARA_LENG = 2.
    MOVE '||' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

* 054 ~ 055 과부족 허용율.
  CASE ZTMLCAMHD-ZFALCQ.
    WHEN 'T'.
                                                            " 047
      WRITE ZTMLCAMHD-ZFALCP TO W_TEXT02.
      PARA_LENG = STRLEN( W_TEXT02 ).
      MOVE ZTMLCAMHD-ZFALCP TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
      ADD PARA_LENG TO BUFFER_POINTER.

      PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

                                                            " 048
      WRITE ZTMLCAMHD-ZFALCM TO W_TEXT02.
      PARA_LENG = STRLEN( W_TEXT02 ).
      MOVE ZTMLCAMHD-ZFALCM TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
      ADD PARA_LENG TO BUFFER_POINTER.

      PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* when 'X' or '2AB' or '2AA'.
    WHEN OTHERS.
      PARA_LENG = 2.
      MOVE '||' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
      ADD PARA_LENG TO BUFFER_POINTER.
  ENDCASE.

* 056 Maximum Credit Amount.
  IF NOT ZTMLCAMHD-ZFALCQ IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCAMHD-ZFALCQ ).
    MOVE ZTMLCAMHD-ZFALCQ TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 057 Additional Amounts Covered1.
  IF NOT ZTMLCAMHD-ZFNAMT1 IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCAMHD-ZFNAMT1 ).
    MOVE ZTMLCAMHD-ZFNAMT1 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 058 Additional Amounts Covered2.
  IF NOT ZTMLCAMHD-ZFNAMT2 IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCAMHD-ZFNAMT2 ).
    MOVE ZTMLCAMHD-ZFNAMT2 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 059 Additional Amounts Covered3.
  IF NOT ZTMLCAMHD-ZFNAMT3 IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCAMHD-ZFNAMT3 ).
    MOVE ZTMLCAMHD-ZFNAMT3 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 060 Additional Amounts Covered4.
  IF NOT ZTMLCAMHD-ZFNAMT4 IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCAMHD-ZFNAMT4 ).
    MOVE ZTMLCAMHD-ZFNAMT4 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 061 Loading on Board.
  IF NOT ZTMLCAMHD-ZFNSPRT IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCAMHD-ZFNSPRT ).
    MOVE ZTMLCAMHD-ZFNSPRT TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 062 도착항.
  IF NOT ZTMLCAMHD-ZFNAPRT IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCAMHD-ZFNAPRT ).
    MOVE ZTMLCAMHD-ZFNAPRT TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 063 Lastest Date of Shipment.
  IF NOT ZTMLCAMHD-ZFNLTSD IS INITIAL.
    PARA_LENG = 8.
    MOVE ZTMLCAMHD-ZFNLTSD TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 064 Shipment Period1.
  IF NOT ZTMLCAMHD-ZFNSHPR1 IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCAMHD-ZFNSHPR1 ).
    MOVE ZTMLCAMHD-ZFNSHPR1 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 065 Shipment Period2.
  IF NOT ZTMLCAMHD-ZFNSHPR2 IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCAMHD-ZFNSHPR2 ).
    MOVE ZTMLCAMHD-ZFNSHPR2 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.
  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 066 Shipment Period3.
  IF NOT ZTMLCAMHD-ZFNSHPR3 IS INITIAL.
    PARA_LENG = STRLEN( ZTMLCAMHD-ZFNSHPR3 ).
    MOVE ZTMLCAMHD-ZFNSHPR3 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 067 Shipment Period 4 ~ 069 Shipment Period 6 Delimeter..
  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.
  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.
  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 070 Narrative.
  CLEAR W_IT_INDEX.
  LOOP AT IT_ZSMLCAMNARR.
    IF NOT IT_ZSMLCAMNARR-ZFNARR IS INITIAL.
      ADD 1 TO W_IT_INDEX.
    ENDIF.
  ENDLOOP.

* 071 Narrative 입력여부.
  IF NOT W_IT_INDEX IS INITIAL.
    WRITE W_IT_INDEX TO W_TEXT02.
    PARA_LENG = STRLEN( W_TEXT02 ).
    MOVE W_TEXT02 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.

    PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

    IF W_IT_INDEX LE 35.
      W_LINE = 1.
      DO W_IT_INDEX TIMES.
        W_INT = ( W_LINE - 1 ) * 50.
        READ TABLE IT_ZSMLCAMNARR INDEX W_LINE.
        MOVE IT_ZSMLCAMNARR-ZFNARR TO L_TEXT1750+W_INT(50).
        ADD 1 TO W_LINE.
      ENDDO.
    ENDIF.
    PARA_LENG = W_IT_INDEX * 50.
    MOVE L_TEXT1750 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.

    PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.
  ELSE.
    PARA_LENG = 2.
    MOVE '0|' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.

    PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

  ENDIF.

* 072 신청업체.
  IF NOT ZTIMIMGTX-ZFAPPNM IS INITIAL.
    PARA_LENG = STRLEN( ZTIMIMGTX-ZFAPPNM ).
    MOVE ZTIMIMGTX-ZFAPPNM TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ELSE.
    MESSAGE E996 WITH W_ZFDHENO 'Applicant 상호/성명'.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 073 명의인.
  IF NOT ZTIMIMGTX-ZFREPRE IS INITIAL.
    PARA_LENG = STRLEN( ZTIMIMGTX-ZFREPRE ).
    MOVE ZTIMIMGTX-ZFREPRE TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ELSE.
    MESSAGE E996 WITH W_ZFDHENO 'Applicant 전자서명 대표자'.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 074 식별부호.
  PARA_LENG = STRLEN( ZTIMIMGTX-ZFELEID(10) ).
  MOVE ZTIMIMGTX-ZFELEID(10) TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ADD PARA_LENG TO BUFFER_POINTER.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 075 주소.
  PARA_LENG = STRLEN( ZTIMIMGTX-ZFAPPAD1 ).
  MOVE ZTIMIMGTX-ZFAPPAD1 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ADD PARA_LENG TO BUFFER_POINTER.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 076 주소.
  IF NOT ZTIMIMGTX-ZFAPPAD2 IS INITIAL.
    PARA_LENG = STRLEN( ZTIMIMGTX-ZFAPPAD2 ).
    MOVE ZTIMIMGTX-ZFAPPAD2 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PARA_LENG = 7.
  MOVE '@@@}}~~' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ADD PARA_LENG TO BUFFER_POINTER.

ENDFUNCTION.
