FUNCTION ZIM_APPPUR_EDI_SEND.
*"----------------------------------------------------------------------
*"*"Local interface:
*"  IMPORTING
*"     VALUE(W_ZFREQNO) LIKE  ZTREQHD-ZFREQNO
*"     VALUE(W_ZFDHENO) LIKE  ZTDHF1-ZFDHENO
*"     VALUE(W_ZFAMDNO) LIKE  ZTREQST-ZFAMDNO
*"  EXCEPTIONS
*"      DB_ERROR
*"----------------------------------------------------------------------
   CALL FUNCTION 'ZIM_GET_PURCH_DOC_DATA'
        EXPORTING
              ZFREQNO           =       W_ZFREQNO
              ZFAMDNO           =       W_ZFAMDNO
        IMPORTING
              W_ZTPUR           =       ZTPUR
        TABLES
              IT_ZSPURSG1       =       IT_ZSPURSG1
              IT_ZSPURSG1G      =       IT_ZSPURSG1G
              IT_ZSPURSG4       =       IT_ZSPURSG4
              IT_ZSPURSG1_ORG   =       IT_ZSPURSG1_ORG
              IT_ZSPURSG1G_ORG  =       IT_ZSPURSG1G_ORG
              IT_ZSPURSG4_ORG   =       IT_ZSPURSG4_ORG
        EXCEPTIONS
              NOT_FOUND         =       4
              NOT_INPUT         =       8.

     CASE SY-SUBRC.
        WHEN 4.
           MESSAGE E054 WITH ZTREQHD-ZFREQNO ZTREQST-ZFAMDNO.
        WHEN 8.
           MESSAGE E019.
     ENDCASE.


*-----------------------------------------------------------------------
* internal Table Append
*-----------------------------------------------------------------------
   REFRESH : IT_ZTDDF1.
   CLEAR : IT_ZTDDF1.
   IT_ZTDDF1-ZFDDENO = W_ZFDHENO.
*>>> 전자문서 시작
   IT_ZTDDF1-ZFDDFDA = '{10'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '2BL'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = W_ZFDHENO.        APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTPUR-ZFEDFN.     APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ''.               APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}10'.            APPEND IT_ZTDDF1.
*>>> 신청인
   IT_ZTDDF1-ZFDDFDA = '{11'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = 'MS'.             APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTPUR-ZFAPPNM1.   APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTPUR-ZFAPPNM2.   APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTPUR-ZFAPPNM3.   APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTPUR-ZFAPPAD1.   APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTPUR-ZFAPPAD2.   APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTPUR-ZFAPPAD3.   APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}11'.            APPEND IT_ZTDDF1.
*>>> 공급자상호
   IT_ZTDDF1-ZFDDFDA = '{11'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = 'SU'.             APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTPUR-ZFVENNM1.   APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTPUR-ZFVENNM2.   APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTPUR-ZFVENID.    APPEND IT_ZTDDF1.  " 식별자
   IT_ZTDDF1-ZFDDFDA = ZTPUR-ZFVENAD1.   APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTPUR-ZFVENAD2.   APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTPUR-ZFVENAD3.   APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}11'.            APPEND IT_ZTDDF1.
*>>> 공급물품명세구분코드
   IT_ZTDDF1-ZFDDFDA = '{12'.                APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '1'.                  APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTPUR-ZFGDCD.         APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}12'.            APPEND IT_ZTDDF1.
*>>> SEGMENT GROUP 1
   LOOP AT IT_ZSPURSG1.
      W_TABIX = SY-TABIX.
* 일련품목번호
      IT_ZTDDF1-ZFDDFDA = '{13'.            APPEND IT_ZTDDF1.
      WRITE : W_TABIX TO W_TEXT_AMOUNT.
      PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.
      IT_ZTDDF1-ZFDDFDA = W_TEXT_AMOUNT.     APPEND IT_ZTDDF1.
* HS 부호
      IF NOT IT_ZSPURSG1-STAWN IS INITIAL.
         IT_ZTDDF1-ZFDDFDA = '{20'.             APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '1'.               APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = IT_ZSPURSG1-STAWN. APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '}20'.             APPEND IT_ZTDDF1.
      ENDIF.
* HS별 품목명
      IF NOT IT_ZSPURSG1-ZFHSDESC IS INITIAL.
         IT_ZTDDF1-ZFDDFDA = '{21'.                APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '1AA'.                APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = IT_ZSPURSG1-ZFHSDESC. APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '}21'.                APPEND IT_ZTDDF1.
      ENDIF.
* 수량/단위
      IF NOT IT_ZSPURSG1-MENGE IS INITIAL.
         WRITE IT_ZSPURSG1-MENGE    TO      W_TEXT_AMOUNT
                            UNIT            IT_ZSPURSG1-MEINS.

         PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.
         IT_ZTDDF1-ZFDDFDA = '{22'.             APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '1'.               APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = W_TEXT_AMOUNT.     APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = IT_ZSPURSG1-MEINS. APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '}22'.             APPEND IT_ZTDDF1.
      ENDIF.
* 대표품목명
      IF NOT IT_ZSPURSG1-ZFGODS1 IS INITIAL OR
         NOT IT_ZSPURSG1-ZFGODS2 IS INITIAL OR
         NOT IT_ZSPURSG1-ZFGODS3 IS INITIAL OR
         NOT IT_ZSPURSG1-ZFGODS4 IS INITIAL OR
         NOT IT_ZSPURSG1-ZFGODS5 IS INITIAL.
         IT_ZTDDF1-ZFDDFDA = '{23'.                APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = 'AAA'.                APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = IT_ZSPURSG1-ZFGODS1.  APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = IT_ZSPURSG1-ZFGODS2.  APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = IT_ZSPURSG1-ZFGODS3.  APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = IT_ZSPURSG1-ZFGODS4.  APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = IT_ZSPURSG1-ZFGODS5.  APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '}23'.                APPEND IT_ZTDDF1.
      ENDIF.
* 금액
      IF NOT IT_ZSPURSG1-ZFGOAMT IS INITIAL.
         WRITE IT_ZSPURSG1-ZFGOAMT   TO      W_TEXT_AMOUNT
                             CURRENCY        IT_ZSPURSG1-WAERS.
         PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.
         IT_ZTDDF1-ZFDDFDA = '{24'.             APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '203'.             APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = W_TEXT_AMOUNT.     APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = IT_ZSPURSG1-WAERS. APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '}24'.             APPEND IT_ZTDDF1.
      ENDIF.
* 금액 ( USD 환산 금액 )
      IF NOT IT_ZSPURSG1-ZFGOAMT IS INITIAL AND
             IT_ZSPURSG1-WAERS NE 'USD'.
         WRITE IT_ZSPURSG1-ZFGOAMTU  TO      W_TEXT_AMOUNT
                             CURRENCY        IT_ZSPURSG1-ZFUSD.
         PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.
         IT_ZTDDF1-ZFDDFDA = '{24'.             APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '2AD'.             APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = W_TEXT_AMOUNT.     APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = IT_ZSPURSG1-ZFUSD. APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '}24'.             APPEND IT_ZTDDF1.
      ENDIF.
* 단가 ( USD 환산 금액 )
      IF NOT IT_ZSPURSG1-ZFGOAMT IS INITIAL AND
             IT_ZSPURSG1-WAERS NE 'USD'.
         WRITE IT_ZSPURSG1-ZFNETPRU  TO      W_TEXT_AMOUNT
                             CURRENCY        IT_ZSPURSG1-ZFUSD.
         PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.
         IT_ZTDDF1-ZFDDFDA = '{24'.             APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '146'.             APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = W_TEXT_AMOUNT.     APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = IT_ZSPURSG1-ZFUSD. APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '}24'.             APPEND IT_ZTDDF1.
      ENDIF.
* 단가
      IF NOT IT_ZSPURSG1-NETPR   IS INITIAL.
         WRITE IT_ZSPURSG1-NETPR     TO      W_TEXT_AMOUNT
                             CURRENCY        IT_ZSPURSG1-WAERS.
         PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.
         IT_ZTDDF1-ZFDDFDA = '{25'.             APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = 'CAL'.             APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = W_TEXT_AMOUNT.     APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = 'PE'.              APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = 'CUP'.             APPEND IT_ZTDDF1.
         WRITE IT_ZSPURSG1-PEINH    TO      W_TEXT_AMOUNT
                            UNIT            IT_ZSPURSG1-BPRME.
         PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.
         IT_ZTDDF1-ZFDDFDA = W_TEXT_AMOUNT.     APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = IT_ZSPURSG1-BPRME. APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '}25'.             APPEND IT_ZTDDF1.
      ENDIF.
* 할인 구분
      IF NOT IT_ZSPURSG1-ZFDCD IS INITIAL.
         IT_ZTDDF1-ZFDDFDA = '{26'.             APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '2AZ'.             APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = IT_ZSPURSG1-ZFDCD. APPEND IT_ZTDDF1.
         WRITE IT_ZSPURSG1-ZFDAM     TO      W_TEXT_AMOUNT
                             CURRENCY        IT_ZSPURSG1-ZFDAMC.
         PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.
*>>>>>>>>>>> 변동금액
         IT_ZTDDF1-ZFDDFDA = '{30'.              APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '8'.                APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = W_TEXT_AMOUNT.      APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = IT_ZSPURSG1-ZFDAMC. APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '}30'.              APPEND IT_ZTDDF1.
*>>>>>>>>>>> 변동금액( USD 환산 금액 )
         IF IT_ZSPURSG1-ZFDAMC NE 'USD'.
            WRITE IT_ZSPURSG1-ZFDAMU    TO      W_TEXT_AMOUNT
                                CURRENCY        IT_ZSPURSG1-ZFUSD.
            PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.
            IT_ZTDDF1-ZFDDFDA = '{30'.              APPEND IT_ZTDDF1.
            IT_ZTDDF1-ZFDDFDA = '2AD'.              APPEND IT_ZTDDF1.
            IT_ZTDDF1-ZFDDFDA = W_TEXT_AMOUNT.      APPEND IT_ZTDDF1.
            IT_ZTDDF1-ZFDDFDA = IT_ZSPURSG1-ZFDAMC. APPEND IT_ZTDDF1.
            IT_ZTDDF1-ZFDDFDA = '}30'.              APPEND IT_ZTDDF1.
         ENDIF.
         IT_ZTDDF1-ZFDDFDA = '}26'.             APPEND IT_ZTDDF1.
      ENDIF.
      IT_ZTDDF1-ZFDDFDA = '}13'.            APPEND IT_ZTDDF1.
   ENDLOOP.

*>>> 총수량
   WRITE ZTPUR-ZFTOCN         TO      W_TEXT_AMOUNT
                      UNIT            ZTPUR-ZFTOCNM.
   PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.

   IT_ZTDDF1-ZFDDFDA = '{14'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '1AA'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = W_TEXT_AMOUNT.    APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTPUR-ZFTOCNM.    APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}14'.            APPEND IT_ZTDDF1.
*>>> 총금액
   WRITE ZTPUR-ZFTOAM          TO      W_TEXT_AMOUNT
                       CURRENCY        ZTPUR-ZFTOAMC.
   PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.
   IT_ZTDDF1-ZFDDFDA = '{15'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '128'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = W_TEXT_AMOUNT.    APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTPUR-ZFTOAMC.    APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}15'.            APPEND IT_ZTDDF1.
*>>> 총금액( USD 환산 금액 )
   IF ZTPUR-ZFTOAMC NE 'USD'.
      WRITE ZTPUR-ZFTOAMU         TO      W_TEXT_AMOUNT
                          CURRENCY        ZTPUR-ZFUSD.
      PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.
      IT_ZTDDF1-ZFDDFDA = '{15'.            APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '2AD'.            APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = W_TEXT_AMOUNT.    APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTPUR-ZFUSD.      APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '}15'.            APPEND IT_ZTDDF1.
   ENDIF.
* 할인 구분
   IF NOT ZTPUR-ZFTDCD IS INITIAL.
      IT_ZTDDF1-ZFDDFDA = '{16'.             APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '2AZ'.             APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTPUR-ZFTDCD.      APPEND IT_ZTDDF1.
      WRITE ZTPUR-ZFTDAM          TO      W_TEXT_AMOUNT
                          CURRENCY        ZTPUR-ZFTDAMC.
      PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.
*>>>>>>>>>>> 변동금액
      IT_ZTDDF1-ZFDDFDA = '{27'.              APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '131'.              APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = W_TEXT_AMOUNT.      APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTPUR-ZFTDAMC.      APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '}27'.              APPEND IT_ZTDDF1.
*>>>>>>>>>>> 변동금액( USD 환산 금액 )
      IF ZTPUR-ZFTDAMC   NE 'USD'.
         WRITE ZTPUR-ZFTDAMU         TO      W_TEXT_AMOUNT
                             CURRENCY        ZTPUR-ZFUSD.
         PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.
         IT_ZTDDF1-ZFDDFDA = '{27'.              APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '2AD'.              APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = W_TEXT_AMOUNT.      APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = ZTPUR-ZFUSD.        APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '}27'.              APPEND IT_ZTDDF1.
      ENDIF.
      IT_ZTDDF1-ZFDDFDA = '}16'.             APPEND IT_ZTDDF1.
   ENDIF.
*>>> 근거서류
   LOOP AT IT_ZSPURSG4.
      IT_ZTDDF1-ZFDDFDA = '{17'.                APPEND IT_ZTDDF1.
* 근거서류
      IT_ZTDDF1-ZFDDFDA = IT_ZSPURSG4-ZFSDOC.   APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = IT_ZSPURSG4-ZFSDNO.   APPEND IT_ZTDDF1.
* H/S CODE
      IF NOT IT_ZSPURSG4-STAWN IS INITIAL.
         IT_ZTDDF1-ZFDDFDA = '{28'.                APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '1'.                  APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = IT_ZSPURSG4-STAWN.    APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '}28'.                APPEND IT_ZTDDF1.
      ENDIF.
* 품목명
      IF NOT IT_ZSPURSG4-ZFGODS1 IS INITIAL OR
         NOT IT_ZSPURSG4-ZFGODS2 IS INITIAL OR
         NOT IT_ZSPURSG4-ZFGODS3 IS INITIAL OR
         NOT IT_ZSPURSG4-ZFGODS4 IS INITIAL OR
         NOT IT_ZSPURSG4-ZFGODS5 IS INITIAL.
         IT_ZTDDF1-ZFDDFDA = '{29'.                APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '1AA'.                APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = IT_ZSPURSG4-ZFGODS1.  APPEND IT_ZTDDF1.
*        IT_ZTDDF1-ZFDDFDA = IT_ZSPURSG4-ZFGODS2.  APPEND IT_ZTDDF1.
*        IT_ZTDDF1-ZFDDFDA = IT_ZSPURSG4-ZFGODS3.  APPEND IT_ZTDDF1.
*        IT_ZTDDF1-ZFDDFDA = IT_ZSPURSG4-ZFGODS4.  APPEND IT_ZTDDF1.
*        IT_ZTDDF1-ZFDDFDA = IT_ZSPURSG4-ZFGODS5.  APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '}29'.                APPEND IT_ZTDDF1.
      ENDIF.
* >>>> 결제금액
      WRITE IT_ZSPURSG4-ZFGOAMT      TO      W_TEXT_AMOUNT
                             CURRENCY        IT_ZSPURSG4-WAERS.
      PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.
      IT_ZTDDF1-ZFDDFDA = '{2A'.                APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '212'.                APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = W_TEXT_AMOUNT.        APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = IT_ZSPURSG4-WAERS.    APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '}2A'.                APPEND IT_ZTDDF1.
* >>>> 유효기간
      IF NOT IT_ZSPURSG4-ZFEXDT IS INITIAL.
         IT_ZTDDF1-ZFDDFDA = '{2B'.                APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '36'.                 APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = IT_ZSPURSG4-ZFEXDT+2. APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '101'.                APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '}2B'.                APPEND IT_ZTDDF1.
      ENDIF.
* >>>> 선적일자
      IF NOT IT_ZSPURSG4-ZFSPDT IS INITIAL.
         IT_ZTDDF1-ZFDDFDA = '{2B'.                APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '38'.                 APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = IT_ZSPURSG4-ZFSPDT+2. APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '101'.                APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '}2B'.                APPEND IT_ZTDDF1.
      ENDIF.
      IT_ZTDDF1-ZFDDFDA = '}17'.                APPEND IT_ZTDDF1.
   ENDLOOP.
* 전자서명
   IT_ZTDDF1-ZFDDFDA = '{18'.                APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = 'AX'.                 APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTPUR-ZFELEAD1.       APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTPUR-ZFELEAD2.       APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTPUR-ZFELEID.        APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}18'.                APPEND IT_ZTDDF1.

* 승인은행(부)명 코드
   IT_ZTDDF1-ZFDDFDA = '{19'.                APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = 'B1'.                 APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTPUR-ZFACBNCD.       APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '25'.                 APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = 'BOK'.                APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTPUR-ZFACNM.         APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTPUR-ZFACBR.         APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}19'.                APPEND IT_ZTDDF1.

* ITEM INSERT
   CALL FUNCTION 'ZIM_EDI_FLAT_ITEM_INSERT'
        EXPORTING
              W_ZFDHENO         =        W_ZFDHENO
        TABLES
              IT_ZTDDF1         =        IT_ZTDDF1
        EXCEPTIONS
              DB_ERROR         =         4.

   IF SY-SUBRC NE 0.
      MESSAGE E118 WITH W_ZFDHENO.
   ENDIF.

ENDFUNCTION.
