FUNCTION ZIM_GET_IDR_DOCUMENT.
*"----------------------------------------------------------------------
*"*"Local interface:
*"  IMPORTING
*"     VALUE(ZFBLNO) LIKE  ZTIDR-ZFBLNO
*"     REFERENCE(ZFCLSEQ) LIKE  ZTIDR-ZFCLSEQ
*"  EXPORTING
*"     VALUE(W_ZTIDR) LIKE  ZTIDR STRUCTURE  ZTIDR
*"  TABLES
*"      IT_ZSIDRHS STRUCTURE  ZSIDRHS
*"      IT_ZSIDRHS_ORG STRUCTURE  ZSIDRHS
*"      IT_ZSIDRHSD STRUCTURE  ZSIDRHSD
*"      IT_ZSIDRHSD_ORG STRUCTURE  ZSIDRHSD
*"      IT_ZSIDRHSL STRUCTURE  ZSIDRHSL
*"      IT_ZSIDRHSL_ORG STRUCTURE  ZSIDRHSL
*"  EXCEPTIONS
*"      NOT_FOUND
*"      NOT_INPUT
*"----------------------------------------------------------------------
DATA : WL_VIA(1)   TYPE   C.

REFRESH : IT_ZSIDRHS,       IT_ZSIDRHSD,    IT_ZSIDRHSL, IT_ZSIDRHS_ORG,
          IT_ZSIDRHSD_ORG,  IT_ZSIDRHSL_ORG.

  CLEAR : W_ZTIDR.

  IF ZFBLNO IS INITIAL OR ZFCLSEQ IS INITIAL.
     RAISE NOT_INPUT.
  ENDIF.

  SELECT SINGLE *        INTO W_ZTIDR FROM ZTIDR
         WHERE  ZFBLNO   EQ   ZFBLNO
         AND    ZFCLSEQ  EQ   ZFCLSEQ.

  IF SY-SUBRC NE 0.    RAISE NOT_FOUND.   ENDIF.

*>> 란 사항 SELECT!
  SELECT *  INTO CORRESPONDING FIELDS OF TABLE IT_ZSIDRHS
  FROM   ZTIDRHS
  WHERE  ZFBLNO    EQ   ZFBLNO
  AND    ZFCLSEQ   EQ   ZFCLSEQ.
  IT_ZSIDRHS_ORG[] = IT_ZSIDRHS[].

*>> 행 사항 SELECT!
  SELECT *   INTO CORRESPONDING FIELDS OF TABLE IT_ZSIDRHSD
  FROM   ZTIDRHSD
  WHERE  ZFBLNO     EQ   ZFBLNO
  AND    ZFCLSEQ    EQ   ZFCLSEQ.
  IT_ZSIDRHSD_ORG[] = IT_ZSIDRHSD_ORG[].

*>> 수입요건 사항 SELECT!
  SELECT * INTO CORRESPONDING FIELDS OF TABLE IT_ZSIDRHSL
  FROM   ZTIDRHSL
  WHERE  ZFBLNO      EQ   ZFBLNO
  AND    ZFCLSEQ     EQ   ZFCLSEQ.
  IT_ZSIDRHSL_ORG[] = IT_ZSIDRHSL[].

  SORT IT_ZSIDRHS   BY ZFBLNO ZFCLSEQ ZFCONO.
  SORT IT_ZSIDRHSD  BY ZFBLNO ZFCLSEQ ZFCONO ZFRONO.
  SORT IT_ZSIDRHSL  BY ZFBLNO ZFCLSEQ ZFCONO ZFCNDC ZFCNNO.

ENDFUNCTION.
