*&---------------------------------------------------------------------*
*&  Function Module 명: APPLOG EDI Send                                *
*&              작성자: 나신호 INFOLINK Ltd.                           *
*&              작성일: 2002.09.12                                     *
*&---------------------------------------------------------------------*
*&   DESC.     :
*&---------------------------------------------------------------------*
*& [변경내용]
*&---------------------------------------------------------------------*
FUNCTION ZIM_MAT_APPLOG_EDI_DOC.
*"----------------------------------------------------------------------
*"*"Local interface:
*"  IMPORTING
*"     REFERENCE(W_ZFBLNO) LIKE  ZTLG-ZFBLNO
*"     REFERENCE(W_ZFLGSEQ) LIKE  ZTLG-ZFLGSEQ
*"     REFERENCE(W_ZFDHENO) LIKE  ZTLG-ZFDOCNO
*"     REFERENCE(W_BAHNS) LIKE  LFA1-BAHNS
*"  EXPORTING
*"     REFERENCE(W_EDI_RECORD)
*"  EXCEPTIONS
*"      CREATE_ERROR
*"----------------------------------------------------------------------
  DATA : L_TEXT         LIKE     DD07T-DDTEXT,
         L_TEXT280(280) TYPE     C,
         L_TEXT350(350) TYPE     C,
         L_BOOLEAN      TYPE     C,
         L_TYPE(002)    TYPE     C,
         L_TYPE_TEMP    LIKE     L_TYPE,
         L_CODE(003)    TYPE     C,
         L_ZFDSOG1      LIKE     IT_ZSMLCSG7G-ZFDSOG1,
         L_ZFDSOG2      LIKE     IT_ZSMLCSG7G-ZFDSOG1,
         L_ZFDSOG3      LIKE     IT_ZSMLCSG7G-ZFDSOG1,
         L_ZFDSOG4      LIKE     IT_ZSMLCSG7G-ZFDSOG1,
         L_ZFDSOG5      LIKE     IT_ZSMLCSG7G-ZFDSOG1.
  DATA : W_STRLEN       TYPE     I.
  DATA : CR_LF          TYPE     X     VALUE   '0A'.
  DATA : L_LINENO       TYPE     I.
  DATA : L_TEXT35(35)     TYPE     C.

*> L/G Document Read.
  CALL FUNCTION 'ZIM_GET_LG_DOCUMENT'
       EXPORTING
            ZFBLNO         = W_ZFBLNO
            ZFLGSEQ        = W_ZFLGSEQ
       IMPORTING
            W_ZTLG         = ZTLG
       TABLES
            IT_ZSLGGOD     = IT_ZSLGGOD
            IT_ZSLGGOD_ORG = IT_ZSLGGOD_ORG
       EXCEPTIONS
            NOT_FOUND      = 4
            NOT_INPUT      = 8.

  CASE SY-SUBRC.
    WHEN 4.
      MESSAGE E053 WITH W_ZFBLNO.
    WHEN 8.
      MESSAGE E039.
  ENDCASE.

  SELECT SINGLE * FROM ZTIMIMGTX
         WHERE    BUKRS   EQ    ZTIMIMGTX-BUKRS.

*-----------------------------------------------------------------------
* FLAT-FILE RECORD CREATE
*-----------------------------------------------------------------------
* 001 문서명.
  CLEAR W_EDI_RECORD.

  PERFORM P3000_DOCNAME_MAKE USING    'APPLOG'
                             CHANGING W_EDI_RECORD.

* 002 인터페이스 일자.
  PERFORM P3000_DOCDATE_MAKE USING SY-DATUM
                             CHANGING W_EDI_RECORD.

* 003 데이터 처리형태.
  BUFFER_POINTER = STRLEN( W_EDI_RECORD ).
  PARA_LENG = 1.
  MOVE 'A' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ADD PARA_LENG TO BUFFER_POINTER.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 004 MEMBER_ID. → 사업장 코드.
  PARA_LENG = 4.
  MOVE '0001' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ADD PARA_LENG TO BUFFER_POINTER.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 005 관리번호.
  PARA_LENG = STRLEN( W_ZFDHENO ).
  MOVE W_ZFDHENO TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ADD PARA_LENG TO BUFFER_POINTER.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 006 사용자 ID.
  PARA_LENG = STRLEN( SY-UNAME(10) ).
  MOVE SY-UNAME(10) TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ADD PARA_LENG TO BUFFER_POINTER.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 007 등록일자.
  PARA_LENG = 8.
  MOVE SY-DATUM TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ADD PARA_LENG TO BUFFER_POINTER.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 008 운송유형.
  IF NOT ZTLG-ZFAOCDE IS INITIAL.
    PARA_LENG = STRLEN( ZTLG-ZFAOCDE ).
    MOVE ZTLG-ZFAOCDE TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ELSE.
    MESSAGE E996 WITH W_ZFDHENO '운송유형'.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 009 전자문서기능.
  PARA_LENG = 1.
  MOVE '9' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ADD PARA_LENG TO BUFFER_POINTER.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 010 응답유형.
  PARA_LENG = 2.
  MOVE 'AB' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ADD PARA_LENG TO BUFFER_POINTER.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 011 선박회사명 1.
  IF NOT ZTLG-ZFCARR1 IS INITIAL.
    PARA_LENG = STRLEN( ZTLG-ZFCARR1 ).
    MOVE ZTLG-ZFCARR1 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 012 선박회사명 2.
  IF NOT ZTLG-ZFCARR2 IS INITIAL.
    PARA_LENG = STRLEN( ZTLG-ZFCARR2 ).
    MOVE ZTLG-ZFCARR2 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 013 선박회사명 3.
  IF NOT ZTLG-ZFCARR3 IS INITIAL.
    PARA_LENG = STRLEN( ZTLG-ZFCARR3 ).
    MOVE ZTLG-ZFCARR3 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 014 송하인 1.
  IF NOT ZTLG-ZFGSNM1 IS INITIAL.
    PARA_LENG = STRLEN( ZTLG-ZFGSNM1 ).
    MOVE ZTLG-ZFGSNM1 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ELSE.
    MESSAGE E996 WITH W_ZFDHENO '송하인1'.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 015 송하인 2.
  IF NOT ZTLG-ZFGSNM2 IS INITIAL.
    PARA_LENG = STRLEN( ZTLG-ZFGSNM2 ).
    MOVE ZTLG-ZFGSNM2 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 016 송하인 3.
  IF NOT ZTLG-ZFGSNM3 IS INITIAL.
    PARA_LENG = STRLEN( ZTLG-ZFGSNM3 ).
    MOVE ZTLG-ZFGSNM3 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 017 신청자 1.
  IF NOT ZTLG-ZFELENM IS INITIAL.
    PARA_LENG = STRLEN( ZTLG-ZFELENM ).
    MOVE ZTLG-ZFELENM TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ELSE.
    MESSAGE E996 WITH W_ZFDHENO 'Applicant 전자서명 상호'.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 018 신청자 2.
  IF NOT ZTLG-ZFAPPAD1 IS INITIAL.
    PARA_LENG = STRLEN( ZTLG-ZFAPPAD1 ).
    MOVE ZTLG-ZFAPPAD1 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ELSE.
    MESSAGE E996 WITH W_ZFDHENO 'Applicant 주소 1'.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 019 신청자 3.
  IF NOT ZTLG-ZFELEID IS INITIAL.
    PARA_LENG = STRLEN( ZTLG-ZFELEID ).
    MOVE ZTLG-ZFELEID TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ELSE.
    MESSAGE E996 WITH W_ZFDHENO 'Applicant 식별자'.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 020 명의인 1.
  PARA_LENG = STRLEN( ZTLG-ZFELENM ).
  MOVE ZTLG-ZFELENM TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ADD PARA_LENG TO BUFFER_POINTER.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 021 명의인 2.
  PARA_LENG = STRLEN( ZTLG-ZFAPPAD1 ).
  MOVE ZTLG-ZFAPPAD1 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ADD PARA_LENG TO BUFFER_POINTER.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 022 명의인 3.
  PARA_LENG = STRLEN( ZTLG-ZFELEID ).
  MOVE ZTLG-ZFELEID TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ADD PARA_LENG TO BUFFER_POINTER.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 023 ~ 024 상업송장 금액 & 통화.
  IF NOT ZTLG-ZFCIAM IS INITIAL.
    PERFORM P3000_AMTR_MAKE USING    ZTLG-ZFCIAM
                                     ZTLG-ZFCIAMC
                            CHANGING W_EDI_RECORD.
  ELSE.
    MESSAGE E996 WITH W_ZFDHENO '상업송장 금액'.
  ENDIF.

* 025 신용장(계약서) 구분 코드.
  IF NOT ZTLG-ZFDOCTY IS INITIAL.
    PARA_LENG = STRLEN( ZTLG-ZFDOCTY ).
    MOVE ZTLG-ZFDOCTY TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ELSE.
    MESSAGE E996 WITH W_ZFDHENO '신용장(계약서) 구분 코드'.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 026 신용장(계약서) 구분 번호.
  IF NOT ZTLG-ZFDCNO IS INITIAL.
    PARA_LENG = STRLEN( ZTLG-ZFDCNO ).
    MOVE ZTLG-ZFDCNO TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ELSE.
    MESSAGE E996 WITH W_ZFDHENO '신용장(계약서) 구분 번호'.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 027 선하증권(항공화물운송장)구분 코드.
  IF NOT ZTLG-ZFBLTY IS INITIAL.
    PARA_LENG = STRLEN( ZTLG-ZFBLTY ).
    MOVE ZTLG-ZFBLTY TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ELSE.
    MESSAGE E996 WITH W_ZFDHENO '선하증권(항공화물운송장)구분 코드'.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 028 선하증권(항공화물운송장)구분.
  IF NOT ZTLG-ZFHBLNO IS INITIAL.
    PARA_LENG = STRLEN( ZTLG-ZFHBLNO ).
    MOVE ZTLG-ZFHBLNO TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ELSE.
    MESSAGE E996 WITH W_ZFDHENO '선하증권(항공화물운송장)구분'.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 029 선박명.
  IF NOT ZTLG-ZFCARNM IS INITIAL.
    PARA_LENG = STRLEN( ZTLG-ZFCARNM ).
    MOVE ZTLG-ZFCARNM TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ELSE.
    MESSAGE E996 WITH W_ZFDHENO '선박명'.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 030 항해번호.
  IF NOT ZTLG-ZFSSEQ IS INITIAL.
    PARA_LENG = STRLEN( ZTLG-ZFSSEQ ).
    MOVE ZTLG-ZFSSEQ TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ELSE.
    MESSAGE E996 WITH W_ZFDHENO '항해번호'.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 031 도착(예정)일.
  IF NOT ZTLG-ZFETA IS INITIAL.
    PARA_LENG = 8.
    MOVE ZTLG-ZFETA TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ELSE.
    MESSAGE E996 WITH W_ZFDHENO '도착(예정)일'.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 032 선하증권 발행일자.
  IF NOT ZTLG-ZFTBIDT IS INITIAL.
    PARA_LENG = 8.
    MOVE ZTLG-ZFTBIDT TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ELSE.
    MESSAGE E996 WITH W_ZFDHENO '선하증권 발행일자'.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 033 신청일자.
  IF NOT ZTLG-ZFAPDT IS INITIAL.
    PARA_LENG = 8.
    MOVE ZTLG-ZFAPDT TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ELSE.
    MESSAGE E996 WITH W_ZFDHENO '신청일자'.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 신청일자 >= 선하증권발급일자.
  IF ZTLG-ZFAPDT LT ZTLG-ZFTBIDT.
    MESSAGE E977
       WITH '신청일자가 선하증권발급일자 이전일 수 없습니다.'.
  ENDIF.

* 034 선적항 코드.
  IF NOT ZTLG-ZFSHCU IS INITIAL.
    PARA_LENG = STRLEN( ZTLG-ZFSHCU ).
    MOVE ZTLG-ZFSHCU TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ELSE.
    MESSAGE E996 WITH W_ZFDHENO '선적국가 코드'.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 035 선적항 지명.
  IF NOT ZTLG-ZFSHCUNM IS INITIAL.
    PARA_LENG = STRLEN( ZTLG-ZFSHCUNM ).
    MOVE ZTLG-ZFSHCUNM TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ELSE.
    MESSAGE E996 WITH W_ZFDHENO '선적항 지명'.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 036 도착항 코드.
  IF NOT ZTLG-ZFARCUM IS INITIAL.
    PARA_LENG = STRLEN( ZTLG-ZFARCUM ).
    MOVE ZTLG-ZFARCUM TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ELSE.
    MESSAGE E996 WITH W_ZFDHENO '도착국가 코드'.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 037 도착항 지명.
  IF NOT ZTLG-ZFARCUNM IS INITIAL.
    PARA_LENG = STRLEN( ZTLG-ZFARCUNM ).
    MOVE ZTLG-ZFARCUNM TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ELSE.
    MESSAGE E996 WITH W_ZFDHENO '도착항 지명'.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 038 화물표시 및 번호 1.
  IF NOT ZTLG-ZFGODR1 IS INITIAL.
    PARA_LENG = STRLEN( ZTLG-ZFGODR1 ).
    MOVE ZTLG-ZFGODR1 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 039 화물표시 및 번호 2.
  IF NOT ZTLG-ZFGODR2 IS INITIAL.
    PARA_LENG = STRLEN( ZTLG-ZFGODR2 ).
    MOVE ZTLG-ZFGODR2 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 040 화물표시 및 번호 3.
  IF NOT ZTLG-ZFGODR3 IS INITIAL.
    PARA_LENG = STRLEN( ZTLG-ZFGODR3 ).
    MOVE ZTLG-ZFGODR3 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 041 화물표시 및 번호 4.
  IF NOT ZTLG-ZFGODR4 IS INITIAL.
    PARA_LENG = STRLEN( ZTLG-ZFGODR4 ).
    MOVE ZTLG-ZFGODR4 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 042 화물표시 및 번호 5.
  IF NOT ZTLG-ZFGODR5 IS INITIAL.
    PARA_LENG = STRLEN( ZTLG-ZFGODR5 ).
    MOVE ZTLG-ZFGODR5 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 043 화물표시 및 번호 6.
  IF NOT ZTLG-ZFGODR6 IS INITIAL.
    PARA_LENG = STRLEN( ZTLG-ZFGODR6 ).
    MOVE ZTLG-ZFGODR6 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 044 화물표시 및 번호 7.
  IF NOT ZTLG-ZFGODR7 IS INITIAL.
    PARA_LENG = STRLEN( ZTLG-ZFGODR7 ).
    MOVE ZTLG-ZFGODR7 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 045 화물표시 및 번호 8.
  IF NOT ZTLG-ZFGODR8 IS INITIAL.
    PARA_LENG = STRLEN( ZTLG-ZFGODR8 ).
    MOVE ZTLG-ZFGODR8 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 046 화물표시 및 번호 9.
  IF NOT ZTLG-ZFGODR9 IS INITIAL.
    PARA_LENG = STRLEN( ZTLG-ZFGODR9 ).
    MOVE ZTLG-ZFGODR9 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 047 화물표시 및 번호 10.
  IF NOT ZTLG-ZFGODR10 IS INITIAL.
    PARA_LENG = STRLEN( ZTLG-ZFGODR10 ).
    MOVE ZTLG-ZFGODR10 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 048 포장수.
  IF NOT ZTLG-ZFPKCN IS INITIAL.
    MOVE ZTLG-ZFPKCN TO L_TEXT35.
    PERFORM P3000_CHAR_DELETE CHANGING L_TEXT35.
    PARA_LENG = STRLEN( L_TEXT35 ).
    MOVE L_TEXT35 TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 049 포장수 단위.
  IF NOT ZTLG-ZFPKCNM IS INITIAL.
    PARA_LENG = STRLEN( ZTLG-ZFPKCNM ).
    MOVE ZTLG-ZFPKCNM TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 050 상품명세1 ~ 054 상품명세5.
  CLEAR: L_LINENO.
  LOOP AT IT_ZSLGGOD FROM 1 TO 5.
    IF NOT IT_ZSLGGOD-ZFGODS IS INITIAL.
      PARA_LENG = STRLEN( IT_ZSLGGOD-ZFGODS ).
      MOVE IT_ZSLGGOD-ZFGODS TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
      ADD PARA_LENG TO BUFFER_POINTER.
    ENDIF.

    PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.
    ADD 1 TO L_LINENO.

  ENDLOOP.

  IF L_LINENO LT 5.
    L_LINENO = 5 - L_LINENO.
    DO L_LINENO TIMES.
      PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.
    ENDDO.
  ENDIF.

* 055 결제구분.
  IF NOT ZTLG-ZFPTRM IS INITIAL.
    PARA_LENG = STRLEN( ZTLG-ZFPTRM ).
    MOVE ZTLG-ZFPTRM TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 056 결제기간.
  IF NOT ZTLG-ZFPTRMD IS INITIAL.
    PARA_LENG = STRLEN( ZTLG-ZFPTRMD ).
    MOVE ZTLG-ZFPTRMD TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 057 발급은행 코드.
  IF NOT ZTLG-ZFISBNCD IS INITIAL.
    PARA_LENG = STRLEN( ZTLG-ZFISBNCD ).
    MOVE ZTLG-ZFISBNCD TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ELSE.
    MESSAGE E996 WITH W_ZFDHENO '발급은행 코드'.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 058 발급은행1.
  IF NOT ZTLG-ZFISBNM IS INITIAL.
    PARA_LENG = STRLEN( ZTLG-ZFISBNM ).
    MOVE ZTLG-ZFISBNM TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ELSE.
    MESSAGE E996 WITH W_ZFDHENO '발급은행명'.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 059 발급은행2.
  IF NOT ZTLG-ZFISBB IS INITIAL.
    PARA_LENG = STRLEN( ZTLG-ZFISBB ).
    MOVE ZTLG-ZFISBB TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ELSE.
    MESSAGE E996 WITH W_ZFDHENO '발급은행 지점명'.
  ENDIF.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 060 문서현황..
  PARA_LENG = 1.
  MOVE '1' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ADD PARA_LENG TO BUFFER_POINTER.

  PERFORM P3000_1BYTE_DELIMETER_INSERT CHANGING W_EDI_RECORD.

* 061 송수신 상태. --> Not Interface.

* 062 수발신인 식별자.
  IF NOT W_BAHNS IS INITIAL.
    PARA_LENG = STRLEN( W_BAHNS ).
    MOVE W_BAHNS TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
    ADD PARA_LENG TO BUFFER_POINTER.
  ELSE.
    MESSAGE E977 WITH '개설은행 수발신인 식별자를 확인하십시오.'.
  ENDIF.

  PARA_LENG = 7.
  MOVE '@@@}}~~' TO W_EDI_RECORD+BUFFER_POINTER(PARA_LENG).
  ADD PARA_LENG TO BUFFER_POINTER.

*>> 마지막 New Line Char. Cut.
* NHJ 막음.
*  PERFORM P3000_EDI_RECORD_ADJUST  CHANGING W_EDI_RECORD.

ENDFUNCTION.
