FUNCTION ZIM_BAPI_PO_CHANGE.
*"----------------------------------------------------------------------
*"*"Local interface:
*"  IMPORTING
*"     VALUE(PURCHASEORDER) LIKE  BAPIMEPOHEADER-PO_NUMBER
*"     VALUE(POHEADER) LIKE  BAPIMEPOHEADER STRUCTURE  BAPIMEPOHEADER
*"       OPTIONAL
*"     VALUE(POHEADERX) LIKE  BAPIMEPOHEADERX STRUCTURE
*"        BAPIMEPOHEADERX OPTIONAL
*"     VALUE(POADDRVENDOR) LIKE  BAPIMEPOADDRVENDOR STRUCTURE
*"        BAPIMEPOADDRVENDOR OPTIONAL
*"     VALUE(TESTRUN) LIKE  BAPIFLAG-BAPIFLAG OPTIONAL
*"     VALUE(MEMORY_UNCOMPLETE) LIKE  BAPIFLAG-BAPIFLAG OPTIONAL
*"     VALUE(MEMORY_COMPLETE) LIKE  BAPIFLAG-BAPIFLAG OPTIONAL
*"  EXPORTING
*"     VALUE(EXPHEADER) LIKE  BAPIMEPOHEADER STRUCTURE  BAPIMEPOHEADER
*"  TABLES
*"      RETURN STRUCTURE  BAPIRET2 OPTIONAL
*"      POITEM STRUCTURE  BAPIMEPOITEM OPTIONAL
*"      POITEMX STRUCTURE  BAPIMEPOITEMX OPTIONAL
*"      POADDRDELIVERY STRUCTURE  BAPIMEPOADDRDELIVERY OPTIONAL
*"      POSCHEDULE STRUCTURE  BAPIMEPOSCHEDULE OPTIONAL
*"      POSCHEDULEX STRUCTURE  BAPIMEPOSCHEDULX OPTIONAL
*"      POACCOUNT STRUCTURE  BAPIMEPOACCOUNT OPTIONAL
*"      POACCOUNTX STRUCTURE  BAPIMEPOACCOUNTX OPTIONAL
*"      POCOND STRUCTURE  BAPIMEPOCOND OPTIONAL
*"      POCONDX STRUCTURE  BAPIMEPOCONDX OPTIONAL
*"      POLIMITS STRUCTURE  BAPIESUHC OPTIONAL
*"      POCONTRACTLIMITS STRUCTURE  BAPIESUCC OPTIONAL
*"      POSERVICES STRUCTURE  BAPIESLLC OPTIONAL
*"      POSRVACCESSVALUES STRUCTURE  BAPIESKLC OPTIONAL
*"      POSERVICESTEXT STRUCTURE  BAPIESLLTX OPTIONAL
*"      EXTENSIONIN STRUCTURE  BAPIPAREX OPTIONAL
*"      EXTENSIONOUT STRUCTURE  BAPIPAREX OPTIONAL
*"----------------------------------------------------------------------
DATA : L_TCODE LIKE SY-TCODE.


   SELECT SINGLE * FROM EKKO
          WHERE    EBELN  EQ   PURCHASEORDER.

   IF EKKO-BSTYP EQ 'L' OR    ">³³Ç°ÀÏÁ¤ °èÈ¹..
      EKKO-BSTYP EQ 'K'.      ">ÀÏ°ý°è¾à.
*>>> UNLOCK.
      CALL FUNCTION 'DEQUEUE_EMEKKOE'
           EXPORTING
              EBELN    =   PURCHASEORDER.

      IF EKKO-BSTYP EQ 'L'.
         L_TCODE = 'ME32L'.
      ELSE.
         L_TCODE = 'ME32K'.
      ENDIF.


      CALL FUNCTION 'ZIM_BDC_CALL_TRANSACTION_ME32L'
          EXPORTING
               PURCHASEORDER      = PURCHASEORDER
               POHEADER           = POHEADER
               TCODE              = L_TCODE
          TABLES
               RETURN             = RETURN.

   ELSE.

     CALL FUNCTION 'BAPI_PO_CHANGE'
          EXPORTING
               PURCHASEORDER      = PURCHASEORDER
               POHEADER           = POHEADER
               POHEADERX          = POHEADERX
               POADDRVENDOR       = POADDRVENDOR
               TESTRUN            = TESTRUN
*               MEMORY_UNCOMPLETE  = MEMORY_UNCOMPLETE
*               MEMORY_COMPLETE    = MEMORY_COMPLETE
*          IMPORTING
*               EXPHEADER          = EXPHEADER
          TABLES
               RETURN             = RETURN
               POITEM             = POITEM
               POITEMX            = POITEMX
               POADDRDELIVERY     = POADDRDELIVERY
               POSCHEDULE         = POSCHEDULE
               POSCHEDULEX        = POSCHEDULEX
               POACCOUNT          = POACCOUNT
*               POACCOUNTPROFITSEGMENT = POACCOUNTPROFITSEGMENT
               POACCOUNTX         = POACCOUNTX
               POCOND             = POCOND
               POCONDX            = POCONDX
               POLIMITS           = POLIMITS
               POCONTRACTLIMITS   = POCONTRACTLIMITS
               POSERVICES         = POSERVICES
               POSRVACCESSVALUES  = POSRVACCESSVALUES
               POSERVICESTEXT     = POSERVICESTEXT.
*              EXTENSIONIN        = EXTENSIONIN
*              EXTENSIONOUT       = EXTENSIONOUT.

*>>> UNLOCK.
      CALL FUNCTION 'DEQUEUE_EMEKKOE'
           EXPORTING
              EBELN    =   PURCHASEORDER.
   ENDIF.

   IF RETURN[] IS INITIAL.
      COMMIT WORK.
   ELSE.
      READ TABLE RETURN  WITH KEY  TYPE = 'E'.

      IF SY-SUBRC NE 0.
         COMMIT WORK.
      ELSE.
         ROLLBACK WORK.
      ENDIF.
   ENDIF.

   EXIT.

ENDFUNCTION.
