FUNCTION ZIM_LOCAPP_EDI_SEND.
*"----------------------------------------------------------------------
*"*"Local interface:
*"       IMPORTING
*"             VALUE(W_ZFREQNO) LIKE  ZTREQHD-ZFREQNO
*"             VALUE(W_ZFDHENO) LIKE  ZTDHF1-ZFDHENO
*"       EXCEPTIONS
*"              DB_ERROR
*"----------------------------------------------------------------------

   CALL FUNCTION 'ZIM_GET_LOCAL_LC_DATA'
        EXPORTING
              ZFREQNO        =       W_ZFREQNO
        IMPORTING
              W_ZTLLCHD      =       ZTLLCHD
              W_ZTLLCSG23    =       ZTLLCSG23
        TABLES
              IT_ZSLLCOF     =       IT_ZSLLCOF
              IT_ZSLLCOF_ORG =       IT_ZSLLCOF_ORG
        EXCEPTIONS
              NOT_FOUND      =       4
              NOT_INPUT      =       8.

     CASE SY-SUBRC.
        WHEN 4.
           MESSAGE E018 WITH ZTREQHD-ZFREQNO.
        WHEN 8.
           MESSAGE E019.
     ENDCASE.

*-----------------------------------------------------------------------
* internal Table Append
*-----------------------------------------------------------------------
   REFRESH : IT_ZTDDF1.
   CLEAR : IT_ZTDDF1.
   IT_ZTDDF1-ZFDDENO = W_ZFDHENO.
*>>> 전자문서 시작
   IT_ZTDDF1-ZFDDFDA = '{10'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '460'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = W_ZFDHENO.        APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTLLCHD-ZFEDFN.   APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = 'AB'.             APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}10'.            APPEND IT_ZTDDF1.
*>>> 개설근거별 용도
   IT_ZTDDF1-ZFDDFDA = '{11'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '1'.              APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTLLCHD-ZFUSG.    APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}11'.            APPEND IT_ZTDDF1.
*>>> 물품매도확약서 번호
   LOOP AT IT_ZSLLCOF.
     IT_ZTDDF1-ZFDDFDA = '{12'.                APPEND IT_ZTDDF1.
     IT_ZTDDF1-ZFDDFDA = 'AAG'.                APPEND IT_ZTDDF1.
     IT_ZTDDF1-ZFDDFDA = IT_ZSLLCOF-ZFOFFER.   APPEND IT_ZTDDF1.
     IT_ZTDDF1-ZFDDFDA = '}12'.                APPEND IT_ZTDDF1.
   ENDLOOP.
*>>> 개설회차
   IT_ZTDDF1-ZFDDFDA = '{12'.                APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '2AG'.                APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTLLCHD-ZFOPCNT.      APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}12'.                APPEND IT_ZTDDF1.
*>>> 개설신청일자
   IT_ZTDDF1-ZFDDFDA = '{13'.              APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '2AA'.              APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTREQST-ZFAPPDT+2.  APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '101'.              APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}13'.              APPEND IT_ZTDDF1.
*>>> 서류제시기간
   IT_ZTDDF1-ZFDDFDA = '{13'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '272'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTLLCHD-ZFDPRP.   APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '804'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}13'.            APPEND IT_ZTDDF1.
*>>> 물품인도기일
   IT_ZTDDF1-ZFDDFDA = '{13'.              APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '2'.                APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTLLCHD-ZFGDDT+2.   APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '101'.              APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}13'.              APPEND IT_ZTDDF1.
*>>> 유효기일
   IT_ZTDDF1-ZFDDFDA = '{13'.              APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '123'.              APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTLLCHD-ZFEXDT+2.   APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '101'.              APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}13'.              APPEND IT_ZTDDF1.
*>>> 분할선적 허용여부
   IT_ZTDDF1-ZFDDFDA = '{14'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTLLCHD-ZFPRAL.   APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}14'.            APPEND IT_ZTDDF1.
*>>> 대표공급물품명
   IT_ZTDDF1-ZFDDFDA = '{15'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = 'AAA'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTLLCHD-ZFGDSC1.  APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTLLCHD-ZFGDSC2.  APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTLLCHD-ZFGDSC3.  APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTLLCHD-ZFGDSC4.  APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTLLCHD-ZFGDSC5.  APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}15'.            APPEND IT_ZTDDF1.
*>>> 기타 정보
   IF NOT ZTLLCHD-ZFETC1 IS INITIAL OR
      NOT ZTLLCHD-ZFETC2 IS INITIAL OR
      NOT ZTLLCHD-ZFETC3 IS INITIAL OR
      NOT ZTLLCHD-ZFETC4 IS INITIAL OR
      NOT ZTLLCHD-ZFETC5 IS INITIAL.
      IT_ZTDDF1-ZFDDFDA = '{15'.            APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = 'ACB'.            APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTLLCHD-ZFGDSC1.  APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTLLCHD-ZFGDSC2.  APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTLLCHD-ZFGDSC3.  APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTLLCHD-ZFGDSC4.  APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTLLCHD-ZFGDSC5.  APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '}15'.            APPEND IT_ZTDDF1.
   ENDIF.
*>>> 개설은행
   IT_ZTDDF1-ZFDDFDA = '{16'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = 'AZ'.             APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTLLCHD-ZFOPBNCD. APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '25'.             APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = 'BOK'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTLLCHD-ZFOBNM.   APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTLLCHD-ZFOBBR.   APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}16'.            APPEND IT_ZTDDF1.
*>>> 개설의뢰인
   IT_ZTDDF1-ZFDDFDA = '{17'.              APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = 'DF'.               APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTLLCSG23-ZFAPPNM1. APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTLLCSG23-ZFAPPNM2. APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTLLCSG23-ZFAPPNM3. APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}17'.              APPEND IT_ZTDDF1.
*>>> 수혜자
   IT_ZTDDF1-ZFDDFDA = '{17'.              APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = 'DG'.               APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTLLCSG23-ZFBENI1.  APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTLLCSG23-ZFBENI2.  APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTLLCSG23-ZFBENI3.  APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}17'.              APPEND IT_ZTDDF1.
*>>> 전자서명
   IT_ZTDDF1-ZFDDFDA = '{17'.              APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = 'AX'.               APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTLLCSG23-ZFELENM.  APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTLLCSG23-ZFREPRE.  APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTLLCSG23-ZFELEID.  APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}17'.              APPEND IT_ZTDDF1.
*>>> 주요구비서류통수
   DO 5 TIMES.
      CASE SY-INDEX.
         WHEN 1.   ASSIGN ZTLLCSG23-ZFDOMYN  TO <FS_F>.
         WHEN 2.   ASSIGN ZTLLCSG23-ZFBILYN  TO <FS_F>.
         WHEN 3.   ASSIGN ZTLLCSG23-ZFINVYN  TO <FS_F>.
         WHEN 4.   ASSIGN ZTLLCSG23-ZFOFYN   TO <FS_F>.
         WHEN 5.   ASSIGN ZTLLCSG23-ZFLLCYN  TO <FS_F>.
      ENDCASE.
      IF NOT <FS_F> IS INITIAL.
         IT_ZTDDF1-ZFDDFDA = '{18'.             APPEND IT_ZTDDF1.
         CASE SY-INDEX.
            WHEN 1.  IT_ZTDDF1-ZFDDFDA = '2AH'.      APPEND IT_ZTDDF1.
              IT_ZTDDF1-ZFDDFDA = ZTLLCSG23-ZFNODOM. APPEND IT_ZTDDF1.
            WHEN 2.  IT_ZTDDF1-ZFDDFDA = '2AJ'.      APPEND IT_ZTDDF1.
              IT_ZTDDF1-ZFDDFDA = ZTLLCSG23-ZFNOBIL. APPEND IT_ZTDDF1.
            WHEN 3.  IT_ZTDDF1-ZFDDFDA = '2AK'.      APPEND IT_ZTDDF1.
              IT_ZTDDF1-ZFDDFDA = ZTLLCSG23-ZFNOINV. APPEND IT_ZTDDF1.
            WHEN 4.  IT_ZTDDF1-ZFDDFDA = '2AP'.      APPEND IT_ZTDDF1.
              IT_ZTDDF1-ZFDDFDA = ZTLLCSG23-ZFNOOF.  APPEND IT_ZTDDF1.
            WHEN 5.  IT_ZTDDF1-ZFDDFDA = '310'.      APPEND IT_ZTDDF1.
              IT_ZTDDF1-ZFDDFDA = ZTLLCSG23-ZFNOLLC. APPEND IT_ZTDDF1.
* >>>>>>>>>>>>>>>>>>>>>>기타구비서류
              IF NOT ZTLLCSG23-ZFEDOC1 IS INITIAL OR
                 NOT ZTLLCSG23-ZFEDOC2 IS INITIAL OR
                 NOT ZTLLCSG23-ZFEDOC3 IS INITIAL OR
                 NOT ZTLLCSG23-ZFEDOC4 IS INITIAL OR
                 NOT ZTLLCSG23-ZFEDOC5 IS INITIAL.
                 IT_ZTDDF1-ZFDDFDA = '{20'.          APPEND IT_ZTDDF1.
                 IT_ZTDDF1-ZFDDFDA = 'ABX'.          APPEND IT_ZTDDF1.
                 IT_ZTDDF1-ZFDDFDA = ZTLLCSG23-ZFEDOC1.
                 APPEND IT_ZTDDF1.
                 IT_ZTDDF1-ZFDDFDA = ZTLLCSG23-ZFEDOC2.
                 APPEND IT_ZTDDF1.
                 IT_ZTDDF1-ZFDDFDA = ZTLLCSG23-ZFEDOC3.
                 APPEND IT_ZTDDF1.
                 IT_ZTDDF1-ZFDDFDA = ZTLLCSG23-ZFEDOC4.
                 APPEND IT_ZTDDF1.
                 IT_ZTDDF1-ZFDDFDA = ZTLLCSG23-ZFEDOC5.
                 APPEND IT_ZTDDF1.
                 IT_ZTDDF1-ZFDDFDA = '}20'.          APPEND IT_ZTDDF1.
              ENDIF.
* >>>>>>>>>>>>>>>>>>>>>>기타구비서류
         ENDCASE.
         IT_ZTDDF1-ZFDDFDA = '}18'.             APPEND IT_ZTDDF1.
      ENDIF.
   ENDDO.
*>>> 내국신용장 종류
   IT_ZTDDF1-ZFDDFDA = '{19'.              APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTLLCHD-ZFLLCTY.    APPEND IT_ZTDDF1.
*>>>>>>>>>>> 개설금액
      WRITE   ZTLLCHD-ZFOPAMT    TO      W_TEXT_AMOUNT
                            CURRENCY     ZTLLCHD-ZFOPAMTC.
      PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.
      IT_ZTDDF1-ZFDDFDA = '{21'.              APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '2AD'.              APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = W_TEXT_AMOUNT.      APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTLLCHD-ZFOPAMTC.   APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '}21'.              APPEND IT_ZTDDF1.
*>>>>>>>>>>> 개설금액
   IT_ZTDDF1-ZFDDFDA = '}19'.              APPEND IT_ZTDDF1.

*>>> 개설근거서류 종류 코드
   IF NOT ZTLLCHD-ZFOPRED IS INITIAL.
      IT_ZTDDF1-ZFDDFDA = '{1A'.              APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTLLCHD-ZFOPRED.    APPEND IT_ZTDDF1.
*>>>>>>>>>>> 신용장(계약서) 번호
      IF NOT ZTLLCHD-ZFDCNO IS INITIAL.
         IT_ZTDDF1-ZFDDFDA = '{22'.              APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = 'AAC'.              APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = ZTLLCHD-ZFDCNO.     APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '}22'.              APPEND IT_ZTDDF1.
      ENDIF.
*>>>>>>>>>>> 개설금액
      IF NOT ZTLLCHD-ZFDCAMT IS INITIAL.
         WRITE   ZTLLCHD-ZFDCAMT    TO      W_TEXT_AMOUNT
                               CURRENCY     ZTLLCHD-WAERS.
         PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.
         IT_ZTDDF1-ZFDDFDA = '{23'.              APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '212'.              APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = W_TEXT_AMOUNT.      APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = ZTLLCHD-WAERS.      APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '}23'.              APPEND IT_ZTDDF1.
      ENDIF.
*>>>>>>>>>>> 선적(인도)기일
      IF NOT ZTLLCHD-ZFDEDT  IS INITIAL.
         IT_ZTDDF1-ZFDDFDA = '{24'.                APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '38'.                 APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = ZTLLCHD-ZFDEDT+2.     APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '101'.                APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '}24'.                APPEND IT_ZTDDF1.
      ENDIF.
*>>>>>>>>>>> 유효기일
      IF NOT ZTLLCHD-ZFDEXDT IS INITIAL.
         IT_ZTDDF1-ZFDDFDA = '{24'.                APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '123'.                APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = ZTLLCHD-ZFDEXDT+2.    APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '101'.                APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '}24'.                APPEND IT_ZTDDF1.
      ENDIF.
*>>>>>>>>>>> 수출(공급)상태방명
      IF NOT ZTLLCHD-ZFEXPR1 IS INITIAL OR
         NOT ZTLLCHD-ZFEXPR2 IS INITIAL OR
         NOT ZTLLCHD-ZFEXPR3 IS INITIAL.
         IT_ZTDDF1-ZFDDFDA = '{25'.              APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = 'IM'.               APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = ZTLLCHD-ZFEXPR1.    APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = ZTLLCHD-ZFEXPR2.    APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = ZTLLCHD-ZFEXPR3.    APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '}25'.              APPEND IT_ZTDDF1.
      ENDIF.
*>>>>>>>>>>> 수출지역코드
      IF NOT ZTLLCHD-ZFEXAR  IS INITIAL.
         IT_ZTDDF1-ZFDDFDA = '{26'.              APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '28'.               APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = ZTLLCHD-ZFEXAR.     APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '162'.              APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '5'.                APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '}26'.              APPEND IT_ZTDDF1.
      ENDIF.
*>>>>>>>>>>> 발신은행
      IF NOT ZTLLCHD-ZFISBN  IS INITIAL OR
         NOT ZTLLCHD-ZFISBNB IS INITIAL.
         IT_ZTDDF1-ZFDDFDA = '{27'.              APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = 'AZ'.               APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = ZTLLCHD-ZFISBN.     APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = ZTLLCHD-ZFISBNB.    APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '}27'.              APPEND IT_ZTDDF1.
      ENDIF.
*>>>>>>>>>>> 대금결제조건
      IF NOT ZTLLCHD-ZFTOP   IS INITIAL.
         IT_ZTDDF1-ZFDDFDA = '{28'.              APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '1'.                APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = ZTLLCHD-ZFTOP.      APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '}28'.              APPEND IT_ZTDDF1.
      ENDIF.
*>>>>>>>>>>> 대표수출물품명
      IF NOT ZTLLCHD-ZFEXGNM1 IS INITIAL OR
         NOT ZTLLCHD-ZFEXGNM2 IS INITIAL OR
         NOT ZTLLCHD-ZFEXGNM3 IS INITIAL OR
         NOT ZTLLCHD-ZFEXGNM4 IS INITIAL OR
         NOT ZTLLCHD-ZFEXGNM5 IS INITIAL.
         IT_ZTDDF1-ZFDDFDA = '{29'.              APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = 'AAA'.              APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = ZTLLCHD-ZFEXGNM1.   APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = ZTLLCHD-ZFEXGNM2.   APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = ZTLLCHD-ZFEXGNM3.   APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = ZTLLCHD-ZFEXGNM4.   APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = ZTLLCHD-ZFEXGNM5.   APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '}29'.              APPEND IT_ZTDDF1.
      ENDIF.
      IT_ZTDDF1-ZFDDFDA = '}1A'.              APPEND IT_ZTDDF1.
   ENDIF.
*
   CALL FUNCTION 'ZIM_EDI_FLAT_ITEM_INSERT'
        EXPORTING
              W_ZFDHENO         =        W_ZFDHENO
        TABLES
              IT_ZTDDF1         =        IT_ZTDDF1
        EXCEPTIONS
              DB_ERROR         =         4.

   IF SY-SUBRC NE 0.
      MESSAGE E118 WITH W_ZFDHENO.
   ENDIF.

ENDFUNCTION.
