FUNCTION ZIM_GET_COMMERCIAL_DOC_HEADER.
*"----------------------------------------------------------------------
*"*"Local interface:
*"  IMPORTING
*"     REFERENCE(ZFCIVRN) LIKE  ZTCIVHD-ZFCIVRN
*"  EXPORTING
*"     REFERENCE(W_ZTCIVHD) LIKE  ZTCIVHD STRUCTURE  ZTCIVHD
*"  TABLES
*"      IT_ZSCIVIT STRUCTURE  ZSCIVIT OPTIONAL
*"      IT_ZSCIVIT_ORG STRUCTURE  ZSCIVIT OPTIONAL
*"      IT_ZSCIVHST STRUCTURE  ZSCIVHST OPTIONAL
*"  EXCEPTIONS
*"      NOT_FOUND
*"      NOT_INPUT
*"----------------------------------------------------------------------
  REFRESH : IT_ZSCIVIT, IT_ZSCIVIT_ORG.
  CLEAR : IT_ZSCIVIT, IT_ZSCIVIT_ORG, W_ZTCIVHD.

  IF ZFCIVRN IS INITIAL.
     RAISE NOT_INPUT.
  ENDIF.

  SELECT SINGLE * INTO W_ZTCIVHD FROM   ZTCIVHD
                                 WHERE  ZFCIVRN  EQ  ZFCIVRN.
  IF SY-SUBRC NE 0.
     RAISE NOT_FOUND.
  ENDIF.

  SELECT * INTO CORRESPONDING FIELDS OF TABLE IT_ZSCIVIT
           FROM ZTCIVIT
           WHERE  ZFCIVRN      EQ   ZFCIVRN.

  SORT IT_ZSCIVIT BY ZFCIVSQ.

  LOOP AT IT_ZSCIVIT.
     W_TABIX = SY-TABIX.
*++++> P/O DATA 조회.
     SELECT SINGLE MENGE UEBTO UEBTK WEPOS ELIKZ LOEKZ UNTTO
                   BPUMN BPUMZ WERKS LGORT
            INTO (IT_ZSCIVIT-MENGE_PO, IT_ZSCIVIT-UEBTO,
                  IT_ZSCIVIT-UEBTK,    IT_ZSCIVIT-WEPOS,
                  IT_ZSCIVIT-ELIKZ,    IT_ZSCIVIT-LOEKZ,
                  IT_ZSCIVIT-UNTTO,
                  IT_ZSCIVIT-BPUMN,    IT_ZSCIVIT-BPUMZ,
                  IT_ZSCIVIT-WERKS,    IT_ZSCIVIT-LGORT)
            FROM   EKPO
            WHERE  EBELN   EQ   IT_ZSCIVIT-EBELN
            AND    EBELP   EQ   IT_ZSCIVIT-EBELP.
*+++++> 수입의뢰 수량.
     SELECT SINGLE MENGE KBETR KWERT KPEIN KMEIN
            INTO (IT_ZSCIVIT-MENGE, IT_ZSCIVIT-KBETR,
                  IT_ZSCIVIT-KWERT, IT_ZSCIVIT-KPEIN,
                  IT_ZSCIVIT-KMEIN)
            FROM  ZTREQIT
            WHERE ZFREQNO EQ IT_ZSCIVIT-ZFREQNO
            AND   ZFITMNO EQ IT_ZSCIVIT-ZFITMNO.

*>>> 기 처리수량.
     IF IT_ZSCIVIT-ZFBLNO IS INITIAL.
        SELECT SUM( ZFPRQN ) INTO IT_ZSCIVIT-CIVTOT
                  FROM  ZTCIVIT
*                  WHERE ZFBLNO  NE ZTBL-ZFBLNO
                  WHERE ZFREQNO EQ IT_ZSCIVIT-ZFREQNO
                  AND   ZFITMNO EQ IT_ZSCIVIT-ZFITMNO.
     ELSE.
        SELECT SUM( ZFPRQN ) INTO IT_ZSCIVIT-CIVTOT
                  FROM  ZTCIVIT
*                  WHERE ZFBLNO  NE ZTBL-ZFBLNO
                  WHERE ZFREQNO EQ IT_ZSCIVIT-ZFREQNO
                  AND   ZFITMNO EQ IT_ZSCIVIT-ZFITMNO
                  AND   ZFBLNO  EQ IT_ZSCIVIT-ZFBLNO
                  AND   ZFBLIT  EQ IT_ZSCIVIT-ZFBLIT.
     ENDIF.

*>>> 기 입력 INVOICE 수량.
     IF IT_ZSCIVIT-ZFBLNO IS INITIAL.
        SELECT SUM( CMENGE ) INTO IT_ZSCIVIT-CIVTOT1
                  FROM  ZTCIVIT
*                  WHERE ZFBLNO  NE ZTBL-ZFBLNO
                  WHERE ZFREQNO EQ IT_ZSCIVIT-ZFREQNO
                  AND   ZFITMNO EQ IT_ZSCIVIT-ZFITMNO
                  AND   ZFPRPYN NE 'Y'.        " 선급금이 아닌 것.
     ELSE.
        SELECT SUM( CMENGE ) INTO IT_ZSCIVIT-CIVTOT1
                  FROM  ZTCIVIT
*                  WHERE ZFBLNO  NE ZTBL-ZFBLNO
                  WHERE ZFREQNO EQ IT_ZSCIVIT-ZFREQNO
                  AND   ZFITMNO EQ IT_ZSCIVIT-ZFITMNO
                  AND   ZFBLNO  EQ IT_ZSCIVIT-ZFBLNO
                  AND   ZFBLIT  EQ IT_ZSCIVIT-ZFBLIT
                  AND   ZFPRPYN NE 'Y'.        " 선급금이 아닌 것.
*>>> B/L 수량.
        SELECT SINGLE BLMENGE WERKS LGORT
                   INTO (IT_ZSCIVIT-MENGE_BL,
                         IT_ZSCIVIT-WERKS,    IT_ZSCIVIT-LGORT)
                   FROM ZTBLIT
                   WHERE ZFBLNO EQ IT_ZSCIVIT-ZFBLNO
                   AND   ZFBLIT EQ IT_ZSCIVIT-ZFBLIT.
     ENDIF.
*>>> B/L TOTAL 수량.
*     SELECT SUM( BLMENGE ) INTO IT_ZSCIVIT-ZFBLTOT
*                   FROM ZTBLIT
*                   WHERE ZFBLNO EQ IT_ZSCIVIT-ZFBLNO
*                   AND   ZFBLIT EQ IT_ZSCIVIT-ZFBLIT.

     MODIFY  IT_ZSCIVIT   INDEX  W_TABIX.
  ENDLOOP.

  IT_ZSCIVIT_ORG[] = IT_ZSCIVIT[].


  SELECT * INTO CORRESPONDING FIELDS OF TABLE IT_ZSCIVHST
           FROM ZTCIVHST
           WHERE  ZFCIVRN      EQ   ZFCIVRN.

ENDFUNCTION.
