FUNCTION ZIM_GET_CC_DOCUMENT.
*"----------------------------------------------------------------------
*"*"Local interface:
*"  IMPORTING
*"     VALUE(ZFIVNO) LIKE  ZTIV-ZFIVNO
*"  EXPORTING
*"     VALUE(W_ZTIV) LIKE  ZTIV STRUCTURE  ZTIV
*"  TABLES
*"      IT_ZSIVIT STRUCTURE  ZSIVIT
*"      IT_ZSIVIT_ORG STRUCTURE  ZSIVIT OPTIONAL
*"      IT_ZSIVCD STRUCTURE  ZSIVCD OPTIONAL
*"      IT_ZSIVHST STRUCTURE  ZSIVHST OPTIONAL
*"      IT_ZSIVHST1 STRUCTURE  ZSIVHST1 OPTIONAL
*"  EXCEPTIONS
*"      NOT_FOUND
*"      NOT_INPUT
*"----------------------------------------------------------------------

  REFRESH : IT_ZSIVIT,  IT_ZSIVIT_ORG, IT_ZSIVCD,
            IT_ZSIVHST, IT_ZSIVHST1.

  CLEAR : W_ZTIV, IT_ZSIVIT, IT_ZSIVIT_ORG.

*>> INPUT VALUE CHECK.
  IF ZFIVNO IS INITIAL.   RAISE NOT_INPUT.   ENDIF.

*>>통관요청 헤더.
  SELECT SINGLE * INTO W_ZTIV FROM ZTIV
                              WHERE ZFIVNO EQ ZFIVNO.
  IF SY-SUBRC NE 0.    RAISE NOT_FOUND.   ENDIF.


* 통관요청 자재.
  SELECT * INTO CORRESPONDING FIELDS OF TABLE IT_ZSIVIT
                FROM ZTIVIT
                WHERE ZFIVNO EQ ZFIVNO.

  LOOP AT IT_ZSIVIT.
     W_TABIX = SY-TABIX.
*++++> P/O DATA 조회.
     IF IT_ZSIVIT-EBELN IS INITIAL.
        CLEAR : IT_ZSIVIT-MENGE_PO, IT_ZSIVIT-UEBTO,
                IT_ZSIVIT-UEBTK,    IT_ZSIVIT-WEPOS,
                IT_ZSIVIT-ELIKZ,    IT_ZSIVIT-LOEKZ,
                IT_ZSIVIT-UNTTO,
                IT_ZSIVIT-BPUMZ,    IT_ZSIVIT-BPUMN,
                IT_ZSIVIT-REPOS.
     ELSE.
        SELECT SINGLE MENGE UEBTO UEBTK WEPOS ELIKZ LOEKZ UNTTO
                   BPUMZ BPUMN REPOS
            INTO (IT_ZSIVIT-MENGE_PO, IT_ZSIVIT-UEBTO,
                  IT_ZSIVIT-UEBTK,    IT_ZSIVIT-WEPOS,
                  IT_ZSIVIT-ELIKZ,    IT_ZSIVIT-LOEKZ,
                  IT_ZSIVIT-UNTTO,
                  IT_ZSIVIT-BPUMZ,    IT_ZSIVIT-BPUMN,
                  IT_ZSIVIT-REPOS)
            FROM   EKPO
            WHERE  EBELN   EQ   IT_ZSIVIT-EBELN
            AND    EBELP   EQ   IT_ZSIVIT-EBELP.
     ENDIF.

*+++++> 수입의뢰 수량.
     IF IT_ZSIVIT-ZFREQNO IS INITIAL.
        CLEAR : IT_ZSIVIT-MENGE, IT_ZSIVIT-KBETR,
                IT_ZSIVIT-KWERT, IT_ZSIVIT-KPEIN,
                IT_ZSIVIT-KMEIN.
     ELSE.
        SELECT SINGLE MENGE KBETR KWERT KPEIN KMEIN
            INTO (IT_ZSIVIT-MENGE, IT_ZSIVIT-KBETR,
                  IT_ZSIVIT-KWERT, IT_ZSIVIT-KPEIN,
                  IT_ZSIVIT-KMEIN)
            FROM  ZTREQIT
            WHERE ZFREQNO EQ IT_ZSIVIT-ZFREQNO
            AND   ZFITMNO EQ IT_ZSIVIT-ZFITMNO.
     ENDIF.
*>> B/L 수량.
     IF NOT IT_ZSIVIT-ZFBLNO IS INITIAL.
        SELECT SINGLE BLMENGE INTO IT_ZSIVIT-MENGE_BL
            FROM ZTBLIT
            WHERE ZFBLNO  EQ IT_ZSIVIT-ZFBLNO
            AND   ZFBLIT  EQ IT_ZSIVIT-ZFBLIT.
     ELSE.
        CLEAR : IT_ZSIVIT-MENGE_BL.
     ENDIF.
*>> 하역수량.
     IF NOT IT_ZSIVIT-ZFCGNO IS INITIAL.
        SELECT SINGLE CGMENGE INTO IT_ZSIVIT-CGMENGE
               FROM  ZTCGIT
               WHERE ZFCGNO  EQ IT_ZSIVIT-ZFCGNO
               AND   ZFCGIT  EQ IT_ZSIVIT-ZFCGIT.
     ELSE.
        CLEAR : IT_ZSIVIT-CGMENGE.
     ENDIF.

*>>>>> 통관요청 TOTAL 수량(B/L별).
     IF IT_ZSIVIT-ZFCGNO IS INITIAL.
        IF IT_ZSIVIT-ZFBLNO IS INITIAL.
           IF IT_ZSIVIT-ZFREQNO IS INITIAL.
              CLEAR : IT_ZSIVIT-ZFCCTOT, IT_ZSIVIT-ZFGRTOT.
           ELSE.
              SELECT SUM( CCMENGE ) SUM( GRMENGE )
                  INTO (IT_ZSIVIT-ZFCCTOT, IT_ZSIVIT-ZFGRTOT)
                  FROM  ZTIVIT
                  WHERE ZFREQNO  EQ IT_ZSIVIT-ZFREQNO
                  AND   ZFITMNO  EQ IT_ZSIVIT-ZFITMNO.
           ENDIF.
        ELSE.
           SELECT SUM( CCMENGE ) SUM( GRMENGE )
               INTO (IT_ZSIVIT-ZFCCTOT, IT_ZSIVIT-ZFGRTOT)
               FROM  ZTIVIT
               WHERE ZFBLNO  EQ IT_ZSIVIT-ZFBLNO
               AND   ZFBLIT  EQ IT_ZSIVIT-ZFBLIT.
        ENDIF.
     ELSE.
*>>>>> 통관요청 TOTAL 수량(하역별).
        SELECT SUM( CCMENGE ) SUM( GRMENGE )
               INTO (IT_ZSIVIT-ZFCCTOT, IT_ZSIVIT-ZFGRTOT)
               FROM  ZTIVIT
               WHERE ZFCGNO  EQ IT_ZSIVIT-ZFCGNO
               AND   ZFCGIT  EQ IT_ZSIVIT-ZFCGIT.
     ENDIF.
*>> 선사 B/L No.
     IF NOT IT_ZSIVIT-ZFBLNO IS INITIAL.
        SELECT SINGLE ZFCGHNO INTO IT_ZSIVIT-ZFCGHNO
               FROM ZTBL
               WHERE ZFBLNO  EQ  IT_ZSIVIT-ZFBLNO.
     ENDIF.


*>>   수입승인번호.
*     SELECT SINGLE ZFOPNNO INTO IT_ZSBLIT-ZFOPNNO
*            FROM   ZTREQHD
*            WHERE  ZFREQNO EQ IT_ZSBLIT-ZFREQNO.

      IF IT_ZSIVIT-CGMENGE IS INITIAL.
         IT_ZSIVIT-ZFNOCGMN = 0.
      ELSE.
         IT_ZSIVIT-ZFNOCGMN  = IT_ZSIVIT-CGMENGE  - IT_ZSIVIT-ZFGRTOT.
      ENDIF.
      IT_ZSIVIT-ZFNOCCMN = IT_ZSIVIT-MENGE_BL - IT_ZSIVIT-ZFCCTOT.
*      IF IT_ZSIVIT-ZFNOCCMN LT 0.
*         IT_ZSIVIT-ZFNOCCMN = 0.
*      ENDIF.
     MODIFY  IT_ZSIVIT   INDEX  W_TABIX.
  ENDLOOP.
  IT_ZSIVIT_ORG[] = IT_ZSIVIT[].

* 통관요청 배부내역.
  SELECT * INTO CORRESPONDING FIELDS OF TABLE IT_ZSIVCD
                FROM ZTIVCD
                WHERE ZFIVNO EQ ZFIVNO.
  LOOP AT IT_ZSIVCD.
     W_TABIX = SY-TABIX.
     CASE IT_ZSIVCD-ZFIMDTY.
        WHEN 'RD'.
           W_ZFCDTY = '003'.
        WHEN 'BL'.
           IF IT_ZSIVCD-ZFCSQ GT '10000'.
              W_ZFCDTY = '004'.
           ELSE.
              W_ZFCDTY = '005'.
           ENDIF.
        WHEN 'CW'.
           W_ZFCDTY = '007'.
        WHEN 'CC'.
           W_ZFCDTY = '006'.
     ENDCASE.
     SELECT SINGLE * FROM  ZTIMIMG08
                     WHERE ZFCDTY EQ  W_ZFCDTY
                     AND   ZFCD EQ  IT_ZSIVCD-ZFCSCD.
     IF SY-SUBRC EQ 0.
        IT_ZSIVCD-ZFCDNM = ZTIMIMG08-ZFCDNM.
        MODIFY IT_ZSIVCD INDEX W_TABIX.
     ENDIF.
  ENDLOOP.

* 통관요청 입고이력.
  SELECT * INTO CORRESPONDING FIELDS OF TABLE IT_ZSIVHST
                FROM ZTIVHST
                WHERE ZFIVNO EQ ZFIVNO.

* 통관요청 제비용 IV 이력.
  SELECT * INTO CORRESPONDING FIELDS OF TABLE IT_ZSIVHST1
                FROM ZTIVHST1
                WHERE ZFIVNO EQ ZFIVNO.


ENDFUNCTION.
