FUNCTION ZIM_CUSBRR_EDI_SEND.
*"----------------------------------------------------------------------
*"*"Local interface:
*"  IMPORTING
*"     VALUE(W_ZFBLNO) LIKE  ZTBLINR-ZFBLNO
*"     VALUE(W_ZFBTSEQ) LIKE  ZTBLINR-ZFBTSEQ
*"     VALUE(W_ZFDHENO) LIKE  ZTDHF1-ZFDHENO
*"  EXCEPTIONS
*"      DB_ERROR
*"----------------------------------------------------------------------
* B/L Doc. No.
  IF W_ZFBLNO IS INITIAL.
     MESSAGE E039.
  ENDIF.

* B/L Doc. 일련번호
  IF W_ZFBTSEQ IS INITIAL.
     MESSAGE E209.
  ENDIF.
* 반입예정정보 조회
  SELECT SINGLE * FROM ZTBLINOU  WHERE ZFBLNO  EQ W_ZFBLNO
                                 AND   ZFBTSEQ EQ W_ZFBTSEQ.
  IF SY-SUBRC NE 0.
     MESSAGE E045 WITH W_ZFBLNO W_ZFBTSEQ.
  ENDIF.
* 반출정보 조회
  SELECT SINGLE * FROM ZTBLOUR   WHERE ZFBLNO  EQ W_ZFBLNO
                                 AND   ZFBTSEQ EQ W_ZFBTSEQ.
  IF SY-SUBRC NE 0.
     MESSAGE E055 WITH W_ZFBLNO W_ZFBTSEQ.
  ENDIF.

*-----------------------------------------------------------------------
* internal Table Append
*-----------------------------------------------------------------------
   REFRESH : IT_ZTDDF1.
   CLEAR : IT_ZTDDF1.
   IT_ZTDDF1-ZFDDENO = W_ZFDHENO.
*>>> 신고번호
   IT_ZTDDF1-ZFDDFDA = '{10'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '6NB'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTBLOUR-ZFOURNO.  APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTBLOUR-ZFEDINF.  APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}10'.            APPEND IT_ZTDDF1.
*>>> 반입일자
   CONCATENATE ZTBLOUR-ZFOTDT ZTBLOUR-ZFOUTM INTO W_TEXT14.
   IT_ZTDDF1-ZFDDFDA = '{11'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '261'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = W_TEXT14.         APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '204'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}11'.            APPEND IT_ZTDDF1.
*>>> 신고세관부호
   IT_ZTDDF1-ZFDDFDA = '{14'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '41'.             APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTBLOUR-ZFINRC.   APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '113'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = 'KCS'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTBLOUR-ZFINRCD.  APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '5AB'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = 'KCS'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}14'.            APPEND IT_ZTDDF1.
*>>> 화물반출구분
   IT_ZTDDF1-ZFDDFDA = '{15'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTBLOUR-ZFOUTY.   APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '148'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = 'KCS'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}15'.            APPEND IT_ZTDDF1.
*>>> 분할구분부호
   IT_ZTDDF1-ZFDDFDA = '{15'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTBLOUR-ZFPROU.   APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '121'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = 'KCS'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}15'.            APPEND IT_ZTDDF1.
*>>> CY/CFS  구분
   IF NOT ZTBLOUR-ZFCYCFS IS INITIAL.
      IT_ZTDDF1-ZFDDFDA = '{15'.           APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTBLOUR-ZFCYCFS. APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '5DL'.           APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = 'KCS'.           APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '}15'.           APPEND IT_ZTDDF1.
   ENDIF.
*>>> 기간연장구분
   IF NOT ZTBLOUR-ZFPRDP  IS INITIAL.
      IT_ZTDDF1-ZFDDFDA = '{15'.           APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTBLOUR-ZFPRDP.  APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '5DM'.           APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = 'KCS'.           APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '}15'.           APPEND IT_ZTDDF1.
   ENDIF.
*>>> 적하목록관리번호
   IT_ZTDDF1-ZFDDFDA = '{16'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = 'XC'.             APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTBLINOU-ZFGMNO.  APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTBLINOU-ZFMSN.   APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTBLINOU-ZFHSN.   APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}16'.            APPEND IT_ZTDDF1.
*>>> 반출근거번호
   IT_ZTDDF1-ZFDDFDA = '{16'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = 'ABP'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTBLINOU-ZFBTRNO. APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ''.               APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ''.               APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}16'.            APPEND IT_ZTDDF1.
*>>> 포장수량
   WRITE   ZTBLOUR-ZFOUQN     TO      W_TEXT_AMOUNT
                         UNIT         ZTBLOUR-ZFOUQNM.
   PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.
   IT_ZTDDF1-ZFDDFDA = '{1A'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = W_TEXT_AMOUNT.    APPEND IT_ZTDDF1.
*>>> 반출중량
      IT_ZTDDF1-ZFDDFDA = '{2F'.            APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = 'WT'.             APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ''.               APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = 'KG'.             APPEND IT_ZTDDF1.
      WRITE   ZTBLOUR-ZFOUWT     TO      W_TEXT_AMOUNT
                                 UNIT    ZTBLOUR-ZFKG.
      PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.
      IT_ZTDDF1-ZFDDFDA = W_TEXT_AMOUNT.    APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '}2F'.            APPEND IT_ZTDDF1.
*>>> 누계반출중량
      IF NOT ZTBLOUR-ZFOUTWT IS INITIAL.
         IT_ZTDDF1-ZFDDFDA = '{2F'.            APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = 'WT'.             APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '9'.              APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = 'KG'.             APPEND IT_ZTDDF1.
         WRITE   ZTBLOUR-ZFOUTWT    TO      W_TEXT_AMOUNT
                                    UNIT    ZTBLOUR-ZFKG.
         PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.
         IT_ZTDDF1-ZFDDFDA = W_TEXT_AMOUNT.    APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '}2F'.            APPEND IT_ZTDDF1.
      ENDIF.
*>>> 누계반입갯수
      IF NOT ZTBLOUR-ZFOUTQN IS INITIAL.
         IT_ZTDDF1-ZFDDFDA = '{2F'.            APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = 'CT'.             APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '9'.              APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = 'CT'.             APPEND IT_ZTDDF1.
         WRITE   ZTBLOUR-ZFOUTQN    TO      W_TEXT_AMOUNT
                                    UNIT    ZTBLOUR-ZFCT.
         PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.
         IT_ZTDDF1-ZFDDFDA = W_TEXT_AMOUNT.    APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '}2F'.            APPEND IT_ZTDDF1.
      ENDIF.
   IT_ZTDDF1-ZFDDFDA = '}1A'.            APPEND IT_ZTDDF1.

*--> 분할반입차수 정보
   IF ZTBLOUR-ZFPROU NE 'A'.
      WRITE   ZTBLOUR-ZFPOUS     TO      W_TEXT_AMOUNT.
      PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.
      IT_ZTDDF1-ZFDDFDA = '{1B'.            APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '6'.              APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = W_TEXT_AMOUNT.    APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '}1B'.            APPEND IT_ZTDDF1.
   ENDIF.

   CALL FUNCTION 'ZIM_EDI_FLAT_ITEM_INSERT'
        EXPORTING
              W_ZFDHENO         =        W_ZFDHENO
        TABLES
              IT_ZTDDF1         =        IT_ZTDDF1
        EXCEPTIONS
              DB_ERROR         =         4.

   IF SY-SUBRC NE 0.
       RAISE DB_ERROR.
   ENDIF.

ENDFUNCTION.
