FUNCTION ZIM_CUSCAR_EDI_SEND.
*"----------------------------------------------------------------------
*"*"Local interface:
*"  IMPORTING
*"     VALUE(W_ZFBLNO) LIKE  ZTBLINR-ZFBLNO
*"     VALUE(W_ZFBTSEQ) LIKE  ZTBLINR-ZFBTSEQ
*"     VALUE(W_ZFDHENO) LIKE  ZTDHF1-ZFDHENO
*"  EXCEPTIONS
*"      DB_ERROR
*"----------------------------------------------------------------------
* B/L Doc. No.
  IF W_ZFBLNO IS INITIAL.
     MESSAGE E039.
  ENDIF.

* B/L Doc. 일련번호
  IF W_ZFBTSEQ IS INITIAL.
     MESSAGE E209.
  ENDIF.
* 반입예정정보 조회
  SELECT SINGLE * FROM ZTBLINOU  WHERE ZFBLNO  EQ W_ZFBLNO
                                 AND   ZFBTSEQ EQ W_ZFBTSEQ.
  IF SY-SUBRC NE 0.
     MESSAGE E045 WITH W_ZFBLNO W_ZFBTSEQ.
  ENDIF.
* 반입정보 조회
  SELECT SINGLE * FROM ZTBLINR   WHERE ZFBLNO  EQ W_ZFBLNO
                                 AND   ZFBTSEQ EQ W_ZFBTSEQ.
  IF SY-SUBRC NE 0.
     MESSAGE E045 WITH W_ZFBLNO W_ZFBTSEQ.
  ENDIF.

*-----------------------------------------------------------------------
* internal Table Append
*-----------------------------------------------------------------------
   REFRESH : IT_ZTDDF1.
   CLEAR : IT_ZTDDF1.
   IT_ZTDDF1-ZFDDENO = W_ZFDHENO.
*>>> 신고번호
   IT_ZTDDF1-ZFDDFDA = '{10'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '632'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTBLINR-ZFINRNO.  APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTBLINR-ZFEDINF.  APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}10'.            APPEND IT_ZTDDF1.
*>>> 반입일자
   CONCATENATE ZTBLINR-ZFINDT ZTBLINR-ZFINTM INTO W_TEXT14.
   IT_ZTDDF1-ZFDDFDA = '{11'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '50'.             APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = W_TEXT14.         APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '204'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}11'.            APPEND IT_ZTDDF1.
*>>> 신고세관부호
   IT_ZTDDF1-ZFDDFDA = '{14'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '41'.             APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTBLINR-ZFINRC.   APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '113'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = 'KCS'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTBLINR-ZFINRCD.  APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '5AB'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = 'KCS'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}14'.            APPEND IT_ZTDDF1.
*>>> HS 품목분류
   IF NOT ZTBLINR-ZFHSCL IS INITIAL.
      IT_ZTDDF1-ZFDDFDA = '{15'.          APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTBLINR-ZFHSCL. APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '5CA'.          APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = 'KCS'.          APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '}15'.          APPEND IT_ZTDDF1.
   ENDIF.
*>>> 화물반입구분
   IT_ZTDDF1-ZFDDFDA = '{15'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTBLINR-ZFINTY.   APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '109'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = 'KCS'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}15'.            APPEND IT_ZTDDF1.
*>>> 현도여부구분
   IF NOT ZTBLINR-ZFHDYN IS INITIAL.
      IT_ZTDDF1-ZFDDFDA = '{15'.          APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = 'Y'.            APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '5DK'.          APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = 'KCS'.          APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '}15'.          APPEND IT_ZTDDF1.
   ENDIF.
*>>> CY/CFS  구분
   IF NOT ZTBLINR-ZFCYCFS IS INITIAL.
      IT_ZTDDF1-ZFDDFDA = '{15'.           APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTBLINR-ZFCYCFS. APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '5DL'.           APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = 'KCS'.           APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '}15'.           APPEND IT_ZTDDF1.
   ENDIF.
*>>> 용도구분
   IF NOT ZTBLINR-ZFUSCD  IS INITIAL.
      IT_ZTDDF1-ZFDDFDA = '{15'.           APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTBLINR-ZFUSCD.  APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '119'.           APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = 'KCS'.           APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '}15'.           APPEND IT_ZTDDF1.
   ENDIF.
*>>> 분할구분부호
   IT_ZTDDF1-ZFDDFDA = '{15'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTBLINR-ZFPRIN.   APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '121'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = 'KCS'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}15'.            APPEND IT_ZTDDF1.
*>>> 적하목록관리번호
   IT_ZTDDF1-ZFDDFDA = '{17'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = 'XC'.             APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTBLINOU-ZFGMNO.  APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTBLINOU-ZFMSN.   APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTBLINOU-ZFHSN.   APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}17'.            APPEND IT_ZTDDF1.
*>>> 반입근거번호
   IT_ZTDDF1-ZFDDFDA = '{17'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = 'ABP'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTBLINOU-ZFBTRNO. APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ''.               APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ''.               APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}17'.            APPEND IT_ZTDDF1.
*>>> 포장종류부호
   WRITE   ZTBLINR-ZFPKCN     TO      W_TEXT_AMOUNT
                         UNIT         ZTBLINR-ZFPKCNM.
   PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.
   IT_ZTDDF1-ZFDDFDA = '{1B'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = W_TEXT_AMOUNT.    APPEND IT_ZTDDF1.
*>>> UNIT ISO CODE <=== 내부코드 변환( PKG    단위 )
   W_MEINS = ZTBLINR-ZFPKCNM.
   PERFORM    SET_UNIT_CONV_TO_EXTERNAL CHANGING W_MEINS.
   IT_ZTDDF1-ZFDDFDA = W_MEINS.          APPEND IT_ZTDDF1.
*>>> 반입사고유형
      IT_ZTDDF1-ZFDDFDA = '{2E'.            APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = 'ACD'.            APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTBLINR-ZFINACD.  APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '}2E'.            APPEND IT_ZTDDF1.
*>>> 반입중량
      IT_ZTDDF1-ZFDDFDA = '{2F'.            APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = 'WT'.             APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ''.               APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = 'KG'.             APPEND IT_ZTDDF1.
      WRITE   ZTBLINR-ZFINWT     TO      W_TEXT_AMOUNT
                                 UNIT    ZTBLINR-ZFKG.
      PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.
      IT_ZTDDF1-ZFDDFDA = W_TEXT_AMOUNT.    APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '}2F'.            APPEND IT_ZTDDF1.
*>>> 반입사고중량
      IF NOT ZTBLINR-ZFINAWT IS INITIAL.
         IT_ZTDDF1-ZFDDFDA = '{2F'.            APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = 'WT'.             APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '14'.             APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = 'KG'.             APPEND IT_ZTDDF1.
         WRITE   ZTBLINR-ZFINAWT    TO      W_TEXT_AMOUNT
                                    UNIT    ZTBLINR-ZFKG.
         PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.
         IT_ZTDDF1-ZFDDFDA = W_TEXT_AMOUNT.    APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '}2F'.            APPEND IT_ZTDDF1.
      ENDIF.
*>>> 반입사고갯수
      IF NOT ZTBLINR-ZFINAQN IS INITIAL.
         IT_ZTDDF1-ZFDDFDA = '{2F'.            APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = 'CT'.             APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '14'.             APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = 'CT'.             APPEND IT_ZTDDF1.
         WRITE   ZTBLINR-ZFINAQN    TO      W_TEXT_AMOUNT
                                    UNIT    ZTBLINR-ZFCT.
         PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.
         IT_ZTDDF1-ZFDDFDA = W_TEXT_AMOUNT.    APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '}2F'.            APPEND IT_ZTDDF1.
      ENDIF.
*>>> 누계반입중량
      IF NOT ZTBLINR-ZFINTWT IS INITIAL.
         IT_ZTDDF1-ZFDDFDA = '{2F'.            APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = 'WT'.             APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '9'.              APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = 'KG'.             APPEND IT_ZTDDF1.
         WRITE   ZTBLINR-ZFINTWT    TO      W_TEXT_AMOUNT
                                    UNIT    ZTBLINR-ZFKG.
         PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.
         IT_ZTDDF1-ZFDDFDA = W_TEXT_AMOUNT.    APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '}2F'.            APPEND IT_ZTDDF1.
      ENDIF.
*>>> 누계반입갯수
      IF NOT ZTBLINR-ZFINTQN IS INITIAL.
         IT_ZTDDF1-ZFDDFDA = '{2F'.            APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = 'CT'.             APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '9'.              APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = 'CT'.             APPEND IT_ZTDDF1.
         WRITE   ZTBLINR-ZFINTQN    TO      W_TEXT_AMOUNT
                                    UNIT    ZTBLINR-ZFCT.
         PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.
         IT_ZTDDF1-ZFDDFDA = W_TEXT_AMOUNT.    APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '}2F'.            APPEND IT_ZTDDF1.
      ENDIF.
   IT_ZTDDF1-ZFDDFDA = '}1B'.            APPEND IT_ZTDDF1.

*--> 분할반입차수 정보
   IF ZTBLINR-ZFPRIN NE 'A'.
      WRITE   ZTBLINR-ZFPINS     TO      W_TEXT_AMOUNT.
      PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.
      IT_ZTDDF1-ZFDDFDA = '{1D'.            APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '5'.              APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = W_TEXT_AMOUNT.    APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '}1D'.            APPEND IT_ZTDDF1.
   ENDIF.

   CALL FUNCTION 'ZIM_EDI_FLAT_ITEM_INSERT'
        EXPORTING
              W_ZFDHENO         =        W_ZFDHENO
        TABLES
              IT_ZTDDF1         =        IT_ZTDDF1
        EXCEPTIONS
              DB_ERROR         =         4.

   IF SY-SUBRC NE 0.
       RAISE DB_ERROR.
   ENDIF.

ENDFUNCTION.
