FUNCTION ZIM_APPLOG_EDI_SEND.
*"----------------------------------------------------------------------
*"*"Local interface:
*"  IMPORTING
*"     VALUE(W_ZFBLNO) LIKE  ZTLG-ZFBLNO
*"     VALUE(W_ZFLGSEQ) LIKE  ZTLG-ZFLGSEQ
*"     VALUE(W_ZFDHENO) LIKE  ZTDHF1-ZFDHENO
*"  EXCEPTIONS
*"      DB_ERROR
*"----------------------------------------------------------------------
  CALL  FUNCTION 'ZIM_GET_LG_DOCUMENT'
     EXPORTING
        ZFBLNO              =          W_ZFBLNO
        ZFLGSEQ             =          W_ZFLGSEQ
     IMPORTING
        W_ZTLG              =          ZTLG
     TABLES
         IT_ZSLGGOD         =          IT_ZSLGGOD
         IT_ZSLGGOD_ORG     =          IT_ZSLGGOD_ORG
      EXCEPTIONS
            NOT_FOUND         =    4
            NOT_INPUT         =    8.

   CASE SY-SUBRC.
      WHEN 4.
         MESSAGE E053 WITH W_ZFBLNO.
      WHEN 8.
         MESSAGE E039.
   ENDCASE.

*-----------------------------------------------------------------------
* internal Table Append
*-----------------------------------------------------------------------
   REFRESH : IT_ZTDDF1.
   CLEAR : IT_ZTDDF1.
   IT_ZTDDF1-ZFDDENO = W_ZFDHENO.
*>>> 전자문서 시작
   IT_ZTDDF1-ZFDDFDA = '{10'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTLG-ZFAOCDE.     APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = W_ZFDHENO.        APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTLG-ZFEDFN.      APPEND IT_ZTDDF1.
*  IT_ZTDDF1-ZFDDFDA = 'AB'.             APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = 'AB'.             APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}10'.            APPEND IT_ZTDDF1.
*>>> 선박회사
   IT_ZTDDF1-ZFDDFDA = '{11'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = 'CA'.             APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTLG-ZFCARR1.     APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTLG-ZFCARR2.     APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTLG-ZFCARR3.     APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}11'.            APPEND IT_ZTDDF1.
*>>> 송하인명
   IT_ZTDDF1-ZFDDFDA = '{11'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = 'SE'.             APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTLG-ZFGSNM1.     APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTLG-ZFGSNM2.     APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTLG-ZFGSNM3.     APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}11'.            APPEND IT_ZTDDF1.
*>>> 신청인 및 신청인 주소
   IT_ZTDDF1-ZFDDFDA = '{11'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = 'MS'.             APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTLG-ZFAPPAD1.    APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTLG-ZFAPPAD2.    APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTLG-ZFAPPAD3.    APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}11'.            APPEND IT_ZTDDF1.
*>>> 신청인 전자서명
   IT_ZTDDF1-ZFDDFDA = '{11'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = 'AX'.             APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTLG-ZFELENM.     APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTLG-ZFREPRE.     APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTLG-ZFELEID.     APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}11'.            APPEND IT_ZTDDF1.
*>>> 상업송장금액
   WRITE   ZTLG-ZFCIAM        TO      W_TEXT_AMOUNT
                         CURRENCY     ZTLG-ZFCIAMC.
   PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.
   IT_ZTDDF1-ZFDDFDA = '{12'.             APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '77'.              APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = W_TEXT_AMOUNT.     APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTLG-ZFCIAMC.      APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}12'.             APPEND IT_ZTDDF1.
*>>> 해당 신용장(계약서) 번호
   IT_ZTDDF1-ZFDDFDA = '{13'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTLG-ZFDOCTY.     APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTLG-ZFDCNO.      APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}13'.            APPEND IT_ZTDDF1.
*>>> 해당 신용장(계약서) 번호
   IT_ZTDDF1-ZFDDFDA = '{13'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTLG-ZFBLTY.      APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTLG-ZFHBLNO.     APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}13'.            APPEND IT_ZTDDF1.
*>>> 항차/편명
   IT_ZTDDF1-ZFDDFDA = '{14'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '20'.             APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTLG-ZFCARNM.     APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTLG-ZFSSEQ.      APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}14'.            APPEND IT_ZTDDF1.
*>>> 도착예정일자
   IT_ZTDDF1-ZFDDFDA = '{15'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '132'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTLG-ZFETA+2.     APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '101'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}15'.            APPEND IT_ZTDDF1.
*>>> 선하증권발급일
   IT_ZTDDF1-ZFDDFDA = '{15'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '95'.             APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTLG-ZFTBIDT+2.   APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '101'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}15'.            APPEND IT_ZTDDF1.
*>>> 신청일자
   IT_ZTDDF1-ZFDDFDA = '{15'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '2AA'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTLG-ZFAPDT+2.    APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '101'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}15'.            APPEND IT_ZTDDF1.
*>>> 선적항
   IF NOT ZTLG-ZFSHCU IS INITIAL.
      IT_ZTDDF1-ZFDDFDA = '{16'.            APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '9'.              APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTLG-ZFSHCU.      APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '162'.            APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '5'.              APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTLG-ZFSHCUNM.    APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '}16'.            APPEND IT_ZTDDF1.
   ENDIF.
*>>> 도착항
   IF NOT ZTLG-ZFSHCU IS INITIAL.
      IT_ZTDDF1-ZFDDFDA = '{16'.            APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '8'.              APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTLG-ZFARCUM.     APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '162'.            APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '5'.              APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTLG-ZFARCUNM.    APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '}16'.            APPEND IT_ZTDDF1.
   ENDIF.
* 화물표시 번호
   IF NOT ( ZTLG-ZFGODR1 IS INITIAL AND ZTLG-ZFGODR2  IS INITIAL AND
            ZTLG-ZFGODR3 IS INITIAL AND ZTLG-ZFGODR4  IS INITIAL AND
            ZTLG-ZFGODR5 IS INITIAL AND ZTLG-ZFGODR6  IS INITIAL AND
            ZTLG-ZFGODR7 IS INITIAL AND ZTLG-ZFGODR7  IS INITIAL AND
            ZTLG-ZFGODR9 IS INITIAL AND ZTLG-ZFGODR10 IS INITIAL ).
      IT_ZTDDF1-ZFDDFDA = '{17'.            APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '28'.             APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTLG-ZFGODR1.     APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTLG-ZFGODR2.     APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTLG-ZFGODR3.     APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTLG-ZFGODR4.     APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTLG-ZFGODR5.     APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTLG-ZFGODR6.     APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTLG-ZFGODR7.     APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTLG-ZFGODR8.     APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTLG-ZFGODR9.     APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTLG-ZFGODR10.    APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '}17'.            APPEND IT_ZTDDF1.
   ENDIF.
* 포장형태(단위) 또는 화물단위 코드
  IF ZTLG-ZFPKCN GT 0.
     WRITE   ZTLG-ZFPKCN        TO      W_TEXT_AMOUNT
                           UNIT         ZTLG-ZFPKCNM.
     PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.
     IT_ZTDDF1-ZFDDFDA = '{18'.             APPEND IT_ZTDDF1.
     IT_ZTDDF1-ZFDDFDA = W_TEXT_AMOUNT.     APPEND IT_ZTDDF1.
     IT_ZTDDF1-ZFDDFDA = ZTLG-ZFCIAMC.      APPEND IT_ZTDDF1.
     IT_ZTDDF1-ZFDDFDA = '}18'.             APPEND IT_ZTDDF1.
  ENDIF.
* 상품명세
  LOOP AT IT_ZSLGGOD.
     W_MOD = SY-TABIX MOD 5.
     CASE W_MOD.
        WHEN 1.
          IT_ZTDDF1-ZFDDFDA = '{19'.             APPEND IT_ZTDDF1.
          IT_ZTDDF1-ZFDDFDA = 'AAA'.             APPEND IT_ZTDDF1.
          IT_ZTDDF1-ZFDDFDA = IT_ZSLGGOD-ZFGODS. APPEND IT_ZTDDF1.
        WHEN 0.
          IT_ZTDDF1-ZFDDFDA = IT_ZSLGGOD-ZFGODS. APPEND IT_ZTDDF1.
          IT_ZTDDF1-ZFDDFDA = '}19'.             APPEND IT_ZTDDF1.
        WHEN OTHERS.
          IT_ZTDDF1-ZFDDFDA = IT_ZSLGGOD-ZFGODS. APPEND IT_ZTDDF1.
     ENDCASE.
  ENDLOOP.
  IF W_MOD NE 0.
     W_MOD = 5 - W_MOD.
     DO W_MOD TIMES.
        IT_ZTDDF1-ZFDDFDA = ''.        APPEND IT_ZTDDF1.
     ENDDO.
     IT_ZTDDF1-ZFDDFDA = '}19'.        APPEND IT_ZTDDF1.
  ENDIF.
*>>> 결제기간 구분
   IF NOT ZTLG-ZFPTRM IS INITIAL.
      IT_ZTDDF1-ZFDDFDA = '{1A'.            APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '1AA'.            APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTLG-ZFPTRM.      APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTLG-ZFPTRMD.     APPEND IT_ZTDDF1.
*     IT_ZTDDF1-ZFDDFDA = '162'.            APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '}1A'.            APPEND IT_ZTDDF1.
   ENDIF.
*>>> 해당 신용장(계약서) 번호
   IT_ZTDDF1-ZFDDFDA = '{1B'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = 'BI'.             APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTLG-ZFISBNCD.    APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '25'.             APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = 'BOK'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTLG-ZFISBNM.     APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTLG-ZFISBB.      APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}1B'.            APPEND IT_ZTDDF1.

   CALL FUNCTION 'ZIM_EDI_FLAT_ITEM_INSERT'
        EXPORTING
              W_ZFDHENO         =        W_ZFDHENO
        TABLES
              IT_ZTDDF1         =        IT_ZTDDF1
        EXCEPTIONS
              DB_ERROR         =         4.

   IF SY-SUBRC NE 0.
      MESSAGE E118 WITH W_ZFDHENO.
   ENDIF.

ENDFUNCTION.
