FUNCTION ZIM_VATBIL_EDI_SEND.
*"----------------------------------------------------------------------
*"*"Local interface:
*"  IMPORTING
*"     VALUE(W_ZFVTNO) LIKE  ZTVT-ZFVTNO
*"     VALUE(W_ZFDHENO) LIKE  ZTDHF1-ZFDHENO
*"  EXCEPTIONS
*"      DB_ERROR
*"----------------------------------------------------------------------

   SELECT SINGLE * FROM ZTVT
                   WHERE ZFVTNO EQ W_ZFVTNO.
   IF SY-SUBRC NE 0.   MESSAGE E831.   ENDIF.

   SELECT SINGLE * FROM ZTVTSG1
                   WHERE ZFVTNO EQ W_ZFVTNO.
   IF SY-SUBRC NE 0.   MESSAGE E831.   ENDIF.

   SELECT * INTO TABLE IT_ZTVTSG3 FROM ZTVTSG3
                   WHERE ZFVTNO EQ W_ZFVTNO.
   IF SY-SUBRC NE 0.   MESSAGE E831.   ENDIF.

*-----------------------------------------------------------------------
* internal Table Append
*-----------------------------------------------------------------------
   REFRESH : IT_ZTDDF1.
   CLEAR : IT_ZTDDF1.
   IT_ZTDDF1-ZFDDENO = W_ZFDHENO.
*>>> 전자문서 시작
   IT_ZTDDF1-ZFDDFDA = '{10'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '2AI'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = W_ZFDHENO.        APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTVT-ZFEDFN.      APPEND IT_ZTDDF1.
*---> HEI HARD CODING ( 응답코드 : 수신자에게 보내는 응답유형 )
   IT_ZTDDF1-ZFDDFDA = 'CO'.             APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}10'.            APPEND IT_ZTDDF1.
*>>> 세금계산서　관리번호
   IT_ZTDDF1-ZFDDFDA = '{11'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = 'ACE'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = W_ZFDHENO.        APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}11'.            APPEND IT_ZTDDF1.
*------------> 공급자
*>>> 공급자
   IT_ZTDDF1-ZFDDFDA = '{12'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = 'SE'.             APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTVTSG1-ZFTXN1.   APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTVTSG1-ZFCONM1.  APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTVTSG1-ZFCHNM1.  APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTVTSG1-ZFLEID1.  APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTVTSG1-ZFADD11.  APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTVTSG1-ZFADD21.  APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTVTSG1-ZFADD31.  APPEND IT_ZTDDF1.
*  업태
   IF NOT ZTVTSG1-ZFBUTY1 IS INITIAL.
       IT_ZTDDF1-ZFDDFDA = '{20'.            APPEND IT_ZTDDF1.
       IT_ZTDDF1-ZFDDFDA = 'SG'.             APPEND IT_ZTDDF1.
       IT_ZTDDF1-ZFDDFDA = ZTVTSG1-ZFBUTY1.  APPEND IT_ZTDDF1.
       IT_ZTDDF1-ZFDDFDA = '}20'.            APPEND IT_ZTDDF1.
   ENDIF.
*  종목
   IF NOT ZTVTSG1-ZFBUGR1 IS INITIAL.
       IT_ZTDDF1-ZFDDFDA = '{20'.            APPEND IT_ZTDDF1.
       IT_ZTDDF1-ZFDDFDA = 'HN'.             APPEND IT_ZTDDF1.
       IT_ZTDDF1-ZFDDFDA = ZTVTSG1-ZFBUGR1.  APPEND IT_ZTDDF1.
       IT_ZTDDF1-ZFDDFDA = '}20'.            APPEND IT_ZTDDF1.
   ENDIF.
   IT_ZTDDF1-ZFDDFDA = '}12'.            APPEND IT_ZTDDF1.
*---------------------------------> 공급받는자
*>>> 공급받는자
   IT_ZTDDF1-ZFDDFDA = '{12'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = 'BY'.             APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTVTSG1-ZFTXN2.   APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTVTSG1-ZFCONM2.  APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTVTSG1-ZFCHNM2.  APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ''.               APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTVTSG1-ZFADD12.  APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTVTSG1-ZFADD22.  APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTVTSG1-ZFADD32.  APPEND IT_ZTDDF1.
*  업태
   IF NOT ZTVTSG1-ZFBUTY2 IS INITIAL.
       IT_ZTDDF1-ZFDDFDA = '{20'.            APPEND IT_ZTDDF1.
       IT_ZTDDF1-ZFDDFDA = 'SG'.             APPEND IT_ZTDDF1.
       IT_ZTDDF1-ZFDDFDA = ZTVTSG1-ZFBUTY2.  APPEND IT_ZTDDF1.
       IT_ZTDDF1-ZFDDFDA = '}20'.            APPEND IT_ZTDDF1.
   ENDIF.
*  종목
   IF NOT ZTVTSG1-ZFBUGR2 IS INITIAL.
       IT_ZTDDF1-ZFDDFDA = '{20'.            APPEND IT_ZTDDF1.
       IT_ZTDDF1-ZFDDFDA = 'HN'.             APPEND IT_ZTDDF1.
       IT_ZTDDF1-ZFDDFDA = ZTVTSG1-ZFBUGR2.  APPEND IT_ZTDDF1.
       IT_ZTDDF1-ZFDDFDA = '}20'.            APPEND IT_ZTDDF1.
   ENDIF.
   IT_ZTDDF1-ZFDDFDA = '}12'.            APPEND IT_ZTDDF1.
*----------------------> 수탁자
*>>> 수탁자
   IF NOT ZTVTSG1-ZFTXN3 IS INITIAL  OR
      NOT ZTVTSG1-ZFCONM3 IS INITIAL OR
      NOT ZTVTSG1-ZFCHNM3 IS INITIAL OR
      NOT ZTVTSG1-ZFADD13 IS INITIAL OR
      NOT ZTVTSG1-ZFADD23 IS INITIAL OR
      NOT ZTVTSG1-ZFADD33 IS INITIAL OR
      NOT ZTVTSG1-ZFBUTY3 IS INITIAL OR
      NOT ZTVTSG1-ZFBUGR3 IS INITIAL OR
      NOT ZTVTSG1-ZFLEID3 IS INITIAL.

      IT_ZTDDF1-ZFDDFDA = '{12'.            APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = 'AG'.             APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTVTSG1-ZFTXN3.   APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTVTSG1-ZFCONM3.  APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTVTSG1-ZFCHNM3.  APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTVTSG1-ZFLEID3.  APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTVTSG1-ZFADD13.  APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTVTSG1-ZFADD23.  APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTVTSG1-ZFADD33.  APPEND IT_ZTDDF1.
*  업태
      IF NOT ZTVTSG1-ZFBUTY3 IS INITIAL.
          IT_ZTDDF1-ZFDDFDA = '{20'.            APPEND IT_ZTDDF1.
          IT_ZTDDF1-ZFDDFDA = 'SG'.             APPEND IT_ZTDDF1.
          IT_ZTDDF1-ZFDDFDA = ZTVTSG1-ZFBUTY3.  APPEND IT_ZTDDF1.
          IT_ZTDDF1-ZFDDFDA = '}20'.            APPEND IT_ZTDDF1.
      ENDIF.
*  종목
      IF NOT ZTVTSG1-ZFBUGR3 IS INITIAL.
          IT_ZTDDF1-ZFDDFDA = '{20'.            APPEND IT_ZTDDF1.
          IT_ZTDDF1-ZFDDFDA = 'HN'.             APPEND IT_ZTDDF1.
          IT_ZTDDF1-ZFDDFDA = ZTVTSG1-ZFBUGR3.  APPEND IT_ZTDDF1.
       IT_ZTDDF1-ZFDDFDA = '}20'.            APPEND IT_ZTDDF1.
      ENDIF.
      IT_ZTDDF1-ZFDDFDA = '}12'.            APPEND IT_ZTDDF1.
   ENDIF.

*>>> 작성일자
   IT_ZTDDF1-ZFDDFDA = '{13'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '182'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = ZTVT-ZFVCDT+2(6). APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '101'.            APPEND IT_ZTDDF1.
* 공란수
   IT_ZTDDF1-ZFDDFDA =  ZTVT-ZFVERC.     APPEND IT_ZTDDF1.
* 공급가액
   WRITE   ZTVT-ZFVTAMT  TO           W_TEXT_AMOUNT
                         CURRENCY     'KRW'.
   PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.
   IT_ZTDDF1-ZFDDFDA = '{21'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '79'.             APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = W_TEXT_AMOUNT.    APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = 'KRW'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}21'.            APPEND IT_ZTDDF1.
* 세액...
   WRITE   ZTVT-ZFTXAMT  TO           W_TEXT_AMOUNT
                         CURRENCY     'KRW'.
   PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.
   IT_ZTDDF1-ZFDDFDA = '{21'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '176'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = W_TEXT_AMOUNT.    APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = 'KRW'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}21'.            APPEND IT_ZTDDF1.
   IT_ZTDDF1-ZFDDFDA = '}13'.            APPEND IT_ZTDDF1.

* 기타( 참조사항)
   IF NOT ZTVT-ZFREMK1 IS INITIAL OR
      NOT ZTVT-ZFREMK2 IS INITIAL OR
      NOT ZTVT-ZFREMK3 IS INITIAL OR
      NOT ZTVT-ZFREMK4 IS INITIAL OR
      NOT ZTVT-ZFREMK5 IS INITIAL.
      IT_ZTDDF1-ZFDDFDA = '{14'.            APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = 'AAI'.            APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTVT-ZFREMK1.     APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTVT-ZFREMK2.     APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTVT-ZFREMK3.     APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTVT-ZFREMK4.     APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTVT-ZFREMK5.     APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '}14'.            APPEND IT_ZTDDF1.
   ENDIF.

*>>>>>> 세금계산서의 공급물품 세부내역을 기재 (M)
   LOOP AT IT_ZTVTSG3.
      IT_ZTDDF1-ZFDDFDA = '{15'.                APPEND IT_ZTDDF1.
* 일련번호
      IT_ZTDDF1-ZFDDFDA = IT_ZTVTSG3-ZFLSG3.    APPEND IT_ZTDDF1.
* LINE 별 공급일자
      IF NOT IT_ZTVTSG3-ZFSUDT IS INITIAL.
         IT_ZTDDF1-ZFDDFDA = '{22'.                   APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '35'.                    APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = IT_ZTVTSG3-ZFSUDT+2(6).  APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '101'.                   APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '}22'.                   APPEND IT_ZTDDF1.
      ENDIF.
* 해당 공급물품의 품목명
      IF NOT IT_ZTVTSG3-ZFGONM IS INITIAL.
         IT_ZTDDF1-ZFDDFDA = '{23'.                   APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '1AA'.                   APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = IT_ZTVTSG3-ZFGONM.       APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '}23'.                   APPEND IT_ZTDDF1.
      ENDIF.
* 공급물품의 규격
      IF NOT IT_ZTVTSG3-ZFGOSD1 IS INITIAL OR
         NOT IT_ZTVTSG3-ZFGOSD2 IS INITIAL OR
         NOT IT_ZTVTSG3-ZFGOSD3 IS INITIAL OR
         NOT IT_ZTVTSG3-ZFGOSD4 IS INITIAL OR
         NOT IT_ZTVTSG3-ZFGOSD5 IS INITIAL.
         IT_ZTDDF1-ZFDDFDA = '{24'.                   APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = 'AAA'.                   APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = IT_ZTVTSG3-ZFGOSD1.      APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = IT_ZTVTSG3-ZFGOSD2.      APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = IT_ZTVTSG3-ZFGOSD3.      APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = IT_ZTVTSG3-ZFGOSD4.      APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = IT_ZTVTSG3-ZFGOSD5.      APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '}24'.                   APPEND IT_ZTDDF1.
      ENDIF.
* 라인별 비고(참조사항)
      IF NOT IT_ZTVTSG3-ZFREMK1 IS INITIAL OR
         NOT IT_ZTVTSG3-ZFREMK2 IS INITIAL OR
         NOT IT_ZTVTSG3-ZFREMK3 IS INITIAL OR
         NOT IT_ZTVTSG3-ZFREMK4 IS INITIAL OR
         NOT IT_ZTVTSG3-ZFREMK5 IS INITIAL.
         IT_ZTDDF1-ZFDDFDA = '{24'.                   APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = 'ACB'.                   APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = IT_ZTVTSG3-ZFREMK1.      APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = IT_ZTVTSG3-ZFREMK2.      APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = IT_ZTVTSG3-ZFREMK3.      APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = IT_ZTVTSG3-ZFREMK4.      APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = IT_ZTVTSG3-ZFREMK5.      APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '}24'.                   APPEND IT_ZTDDF1.
      ENDIF.
* 라인별 공급물품의 수량
      IF NOT IT_ZTVTSG3-ZFQUN  IS INITIAL.
         WRITE  IT_ZTVTSG3-ZFQUN    TO     W_TEXT_AMOUNT
                UNIT IT_ZTVTSG3-ZFQUNM.
         PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.

         IT_ZTDDF1-ZFDDFDA = '{25'.                   APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '1'.                     APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = W_TEXT_AMOUNT.           APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = IT_ZTVTSG3-ZFQUNM.       APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '}25'.                   APPEND IT_ZTDDF1.
      ENDIF.
* 라인별 공급물품의 수량 소례
      IF NOT IT_ZTVTSG3-ZFQUNS IS INITIAL.
         WRITE  IT_ZTVTSG3-ZFQUNS   TO     W_TEXT_AMOUNT
                UNIT IT_ZTVTSG3-ZFQUNSM.
         PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.

         IT_ZTDDF1-ZFDDFDA = '{25'.                   APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '3'.                     APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = W_TEXT_AMOUNT.           APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = IT_ZTVTSG3-ZFQUNSM.      APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '}25'.                   APPEND IT_ZTDDF1.
      ENDIF.
* 각 규격별 단가
      IF NOT IT_ZTVTSG3-NETPR IS INITIAL.
*------------------> 단가
         WRITE  IT_ZTVTSG3-NETPR    TO     W_TEXT_AMOUNT
                CURRENCY IT_ZTVTSG3-ZFSAMFC.
         PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.

         IT_ZTDDF1-ZFDDFDA = '{26'.                   APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = 'CAL'.                   APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = W_TEXT_AMOUNT.           APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = 'PE'.                    APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = 'CUP'.                   APPEND IT_ZTDDF1.
*-----------------> 단가 기준
         WRITE  IT_ZTVTSG3-PEINH    TO     W_TEXT_AMOUNT.
         PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.
         IT_ZTDDF1-ZFDDFDA = W_TEXT_AMOUNT.           APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = IT_ZTVTSG3-BPRME.        APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '}26'.                   APPEND IT_ZTDDF1.
      ENDIF.
* 공급가액
      IF NOT IT_ZTVTSG3-ZFSAMK IS INITIAL.
         WRITE  IT_ZTVTSG3-ZFSAMK   TO     W_TEXT_AMOUNT
                CURRENCY IT_ZTVTSG3-ZFKRW.
         PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.
         IT_ZTDDF1-ZFDDFDA = '{27'.                   APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '203'.                   APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = W_TEXT_AMOUNT.           APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = IT_ZTVTSG3-ZFKRW.        APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '}27'.                   APPEND IT_ZTDDF1.
      ENDIF.
* 세액
      IF NOT IT_ZTVTSG3-ZFTXAMT IS INITIAL.
         WRITE  IT_ZTVTSG3-ZFTXAMT  TO     W_TEXT_AMOUNT
                CURRENCY IT_ZTVTSG3-ZFKRW.
         PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.
         IT_ZTDDF1-ZFDDFDA = '{27'.                   APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '124'.                   APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = W_TEXT_AMOUNT.           APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = IT_ZTVTSG3-ZFKRW.        APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '}27'.                   APPEND IT_ZTDDF1.
      ENDIF.
* 외화-공급가액
      IF NOT IT_ZTVTSG3-ZFSAMF IS INITIAL.
         WRITE  IT_ZTVTSG3-ZFSAMF   TO     W_TEXT_AMOUNT
                CURRENCY IT_ZTVTSG3-ZFSAMFC.
         PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.
         IT_ZTDDF1-ZFDDFDA = '{27'.                   APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '261'.                   APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = W_TEXT_AMOUNT.           APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = IT_ZTVTSG3-ZFSAMFC.      APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '}27'.                   APPEND IT_ZTDDF1.
      ENDIF.
* Line별 공급가액 소계
      IF NOT IT_ZTVTSG3-ZFSAMKS IS INITIAL.
         WRITE  IT_ZTVTSG3-ZFSAMKS  TO     W_TEXT_AMOUNT
                CURRENCY IT_ZTVTSG3-ZFKRW.
         PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.
         IT_ZTDDF1-ZFDDFDA = '{27'.                   APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '17'.                    APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = W_TEXT_AMOUNT.           APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = IT_ZTVTSG3-ZFKRW.        APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '}27'.                   APPEND IT_ZTDDF1.
      ENDIF.
* Line별 세액 소계
      IF NOT IT_ZTVTSG3-ZFTXAMS IS INITIAL.
         WRITE  IT_ZTVTSG3-ZFTXAMS  TO     W_TEXT_AMOUNT
                CURRENCY IT_ZTVTSG3-ZFKRW.
         PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.
         IT_ZTDDF1-ZFDDFDA = '{27'.                   APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '168'.                   APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = W_TEXT_AMOUNT.           APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = IT_ZTVTSG3-ZFKRW.        APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '}27'.                   APPEND IT_ZTDDF1.
      ENDIF.
* Line별 공급가액(외화) 소계
      IF NOT IT_ZTVTSG3-ZFSAMFS IS INITIAL.
         WRITE  IT_ZTVTSG3-ZFSAMFS  TO     W_TEXT_AMOUNT
                CURRENCY IT_ZTVTSG3-ZFKRW.
         PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.
         IT_ZTDDF1-ZFDDFDA = '{27'.                   APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '289'.                   APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = W_TEXT_AMOUNT.           APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = IT_ZTVTSG3-ZFSAMFC.      APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '}27'.                   APPEND IT_ZTDDF1.
      ENDIF.
* Line별 전신환 매입율
      IF NOT IT_ZTVTSG3-ZFEXRT  IS INITIAL.
         WRITE  IT_ZTVTSG3-ZFEXRT   TO     W_TEXT_AMOUNT.
         PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.
         IT_ZTDDF1-ZFDDFDA = '{28'.                   APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = W_TEXT_AMOUNT.           APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '}28'.                   APPEND IT_ZTDDF1.
      ENDIF.
      IT_ZTDDF1-ZFDDFDA = '}15'.                APPEND IT_ZTDDF1.
   ENDLOOP.

*>>> 총 금액
   IF NOT ZTVT-ZFTOTAM IS INITIAL.
      WRITE  ZTVT-ZFTOTAM        TO     W_TEXT_AMOUNT
              CURRENCY ZTVT-ZFKRW.
      PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.
      IT_ZTDDF1-ZFDDFDA = '{16'.                 APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '128'.                 APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = W_TEXT_AMOUNT.         APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTVT-ZFKRW.            APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '}16'.                 APPEND IT_ZTDDF1.
   ENDIF.
*>>> 총 공급가액
   IF NOT ZTVT-ZFTSAMK IS INITIAL.
      WRITE  ZTVT-ZFTSAMK        TO     W_TEXT_AMOUNT
              CURRENCY ZTVT-ZFKRW.
      PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.
      IT_ZTDDF1-ZFDDFDA = '{16'.                 APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '79'.                  APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = W_TEXT_AMOUNT.         APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTVT-ZFKRW.            APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '}16'.                 APPEND IT_ZTDDF1.
   ENDIF.
*>>> 총 세액 합계
   IF NOT ZTVT-ZFTTXAM IS INITIAL.
      WRITE  ZTVT-ZFTTXAM        TO     W_TEXT_AMOUNT
              CURRENCY ZTVT-ZFKRW.
      PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.
      IT_ZTDDF1-ZFDDFDA = '{16'.                 APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '176'.                 APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = W_TEXT_AMOUNT.         APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTVT-ZFKRW.            APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '}16'.                 APPEND IT_ZTDDF1.
   ENDIF.
*>>> 총 공급가액 합계 - 외화
   IF NOT ZTVT-ZFTSAMF IS INITIAL.
      WRITE  ZTVT-ZFTSAMF        TO     W_TEXT_AMOUNT
              CURRENCY ZTVT-ZFTSAMFC.
      PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.
      IT_ZTDDF1-ZFDDFDA = '{16'.                 APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '14'.                  APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = W_TEXT_AMOUNT.         APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTVT-ZFTSAMFC.         APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '}16'.                 APPEND IT_ZTDDF1.
   ENDIF.

*>>> 총 수량
   IF NOT ZTVT-ZFTQUN  IS INITIAL.
      WRITE  ZTVT-ZFTQUN         TO     W_TEXT_AMOUNT
              UNIT     ZTVT-ZFTQUNM.
      PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.
      IT_ZTDDF1-ZFDDFDA = '{17'.                 APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '1AA'.                 APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = W_TEXT_AMOUNT.         APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTVT-ZFTQUNM.          APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '}17'.                 APPEND IT_ZTDDF1.
   ENDIF.
* 결제 방법
   IF NOT ZTVT-ZFVPTB  IS INITIAL.
      IT_ZTDDF1-ZFDDFDA = '{18'.                 APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTVT-ZFVPTB.           APPEND IT_ZTDDF1.
* >>>>>>>>> 개설 원화 금액
      IF NOT ZTVT-ZFVPAMK IS INITIAL.
         WRITE  ZTVT-ZFVPAMK        TO     W_TEXT_AMOUNT
                CURRENCY ZTVT-ZFKRW.
         PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.
         IT_ZTDDF1-ZFDDFDA = '{29'.                   APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '2AE'.                   APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = W_TEXT_AMOUNT.           APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = ZTVT-ZFKRW.              APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '}29'.                   APPEND IT_ZTDDF1.
      ENDIF.
* >>>>>>>>> 개설 외화 금액
      IF NOT ZTVT-ZFVPAMF IS INITIAL.
         WRITE  ZTVT-ZFVPAMF        TO     W_TEXT_AMOUNT
                CURRENCY ZTVT-ZFTSAMFC.
         PERFORM    P2000_WRITE_NO_MASK     CHANGING  W_TEXT_AMOUNT.
         IT_ZTDDF1-ZFDDFDA = '{29'.                   APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '2AD'.                   APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = W_TEXT_AMOUNT.           APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = ZTVT-ZFTSAMFC.           APPEND IT_ZTDDF1.
         IT_ZTDDF1-ZFDDFDA = '}29'.                   APPEND IT_ZTDDF1.
      ENDIF.
      IT_ZTDDF1-ZFDDFDA = '}18'.                 APPEND IT_ZTDDF1.
   ENDIF.
* 영수/청구 구분
   IF NOT ZTVT-ZFVTCD IS INITIAL.
      IT_ZTDDF1-ZFDDFDA = '{19'.                   APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = ZTVT-ZFVTCD.             APPEND IT_ZTDDF1.
      IT_ZTDDF1-ZFDDFDA = '}19'.                   APPEND IT_ZTDDF1.
   ENDIF.
*-----------------------------------------------------------------------
* Item Insert
   CALL FUNCTION 'ZIM_EDI_FLAT_ITEM_INSERT'
        EXPORTING
              W_ZFDHENO         =        W_ZFDHENO
        TABLES
              IT_ZTDDF1         =        IT_ZTDDF1
        EXCEPTIONS
              DB_ERROR         =         4.

   IF SY-SUBRC NE 0.
      MESSAGE E118 WITH W_ZFDHENO.
   ENDIF.

ENDFUNCTION.
