FUNCTION ZPMF_PDA104.
*"----------------------------------------------------------------------
*"*"Local interface:
*"  EXPORTING
*"     VALUE(SUBRC) LIKE  SY-SUBRC
*"  TABLES
*"      T104 STRUCTURE  ZSPM_PDA104
*"      TMSEG STRUCTURE  ZMSEG
*"      MESSTAB STRUCTURE  ZBDCMSG
*"----------------------------------------------------------------------
  DATA : IT_MSEG LIKE TABLE OF MSEG WITH HEADER LINE.

  READ TABLE T104 INDEX 1.


  PERFORM CONVERSION_EXIT_ALPHA_INPUT USING T104-MBLNR T104-MBLNR.

  MATERIALDOCUMENT = T104-MBLNR.
  MATDOCUMENTYEAR = T104-BUDAT+0(4).

  CALL FUNCTION 'BAPI_GOODSMVT_CANCEL'
    EXPORTING
      MATERIALDOCUMENT          = MATERIALDOCUMENT
      MATDOCUMENTYEAR           = MATDOCUMENTYEAR
*     GOODSMVT_PSTNG_DATE       = T104-BUDAT
*     GOODSMVT_PR_UNAME         =
    IMPORTING
      GOODSMVT_HEADRET          = GS_HEADRET
    TABLES
      RETURN                    = GT_RETURN
*     GOODSMVT_MATDOCITEM       = MATERIALDOCUMENT
          .


  SUBRC = 4.
  IF NOT GS_HEADRET-MAT_DOC IS INITIAL.
    SUBRC = 0.

    CALL FUNCTION 'BAPI_TRANSACTION_COMMIT'
         EXPORTING
              WAIT = 'X'.

    WAIT UP TO 1 SECONDS.

    SELECT * INTO CORRESPONDING FIELDS OF TABLE IT_MSEG
           FROM MSEG
          WHERE MBLNR EQ GS_HEADRET-MAT_DOC
          AND   MJAHR EQ GS_HEADRET-DOC_YEAR.
    LOOP AT IT_MSEG.
      MOVE-CORRESPONDING IT_MSEG TO TMSEG.

      SELECT SINGLE MAKTX INTO TMSEG-MAKTX
             FROM MAKT
            WHERE MATNR EQ TMSEG-MATNR
            AND   SPRAS EQ SY-LANGU.

     PERFORM CONVERSION_EXIT_ALPHA_OUTPUT USING TMSEG-MBLNR TMSEG-MBLNR
.
     PERFORM CONVERSION_EXIT_MATN1_OUTPUT USING TMSEG-MATNR TMSEG-MATNR
.
     PERFORM CONVERSION_EXIT_CUNIT_OUTPUT USING TMSEG-ERFME TMSEG-ERFME
.

      APPEND TMSEG. CLEAR TMSEG.
    ENDLOOP.
  ENDIF.

  LOOP AT GT_RETURN.
    MESSTAB-MSGTYP = GT_RETURN-TYPE.
    MESSTAB-MSGID = GT_RETURN-ID.
    MESSTAB-MSGNR = GT_RETURN-NUMBER.
    MESSTAB-MSGV1 = GT_RETURN-MESSAGE_V1.
    MESSTAB-MSGV2 = GT_RETURN-MESSAGE_V2.
    MESSTAB-MSGV3 = GT_RETURN-MESSAGE_V3.
    MESSTAB-MSGV4 = GT_RETURN-MESSAGE_V4.
    MESSTAB-MESSAGE_TEXT = GT_RETURN-MESSAGE.

    APPEND MESSTAB. CLEAR MESSTAB.
  ENDLOOP.





ENDFUNCTION.
