FUNCTION ZPMF_PDA704 .
*"----------------------------------------------------------------------
*"*"Local interface:
*"  EXPORTING
*"     VALUE(SUBRC) LIKE  SY-SUBRC
*"  TABLES
*"      T704 STRUCTURE  ZSPM_PDA704 OPTIONAL
*"      T704R STRUCTURE  ZSPM_PDA704R OPTIONAL
*"----------------------------------------------------------------------
  DATA : L_INDEX LIKE SY-TABIX,
         L_INACT LIKE JEST-INACT,
         L_DATE  LIKE EQUZ-DATBI.

  READ TABLE T704 INDEX 1.

  RANGES : R_STORT FOR ILOA-STORT,
           R_EQKTX FOR EQKT-EQKTX.

  READ TABLE T704 INDEX 1.

  IF NOT T704-STORT IS  INITIAL.
    R_STORT-SIGN = 'I'.
    R_STORT-OPTION = 'CP'.
*    R_STORT-OPTION = 'EQ'. "PAUL
    R_STORT-LOW = T704-STORT.
    APPEND R_STORT.
  ENDIF.

  IF NOT T704-EQKTX IS  INITIAL.
    R_EQKTX-SIGN = 'I'.
    R_EQKTX-OPTION = 'CP'.
*    R_STORT-OPTION = 'EQ'. PAUL
    R_EQKTX-LOW = T704-EQKTX.
    APPEND R_EQKTX.
  ENDIF.

  SELECT E~EQUNR
         X~ABCKZ
         X~STORT
    INTO CORRESPONDING FIELDS OF TABLE T704R
    FROM EQUZ AS E INNER JOIN ILOA AS X
      ON E~ILOAN EQ X~ILOAN
   WHERE E~DATBI EQ '99991231' "GE SY-DATUM
     AND X~SWERK EQ T704-SWERK
     AND X~STORT IN R_STORT
     AND X~BEBER EQ T704-BEBER
     AND X~OWNER EQ ''.

  LOOP AT T704R.
    L_INDEX = SY-TABIX.

    SELECT SINGLE EQKTX
      INTO T704R-EQKTX_E
      FROM EQKT
     WHERE EQUNR EQ T704R-EQUNR
       AND SPRAS EQ 'E'
       AND EQKTU NE 'NOT USED'
       AND EQKTX IN R_EQKTX.
    IF SY-SUBRC <> 0.
      DELETE T704R INDEX L_INDEX.
      CONTINUE.
    ENDIF.

** Changed on 04/11/11
*    CLEAR: L_INACT.
*    SELECT SINGLE INACT INTO L_INACT
*             FROM EQUI AS A
*             INNER JOIN JEST AS B
*             ON A~OBJNR = B~OBJNR
*             WHERE EQUNR EQ T704R-EQUNR
*               AND STAT = 'I0076'.
*    IF SY-SUBRC = 0 AND L_INACT IS INITIAL.
*      DELETE T704R INDEX L_INDEX.
*      CONTINUE.
*    ENDIF.

** End of change

    SELECT SINGLE EQKTX INTO T704R-EQKTX_C
           FROM EQKT
          WHERE EQUNR EQ T704R-EQUNR
          AND   SPRAS EQ 'C'.

    PERFORM CONVERSION_EXIT_ALPHA_OUTPUT USING T704R-EQUNR T704R-EQUNR.

    MODIFY T704R INDEX L_INDEX.
  ENDLOOP.

  DESCRIBE TABLE T704R LINES SY-INDEX.
  IF SY-INDEX = 0.
    SUBRC = 4.
  ELSE.
    SUBRC = 0.
  ENDIF.

  SORT T704R.
ENDFUNCTION.
