*----------------------------------------------------------------------*
*   INCLUDE ZEMMPM53C_INFO_TOP                                         *
*----------------------------------------------------------------------*
REPORT  ZEMMPM53C_INFO  MESSAGE-ID ZMMM .

TYPE-POOLS: SLIS, VRM.
TABLES:ZTMM_IF_PRICE,LFA1,EINA,T685,USR01,EINE,MARA,MARC,KONH,A018 .


INCLUDE <ICON>.
INCLUDE <SYMBOL>.
CLASS CL_GUI_RESOURCES DEFINITION LOAD.
*Internal table declation

DATA: IT_IF_PRICE TYPE ZTMM_IF_PRICE OCCURS 0 WITH HEADER LINE.

*output
DATA : BEGIN OF GT_OUT OCCURS 0,
        ICON(4),
        CHKBOX  TYPE C,
        LIGHT   TYPE C,
        TABCOLOR     TYPE SLIS_T_SPECIALCOL_ALV.
        INCLUDE STRUCTURE ZTMM_IF_PRICE.
DATA:  END OF GT_OUT.
DATA : IT_OUT LIKE GT_OUT OCCURS 0 WITH HEADER LINE.
DATA  :WA_OUT LIKE GT_OUT.
DATA : IT_A018 LIKE A018 OCCURS 0 WITH HEADER LINE.
DATA:  LD_TABLE  LIKE GT_OUT OCCURS 0 WITH HEADER LINE.
*Data declation
DATA : W_INT TYPE I,
       EXIST.
DATA : P_TCODE LIKE SY-TCODE.
DATA : ALREADY_FLAG TYPE C,
       LD_DATE LIKE SY-DATUM.
DATA : C_NUM(2) TYPE N,
       Z_SEQ(2) TYPE N.
DATA : W_DATE(8) TYPE N,
       W_DATE1(8) TYPE N,
       W_DATE2(8) TYPE N,
       W_DATBI(8) TYPE N,
       VAKE_DATAB(14).
DATA : DEL_DATE LIKE SY-DATUM,
       LD_LDC(3) TYPE C.
*BDC
DATA: IT_MSG      LIKE TABLE OF BDCMSGCOLL  WITH HEADER LINE,
      IT_BDCDATA  LIKE TABLE OF BDCDATA     WITH HEADER LINE.

DATA: L_MESSA(100).

DATA : E_LIFNR LIKE EINAE-LIFNR,
       E_MATNR LIKE EINAE-MATNR.

DATA : BEGIN OF LDC_KONP OCCURS 0,
       KSCHL LIKE KONP-KSCHL,
       KBETR LIKE KONP-KBETR,
END OF LDC_KONP.
DATA : IT_COMP LIKE LDC_KONP OCCURS 0 WITH HEADER LINE.

*ALV ----
DATA: GT_FIELDCAT TYPE SLIS_T_FIELDCAT_ALV,
      GS_LAYOUT   TYPE SLIS_LAYOUT_ALV,
      GT_SP_GROUP TYPE SLIS_T_SP_GROUP_ALV,
      GT_EVENTS   TYPE SLIS_T_EVENT,
      GT_SORTS    TYPE SLIS_T_SORTINFO_ALV WITH HEADER LINE,
      GS_PRNT     TYPE SLIS_PRINT_ALV.

DATA: WA_REPID LIKE SY-REPID,
      WA_VAR_SAVE(1) TYPE C             VALUE  'A',
      WA_DEFAULT(1)  TYPE C,
      WA_EXIT(1) TYPE C,
      WA_VARIANT LIKE DISVARIANT,
      WA_VAR LIKE DISVARIANT,
      WA_ALV_FUNCTION_NAME(30) TYPE C VALUE 'REUSE_ALV_GRID_LIST',
      WA_ALV_GET_INFO_NAME(40) TYPE C.

DATA : W_FIELDCAT TYPE SLIS_T_FIELDCAT_ALV WITH HEADER LINE,
       W_EVENTCAT TYPE SLIS_T_EVENT WITH HEADER LINE,
       W_SELFIELD TYPE SLIS_SELFIELD,
       W_SORTCAT  TYPE SLIS_T_SORTINFO_ALV WITH HEADER LINE,
       W_COL_POS  TYPE I,
       W_PROGRAM  LIKE SY-REPID,
       W_TOP_OF_PAGE TYPE SLIS_T_LISTHEADER,
       W_LINE1 TYPE SLIS_LISTHEADER.

*---// Constants
CONSTANTS: C_ICON_EQUAL(4)          VALUE ICON_GREEN_LIGHT,
           C_ICON_DIFF(4)           VALUE ICON_YELLOW_LIGHT,
           C_ICON_ERR(4)            VALUE ICON_RED_LIGHT,
           C_ICON_NONE(4)           VALUE ICON_LIGHT_OUT.
CONSTANTS: C_F2CODE    LIKE SY-UCOMM       VALUE '&ETA'.


**----------------------------------------------------------------------
* SELECTION-SCREEN
*----------------------------------------------------------------------
SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-001.

SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME TITLE TEXT-002.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT  1(10) TEXT-003.
SELECTION-SCREEN POSITION 12.
PARAMETERS  PB_E TYPE C  RADIOBUTTON GROUP RA01.
SELECTION-SCREEN COMMENT  22(9) TEXT-004.
SELECTION-SCREEN POSITION 31.
PARAMETERS  PB_S TYPE C  RADIOBUTTON GROUP RA01.
SELECTION-SCREEN COMMENT  41(11) TEXT-005.
SELECTION-SCREEN POSITION 52.
PARAMETERS  PB_A TYPE C  RADIOBUTTON GROUP RA01.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK B2.

*Selection condition
SELECTION-SCREEN BEGIN OF BLOCK B3 WITH FRAME TITLE TEXT-002.

SELECT-OPTIONS : S_LIFNR FOR ZTMM_IF_PRICE-LIFNR,
                 S_MATNR FOR ZTMM_IF_PRICE-MATNR,
                 S_INF_D FOR EINE-ERDAT,
                 S_EKGRP FOR EINE-EKGRP.      "Purchaing group

SELECTION-SCREEN END OF BLOCK B3.
PARAMETERS P_MODE TYPE C DEFAULT 'N'.
SELECTION-SCREEN END OF BLOCK B1.
