*----------------------------------------------------------------------*
*   INCLUDE Z_APP_DELETE_TOP_R252718
*----------------------------------------------------------------------*
REPORT  Z_APP_DELETE_TOP_R252718 MESSAGE-ID ZMPP.

TABLES : PLAF,RESB,ZTPP_STATUS,ZTPP_BFST_BK, AUSP.

DATA  : IT_BFST      LIKE  ZTPP_BFST  OCCURS 0  WITH HEADER LINE,
        WA_BFST      LIKE  IT_BFST OCCURS 0  WITH HEADER LINE,
        IT_DELETE_C  LIKE  ZTPP_BFST  OCCURS 0  WITH HEADER LINE,
        IT_DELETE_S  LIKE  ZTPP_BFST  OCCURS 0  WITH HEADER LINE.
DATA:   IT_BFST_BK   LIKE  ZTPP_BFST  OCCURS 0  WITH HEADER LINE.
DATA : BEGIN OF IT_DELETE OCCURS 0,
         PLNUM       LIKE PLAF-PLNUM,
         PLAF_COUNT  TYPE I,
         RESB_COUNT  TYPE I,
       END OF IT_DELETE .

DATA : IT_RETURN     LIKE BAPIRETURN1 OCCURS 0  WITH HEADER LINE.

DATA : PLAF_COUNT    TYPE I,
       RESB_COUNT    TYPE I,
       W_INT         TYPE I,
       W_BACKUP      TYPE I,
       TO_DATE       LIKE SY-DATUM,
       BE_DATE       LIKE SY-DATUM,
       WK_GUI_MSG(40),
       W_ARBPL       LIKE CRHD-ARBPL,
       W_RP_POINT    LIKE ZTPP_STATUS-RP_POINT VALUE '17',
       W_WERKS       LIKE T001W-WERKS VALUE 'P001',
       W_KALID       LIKE KAKO-KALID,                  "Calender ID
       W_MOSID       LIKE KAKO-MOSID,                  "Schedule group
       W_KAPID       LIKE KAKO-KAPID.                  "Capacity ID
** HASEEB ADDED THE VARIABLES.
DATA : BEGIN OF IT_AUSP OCCURS 0 ,
       OBJEK LIKE AUSP-OBJEK,
       ATINN LIKE AUSP-ATINN,
       ATWRT LIKE AUSP-ATWRT,
       END OF IT_AUSP.

DATA : BEGIN OF IT_AUSP_actural OCCURS 0 ,
       OBJEK LIKE AUSP-OBJEK,
       ATINN LIKE AUSP-ATINN,
       ATWRT LIKE AUSP-ATWRT,
       END OF IT_AUSP_Actural.

DATA : BEGIN OF IT_AUSPSTATUS OCCURS 0 ,
       OBJEK LIKE AUSP-OBJEK,
       ATINN LIKE AUSP-ATINN,
       ATWRT LIKE AUSP-ATWRT,
       END OF IT_AUSPSTATUS.
DATA : BEGIN OF wa_AUSPDATE  ,
       OBJEK LIKE AUSP-OBJEK,
       ATINN LIKE AUSP-ATINN,
       ATWRT LIKE AUSP-ATWRT,
       END OF wa_AUSPDATE.


DATA : BEGIN OF IT_ATWRT OCCURS 0,
        PLN_ORD  LIKE AUSP-ATWRT,
*        OBJEK LIKE AUSP-OBJEK,
       END OF IT_ATWRT.

RANGES r_atnam FOR cabn-atnam.
DATA : BEGIN OF it_cabn OCCURS 0,
       atinn LIKE cabn-atinn,
       atnam LIKE cabn-atnam,
       END OF it_cabn.

RANGES R_ATINN FOR AUSP-ATINN OCCURS 0.
DATA : BEGIN OF IT_OBJEK OCCURS 0,
        OBJEK LIKE ausp-OBJEK,
       END OF IT_OBJEK.
