************************************************************************
* Program Name      : ZIPP_GCC_ELOG
* Author            : Furong Wang
* Creation Date     : 09/24/2009
* Specifications By :
* Development Request No :
* Addl Documentation:
* Description       :
* Modification Logs
* Date       Developer    RequestNo    Description
*
*********************************************************************

REPORT ZIPP_GCC_ELOG_ NO STANDARD PAGE HEADING
                     LINE-SIZE 132
                     LINE-COUNT 64(1)
                     MESSAGE-ID ZMPP.

DATA: V_SEQ LIKE ZTPP_GCC_ELOG-ELOG_SEQ,
       V_DAYTIME LIKE ZTPP_GCC_ELOG-ELOG_DAYTIME.

DATA: BEGIN OF IT_ACT OCCURS 0,
      PRDT_DATE LIKE SY-DATUM,
      DEST LIKE ZTPP_ACT_HMC-DEST,
      QTY LIKE ZTPP_ACT_HMC-QTY_SIGNOFF,
      SUM TYPE I,
      END OF IT_ACT.

DATA: BEGIN OF IT_TEMP OCCURS 0,
      PRDT_DATE LIKE SY-DATUM,
      DEST(3),
      QTY LIKE ZTPP_ACT_HMC-QTY_SIGNOFF,
      SUM TYPE I,
      END OF IT_TEMP.

DATA: BEGIN OF IT_PLAN OCCURS 0,
       PRDT_DATE LIKE SY-DATUM,
*        DEST LIKE ZTPP_ACT_HMC-DEST,
       QTY LIKE ZTPP_PLAN_HMC-QTY_PLAN,
       SUM TYPE I,
       END OF IT_PLAN.

DATA: BEGIN OF IT_DELIVERY OCCURS 0,
      PRDT_DATE LIKE SY-DATUM,
      DIST LIKE ZTPP_DELIVER_HMC-DIST,
      QTY LIKE ZTPP_DELIVER_HMC-QTY_DD,
      SUM TYPE I,
      END OF IT_DELIVERY.

DATA: IT_GCCELOG LIKE TABLE OF ZTPP_GCC_ELOG WITH HEADER LINE.

SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.
PARAMETERS: P_DATE LIKE SY-DATUM OBLIGATORY.
SELECTION-SCREEN END OF BLOCK B1.

CONCATENATE SY-DATUM SY-UZEIT INTO V_DAYTIME.

*** GET PRODUCTION QTY
SELECT PRDT_DATE DEST COUNT( * ) AS QTY
                      SUM( QTY_SIGNOFF ) AS SUM
           INTO CORRESPONDING FIELDS OF TABLE IT_ACT
   FROM ZTPP_ACT_HMC
   WHERE PRDT_DATE = P_DATE
   GROUP BY PRDT_DATE DEST.

LOOP AT IT_ACT.
  MOVE-CORRESPONDING IT_ACT TO IT_TEMP.
  COLLECT IT_TEMP.
  CLEAR: IT_TEMP, IT_ACT.
ENDLOOP.

SELECT SINGLE ELOG_SEQ INTO V_SEQ
  FROM ZTPP_GCC_ELOG
  WHERE ELOG_DATE = P_DATE
   AND ELOG_KIND = 'PROD_QTY '.
IF SY-SUBRC = 0.
  V_SEQ = V_SEQ + 1.
ELSE.
  V_SEQ = '1'.
ENDIF.

LOOP AT IT_TEMP.
  IT_GCCELOG-ELOG_DATE = IT_TEMP-PRDT_DATE.
  IT_GCCELOG-ELOG_KIND = 'PROD_QTY'.
  IT_GCCELOG-ELOG_SEQ = V_SEQ.
  IT_GCCELOG-ELOG_HKMC = 'HMC'.
  IF IT_TEMP-DEST = 'B28'.
    IT_GCCELOG-ELOG_EXDO = 'D'.
  ELSE.
    IT_GCCELOG-ELOG_EXDO = 'E'.
  ENDIF.
  IT_GCCELOG-ELOG_NAT = IT_TEMP-DEST.
  IT_GCCELOG-ELOG_LOC = 'HMMA'.

  IT_GCCELOG-ELOG_DAYTIME = V_DAYTIME.
  IT_GCCELOG-ELOG_QTY = IT_TEMP-QTY.
  IT_GCCELOG-ELOG_SUM = IT_TEMP-SUM.

  SHIFT IT_GCCELOG-ELOG_QTY LEFT DELETING LEADING SPACE.
  SHIFT IT_GCCELOG-ELOG_SUM LEFT DELETING LEADING SPACE.

  IT_GCCELOG-IF_USER = SY-UNAME.
  APPEND IT_GCCELOG.
  CLEAR:IT_GCCELOG.
ENDLOOP.

*** GET PLAN QTY
CLEAR: V_SEQ.
SELECT PRDT_DATE COUNT( * ) AS QTY
                SUM( QTY_PLAN ) AS SUM
           INTO CORRESPONDING FIELDS OF TABLE IT_PLAN
   FROM ZTPP_PLAN_HMC
   WHERE PRDT_DATE = P_DATE
   GROUP BY PRDT_DATE.

SELECT SINGLE ELOG_SEQ INTO V_SEQ
   FROM ZTPP_GCC_ELOG
   WHERE ELOG_DATE = P_DATE
    AND ELOG_KIND = 'PROD_OPLAN'.
IF SY-SUBRC = 0.
  V_SEQ = V_SEQ + 1.
ELSE.
  V_SEQ = '1'.
ENDIF.

LOOP AT IT_PLAN.
  IT_GCCELOG-ELOG_DATE = IT_PLAN-PRDT_DATE.
  IT_GCCELOG-ELOG_KIND = 'PROD_OPLAN'.
  IT_GCCELOG-ELOG_SEQ = V_SEQ.
  IT_GCCELOG-ELOG_HKMC = 'HMC'.

  IT_GCCELOG-ELOG_LOC = 'HMMA'.
  IT_GCCELOG-ELOG_DAYTIME = V_DAYTIME.

  IT_GCCELOG-ELOG_QTY = IT_PLAN-QTY.
  IT_GCCELOG-ELOG_SUM = IT_PLAN-SUM.

  SHIFT IT_GCCELOG-ELOG_QTY LEFT DELETING LEADING SPACE.
  SHIFT IT_GCCELOG-ELOG_SUM LEFT DELETING LEADING SPACE.

  IT_GCCELOG-IF_USER = SY-UNAME.
  APPEND IT_GCCELOG.
  CLEAR: IT_GCCELOG.
ENDLOOP.

*** GET SALES ACTUAL QTY
*CLEAR: V_SEQ.
*SELECT PRDT_DATE DIST COUNT( * ) AS QTY
*                      SUM( QTY_DD ) AS SUM
*           INTO CORRESPONDING FIELDS OF TABLE IT_DELIVERY
*   FROM ZTPP_DELIVER_HMC
*   WHERE PRDT_DATE = P_DATE
*   GROUP BY PRDT_DATE DIST.
*
*SELECT SINGLE ELOG_SEQ INTO V_SEQ
*  FROM ZTPP_GCC_ELOG
*  WHERE ELOG_DATE = P_DATE
*   AND ELOG_KIND = 'GCDS'.
*IF SY-SUBRC = 0.
*  V_SEQ = V_SEQ + 1.
*ELSE.
*  V_SEQ = '1'.
*ENDIF.
*
*LOOP AT IT_DELIVERY.
*  IT_GCCELOG-ELOG_DATE = IT_DELIVERY-PRDT_DATE.
*  IT_GCCELOG-ELOG_KIND = 'GCDS'.
*  IT_GCCELOG-ELOG_SEQ = V_SEQ.
*  IT_GCCELOG-ELOG_HKMC = 'HMC'.
*  IF IT_DELIVERY-DIST = 'B28'.
*    IT_GCCELOG-ELOG_EXDO = 'D'.
*  ELSE.
*    IT_GCCELOG-ELOG_EXDO = 'E'.
*  ENDIF.
*  IT_GCCELOG-ELOG_NAT = IT_DELIVERY-DIST.
*  IT_GCCELOG-ELOG_LOC = 'HMMA'.
*  IT_GCCELOG-ELOG_DAYTIME = V_DAYTIME.
*
*  IT_GCCELOG-ELOG_QTY = IT_DELIVERY-QTY.
*  IT_GCCELOG-ELOG_SUM = IT_DELIVERY-SUM.
*  IT_GCCELOG-IF_USER = SY-UNAME.
*  APPEND IT_GCCELOG.
*  CLEAR: IT_GCCELOG.
*ENDLOOP.

MODIFY ZTPP_GCC_ELOG FROM TABLE IT_GCCELOG.
