REPORT ZRM60_UPDATE_PROFILE .
*REPORT RM60_UPDATE_PROFILE .

DATA: BEGIN OF LT_TPHVP  OCCURS 100,
      PROFILID LIKE TPHVP-PROFILID,
      OBJEKT LIKE PBIM-MATNR,
END OF LT_TPHVP.

DATA: LT_PBIM TYPE PBIM OCCURS 100 WITH HEADER LINE.
DATA: LT_PBIM_UPDATE TYPE PBIM OCCURS 100 WITH HEADER LINE.


* start of selection
SELECT PROFILID OBJEKT FROM TPHVP INTO TABLE LT_TPHVP.
IF SY-SUBRC IS INITIAL.
  SELECT * FROM PBIM INTO TABLE LT_PBIM
                             FOR ALL ENTRIES IN LT_TPHVP
                             WHERE MATNR EQ LT_TPHVP-OBJEKT.
  IF SY-SUBRC IS INITIAL.
    LOOP AT LT_PBIM.
      READ TABLE LT_TPHVP WITH KEY OBJEKT = LT_PBIM-MATNR.
      IF SY-SUBRC IS INITIAL.
        IF LT_PBIM-PROFILID NE LT_TPHVP-PROFILID.
          MOVE-CORRESPONDING LT_PBIM TO LT_PBIM_UPDATE.
          MOVE LT_TPHVP-PROFILID TO LT_PBIM_UPDATE-PROFILID.
          APPEND LT_PBIM_UPDATE.
        ENDIF.
      ENDIF.
    ENDLOOP.
  ENDIF.
ENDIF.

READ TABLE LT_PBIM_UPDATE INDEX 1.
IF SY-SUBRC IS INITIAL.
 UPDATE PBIM FROM TABLE LT_PBIM_UPDATE.
ENDIF.
