*----------------------------------------------------------------------*
*   INCLUDE ZRPP113I_APS_2AB1_2TOP                                     *
*----------------------------------------------------------------------*
TYPE-POOLS: SLIS, VRM.

TABLES: ZTPP_PVV02AB.
DATA: IT_PVV02AB LIKE TABLE OF ZTPP_PVV02AB WITH HEADER LINE,
      IT_PVV01RR LIKE TABLE OF ZTPP_PVV01RR WITH HEADER LINE.

DATA: BEGIN OF IT_PVV02AB_OUT OCCURS 0,
      STDT LIKE ZTPP_PVV02AB-STDT,
      MODL LIKE ZTPP_PVV02AB-MODL,
      USEE LIKE ZTPP_PVV02AB-USEE,
      NATN LIKE ZTPP_PVV02AB-NATN,
      ECNM LIKE ZTPP_PVV02AB-ECNM,
      EGNM LIKE ZTPP_PVV02AB-EGNM,
      FUNM LIKE ZTPP_PVV02AB-FUNM,
      TMNM LIKE ZTPP_PVV02AB-TMNM,
      NGRD LIKE ZTPP_PVV02AB-NGRD,
      PLNB0 LIKE ZTPP_WOSUM-MODQTY,
      PLNB1 LIKE ZTPP_WOSUM-MODQTY,
      PLNB2 LIKE ZTPP_WOSUM-MODQTY,
      PLNB3 LIKE ZTPP_WOSUM-MODQTY,
      PLNB4 LIKE ZTPP_WOSUM-MODQTY,
      TOTAL LIKE ZTPP_PRO_SUM-RP01,
      END OF IT_PVV02AB_OUT.

DATA: BEGIN OF IT_PVV01RR_OUT OCCURS 0,
      DESC(50),
      PLNB0  LIKE ZTPP_WOSUM-MODQTY,
      PLNB1 LIKE ZTPP_WOSUM-MODQTY,
      PLNB2 LIKE ZTPP_WOSUM-MODQTY,
      PLNB3 LIKE ZTPP_WOSUM-MODQTY,
      PLNB4 LIKE ZTPP_WOSUM-MODQTY,
      TOTAL LIKE ZTPP_PRO_SUM-RP01,
      END OF IT_PVV01RR_OUT.

DATA: P_MODL LIKE ZTPP_PVV02AB-MODL,
      P_USEE LIKE ZTPP_PVV02AB-USEE,
      P_NATN LIKE ZTPP_PVV02AB-NATN,
      P_EXCO LIKE ZTPP_PVV02AB-EXCO.

DATA: OK_CODE      LIKE SY-UCOMM,
      W_REPID  LIKE SY-REPID,
      W_CNT       TYPE   I.

DATA: XNAME    TYPE VRM_ID,
      XLIST    TYPE VRM_VALUES,
      XVALUE   LIKE LINE OF XLIST.

DATA:  L_KALID LIKE KAKO-KALID.

DATA : IT_FIELDCAT     TYPE LVC_T_FCAT WITH HEADER LINE,
       IT_FIELDCAT_TOT  TYPE LVC_T_FCAT WITH HEADER LINE,
       IT_FIELDNAME    TYPE SLIS_T_FIELDCAT_ALV,
       IT_FIELDNAME_TOT    TYPE SLIS_T_FIELDCAT_ALV,
       IT_SORT         TYPE LVC_T_SORT WITH HEADER LINE,
       IT_EXCLUDE      TYPE UI_FUNCTIONS,
       IT_EXCLUDE_TOT  TYPE UI_FUNCTIONS.

DATA : WA_IS_LAYOUT TYPE LVC_S_LAYO, "/The Layout Structure
       WA_IS_LAYOUT_TOT TYPE LVC_S_LAYO,
       W_FIELDNAME  LIKE LINE OF IT_FIELDCAT.

DATA: WA_SAVE    TYPE C   VALUE 'A',   "for Parameter I_SAVE
      WA_VARIANT TYPE DISVARIANT,      "for parameter IS_VARIANT
      WA_SAVE_TOT  TYPE C   VALUE 'A',   "for Parameter I_SAVE
      WA_VARIANT_TOT TYPE DISVARIANT.     "for parameter IS_VARIANT

DATA: WA_CUSTOM_CONTROL TYPE        SCRFNAME VALUE 'ALV_CONTAINER',
      ALV_GRID          TYPE REF TO CL_GUI_ALV_GRID,
      GRID_CONTAINER    TYPE REF TO CL_GUI_CUSTOM_CONTAINER.

DATA: WA_CUSTOM_CONTROL_TOT TYPE    SCRFNAME VALUE 'ALV_CONTAINER_TOT',
      ALV_GRID_TOT          TYPE REF TO CL_GUI_ALV_GRID,
      GRID_CONTAINER_TOT    TYPE REF TO CL_GUI_CUSTOM_CONTAINER.
DATA: WA_STBL  TYPE LVC_S_STBL.

DATA: BEGIN OF IT_EXCEL OCCURS 0,
      COL01(6),
      COL02(6),
      COL03(6),
      COL04(10),
      COL05(10),
      COL06(10),
      COL07(10),
      COL08(10),
      COL09(10),
      COL10(10),
      COL11(10),
      COL12(10),
      COL13(10),
      COL14(10),
      END OF IT_EXCEL.

DATA:V_MONTH0(9),
     V_MONTH1(9),
     V_MONTH2(9),
     V_MONTH3(9),
     V_MONTH4(9).
