*-------------------------------------------------------------------*
*   INCLUDE ZSJ_TEST033_SEL                                         *
*-------------------------------------------------------------------*

*-------------------------------------------------------------------*
*  SELECT-OPTIONS
*-------------------------------------------------------------------*
SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-001.
SELECT-OPTIONS :
 S_CREDAT   FOR  EDIDC-CREDAT DEFAULT SY-DATUM  OBLIGATORY .
PARAMETERS :
 P_MESTYP LIKE EDIDC-MESTYP DEFAULT 'ZPODER_MST' NO-DISPLAY.
* SELECTION-SCREEN ULINE.

*SELECTION-SCREEN BEGIN OF BLOCK RBOX WITH FRAME TITLE TEXT-002.
*SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS :  R_ALL  NO-DISPLAY.
*PARAMETERS :  R_ALL RADIOBUTTON GROUP R1 DEFAULT 'X'.
*SELECTION-SCREEN COMMENT 5(30) TEXT-C00 MODIF ID NEW.
*SELECTION-SCREEN END OF LINE.
*SELECTION-SCREEN ULINE.
SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS :  R_NEW RADIOBUTTON GROUP R1 DEFAULT 'X' .
SELECTION-SCREEN COMMENT 5(30) TEXT-C01 MODIF ID NEW.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN BEGIN OF BLOCK ROP  .
PARAMETERS : R_RUN MODIF ID NEW NO-DISPLAY.
PARAMETERS : R_SAV MODIF ID NEW NO-DISPLAY.
SELECTION-SCREEN END OF BLOCK ROP.
*SELECTION-SCREEN ULINE.

SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS : R_OLD  RADIOBUTTON GROUP R1 MODIF ID RAD.
SELECTION-SCREEN COMMENT 5(30) TEXT-C02.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF BLOCK BCO WITH FRAME.
SELECTION-SCREEN COMMENT 1(70) TEXT-C05 MODIF ID OLD.
SELECTION-SCREEN END OF BLOCK BCO.
SELECTION-SCREEN END OF BLOCK B1.

*-------------------------------------------------------------------*
*     AT SELECTION-SCREEN                                           *
*-------------------------------------------------------------------*

AT SELECTION-SCREEN OUTPUT.
*  PERFORM CHANGE_SEL_SCREEN.
