*----------------------------------------------------------------------*
*   INCLUDE ZRPP_REQUIRMENTS_TOP                                       *
*----------------------------------------------------------------------*
TABLES:mdbs,
       makt,	
       mard,	
       ekko,	
       marc,
       EORD,
       TDG41,
       V_MMIM_BS,
       mara.	

*********************************************************************
**  CONSTANT DECLARATION
*********************************************************************

*********************************************************************
**  VARIABLES DECLARATION
*********************************************************************
DATA: WA_LPKD LIKE TDG41-PROFL.
DATA: V_STAT. "STATUS: 'N'-NO DATA SELECTED
DATA: G_MESSAGE(50).
DATA: L_TABIX LIKE SY-TABIX.
DATA: G_LTP_BEGDATE LIKE SY-DATUM.
DATA: G_LTP(1). " 'X'--LTP DATA IS NEEDED.
DATA: SC_VENDOR LIKE LFA1-LIFNR,
      SC_MATERIAL LIKE MARC-MATNR,
      SC_LPKD LIKE MARA-PROFL,
      SC_DATE_LOW LIKE SY-DATUM,
      SC_DATE_HIGH LIKE SY-DATUM.
DATA: L_MRP_LASTDATE LIKE SY-DATUM.
DATA: I_NO TYPE I.
DATA: OK_CODE LIKE SY-UCOMM,
      OK_SAVE LIKE SY-UCOMM.
CONTROLS TC_DETAIL TYPE TABLEVIEW USING SCREEN 100.
DATA: G_CONTAINER TYPE SCRFNAME VALUE 'SC_CONTAINER',
      GRID1  TYPE REF TO CL_GUI_ALV_GRID,
      G_CUSTOM_CONTAINER TYPE REF TO CL_GUI_CUSTOM_CONTAINER.
DATA: G_COLOR    TYPE SLIS_T_SPECIALCOL_ALV.
DATA: WA_COLOR  LIKE LINE OF G_COLOR.
*******************************
**************************************
**  INTERNAL TABLE DECLARATION
*********************************************************************
DATA: BEGIN OF FIELDS OCCURS 0.
        INCLUDE STRUCTURE HELP_VALUE.
DATA: END OF FIELDS.
DATA  SELECT_INDEX LIKE SY-TABIX.
DATA: SELECT_VALUE(10).
DATA: BEGIN OF SELECT_VALUES OCCURS 0.
        INCLUDE STRUCTURE HELP_VTAB.
DATA: END OF SELECT_VALUES.
DATA: BEGIN OF VALUETAB OCCURS 0,
          VALUE(30).
DATA: END OF VALUETAB.

DATA: BEGIN OF IT_MDKP OCCURS 0,
        MATNR LIKE MDKP-MATNR,
        WERKS LIKE MDKP-PLWRK,
        PLSCN LIKE MDKP-PLSCN,
        LGPRO LIKE MARC-LGPRO, "?????
      END OF IT_MDKP.
DATA: BEGIN OF IT_REQ OCCURS 0,
        MATNR LIKE MARA-MATNR,  "MATERIAL NUMBER
        LGORT LIKE RESB-LGORT,  "STORAGE LOCATION
        WERKS LIKE RESB-WERKS,  "PLANT
        MAKTX LIKE MAKT-MAKTX,  "DESCRIPTION
        BDMNG LIKE RESB-BDMNG,  "REQUIREMENTS QTY
        MENGE LIKE MDBS-MENGE,  "DUE-IN QTY
        LABST LIKE MARD-LABST,  "CURRENT STOCK QTY
        SHORT LIKE RESB-BDMNG,  "QTY SHORTAGE
        LIFNR LIKE EKKO-LIFNR,  "VENDOR
        PROFL LIKE MARA-PROFL,  "PART TYPE: LP/KD
        CFIELD LIKE G_COLOR,
      END OF IT_REQ.
DATA: IT_REQ_A LIKE IT_REQ OCCURS 0 WITH HEADER LINE.
DATA: BEGIN OF IT_DUEIN OCCURS 0,
         EBELN LIKE EKPO-EBELN,
         EBELP LIKE EKPO-EBELP,
         ETENR LIKE EKET-ETENR,
         MATNR LIKE EKPO-MATNR,
         EINDT LIKE EKET-EINDT,
         MENGE LIKE EKET-MENGE,
         WEMNG LIKE EKET-WEMNG,
      END OF IT_DUEIN.
DATA: BEGIN OF IT_VENDOR OCCURS 0,
         MATNR LIKE EINA-MATNR,
         LIFNR LIKE EINA-LIFNR,
      END OF IT_VENDOR.
DATA: BEGIN OF IT_PO OCCURS 0,
         EBELN LIKE EKKO-EBELN,
         EBELP LIKE EKPO-EBELP,
         MATNR LIKE EKPO-MATNR,
         LIFNR LIKE EKKO-LIFNR,
      END OF IT_PO.
TYPES: BEGIN OF DETAIL,
         DAT00 LIKE MDSU-DAT00,
         ELEMT(15),
         MNG02 LIKE MDSU-MNG02,
         MNG03 LIKE MDSU-MNG02,
         MNG04 LIKE MDSU-MNG02,
      END OF DETAIL.

DATA: IT_DETAIL TYPE STANDARD TABLE OF DETAIL.
DATA: IT_DETAIL_MRP TYPE STANDARD TABLE OF DETAIL.
DATA: IT_DETAIL_LTP TYPE STANDARD TABLE OF DETAIL.
DATA: WA_DETAIL TYPE DETAIL.
DATA: BEGIN OF IT_21 OCCURS 0,
        MATNR   LIKE MARA-MATNR,
        DAT00   LIKE MDSU-DAT00,
        ELEMT(15),
        MNG02 LIKE MDSU-MNG02,
        MNG03 LIKE MDSU-MNG02,
        MNG04 LIKE MDSU-MNG02.
DATA: END OF IT_21.
DATA: BEGIN OF IT_21LAYOUT OCCURS 0,
        MATNR   LIKE MARA-MATNR,
        MAKTX   LIKE MAKT-MAKTX,
        PROFL   LIKE MARA-PROFL,
        D00     LIKE MDSU-MNG02,
        D01     LIKE MDSU-MNG02,
        D02     LIKE MDSU-MNG02,
        D03     LIKE MDSU-MNG02,
        D04     LIKE MDSU-MNG02,
        D05     LIKE MDSU-MNG02,
        D06     LIKE MDSU-MNG02,
        D07     LIKE MDSU-MNG02,
        D08     LIKE MDSU-MNG02,
        D09     LIKE MDSU-MNG02,
        D10     LIKE MDSU-MNG02,
        D11     LIKE MDSU-MNG02,
        D12     LIKE MDSU-MNG02,
        D13     LIKE MDSU-MNG02,
        D14     LIKE MDSU-MNG02,
        D15     LIKE MDSU-MNG02,
        D16     LIKE MDSU-MNG02,
        W01     LIKE MDSU-MNG02,
        W02     LIKE MDSU-MNG02,
        W03     LIKE MDSU-MNG02,
        W04     LIKE MDSU-MNG02,
        W05     LIKE MDSU-MNG02,
        W06     LIKE MDSU-MNG02,
        W07     LIKE MDSU-MNG02,
        W08     LIKE MDSU-MNG02,
        W09     LIKE MDSU-MNG02,
        W10     LIKE MDSU-MNG02,
        W11     LIKE MDSU-MNG02,
        W12     LIKE MDSU-MNG02,
        W13     LIKE MDSU-MNG02,
        W14     LIKE MDSU-MNG02,
        W15     LIKE MDSU-MNG02,
        W16     LIKE MDSU-MNG02,
        W17     LIKE MDSU-MNG02,
        W18     LIKE MDSU-MNG02,
        W19     LIKE MDSU-MNG02,
        W20     LIKE MDSU-MNG02,
        W21     LIKE MDSU-MNG02,
        W22     LIKE MDSU-MNG02,
        W23     LIKE MDSU-MNG02,
        W24     LIKE MDSU-MNG02,
      END OF IT_21LAYOUT.
DATA: BEGIN OF IT_WORKDAY OCCURS 0,
        DSEQ(3),
        DATE    LIKE SY-DATUM,
      END OF IT_WORKDAY.
DATA: BEGIN OF IT_WEEKS OCCURS 0,
        WSEQ(3) ,
        WEEK   LIKE SCAL-WEEK,
        DATE1  LIKE SY-DATUM,
        DATE2  LIKE SY-DATUM,
      END OF IT_WEEKS.

data  L_TODAY(5) TYPE C VALUE 'Today'.
*********************************************************************
data: BEGIN OF  IT_LTP_BEG OCCURS 0,
        MATNR     LIKE MARA-MATNR,
        BEGDT     LIKE MDSU-DAT00,
      END OF IT_LTP_BEG.
**  ALV-GRID CONTROL DECLARATION
data  G_DISPLAY_END_WEEK TYPE I.
data  G_DISPLAY_BEGIN_WEEK TYPE I.
*********************************************************************

INCLUDE: <ICON>.
INCLUDE : <LIST>.
TYPE-POOLS: SLIS.
DATA: GT_FIELDCAT TYPE SLIS_T_FIELDCAT_ALV,
      GT_FC       TYPE SLIS_T_FIELDCAT_ALV,
      G_FIELDCAT_S LIKE LINE OF GT_FIELDCAT,
      GS_LAYOUT   TYPE SLIS_LAYOUT_ALV,
      GS_PRINT    TYPE SLIS_PRINT_ALV,
      GT_SORT     TYPE SLIS_T_SORTINFO_ALV,
      GT_SP_GROUP TYPE SLIS_T_SP_GROUP_ALV,
      GT_EVENTS   TYPE SLIS_T_EVENT,
      GT_HEADER   TYPE SLIS_T_LISTHEADER,
      GT_FCAT     TYPE LVC_T_FCAT,
*      gt_header1  TYPE slis_t_listheader,
      GT_COLINFO_TABLE TYPE SLIS_T_SPECIALCOL_ALV. "line color.
DATA:  G_VARIANT LIKE DISVARIANT.
* return
DATA : G_EXIT_CAUSED_BY_CALLER  TYPE C,
       GS_EXIT_CAUSED_BY_USER   TYPE SLIS_EXIT_BY_USER.

* hierarchy(simple)
DATA : G_TABNAME_HEADER       TYPE SLIS_TABNAME,       "header part
       G_TABNAME_ITEM         TYPE SLIS_TABNAME,       "detail list
       GS_KEYINFO             TYPE SLIS_KEYINFO_ALV,   "relation key
       G_REPID                LIKE SY-REPID.




*********************************************************************
**  SELECTION-SCREEN
*********************************************************************
SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-001.
 SELECT-OPTIONS: P_MAT   FOR    MARC-MATNR.
 PARAMETERS: P_Vend      LIKE   EORD-lifnr,
             P_CTRL      LIKE	MDKP-dispo,
             P_PLANT     LIKE   MARC-WERKS DEFAULT 'P001',
             P_LPKD      LIKE	mara-profl,
             p_LGORT     LIKE   MARD-LGORT,           "UD1K912703
             p_RAUBE     LIKE   MARA-RAUBE.           "UD1K912703

 SELECT-OPTIONS: P_DATE  FOR	SY-DATUM .


SELECTION-SCREEN END OF BLOCK B1.

SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME TITLE TEXT-001.
  SELECTION-SCREEN BEGIN OF LINE.
  PARAMETERS: P_21 AS CHECKBOX.
  SELECTION-SCREEN COMMENT  5(40) TEXT-002 FOR FIELD P_21 .
  SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK B2.
