


MODULE STATUS_0100 OUTPUT.

  DATA: UCOMM TYPE TABLE OF SY-UCOMM,
        TMP_MAKTX LIKE MAKT-MAKTX.

  DATA : LV_DATUM(20), LV_TEXT(30).

  CONCATENATE S_CREDAT-LOW S_CREDAT-HIGH INTO LV_DATUM
  SEPARATED BY SPACE.


  REFRESH UCOMM.

  SET PF-STATUS 'S100' EXCLUDING UCOMM.
  SET TITLEBAR  'T100' WITH LV_DATUM.


  CALL METHOD SCREEN_INIT=>INIT_SCREEN.

ENDMODULE.
