*----------------------------------------------------------------------*
*   INCLUDE ZXM61U03                                                   *
*----------------------------------------------------------------------*
DATA: L_ATINN LIKE AUSP-ATINN.
DATA: L_ATNAM LIKE CABN-ATNAM.
DATA: L_CODE TYPE C.
DATA: L_OBJEK LIKE AUSP-OBJEK.
DATA: L_VALUE1 LIKE MDEZ-USEX1.
DATA: L_VALUE2 LIKE MDEZ-USEX2.
DATA: L_VALUE3 LIKE MDEZ-USEX3.
DATA: L_PO LIKE PLAF-PLNUM.
DATA: L_SERIAL LIKE ZTPP_INPUT_PLAN-BODY_SER.
DATA: L_MODEL LIKE ZTPP_INPUT_PLAN-MODL.

*IF THE MRP ELEMENT INDICATOR IS VJ(DELIVERY)
IF IE3MDPSLX-DELKZ = 'VJ'.
*GET THE OBJECT NUMBER
L_OBJEK = IE3MDPSLX-DELNR.
*FILL THE VALUE IF BUTTON1 IS PRESSED
IF IBUTT1 = 'X'.
 CLEAR L_CODE.
 L_ATNAM = 'P_VIN'.  "VEHICLE NUMBER
 SELECT SINGLE ATINN INTO L_ATINN
    FROM CABN
    WHERE ATNAM = L_ATNAM.
 IF SY-SUBRC <> 0.
    L_CODE = 'N'.
 ELSE.
    SELECT SINGLE ATWRT INTO L_VALUE1
     FROM AUSP
     WHERE OBJEK = L_OBJEK AND
           ATINN = L_ATINN.
   IF SY-SUBRC <> 0.
     L_CODE = 'N'.
   ENDIF.
 ENDIF.
*ASSIGN THE VALUE TO EXPORT PARAMETER
 IF L_CODE IS INITIAL.
   EMDEZX_USEX1 = L_VALUE1.
 ENDIF.
ENDIF.

IF IBUTT2 = 'X'.
 CLEAR L_CODE.
 L_ATNAM = 'P_PLAN_ORDER'.  "PLAN_ORDER NUMBER
 SELECT SINGLE ATINN INTO L_ATINN
    FROM CABN
    WHERE ATNAM = L_ATNAM.
 IF SY-SUBRC <> 0.
    L_CODE = 'N'.
 ELSE.
    SELECT SINGLE ATWRT INTO L_VALUE2
     FROM AUSP
     WHERE OBJEK = L_OBJEK AND
           ATINN = L_ATINN.
   IF SY-SUBRC <> 0.
     L_CODE = 'N'.
   ENDIF.
 ENDIF.
*ASSIGN THE VALUE TO EXPORT PARAMETER
 IF L_CODE IS INITIAL.
   EMDEZX_USEX2 = L_VALUE2.
 ENDIF.
ENDIF.

IF IBUTT3 = 'X'.
 CLEAR L_CODE.
 L_ATNAM = 'P_WORK_ORDER'.  "WORK ORDER NUMBER
 SELECT SINGLE ATINN INTO L_ATINN
    FROM CABN
    WHERE ATNAM = L_ATNAM.
 IF SY-SUBRC <> 0.
    L_CODE = 'N'.
 ELSE.
    SELECT SINGLE ATWRT INTO L_VALUE3
     FROM AUSP
     WHERE OBJEK = L_OBJEK AND
           ATINN = L_ATINN.
   IF SY-SUBRC <> 0.
     L_CODE = 'N'.
   ENDIF.
 ENDIF.
*ASSIGN THE VALUE TO EXPORT PARAMETER
 IF L_CODE IS INITIAL.
   EMDEZX_USEX3 = L_VALUE3.
 ENDIF.
ENDIF.
ENDIF.  "IF IE3MDPSLX-DELKZ = 'VJ'

*IF THE MRP ELEMENT INDICATOR IS 'PA'(PLANNED ORDER)

IF IE3MDPSLX-DELKZ = 'PA'.
* GET THE EQUIPMENT
  L_ATNAM = 'P_PLAN_ORDER'.
  SELECT SINGLE ATINN INTO L_ATINN
    FROM CABN
     WHERE ATNAM = L_ATNAM.
  IF SY-SUBRC <> 0.
    EXIT.
  ENDIF.

  L_PO = IE3MDPSLX-DELNR.
  IF NOT L_PO IS INITIAL.
  SELECT SINGLE OBJEK INTO L_OBJEK
    FROM AUSP
    WHERE KLART = '002' AND
          ATWRT = L_PO AND
          ATINN = L_ATINN
           .
  ENDIF.
  IF SY-SUBRC <> 0.
   EXIT.
  ENDIF.

* FILL THE VALUE IF BUTTON1 IS PRESSED
  IF IBUTT1 = 'X'.
   CLEAR L_CODE.
   L_ATNAM = 'P_VIN'.  "VEHICLE NUMBER
   SELECT SINGLE ATINN INTO L_ATINN
      FROM CABN
      WHERE ATNAM = L_ATNAM.
   IF SY-SUBRC <> 0.
      L_CODE = 'N'.
   ELSE.
      SELECT SINGLE ATWRT INTO L_VALUE1
       FROM AUSP
       WHERE OBJEK = L_OBJEK AND
           ATINN = L_ATINN.
     IF SY-SUBRC <> 0.
       L_CODE = 'N'.
     ENDIF.
   ENDIF.
*ASSIGN THE VALUE TO EXPORT PARAMETER
   IF L_CODE IS INITIAL.
     EMDEZX_USEX1 = L_VALUE1.
   ENDIF.
  ENDIF.

  IF IBUTT2 = 'X'.
   CLEAR L_CODE.
   L_ATNAM = 'P_MODEL'.  "VEHICLE MODEL
   SELECT SINGLE ATINN INTO L_ATINN
      FROM CABN
      WHERE ATNAM = L_ATNAM.
   IF SY-SUBRC <> 0.
      L_CODE = 'N'.
   ELSE.
      SELECT SINGLE ATWRT INTO L_VALUE2
       FROM AUSP
       WHERE OBJEK = L_OBJEK AND
           ATINN = L_ATINN.
     IF SY-SUBRC <> 0.
       L_CODE = 'N'.
     ENDIF.
   ENDIF.
   L_ATNAM = 'P_BODY_SERIAL'.  "SERIAL NUMBER
   SELECT SINGLE ATINN INTO L_ATINN
      FROM CABN
      WHERE ATNAM = L_ATNAM.
   IF SY-SUBRC <> 0.
      L_CODE = 'N'.
   ELSE.
      SELECT SINGLE ATWRT INTO L_SERIAL
       FROM AUSP
       WHERE OBJEK = L_OBJEK AND
           ATINN = L_ATINN.
     IF SY-SUBRC <> 0.
       L_CODE = 'N'.
     ENDIF.
   ENDIF.
   IF L_CODE <> 'N'.
     CONCATENATE L_VALUE2 L_SERIAL INTO L_VALUE2.
   ENDIF.

*  ASSIGN THE VALUE TO EXPORT PARAMETER
   IF L_CODE IS INITIAL.
     EMDEZX_USEX2 = L_VALUE2.
   ENDIF.
 ENDIF.

  IF IBUTT3 = 'X'.
   CLEAR L_CODE.
   L_ATNAM = 'P_WORK_ORDER'.  "WORK ORDER NUMBER
   SELECT SINGLE ATINN INTO L_ATINN
      FROM CABN
      WHERE ATNAM = L_ATNAM.
   IF SY-SUBRC <> 0.
      L_CODE = 'N'.
   ELSE.
      SELECT SINGLE ATWRT INTO L_VALUE3
       FROM AUSP
       WHERE OBJEK = L_OBJEK AND
           ATINN = L_ATINN.
     IF SY-SUBRC <> 0.
       L_CODE = 'N'.
     ENDIF.
   ENDIF.
*  ASSIGN THE VALUE TO EXPORT PARAMETER
   IF L_CODE IS INITIAL.
     EMDEZX_USEX3 = L_VALUE3.
   ENDIF.
  ENDIF.
  ENDIF.  "IF IE3MDPSLX-DELKZ = 'PA'
