FUNCTION Z_MM_IF_OB_02_006_DB.
*"----------------------------------------------------------------------
*"*"Local interface:
*"  EXPORTING
*"     VALUE(E_RETURN) LIKE  ZMMS0053 STRUCTURE  ZMMS0053
*"  TABLES
*"      IT_BODY STRUCTURE  ZMMT0048
*"----------------------------------------------------------------------
  CLEAR : IT_M048, IT_M048[].
  G_DEST = 'WMPM01'.

  LOOP AT IT_BODY.

    IF IT_BODY-XEGLD = ''.
      PERFORM MAKE_SELECT_FIELD USING 'A~TRAID AS LIFEX'.
    ELSE.
      PERFORM MAKE_SELECT_FIELD USING 'A~VERUR AS LIFEX'.
    ENDIF.

    SELECT (FTAB)
    APPENDING CORRESPONDING FIELDS OF TABLE IT_M048
    FROM LIKP AS A INNER JOIN LIPS AS B
             ON A~VBELN = B~VBELN
              LEFT OUTER JOIN VEPO AS C
                     ON B~VBELN = C~VBELN
                    AND B~POSNR = C~POSNR
                   INNER JOIN VEKP AS E
                     ON C~VENUM = E~VENUM
                    AND E~STATUS <> '0060'
                  WHERE B~VGBEL = IT_BODY-EBELN
                   AND  B~VGPOS = IT_BODY-EBELP
                   AND  B~VBELN = IT_BODY-VBELN
                   AND  B~POSNR = IT_BODY-POSNR
                   AND  B~MATNR = IT_BODY-MATNR.
  ENDLOOP.

  LOOP AT IT_M048.
    IT_M048-ZFLAG = IT_BODY-ZFLAG.
    IT_M048-BUDAT = IT_BODY-BUDAT.
    IT_M048-MBLNR = IT_BODY-MBLNR.
    IT_M048-XEGLD = IT_BODY-XEGLD.

    CALL FUNCTION 'CONVERSION_EXIT_ALPHA_OUTPUT'
         EXPORTING
              INPUT  = IT_M048-EXIDV
         IMPORTING
              OUTPUT = IT_M048-EXIDV.

    MODIFY IT_M048.
  ENDLOOP.
**Paul Change TIME/DATE/NAME : 071211
  IT_M048-ATNAM = SY-UNAME.
  IT_M048-ATDAT = SY-DATUM.
  IT_M048-ATTIM = SY-UZEIT.

  MODIFY IT_M048 TRANSPORTING ATNAM ATDAT ATTIM
                 WHERE MBLNR NE ''.
**
** Furong on 07/21/11
  SORT IT_M048 BY VBELN MBLNR EXIDV.

  DELETE ADJACENT DUPLICATES FROM IT_M048
         COMPARING VBELN MBLNR EXIDV.

* SORT IT_M048 BY VBELN MBLNR EXIDV LIFNR MATNR POSNR.
*DELETE ADJACENT DUPLICATES FROM IT_M048
*         COMPARING VBELN MBLNR EXIDV LIFNR MATNR POSNR.
** End on 07/21/11

  MODIFY ZMMT0048 FROM TABLE IT_M048.


ENDFUNCTION.
