FUNCTION ZMMF_VAZ_IF_PR_INBOUND.
*"----------------------------------------------------------------------
*"*"Local interface:
*"  EXPORTING
*"     VALUE(E_IFRESULT) TYPE  ZRESULT
*"     VALUE(E_IFFAILMSG) TYPE  BAPIRETURN-MESSAGE
*"  TABLES
*"      IT_ZSMM_IF081 STRUCTURE  ZSMM_VAZ_IF081
*"      E_RETURN STRUCTURE  ZSMM_IF017 OPTIONAL
*"----------------------------------------------------------------------

  DATA  C_ZSMM_IF081 LIKE ZSMM_VAZ_IF081.
  DATA  IT_RETN LIKE TABLE OF ZSMM_IF017 WITH HEADER LINE.
  DATA  L_FLAG.

  DELETE ZTMM_VAZ_PR_LOG FROM TABLE IT_ZSMM_IF081.
INSERT ZTMM_VAZ_PR_LOG FROM TABLE IT_ZSMM_IF081 ACCEPTING DUPLICATE KEYS
  .
  IF SY-SUBRC = 0.
    COMMIT WORK.
  ENDIF.

  CLEAR:   C_ZSMM_IF081, IT_RETN, L_FLAG.
  REFRESH: IT_RETN.

  READ TABLE IT_ZSMM_IF081 WITH KEY ZFLAG = 'R'.
  IF SY-SUBRC = 0.
    DELETE IT_ZSMM_IF081 WHERE ZFLAG = 'C'.
    L_FLAG = 'X'.
  ENDIF.

  READ TABLE IT_ZSMM_IF081 WITH KEY ZFLAG = 'D'.
  IF SY-SUBRC = 0.
    DELETE IT_ZSMM_IF081 WHERE ZFLAG = 'C'.
    L_FLAG = 'X'.
  ENDIF.

  IF L_FLAG NE 'X'.

    CALL FUNCTION 'ZMMF_IF_PR_INBOUND_CREATE'
         TABLES
              IT_ZSMM_IF081 = IT_ZSMM_IF081
              E_RETURN      = IT_RETN.

    E_RETURN[] = IT_RETN[].

  ELSE.
    LOOP AT IT_ZSMM_IF081.
      IF IT_ZSMM_IF081-ZFLAG = 'R'.

        CLEAR IT_RETN.REFRESH IT_RETN.
        CALL FUNCTION 'ZMMF_IF_PR_INBOUND_CHANGE'
             EXPORTING
                  I_ZSMM_IF081 = IT_ZSMM_IF081
             TABLES
                  E_RETURN     = IT_RETN.

        LOOP AT IT_RETN.
          MOVE-CORRESPONDING IT_RETN TO E_RETURN.
          APPEND E_RETURN.
        ENDLOOP.
      ELSEIF IT_ZSMM_IF081-ZFLAG = 'D'.

        CLEAR IT_RETN.REFRESH IT_RETN.
        CALL FUNCTION 'ZMMF_VAZ_IF_PR_INBOUND_DEL'
             EXPORTING
                  I_ZSMM_IF081 = IT_ZSMM_IF081
             TABLES
                  E_RETURN     = IT_RETN.

        LOOP AT IT_RETN.
          MOVE-CORRESPONDING IT_RETN TO E_RETURN.
          APPEND E_RETURN.
        ENDLOOP.

      ENDIF.
    ENDLOOP.
  ENDIF.

  READ TABLE E_RETURN WITH KEY TYPE = 'E'.
  IF SY-SUBRC = 0.
    E_IFRESULT = 'E'.
    E_IFFAILMSG = E_RETURN-MESSAGE.
  ELSE.
    E_IFRESULT = 'S'.
    E_IFFAILMSG = 'Success'.
  ENDIF.

ENDFUNCTION.
