REPORT RAIMCOPY MESSAGE-ID AP
                LINE-SIZE 150
                NO STANDARD PAGE HEADING.

INCLUDE LKBPPEQU.

TYPE-POOLS: IM, BSV, SSCR.

TABLES: IMTP, IMTT, IMPR, IMPU, IMPS, IMZO.
TABLES: TBP1C, TAI05, TAI08, JEST, TAIF2, RAIP3.
TABLES: IMAK, IMAKZ, BPGE, BPEG, BPJA, BPEJ.
TABLES: PRPS, AUFKV.
*ABLES: rssubinfo.

SELECTION-SCREEN SKIP 1.
* Quellprogramm.
SELECTION-SCREEN BEGIN OF BLOCK OLD.
  PARAMETERS: PA_PRNAM LIKE IMTP-PRNAM
                       MEMORY ID IMT
                       MODIF ID OLD,
              PA_POSID LIKE IMPR-POSID
                       MODIF ID OIN,
              PA_GJAHR LIKE IMTP-GJAHR
                       MEMORY ID GJR
                       MODIF ID OLD.
SELECTION-SCREEN END   OF BLOCK OLD.

SELECTION-SCREEN SKIP 1.
* Zielprogramm.
SELECTION-SCREEN BEGIN OF BLOCK NEW
                       WITH FRAME TITLE TEXT-F01.
  PARAMETERS: P_PRNAM  LIKE IMTP-PRNAM
                       MODIF ID NEW,
              P_POSID  LIKE IMPR-POSID
                       MODIF ID NIN,
              P_GJAHR  LIKE IMTP-GJAHR
                       MODIF ID NEW.
SELECTION-SCREEN END   OF BLOCK NEW.

* Parameter für Vortrag.
SELECTION-SCREEN BEGIN OF BLOCK SET
                       WITH FRAME TITLE TEXT-F02.
*PARAMETERS: P_XCFPO LIKE RAIP1-XCFPO MODIF ID CFP.
PARAMETER P_XCFMR LIKE RAIP1-XCFMR MODIF ID CFM DEFAULT 'X'.
PARAMETER P_XCFTC LIKE RAIP1-XCFTC NO-DISPLAY DEFAULT 'X'.
PARAMETER P_XCFBU LIKE RAIP1-XCFBU MODIF ID CFV DEFAULT 'X'.
PARAMETER P_XCFPL LIKE RAIP1-XCFPL MODIF ID CFV.
*                                                " beg_ins " n. 514168
*
SELECT-OPTIONS: SO_VERSN FOR RAIP3-VERSN
                MODIF ID VSN DEFAULT '000'.
*PARAMETERS:     P_PTRUP TYPE IM_PTRUP
*                MODIF ID PRU.
SELECTION-SCREEN END   OF BLOCK SET.
* Parameter für Hochrollen.
PARAMETERS: P_XPPPL LIKE RAIP1-XPPPL NO-DISPLAY,
            P_XPPBU LIKE RAIP1-XPPBU NO-DISPLAY.

FIELD-SYMBOLS: <FS>.

CONSTANTS: CON_INSERT(1)    TYPE C         VALUE 'I',
           CON_UPDATE(1)    TYPE C         VALUE 'U',
           CON_DELETE(1)    TYPE C         VALUE 'D',
           CON_STATUS_FREI  LIKE JEST-STAT VALUE 'I0002',
           CON_STATUS_TABGS LIKE JEST-STAT VALUE 'I0045',
           CON_STATUS_ABGS  LIKE JEST-STAT VALUE 'I0046',
           CON_STATUS_ABGL  LIKE JEST-STAT VALUE 'I0359',
           ON(1)            TYPE C         VALUE 'X',
           OFF(1)           TYPE C         VALUE ' '.
DATA:      CON_MODE(1)      TYPE C         VALUE 'N'.

DATA:      FLG_TAKEOVER_ALLOWED,
           FLG_NO_VERSIONS_USED.
DATA:      FLG_SEND_LOSS_OF_DATA_WARNING VALUE 'X'.        " n. 533836
data:      l_plget like raip1-plget.                       " n. 536448
data:      flg_single_request_sel_only.                    " n. 420875

DATA:      PRNAM_INIT LIKE IMPR-PRNAM,
           POSID_INIT LIKE IMPR-POSID,
           GJAHR_INIT LIKE IMPR-GJAHR,
           L_SPRAS    TYPE SPRAS.

DATA:      YDIST_OLD  LIKE IMTP-YDIST,                     " n. 373709
           YDIST_NEW  LIKE IMTP-YDIST.                     " n. 373709

DATA: HLP_PROTTEXT0(150) TYPE C,
      HLP_PROTTEXT(150) TYPE C.
DATA: HLP_PRART      LIKE IMTP-PRART.
DATA: HLP_PROGRAM LIKE SY-REPID,
      HLP_DYNNR   LIKE SY-DYNNR.
DATA: HLP_CALLMODE TYPE IM_UPD_CALLMODE.
DATA: BEGIN OF HLP_INVPROG_FROM,
        PRNAM  LIKE IMTP-PRNAM,
        SLASH1 TYPE C,
        POSID  LIKE IMPR-POSID,
        SLASH2 TYPE C,
        GJAHR  LIKE IMTP-GJAHR,
      END   OF HLP_INVPROG_FROM.
DATA: BEGIN OF HLP_INVPROG_TO,
        PRNAM  LIKE IMTP-PRNAM,
        SLASH1 TYPE C,
        POSID  LIKE IMPR-POSID,
        SLASH2 TYPE C,
        GJAHR  LIKE IMTP-GJAHR,
      END   OF HLP_INVPROG_TO.

DATA: RESTRICT        TYPE SSCR_RESTRICT.
DATA: BEGIN OF        T_SELOP_NAME OCCURS 2,
        NAME(30)      TYPE C,
      END   OF        T_SELOP_NAME.

DATA: NEW_IMTP  LIKE IMTP  OCCURS   1 WITH HEADER LINE.
DATA: NEW_IMTT  LIKE IMTT  OCCURS   1 WITH HEADER LINE.
DATA: NEW_IMPR  LIKE IMPR  OCCURS 100 WITH HEADER LINE.
DATA: NEW_IMPU  LIKE IMPU  OCCURS 100 WITH HEADER LINE.
DATA: NEW_IMPS  LIKE IMPS  OCCURS 100 WITH HEADER LINE.
DATA: OLD_IMZO  LIKE IMZO  OCCURS 100 WITH HEADER LINE.
DATA: NEW_IMZO  LIKE IMZO  OCCURS 100 WITH HEADER LINE.
DATA: DEL_IMZO  LIKE IMZO  OCCURS 100 WITH HEADER LINE.
DATA: UPD_IMZO  LIKE IMZO  OCCURS 100 WITH HEADER LINE.

DATA: OLD_IMPR     LIKE IMPR  OCCURS 100 WITH HEADER LINE.
DATA: OLD_IMPR_PAR LIKE IMPR  OCCURS 100 WITH HEADER LINE.
DATA: NEW_IMPR_PAR LIKE IMPR  OCCURS 100 WITH HEADER LINE.

DATA: XTAIF2 LIKE TAIF2 OCCURS 10 WITH HEADER LINE.
DATA: XTAIF7 LIKE TAIF7 OCCURS 10 WITH HEADER LINE.

DATA: BEGIN OF REPLACETAB OCCURS 100,
        POSNR_OLD LIKE IMPR-POSNR,
        POSNR_NEW LIKE IMPR-POSNR,
      END   OF REPLACETAB.

DATA:   IM_OBARTS(10) TYPE C.
RANGES: SEL_OBJNR FOR IMZO-OBJNR.


*AT SELECTION-SCREEN ON BLOCK OLD.
*
**  Quellprogramm O.K.?
*   CALL FUNCTION 'AIPA_CHECK_SUBTREE_INVPROG'
*        EXPORTING
*           I_PRNAM                  = PA_PRNAM
*           I_POSID                  = PA_POSID
*           I_GJAHR                  = PA_GJAHR.
*   " EXCEPTIONS
*   "       NO_ENTRIES_MADE          = 1
*   "       ENTRIES_NOT_COMPLETE     = 2
*   "       PROGRAM_DOES_NOT_EXIST   = 3
*   "       POSITION_DOES_NOT_EXIST  = 4
*   "       OTHERS                   = 5.
*

AT SELECTION-SCREEN OUTPUT.
    LOOP AT SCREEN.
      IF SCREEN-NAME = 'P_XCFPL'.
        SCREEN-INPUT =  0.
        MODIFY SCREEN.
      ENDIF.
    ENDLOOP.

START-OF-SELECTION.

  SUBMIT RAIMCOPY
          WITH PA_PRNAM = p_prnam
          WITH PA_POSID = p_posid
          WITH PA_GJAHR = p_gjahr
          WITH P_PRNAM  = pA_prnam
          WITH P_POSID  = pA_posid
          WITH P_GJAHR  = pA_gjahr
*          WITH PA_RPLA  = '1'  "ar plan
*          WITH PA_PLAN  = '2'  "pi plan
*          WITH PA_BUDG  = '3'  "budget(program)
*          WITH PA_MPLAN = '4'  "order plan
*          WITH PA_MBUDG = '5'  "budget(measure)
*          WITH PA_IST   = '6'  "actual
*          WITH PA_OBLIG = '7'  "commitment
*          WITH PA_VERFB = '8'  "avail
*          WITH PA_ANZA  = '9'  "downpay
*          WITH PA_POSRM = 'X'  "posi,req,measure
*          WITH PA_OLDMS = 'X'  "old also
          WITH PA_TCODE = 'IM27_REPEAT'
          WITH P_XCFMR  = 'X'
          WITH P_XCFTC  = 'X'
          WITH P_XCFBU  = 'X'
          WITH P_XCFPL  = ' '
            and return.
