*&---------------------------------------------------------------------*
*&  Include           ZFMR0030TOP
*&---------------------------------------------------------------------*

TYPE-POOLS : SLIS.
TABLES : BPPE, FMFCTR, FMCI, FM01, TBPFE, FAGLFLEX02.

FIELD-SYMBOLS <FS>.
*Define
DEFINE ICLEAR.
  CLEAR : &1, &1[].
END-OF-DEFINITION.

DEFINE IAPPEND.
  APPEND : &1.
  CLEAR  : &1.
END-OF-DEFINITION.

DEFINE ICOLLECT.
  COLLECT : &1.
  CLEAR   : &1.
END-OF-DEFINITION.

*---// Internal tables
DATA : GT_9000 TYPE STANDARD TABLE OF ZSFM0008
                                     WITH HEADER LINE,
       GT_NODE LIKE SETNODE OCCURS 0 WITH HEADER LINE,
       GT_LEAF LIKE SETLEAF OCCURS 0 WITH HEADER LINE,
       GT_SETHEADERT LIKE SETHEADERT OCCURS 0 WITH HEADER LINE,

       BEGIN OF GT_FMCI OCCURS 0,
         FIPEX LIKE FMCIT-FIPEX,
         BEZEI LIKE FMCIT-BEZEI,
         TEXT1 LIKE FMCIT-TEXT1,
       END OF GT_FMCI,

       BEGIN OF GT_ITAB OCCURS 0,
         FIPEX    LIKE ZSFM0008-FIPEX,
         BEZEI(100),
         WAERS    LIKE ZSFM0008-WAERS,
         C_PLAN   LIKE ZSFM0008-WTP01,
         C_ACTUAL LIKE ZSFM0008-WTP01,
         C_DIFF   LIKE ZSFM0008-WTP01,
         T_PLAN   LIKE ZSFM0008-WTP01,
         T_ACTUAL LIKE ZSFM0008-WTP01,
         T_DIFF   LIKE ZSFM0008-WTP01,
       END OF GT_ITAB.

DATA : BEGIN OF GT_DOWN OCCURS 0,
          BEZEI(40),
          FIPEX(20),
          C_PLAN   LIKE ZSFM0008-WTP01,
          C_ACTUAL LIKE ZSFM0008-WTP01,
          C_DIFF   LIKE ZSFM0008-WTP01,
          T_PLAN   LIKE ZSFM0008-WTP01,
          T_ACTUAL LIKE ZSFM0008-WTP01,
          T_DIFF   LIKE ZSFM0008-WTP01,
        END OF GT_DOWN.

DATA : BEGIN OF LT_DOWN OCCURS 0,
          BEZEI(50),
          FIPEX(20),
          C_ACTUAL(20),
          C_PLAN(20),
          C_DIFF(20),
          T_ACTUAL(20),
          T_PLAN(20),
          T_DIFF(20),
        END OF LT_DOWN.

RANGES : R_FIPEX  FOR FMCI-FIPEX,
         R_WRTTP  FOR FMFIX-WRTTP.

CONSTANTS : C_SIZE TYPE I VALUE '168'.
*----------------------------------------------------------------------
* ALV
*----------------------------------------------------------------------
CLASS LCL_APPLICATION DEFINITION DEFERRED.

TYPES: ITEM_TABLE_TYPE LIKE STANDARD TABLE OF MTREEITM
       WITH DEFAULT KEY.

DATA : G_CUSTOM_CONTAINER  TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
       G_GRID              TYPE REF TO CL_GUI_COLUMN_TREE,
       G_APPLICATION       TYPE REF TO LCL_APPLICATION,

       GT_NODE_TABLE       TYPE TREEV_NTAB WITH HEADER LINE,
       GT_ITEM_TABLE       TYPE ITEM_TABLE_TYPE WITH HEADER LINE,
       GS_HIERARCHY_HEADER TYPE TREEV_HHDR,
       G_RETURN_CODE       TYPE I,
       G_NODE_KEY_TABLE    TYPE TREEV_NKS WITH HEADER LINE,
       G_EVENTS            TYPE CNTL_SIMPLE_EVENTS,
       G_EVENT             TYPE CNTL_SIMPLE_EVENT,
       G_AUTH_CHECK(1),
       GT_FIELDCAT         TYPE SLIS_T_FIELDCAT_ALV WITH HEADER LINE,
       GS_LAYOUT           TYPE SLIS_LAYOUT_ALV,
       GT_LIST_TOP         TYPE SLIS_T_LISTHEADER,
       P_FICTR             LIKE FMFCTR-FICTR,
       P_BEZEICH           LIKE FMFCTRT-BEZEICH.

CONSTANTS : C_CLASS  LIKE SETNODE-SETCLASS VALUE '0311',
            ROOT TYPE TV_ITMNAME VALUE 'Root',
            BEGIN OF C_COL,
              C01 TYPE TV_ITMNAME VALUE 'C01',
              C02 TYPE TV_ITMNAME VALUE 'C02',
              C03 TYPE TV_ITMNAME VALUE 'C03',
              C04 TYPE TV_ITMNAME VALUE 'C04',
              C05 TYPE TV_ITMNAME VALUE 'C05',
              C06 TYPE TV_ITMNAME VALUE 'C06',
              C07 TYPE TV_ITMNAME VALUE 'C07',
              C08 TYPE TV_ITMNAME VALUE 'C08',
            END OF C_COL.

*---// Selection screen
SELECTION-SCREEN BEGIN OF BLOCK BL1 WITH FRAME TITLE TEXT-T01.
PARAMETERS: P_FIKRS LIKE FMCI-FIKRS OBLIGATORY,
            P_GJAHR LIKE FMCI-GJAHR MEMORY ID GJR OBLIGATORY
                                    DEFAULT SY-DATUM(4),
            P_PERIOD TYPE PERMO DEFAULT SY-DATUM+4(2).
SELECT-OPTIONS:
                S_GEBER  FOR BPPE-GEBER  NO-DISPLAY,
                S_FICTR  FOR FMFCTR-FICTR,
                S_FIPEX  FOR FMCI-FIPEX,
                S_PROFIL FOR TBPFE-PROFIL,
                S_POTYP  FOR FMCI-POTYP.
SELECTION-SCREEN SKIP 1.
PARAMETERS: P_GRPID LIKE GRPDYNP-NAME_COALL OBLIGATORY.
SELECTION-SCREEN END OF BLOCK BL1.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR P_GRPID.

  DATA : SETID       LIKE  RGSBS-SETNR.

  CALL FUNCTION 'K_GROUP_SELECT'
    EXPORTING
      CLASS           = C_CLASS
      FIELD_NAME      = ' '
      SEARCHFLD       = ' '
      SEARCHFLD_INPUT = ' '
      SET             = '*'
    IMPORTING
      SETID           = SETID
    EXCEPTIONS
      NO_SET_PICKED   = 1.

  P_GRPID = SETID+8(10).
