FUNCTION Z_FSD_GLOVIS_PREP.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(BODYNO) LIKE  AUSP-OBJEK OPTIONAL
*"     REFERENCE(MESTYP) LIKE  EDP13-MESTYP DEFAULT 'ZSIGNOFF_MST'
*"     REFERENCE(SEGNAM) LIKE  EDIDD-SEGNAM DEFAULT 'ZSOFFSEG'
*"  EXPORTING
*"     REFERENCE(RETURN) LIKE  BAPIRETURN STRUCTURE  BAPIRETURN
*"     VALUE(OUTPUT) LIKE  ZSOFFSEG STRUCTURE  ZSOFFSEG
*"  TABLES
*"      T_BODYNO STRUCTURE  ZSSD_GLOV_INPUT
*"----------------------------------------------------------------------
*Select P_MODEL  P_BODY_SERIAL
*from ZTPPVR
*where ( P_STATUS IN R_STATUS
* AND  P_DEST_CODE IN R_DEST .
*
* ‘T01’ or ‘T02’ or ‘T03’) and
*              (ZTPPVR-P_DEST_CODE = ‘B28A*’)
*
*concatenate P_MODEL  P_BODY_SERIAL = key
  DATA : LT_DATA   LIKE TABLE OF T_BODYNO WITH HEADER LINE,
         LT_UM     LIKE TABLE OF ZTSD_UM  WITH HEADER LINE,
         LT_XZSSEG LIKE TABLE OF ZSOFFSEG WITH HEADER LINE.

  DATA : XMDCD    LIKE ZTSD_UM-MODEL_CODE,
         XBDNO    LIKE ZTSD_UM-BODY_NO,
         XOBJEK   LIKE MARA-MATNR,
         XZSSEG   LIKE ZSOFFSEG,
         XWOSER   LIKE AUSP-ATWRT ,
         XSDATE   LIKE AUSP-ATWRT .

  DATA : XAUSP    LIKE TABLE OF ZSPP_VIN_VALUE WITH HEADER LINE.

  CLEAR : XZSSEG , XOBJEK.
  MOVE : BODYNO TO XOBJEK .
  XMDCD = XOBJEK+0(3).
  XBDNO = XOBJEK+3(6).

** Furong on 10/31/11
*  check not T_BODYNO[] is initial.
** end on 10/31/11
  LT_DATA[] = T_BODYNO[].

  LOOP AT LT_DATA.
    LT_DATA-MODEL_CODE = LT_DATA-OBJEK+0(3).
    LT_DATA-BODY_NO    = LT_DATA-OBJEK+3(6).
    MODIFY LT_DATA.
  ENDLOOP.

** KDM on 11/01/11 : Check lt_data[]
  IF LT_DATA[] IS NOT INITIAL.
    SELECT ZVIN MODEL_CODE BODY_NO "XZSSEG-ZVIN
        INTO CORRESPONDING FIELDS OF TABLE LT_UM "XZSSEG-ZVIN
       FROM ZTSD_UM
       FOR ALL ENTRIES IN LT_DATA
      WHERE MODEL_CODE    = LT_DATA-MODEL_CODE
        AND BODY_NO       = LT_DATA-BODY_NO
        AND STATUS     <> 'S'
        AND STATUS     <> 'D'.

    SORT LT_UM BY MODEL_CODE BODY_NO.
  ENDIF.
** end on 11/01/11

  CLEAR : XZSSEG, XWOSER, XSDATE .
  LOOP AT LT_DATA.

    PERFORM GETSINGLE_ATWRT USING :
       LT_DATA-OBJEK XZSSEG-VIN        'P_VIN',
       LT_DATA-OBJEK XZSSEG-MODEL_CODE 'P_MI' ,
       LT_DATA-OBJEK XZSSEG-OCCN       'P_OCN' ,
       LT_DATA-OBJEK XWOSER            'P_WORK_ORDER' ,
       LT_DATA-OBJEK XZSSEG-WO_EXTC    'P_EXT_COLOR' ,
       LT_DATA-OBJEK XZSSEG-WO_INTC    'P_INT_COLOR' ,
       LT_DATA-OBJEK XZSSEG-ENG_NO     'P_ENGINE_NO'   ,
       LT_DATA-OBJEK XZSSEG-KEYN       'P_KEY_NO'  ,
       LT_DATA-OBJEK XZSSEG-SHOP_DATE  'P_RP18_SHOP_DATE'  ,
       LT_DATA-OBJEK XSDATE            'P_RP18_ACTUAL_DATE',
       LT_DATA-OBJEK XZSSEG-XMID       'P_AIRBAG_NO10'  ,
       LT_DATA-OBJEK XZSSEG-IMMOID     'P_AIRBAG_NO16'.

    XZSSEG-HKMC   =   'HMG'.
    XZSSEG-WKNO   =   XWOSER+0(9) .
    XZSSEG-DISTCO =   XWOSER+9(5) .
    XZSSEG-ACT_DATE = XSDATE+0(8).
    XZSSEG-ACT_TIME = XSDATE+8(14).

    READ TABLE LT_UM WITH KEY MODEL_CODE = LT_DATA-MODEL_CODE
                              BODY_NO    = LT_DATA-BODY_NO
                              BINARY SEARCH.
    IF SY-SUBRC <> 0 . CLEAR  LT_UM. ENDIF.
    XZSSEG-ZVIN = LT_UM-ZVIN.

    APPEND XZSSEG TO LT_XZSSEG.
    CLEAR : XZSSEG, XWOSER, XSDATE .
  ENDLOOP.

***********************************************************
*# Send Glovis
***********************************************************
  PERFORM SEND_GLOVIS TABLES LT_XZSSEG.

ENDFUNCTION.
