FUNCTION Z_FSD_GET_KSBOHMM.
*"----------------------------------------------------------------------
*"*"Local interface:
*"  TABLES
*"      T_ZTSD_HACPO STRUCTURE  ZTSD_HACPO
*"----------------------------------------------------------------------

  DATA : IT_ZTSD_HACPO LIKE TABLE OF ZTSD_HACPO WITH HEADER LINE,
         L_DEALER(2) TYPE C,
         L_DEAL(1) TYPE C.

*  DELETE FROM ZTSD_HACPO CLIENT SPECIFIED WHERE ZSDAT < L_DATE
*                                            AND MANDT = SY-MANDT.

  LOOP AT T_ZTSD_HACPO.
    MOVE-CORRESPONDING T_ZTSD_HACPO TO IT_ZTSD_HACPO.
    L_DEAL = T_ZTSD_HACPO-DEALER.
    CALL FUNCTION 'ZFEB_GET_OLD_DEALER_CODE'
         EXPORTING
              NEW_DEALER = L_DEAL
         IMPORTING
              OLD_DEALER = L_DEALER.

    IF L_DEALER IS INITIAL.
      MOVE  'E' TO T_ZTSD_HACPO-ZZRET.
*      CONTINUE.
      MESSAGE E001 WITH 'Dealer conversion error:' T_ZTSD_HACPO-WO_SER
                         T_ZTSD_HACPO-DEALER.
    ELSE.
      IT_ZTSD_HACPO-DEALER =  L_DEALER.
    ENDIF.
*    CONCATENATE IT_ZTSD_HACPO-HACPO+1(3) IT_ZTSD_HACPO-HACPO+5(5)
*               INTO IT_ZTSD_HACPO-HACPO.
    SELECT SINGLE ZSDAT ZSTIM INTO (IT_ZTSD_HACPO-ZSDAT,
      IT_ZTSD_HACPO-ZSTIM)
      FROM ZTSD_HACPO
      WHERE WO_SER = T_ZTSD_HACPO-WO_SER
        AND NATION = T_ZTSD_HACPO-NATION
        AND DEALER = T_ZTSD_HACPO-DEALER
        AND EXTC = T_ZTSD_HACPO-EXTC
        AND INTC = T_ZTSD_HACPO-INTC.
    IF SY-SUBRC = 0.
      IT_ZTSD_HACPO-ZEDAT = SY-DATUM.
      IT_ZTSD_HACPO-ZETIM = SY-UZEIT.
    ELSE.
      IT_ZTSD_HACPO-ZSDAT = SY-DATUM.
      IT_ZTSD_HACPO-ZSTIM = SY-UZEIT.
      IT_ZTSD_HACPO-ZEDAT = SY-DATUM.
      IT_ZTSD_HACPO-ZETIM = SY-UZEIT.
    ENDIF.
    APPEND IT_ZTSD_HACPO.
    MODIFY ZTSD_HACPO FROM IT_ZTSD_HACPO.
    IF SY-SUBRC = 0.
      MOVE  'S' TO T_ZTSD_HACPO-ZZRET.
    ELSE.
      MOVE  'E' TO T_ZTSD_HACPO-ZZRET.
    ENDIF.
    MODIFY T_ZTSD_HACPO.
  ENDLOOP.
  COMMIT WORK.
ENDFUNCTION.
