FUNCTION Z_FSD_WO_INFO1.
*"----------------------------------------------------------------------
*"*"Local interface:
*"  IMPORTING
*"     REFERENCE(P_MATNR) LIKE  MARA-MATNR
*"     REFERENCE(P_MTART) LIKE  MARA-MTART
*"  EXPORTING
*"     REFERENCE(P_MODQT) LIKE  VBAP-KWMENG
*"     REFERENCE(P_SO) LIKE  VBAK-VBELN
*"     REFERENCE(P_INDEX) LIKE  MARA-LVORM
*"  EXCEPTIONS
*"      1
*"      2
*"----------------------------------------------------------------------
*  DATA: L_CUOBF LIKE MARA-CUOBF.
*  DATA: L_MATNR LIKE MARA-MATNR.
*  DATA: L_CONFIGURATION	LIKE  CONF_OUT  OCCURS 0 WITH HEADER LINE.
*  DATA: L_CONFIGURATION_IDOC LIKE  API_VALUE OCCURS 0 WITH HEADER LINE.
*
**  CALL FUNCTION 'CONVERSION_EXIT_ALPHA_INPUT'
**    EXPORTING
**      INPUT         = P_MATNR
**   IMPORTING
**     OUTPUT         = L_MATNR.
*
*  SELECT SINGLE CUOBF
*  INTO   L_CUOBF
*  FROM   MARA
*  WHERE  MATNR EQ P_MATNR
*  AND    MTART EQ P_MTART
*  AND    KZKFG EQ ''.
*
*  CALL FUNCTION 'VC_I_GET_CONFIGURATION_IBASE'
*    EXPORTING
*      INSTANCE                  = L_CUOBF
**     BUSINESS_OBJECT           =
*      LANGUAGE                  = SY-LANGU
**     IV_INVALID_POSSIBLE       = ' '
**     IV_NEUTRAL                = ' '
*   TABLES
*     CONFIGURATION             = L_CONFIGURATION
*     ET_CONF_WITH_AUTHOR       = L_CONFIGURATION_IDOC
*   EXCEPTIONS
*     INSTANCE_NOT_FOUND        = 1
*     OTHERS                    = 2.
*
*  IF SY-SUBRC = 0.
*    IF P_MTART EQ 'WOCL'.
*      READ TABLE L_CONFIGURATION_IDOC WITH KEY ATNAM = 'P_SALES_ORDER'.
*      IF SY-SUBRC = 0.
*        P_SO = L_CONFIGURATION_IDOC-ATWRT.
*      ENDIF.
*
*      READ TABLE L_CONFIGURATION_IDOC WITH KEY ATNAM = 'P_MOD_QTY'.
*      IF SY-SUBRC = 0.
*        P_MODQT = L_CONFIGURATION_IDOC-ATWRT.
*      ENDIF.
*    ELSEIF P_MTART EQ 'WOHD'.
*      P_INDEX = 1.
*    ENDIF.
*  ELSE.
*    P_INDEX = 'X'.
*  ENDIF.

DATA : W_SALES_ORDER LIKE CABN-ATINN,
       W_MOD_QTY LIKE CABN-ATINN,
       W_N_10(10) TYPE N.

IF P_MTART = 'WOHD'.
  SELECT SINGLE * FROM AUSP
         WHERE OBJEK = P_MATNR.
  IF SY-SUBRC = 0.
    P_INDEX = 1.
  ELSE.
    P_INDEX  = 'X'.
    EXIT.
  ENDIF.
ELSE. "WOCL
  SELECT SINGLE * FROM AUSP
         WHERE OBJEK = P_MATNR.
  IF SY-SUBRC = 0.
    P_INDEX = 1.
  ELSE.
    P_INDEX  = 'X'.
    EXIT.
  ENDIF.

  SELECT SINGLE ATINN INTO W_SALES_ORDER
         FROM CABN
        WHERE ATNAM = 'P_SALES_ORDER'.
  SELECT SINGLE ATINN INTO W_MOD_QTY
         FROM CABN
        WHERE ATNAM = 'P_MOD_QTY'.

  SELECT SINGLE * FROM AUSP
         WHERE OBJEK = P_MATNR
         AND   ATINN = W_SALES_ORDER.
  IF SY-SUBRC = 0.
    P_SO = AUSP-ATWRT.
  ELSE.
    P_SO = ''.
  ENDIF.

  SELECT SINGLE * FROM AUSP
         WHERE OBJEK = P_MATNR
         AND   ATINN = W_MOD_QTY.
  IF SY-SUBRC = 0.
    W_N_10 = AUSP-ATFLV.
    P_MODQT = W_N_10.
  ELSE.
    P_MODQT = ''.
  ENDIF.
ENDIF.
ENDFUNCTION.
