FUNCTION Z_FSD_ORDER_STATUS2.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(DATE) LIKE  T093B-ABGJA
*"     VALUE(IT_WOSUM) LIKE  ZTPP_WOSUM STRUCTURE  ZTPP_WOSUM
*"     VALUE(FLAG) TYPE  FLAG
*"     VALUE(HACPO) TYPE  FLAG
*"  TABLES
*"      S_ATINN STRUCTURE  ZX300
*"      IT_CABN STRUCTURE  ZX400
*"      IT_DOWNFILE STRUCTURE  ZX200
*"      IT_DOWNFILE_HMA STRUCTURE  ZX200
*"      IT_DOWNFILE_HAC STRUCTURE  ZX200
*"----------------------------------------------------------------------
* Modification Log
* Date        Developer    Request ID   Description
* 10/25/2004  Shiva        UD1K912648   Formatted the file to place the
*                                       fields in correct position.
* 12/20/2004  Shiva        UD1K913591   Changed the position from 67 to
*                                       68 and added 1 on following.
* 05/31/2005  Shiva        UD1K916278   Number of MAXHITS parameter
*                                       needs to set to 2000.
* 07/22/2005  Shiva        UD1K916989   Don't select scrap cars.
* 07/25/2005  Shiva        UD1K917001   Remove scrap cars.
* 04/08/2006  Manju        UD1K940247   HAC Changes : Include all VIN
*                                       detail records even after ship
*                                       out / Change RP07 to RP17 in 02D
*                                       records.
************************************************************************

  DATA : W_N_8(8) TYPE N.

  DATA : BEGIN OF IT_AUSP OCCURS 0,
         OBJEK LIKE AUSP-OBJEK,
         ATINN LIKE AUSP-ATINN,
         ATNAM LIKE CABN-ATNAM,
         ATWRT LIKE AUSP-ATWRT,
         ATFLV LIKE AUSP-ATFLV,
         END OF IT_AUSP.

  DATA : BEGIN OF IT_AUSP_L OCCURS 0,
         OBJEK LIKE AUSP-OBJEK,
         ATINN LIKE AUSP-ATINN,
         ATNAM LIKE CABN-ATNAM,
         ATWRT LIKE AUSP-ATWRT,
         ATFLV LIKE AUSP-ATFLV,
         END OF IT_AUSP_L.
  DATA:  WA_AUSP LIKE IT_AUSP.
  DATA : L_COLOR_SER(2),
         L_MODEL LIKE ZTBM_ABYCOLDT-CTRN_CARS_C,
         L_YEAR LIKE ZTBM_ABYCOLDT-CTRN_YEAR_C2,
         L_EXT_COL3 LIKE ZTBM_ABYCOLDT-CTRN_GUBN_C,
         L_INT_COL3 LIKE ZTBM_ABYCOLDT-CTRN_GUBN_C.

  DATA : W_OBJEK LIKE AUSP-OBJEK.

  DATA: L_RP01_ACTUAL LIKE ZTPP_WOSUM-RP01TQ,
        L_RP02_ACTUAL LIKE ZTPP_WOSUM-RP01TQ,
        L_RP17_ACTUAL LIKE ZTPP_WOSUM-RP01TQ,
        L_RP18_ACTUAL LIKE ZTPP_WOSUM-RP01TQ,
        L_RP19_ACTUAL LIKE ZTPP_WOSUM-RP01TQ,
        L_RP20_ACTUAL LIKE ZTPP_WOSUM-RP01TQ,
        L_RP24_RP26_ACTUAL LIKE ZTPP_WOSUM-RP01TQ,
        L_RP25_RP27_ACTUAL LIKE ZTPP_WOSUM-RP01TQ,
        L_RP27_ACTUAL LIKE ZTPP_WOSUM-RP01TQ.

*&* PERFORM MAKE_VM
  DATA : SO LIKE BAPI_SELECTED_OBJECTS OCCURS 0 WITH HEADER LINE,
         SC LIKE BAPI_SELECTION_CRITERIONS OCCURS 0 WITH HEADER LINE.

  DATA : W_WORKORDER(14).

  REFRESH : SC, SO. CLEAR : SC, SO.

  CONCATENATE IT_WOSUM-WO_SER IT_WOSUM-NATION IT_WOSUM-DEALER
              INTO W_WORKORDER.

  SC-NAME_CHAR  = 'P_WORK_ORDER'.
  SC-CHAR_VALUE = W_WORKORDER.
  APPEND SC.

  SC-NAME_CHAR  = 'P_EXT_COLOR'.
  SC-CHAR_VALUE = IT_WOSUM-EXTC.
  APPEND SC.

  SC-NAME_CHAR  = 'P_INT_COLOR'.
  SC-CHAR_VALUE = IT_WOSUM-INTC.
  APPEND SC.

  SC-NAME_CHAR  = 'P_SALES_ORDER'.
  SC-CHAR_VALUE = IT_WOSUM-SALES.
  APPEND SC.

**  SC-NAME_CHAR  = 'P_FSC'.
**  SC-CHAR_VALUE = IT_WOSUM-FSC.
**  APPEND SC.

  CALL FUNCTION 'BAPI_CLASS_SELECT_OBJECTS'
    EXPORTING
      CLASSTYPE                  = '002'
      CLASSNUM                   = 'P_VEHICLE_MASTER'
*     LANGUISO                   =
*     LANGUINT                   =
      KEYDATE                    = SY-DATUM
      MAXHITS                    = 99999
*     I_STATUS_LOCKED            = ' '
*     I_STATUS_INCOMPLETE        = ' '
*   IMPORTING
*     RETURN                     =
    TABLES
      SELECTIONCRITERIONS        = SC
      SELECTEDOBJECTS            = SO
*     OBJECTCLASSIFICATION       =
              .

  REFRESH : IT_AUSP, IT_AUSP_L.
  CLEAR   : IT_AUSP, IT_AUSP_L.
  LOOP AT SO.
    SELECT * INTO CORRESPONDING FIELDS OF TABLE IT_AUSP_L
           FROM AUSP
          WHERE ATINN IN S_ATINN
          AND   OBJEK EQ SO-OBJECT.
    LOOP AT IT_AUSP_L.
      IT_AUSP-OBJEK = IT_AUSP_L-OBJEK.
      IT_AUSP-ATINN = IT_AUSP_L-ATINN.
      IT_AUSP-ATWRT = IT_AUSP_L-ATWRT.
      IT_AUSP-ATFLV = IT_AUSP_L-ATFLV.
      READ TABLE IT_CABN WITH KEY ATINN = IT_AUSP-ATINN.
      IT_AUSP-ATNAM = IT_CABN-ATNAM.
      APPEND IT_AUSP. CLEAR IT_AUSP.
    ENDLOOP.
    CLEAR IT_AUSP_L.
  ENDLOOP.

*&* PERFORM MAKE_VM

**
*  IF it_wosum-wo_ser+1(4) LE date AND
*     it_wosum-modqty > it_wosum-seqqty.

** CHANGED BY FURONG ON 06/05/07, TRANSPORT #: UD1K940758

*&----Remove scrapped car.
  LOOP AT IT_AUSP.
    IF ( IT_AUSP-ATNAM = 'P_USAGE_CAR' AND IT_AUSP-ATWRT = 'D' )
     OR ( IT_AUSP-ATNAM = 'P_USAGE_CAR' AND IT_AUSP-ATWRT = 'S' ).
      DELETE IT_AUSP WHERE OBJEK = IT_AUSP-OBJEK.
    ENDIF.
  ENDLOOP.

  IT_DOWNFILE-RECORD+0(3)    = 'O1D'.
  IT_DOWNFILE-RECORD+3(2)    = '20'.
  IT_DOWNFILE-RECORD+5(2)    = IT_WOSUM-WO_SER+1(2).
  IT_DOWNFILE-RECORD+7(2)    = IT_WOSUM-WO_SER+3(2).
  IT_DOWNFILE-RECORD+9(3)    = IT_WOSUM-NATION.
  IT_DOWNFILE-RECORD+12(2)   = IT_WOSUM-DEALER.
  IT_DOWNFILE-RECORD+14(1)   = IT_WOSUM-WO_SER+5(1).

** Changed by Furong on 06/12/07
  CLEAR: L_EXT_COL3, L_INT_COL3.
  IF HACPO = 'X' AND IT_WOSUM-NATION = 'B06'.
    DATA: L_HACPO(10).
    SELECT SINGLE HACPO INTO L_HACPO
      FROM ZTSD_HACPO
      WHERE WO_SER = IT_WOSUM-WO_SER
        AND NATION = IT_WOSUM-NATION
        AND DEALER = IT_WOSUM-DEALER
        AND EXTC = IT_WOSUM-EXTC
        AND INTC = IT_WOSUM-INTC.
    IF SY-SUBRC = 0 .
      CONCATENATE L_HACPO+1(3) L_HACPO+5(5)
              INTO L_HACPO.
    ELSE.
** Changed by Furong on 10/16/09
      L_MODEL = IT_WOSUM-FSC+5(2).
      L_YEAR = IT_WOSUM-FSC+(1).

      SELECT SINGLE CTRN_KEY_COLR INTO L_EXT_COL3
        FROM ZTBM_ABYCOLDT
        WHERE CTRN_CARS_C = L_MODEL
          AND CTRN_YEAR_C2 = L_YEAR
          AND CTRN_GUBN_C = 'EXT'
** Changed by Furong on 01/20/10
          AND CTRN_CONF_COLR  = IT_WOSUM-EXTC.
*          and CTRN_TRAN_COLR = IT_WOSUM-EXTC.
** End of change
      SELECT SINGLE CTRN_KEY_COLR INTO L_INT_COL3
        FROM ZTBM_ABYCOLDT
        WHERE CTRN_CARS_C = L_MODEL
          AND CTRN_YEAR_C2 = L_YEAR
          AND CTRN_GUBN_C = 'INT'
** Changed by Furong on 01/20/10
          AND CTRN_CONF_COLR = IT_WOSUM-INTC.
*          AND CTRN_TRAN_COLR = IT_WOSUM-INTC.
** End of change
      SELECT SINGLE HACPO INTO L_HACPO
          FROM ZTSD_HACPO
          WHERE WO_SER = IT_WOSUM-WO_SER
            AND NATION = IT_WOSUM-NATION
            AND DEALER = IT_WOSUM-DEALER
            AND EXTC = L_EXT_COL3
            AND INTC = L_INT_COL3.
      IF SY-SUBRC = 0.
        CONCATENATE L_HACPO+1(3) L_HACPO+5(5)
                  INTO L_HACPO.
      ELSE.
** End of change
        CLEAR: L_HACPO.
      ENDIF.
    ENDIF.
    IT_DOWNFILE-RECORD+15(8) = L_HACPO.
  ELSE.
    IT_DOWNFILE-RECORD+15(1)   = IT_WOSUM-WO_SER+2(1).
    IT_DOWNFILE-RECORD+16(2)   = IT_WOSUM-WO_SER+3(2).
    IT_DOWNFILE-RECORD+18(3)   = IT_WOSUM-WO_SER+6(3).

* requested by catherine s. changed by chris
*      IT_DOWNFILE-RECORD+21(2)   = '01'. "COLOR_SER
    DATA: L_OBJECT LIKE MARA-MATNR.
    IF NOT IT_WOSUM-EXTC IS INITIAL AND
       NOT IT_WOSUM-INTC IS INITIAL.
      CONCATENATE W_WORKORDER
                  IT_WOSUM-EXTC
                  IT_WOSUM-INTC
             INTO L_OBJECT.
      CLEAR: WA_AUSP.

      SELECT SINGLE ATWRT INTO L_COLOR_SER
        FROM AUSP
        WHERE OBJEK  = L_OBJECT  AND
              KLART  = '001'     AND
              ATINN  = '0000002743'.
      IT_DOWNFILE-RECORD+21(2)   = L_COLOR_SER.
    ENDIF.
* end of change on 02/24/2005
  ENDIF.
** END OF CHANGE

  IT_DOWNFILE-RECORD+23(10)  = IT_WOSUM-SALES.
  IT_DOWNFILE-RECORD+33(10)  = IT_WOSUM-WO_SER.
  IT_DOWNFILE-RECORD+43(18)  = IT_WOSUM-FSC.

  IF HACPO = 'X' AND IT_WOSUM-NATION = 'B06'.
    IF L_EXT_COL3 IS INITIAL AND L_INT_COL3 IS INITIAL.
      IT_DOWNFILE-RECORD+61(3)   = IT_WOSUM-EXTC.
      IT_DOWNFILE-RECORD+64(3)   = IT_WOSUM-INTC.
    ELSE.
      IT_DOWNFILE-RECORD+61(3)   = L_EXT_COL3.
      IT_DOWNFILE-RECORD+64(3)   = L_INT_COL3.
    ENDIF.
  ELSE.
    IT_DOWNFILE-RECORD+61(3)   = IT_WOSUM-EXTC.
    IT_DOWNFILE-RECORD+64(3)   = IT_WOSUM-INTC.
  ENDIF.
  IT_DOWNFILE-RECORD+68(5)   = IT_WOSUM-MODQTY.
  IT_DOWNFILE-RECORD+73(5)   = IT_WOSUM-PLANQTY.
  IT_DOWNFILE-RECORD+78(5)   = IT_WOSUM-SEQQTY.

** Changed by Furong on06/08/07: UD1K940759
  LOOP AT IT_AUSP.
    CASE IT_AUSP-ATNAM.
      WHEN 'P_RP01_ACTUAL_DATE'.
        L_RP01_ACTUAL = L_RP01_ACTUAL + 1.
      WHEN 'P_RP02_ACTUAL_DATE'.
        L_RP02_ACTUAL = L_RP02_ACTUAL + 1.
      WHEN 'P_RP17_ACTUAL_DATE'.
        L_RP17_ACTUAL = L_RP17_ACTUAL + 1.
      WHEN 'P_RP18_ACTUAL_DATE'.
        L_RP18_ACTUAL = L_RP18_ACTUAL + 1.
      WHEN 'P_RP19_ACTUAL_DATE'.
        L_RP19_ACTUAL = L_RP19_ACTUAL + 1.
      WHEN 'P_RP20_ACTUAL_DATE'.
        L_RP20_ACTUAL = L_RP20_ACTUAL + 1.
      WHEN 'P_RP24_ACTUAL_DATE' OR 'P_RP26_ACTUAL_DATE'.
        L_RP24_RP26_ACTUAL = L_RP24_RP26_ACTUAL + 1.
      WHEN 'P_RP25_ACTUAL_DATE' OR 'P_RP27_ACTUAL_DATE'.
        L_RP25_RP27_ACTUAL = L_RP25_RP27_ACTUAL + 1.
    ENDCASE.
  ENDLOOP.

  IT_DOWNFILE-RECORD+83(5)   = L_RP01_ACTUAL.
  IT_DOWNFILE-RECORD+88(5)  = L_RP02_ACTUAL.
  IT_DOWNFILE-RECORD+93(5)  = L_RP17_ACTUAL.
  IT_DOWNFILE-RECORD+98(5)  = L_RP18_ACTUAL.
  IT_DOWNFILE-RECORD+103(5)  = L_RP19_ACTUAL.
  IT_DOWNFILE-RECORD+108(5)  = L_RP20_ACTUAL.
  IT_DOWNFILE-RECORD+113(5)  = L_RP24_RP26_ACTUAL.
  IT_DOWNFILE-RECORD+118(5)  = L_RP25_RP27_ACTUAL.

*  IT_DOWNFILE-RECORD+83(5)   = IT_WOSUM-RP01TQ.
*  IT_DOWNFILE-RECORD+88(5)  = IT_WOSUM-RP02TQ.
*  IT_DOWNFILE-RECORD+93(5)  = IT_WOSUM-RP07TQ.
*  IT_DOWNFILE-RECORD+98(5)  = IT_WOSUM-RP08TQ.
*  IT_DOWNFILE-RECORD+103(5)  = IT_WOSUM-RP09TQ.
*  IT_DOWNFILE-RECORD+108(5)  = IT_WOSUM-RP10TQ.
*** change by Furong on 24/06/05
**  IT_DOWNFILE-RECORD+113(5)  = IT_WOSUM-RP15TQ.
*  IT_DOWNFILE-RECORD+113(5)  = IT_WOSUM-RP14TQ.
*** end of change
*  IT_DOWNFILE-RECORD+118(5)  = IT_WOSUM-RP15TQ.

** end of change 06/08/07

  LOOP AT IT_AUSP.
    IF IT_AUSP-ATNAM = 'P_RP24_ACTUAL_DATE'.
      DELETE IT_AUSP.
    ENDIF.

    IF IT_AUSP-ATNAM = 'P_RP26_ACTUAL_DATE'.
      DELETE IT_AUSP.
    ENDIF.

    IF FLAG = 'X'.
      IF IT_AUSP-ATNAM = 'P_RP25_ACTUAL_DATE' AND
         IT_AUSP-ATWRT+0(8) <> '00000000'.
*         AND IT_WOSUM-NATION <> 'B06' .   "UD1K940247 UD1K940758
        DELETE IT_AUSP WHERE OBJEK = IT_AUSP-OBJEK.
      ENDIF.

      IF IT_AUSP-ATNAM = 'P_RP27_ACTUAL_DATE' AND
         IT_AUSP-ATWRT+0(8) <> '00000000'.
*         AND IT_WOSUM-NATION <> 'B06' .   "UD1K940247  UD1K940758
        DELETE IT_AUSP WHERE OBJEK = IT_AUSP-OBJEK.
      ENDIF.
      " UD1K940758
    ENDIF.
  ENDLOOP.
  APPEND IT_DOWNFILE.

*&* PERFORM R2

  IF IT_WOSUM-NATION = 'B28'.
    IT_DOWNFILE_HMA = IT_DOWNFILE.
    APPEND IT_DOWNFILE_HMA. CLEAR IT_DOWNFILE_HMA.
  ELSEIF IT_WOSUM-NATION = 'B06'.                           "UD1K913472

    IT_DOWNFILE_HAC = IT_DOWNFILE.
    APPEND IT_DOWNFILE_HAC. CLEAR IT_DOWNFILE_HAC.
  ENDIF.
  CLEAR IT_DOWNFILE.
*&* PERFORM R2


*&* PERFORM R3

**
*  READ TABLE IT_AUSP INDEX 1.
*  W_OBJEK = IT_AUSP-OBJEK.
  DATA: L_TABIX LIKE SY-TABIX.

  LOOP AT IT_AUSP.

    L_TABIX = SY-TABIX + 1.

    CASE IT_AUSP-ATNAM.
      WHEN 'P_COLOR_SER'.
        IT_DOWNFILE-RECORD+21(2)   = IT_AUSP-ATWRT.
      WHEN 'P_FLEET'.
        IT_DOWNFILE-RECORD+67(1)   = IT_AUSP-ATWRT.
      WHEN 'P_MANUAL_ORDER'.
        IT_DOWNFILE-RECORD+68(1)   = IT_AUSP-ATWRT.
      WHEN 'P_VIN'.
        IT_DOWNFILE-RECORD+69(18)  = IT_AUSP-ATWRT.
      WHEN 'P_ENGINE_NO'.
        IT_DOWNFILE-RECORD+87(15)  = IT_AUSP-ATWRT.
      WHEN 'P_KEY_NO'.
        IT_DOWNFILE-RECORD+102(6)  = IT_AUSP-ATWRT.
      WHEN 'P_SEQUENCE_DATE'.
        W_N_8 = IT_AUSP-ATFLV.
        IT_DOWNFILE-RECORD+116(8)  = W_N_8.
      WHEN 'P_RP01_ACTUAL_DATE'.
        IT_DOWNFILE-RECORD+124(8)  = IT_AUSP-ATWRT+0(8).
      WHEN 'P_RP02_ACTUAL_DATE'.
        IT_DOWNFILE-RECORD+132(8)  = IT_AUSP-ATWRT+0(8).
*      WHEN 'P_RP07_ACTUAL_DATE'.      "UD1K940247
      WHEN 'P_RP17_ACTUAL_DATE'.                            "UD1K940247
        IT_DOWNFILE-RECORD+140(8)  = IT_AUSP-ATWRT+0(8).
      WHEN 'P_RP18_ACTUAL_DATE'.
        IT_DOWNFILE-RECORD+148(8)  = IT_AUSP-ATWRT+0(8).
      WHEN 'P_RP19_ACTUAL_DATE'.
        IT_DOWNFILE-RECORD+156(8)  = IT_AUSP-ATWRT+0(8).
      WHEN 'P_RP21_ACTUAL_DATE'.
        IT_DOWNFILE-RECORD+162(8)  = IT_AUSP-ATWRT+0(8).
    ENDCASE.


    CLEAR: WA_AUSP.
    READ TABLE IT_AUSP INTO WA_AUSP INDEX L_TABIX.

    IF WA_AUSP-OBJEK <> IT_AUSP-OBJEK.
      IT_DOWNFILE-RECORD+0(3)    = 'O2D'.
      IT_DOWNFILE-RECORD+3(2)    = '20'.
      IT_DOWNFILE-RECORD+5(2)    = IT_WOSUM-WO_SER+1(2).
      IT_DOWNFILE-RECORD+7(2)    = IT_WOSUM-WO_SER+3(2).
      IT_DOWNFILE-RECORD+9(3)    = IT_WOSUM-NATION.
      IT_DOWNFILE-RECORD+12(2)   = IT_WOSUM-DEALER.
      IT_DOWNFILE-RECORD+14(1)   = IT_WOSUM-WO_SER+5(1).
      IF HACPO = 'X' AND IT_WOSUM-NATION = 'B06'.
        IT_DOWNFILE-RECORD+15(8) = L_HACPO.
      ELSE.
        IT_DOWNFILE-RECORD+15(1)   = IT_WOSUM-WO_SER+2(1).
        IT_DOWNFILE-RECORD+16(2)   = IT_WOSUM-WO_SER+3(2).
        IT_DOWNFILE-RECORD+18(3)   = IT_WOSUM-WO_SER+6(3).
        IT_DOWNFILE-RECORD+21(2)   = L_COLOR_SER.
      ENDIF.
      IT_DOWNFILE-RECORD+23(10)  = IT_WOSUM-SALES.
      IT_DOWNFILE-RECORD+33(10)  = IT_WOSUM-WO_SER.
      IT_DOWNFILE-RECORD+43(18)  = IT_WOSUM-FSC.

** Changed by Furong on 11/12/09
      IF  IT_WOSUM-NATION = 'B06'.
        IF L_EXT_COL3 IS INITIAL AND L_INT_COL3 IS INITIAL.
          IT_DOWNFILE-RECORD+61(3)   = IT_WOSUM-EXTC.
          IT_DOWNFILE-RECORD+64(3)   = IT_WOSUM-INTC.
        ELSE.
          IT_DOWNFILE-RECORD+61(3)   = L_EXT_COL3.
          IT_DOWNFILE-RECORD+64(3)   = L_INT_COL3.

        ENDIF.
      ELSE.
        IT_DOWNFILE-RECORD+61(3)   = IT_WOSUM-EXTC.
        IT_DOWNFILE-RECORD+64(3)   = IT_WOSUM-INTC.
      ENDIF.
** End of change

      IT_DOWNFILE-RECORD+108(8)  = IT_WOSUM-WOCREDATE.

      APPEND IT_DOWNFILE.
      IF IT_WOSUM-NATION = 'B28'.
        IT_DOWNFILE_HMA = IT_DOWNFILE.
        APPEND IT_DOWNFILE_HMA. CLEAR IT_DOWNFILE_HMA.
      ELSEIF IT_WOSUM-NATION = 'B06'.
        IT_DOWNFILE_HAC = IT_DOWNFILE.
        APPEND IT_DOWNFILE_HAC. CLEAR IT_DOWNFILE_HAC.
      ENDIF.
      CLEAR IT_DOWNFILE.
*      W_OBJEK = IT_AUSP-OBJEK.
    ENDIF.

  ENDLOOP.
*  IF SY-SUBRC = 0.
*    IT_DOWNFILE-RECORD+0(3)    = 'O2D'.
*    IT_DOWNFILE-RECORD+3(2)    = '20'.
*    IT_DOWNFILE-RECORD+5(2)    = IT_WOSUM-WO_SER+1(2).
*    IT_DOWNFILE-RECORD+7(2)    = IT_WOSUM-WO_SER+3(2).
*    IT_DOWNFILE-RECORD+9(3)    = IT_WOSUM-NATION.
*    IT_DOWNFILE-RECORD+12(2)   = IT_WOSUM-DEALER.
*    IT_DOWNFILE-RECORD+14(1)   = IT_WOSUM-WO_SER+5(1).
*    IT_DOWNFILE-RECORD+15(1)   = IT_WOSUM-WO_SER+2(1).
*    IT_DOWNFILE-RECORD+16(2)   = IT_WOSUM-WO_SER+3(2).
*    IT_DOWNFILE-RECORD+18(3)   = IT_WOSUM-WO_SER+6(3).
*
*    IT_DOWNFILE-RECORD+21(2)   = '01'. "COLOR_SER
*    IT_DOWNFILE-RECORD+23(10)  = IT_WOSUM-SALES.
*    IT_DOWNFILE-RECORD+33(10)  = IT_WOSUM-WO_SER.
*    IT_DOWNFILE-RECORD+43(18)  = IT_WOSUM-FSC.
**    IT_DOWNFILE-RECORD+62(3)   = IT_WOSUM-EXTC.
*    IT_DOWNFILE-RECORD+61(3)   = IT_WOSUM-EXTC.
**    IT_DOWNFILE-RECORD+65(3)   = IT_WOSUM-INTC.
*    IT_DOWNFILE-RECORD+64(3)   = IT_WOSUM-INTC.
*
**    IT_DOWNFILE-RECORD+109(8)  = IT_WOSUM-WOCREDATE.
*    IT_DOWNFILE-RECORD+108(8)  = IT_WOSUM-WOCREDATE.
*
*    APPEND IT_DOWNFILE.
*    IF IT_WOSUM-NATION = 'B28'.
*      IT_DOWNFILE_HMA = IT_DOWNFILE.
*      APPEND IT_DOWNFILE_HMA. CLEAR IT_DOWNFILE_HMA.
*
*    ELSEIF IT_WOSUM-NATION = 'B06'.
*      IT_DOWNFILE_HAC = IT_DOWNFILE.
*      APPEND IT_DOWNFILE_HAC. CLEAR IT_DOWNFILE_HAC.
*    ENDIF.
*    CLEAR IT_DOWNFILE.
*    W_OBJEK = IT_AUSP-OBJEK.
*  ENDIF.
*&* PERFORM R3
ENDFUNCTION.
