FUNCTION Z_ORDER_PALL.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(IT_WOSUM) LIKE  ZTPP_WOSUM STRUCTURE  ZTPP_WOSUM
*"  TABLES
*"      S_ATINN STRUCTURE  ZX300
*"      IT_DOWNFILE STRUCTURE  ZX200
*"      IT_DOWNFILE_HMA STRUCTURE  ZX200
*"      IT_DOWNFILE_HAC STRUCTURE  ZX200
*"----------------------------------------------------------------------
DATA : W_CNT TYPE I,
       W_N_9(9) TYPE N,
       W_N_8(8) TYPE N.

DATA : BEGIN OF IT_AUSP OCCURS 0,
       OBJEK LIKE AUSP-OBJEK,
       ATINN LIKE AUSP-ATINN,
       ATNAM LIKE CABN-ATNAM,
       ATWRT LIKE AUSP-ATWRT,
       ATFLV LIKE AUSP-ATFLV,
       END OF IT_AUSP.

DATA : BEGIN OF IT_AUSP_L OCCURS 0,
       OBJEK LIKE AUSP-OBJEK,
       ATINN LIKE AUSP-ATINN,
       ATNAM LIKE CABN-ATNAM,
       ATWRT LIKE AUSP-ATWRT,
       ATFLV LIKE AUSP-ATFLV,
       END OF IT_AUSP_L.

DATA : BEGIN OF IT_CABN OCCURS 0,
       ATINN LIKE CABN-ATINN,
       ATNAM LIKE CABN-ATNAM,
       END OF IT_CABN.

  IT_DOWNFILE-RECORD+0(3)    = 'O1D'.
  IT_DOWNFILE-RECORD+3(10)   = IT_WOSUM-WO_SER.
  IT_DOWNFILE-RECORD+13(3)   = IT_WOSUM-EXTC.
  IT_DOWNFILE-RECORD+16(3)   = IT_WOSUM-INTC.
  IT_DOWNFILE-RECORD+19(9)   = IT_WOSUM-MODQTY.
  IT_DOWNFILE-RECORD+28(9)   = IT_WOSUM-SEQQTY.
  IT_DOWNFILE-RECORD+37(9)   = IT_WOSUM-RP01TQ.
  IT_DOWNFILE-RECORD+46(9)   = IT_WOSUM-RP02TQ.
  IT_DOWNFILE-RECORD+55(9)   = IT_WOSUM-RP06TQ.
  IT_DOWNFILE-RECORD+64(9)   = IT_WOSUM-RP08TQ.
  IT_DOWNFILE-RECORD+73(9)   = IT_WOSUM-RP09TQ.
  IT_DOWNFILE-RECORD+82(9)   = IT_WOSUM-RP10TQ.
  IT_DOWNFILE-RECORD+91(9)   = IT_WOSUM-RP11TQ.
  IT_DOWNFILE-RECORD+100(9)  = IT_WOSUM-RP15TQ.

  APPEND IT_DOWNFILE.
  IF IT_WOSUM-NATION = 'B28'.
    IT_DOWNFILE_HMA = IT_DOWNFILE.
    APPEND IT_DOWNFILE_HMA. CLEAR IT_DOWNFILE_HMA.
  ELSEIF IT_WOSUM-NATION = 'B06'.
    IT_DOWNFILE_HAC = IT_DOWNFILE.
    APPEND IT_DOWNFILE_HAC. CLEAR IT_DOWNFILE_HAC.
  ENDIF.
  CLEAR IT_DOWNFILE.


  W_N_9 = W_N_9 + 1.



*ERFORM R3.

  DATA : W_OBJEK LIKE AUSP-OBJEK.

* PERFORM MAKE_VM.


  DATA : SO LIKE BAPI_SELECTED_OBJECTS OCCURS 0 WITH HEADER LINE,
         SC LIKE BAPI_SELECTION_CRITERIONS OCCURS 0 WITH HEADER LINE.

  DATA : W_WORKORDER(14).

  REFRESH : SC, SO. CLEAR : SC, SO.

  CONCATENATE IT_WOSUM-WO_SER IT_WOSUM-NATION IT_WOSUM-DEALER
              INTO W_WORKORDER.

  SC-NAME_CHAR  = 'P_WORK_ORDER'.
  SC-CHAR_VALUE = W_WORKORDER.
  APPEND SC.

  SC-NAME_CHAR  = 'P_EXT_COLOR'.
  SC-CHAR_VALUE = IT_WOSUM-EXTC.
  APPEND SC.

  SC-NAME_CHAR  = 'P_INT_COLOR'.
  SC-CHAR_VALUE = IT_WOSUM-INTC.
  APPEND SC.

  SC-NAME_CHAR  = 'P_SALES_ORDER'.
  SC-CHAR_VALUE = IT_WOSUM-SALES.
  APPEND SC.

**  SC-NAME_CHAR  = 'P_FSC'.
**  SC-CHAR_VALUE = IT_WOSUM-FSC.
**  APPEND SC.

  CALL FUNCTION 'BAPI_CLASS_SELECT_OBJECTS'
    EXPORTING
      CLASSTYPE                  = '002'
      CLASSNUM                   = 'P_VEHICLE_MASTER'
*     LANGUISO                   =
*     LANGUINT                   =
      KEYDATE                    = SY-DATUM
*     MAXHITS                    = 100
*     I_STATUS_LOCKED            = ' '
*     I_STATUS_INCOMPLETE        = ' '
*   IMPORTING
*     RETURN                     =
    TABLES
      SELECTIONCRITERIONS        = SC
      SELECTEDOBJECTS            = SO
*     OBJECTCLASSIFICATION       =
              .

  REFRESH : IT_AUSP.
  CLEAR   : IT_AUSP.
  LOOP AT SO.

    SELECT * INTO CORRESPONDING FIELDS OF TABLE IT_AUSP_L
           FROM AUSP
          WHERE ATINN IN S_ATINN
          AND   OBJEK EQ SO-OBJECT.
    LOOP AT IT_AUSP_L.
      IT_AUSP-OBJEK = IT_AUSP_L-OBJEK.
      IT_AUSP-ATINN = IT_AUSP_L-ATINN.
      IT_AUSP-ATWRT = IT_AUSP_L-ATWRT.
      IT_AUSP-ATFLV = IT_AUSP_L-ATFLV.
      READ TABLE IT_CABN WITH KEY ATINN = IT_AUSP-ATINN.
      IT_AUSP-ATNAM = IT_CABN-ATNAM.
      APPEND IT_AUSP. CLEAR IT_AUSP.
    ENDLOOP.
    CLEAR IT_AUSP_L.
  ENDLOOP.



  READ TABLE IT_AUSP INDEX 1.
  W_OBJEK = IT_AUSP-OBJEK.

  LOOP AT IT_AUSP.
  IF W_OBJEK <> IT_AUSP-OBJEK.
    IT_DOWNFILE-RECORD+0(3)    = 'O2D'.
    IT_DOWNFILE-RECORD+3(3)    = IT_WOSUM-NATION.
    IT_DOWNFILE-RECORD+6(2)    = ''. "IT_WOSUM-DEALER.

**    IT_DOWNFILE-RECORD+8(5)    = IT_WOSUM-DEALER.
    IT_DOWNFILE-RECORD+08(4)   = IT_WOSUM-WO_SER+1(2).
    IT_DOWNFILE-RECORD+12(2)   = IT_WOSUM-WO_SER+3(2).
    IT_DOWNFILE-RECORD+14(1)   = IT_WOSUM-WO_SER+5(1).

    IT_DOWNFILE-RECORD+15(01)  = IT_WOSUM-WO_SER+2(1).
    IT_DOWNFILE-RECORD+16(02)  = IT_WOSUM-WO_SER+3(2).
    IT_DOWNFILE-RECORD+18(03)  = IT_WOSUM-WO_SER+6(3).

    IT_DOWNFILE-RECORD+23(10)  = IT_WOSUM-SALES.
    IT_DOWNFILE-RECORD+33(10)  = IT_WOSUM-WO_SER.
    IT_DOWNFILE-RECORD+43(18)  = IT_WOSUM-FSC.
    IT_DOWNFILE-RECORD+61(3)   = IT_WOSUM-EXTC.
    IT_DOWNFILE-RECORD+64(3)   = IT_WOSUM-INTC.

    IT_DOWNFILE-RECORD+67(1)   = ''.
    IT_DOWNFILE-RECORD+68(1)   = ''.

    IT_DOWNFILE-RECORD+103(8)  = IT_WOSUM-WOCREDATE.

    APPEND IT_DOWNFILE.
    IF IT_WOSUM-NATION = 'B28'.
      IT_DOWNFILE_HMA = IT_DOWNFILE.
      APPEND IT_DOWNFILE_HMA. CLEAR IT_DOWNFILE_HMA.
    ELSEIF IT_WOSUM-NATION = 'B06'.
      IT_DOWNFILE_HAC = IT_DOWNFILE.
      APPEND IT_DOWNFILE_HAC. CLEAR IT_DOWNFILE_HAC.
    ENDIF.
    CLEAR IT_DOWNFILE.
    W_OBJEK = IT_AUSP-OBJEK.
    W_N_9 = W_N_9 + 1.
  ENDIF.

  CASE IT_AUSP-ATNAM.
**  WHEN 'P_ORDER_ZONE'.
**    IT_DOWNFILE-RECORD+20(4)   = IT_AUSP-ATWRT.
**  WHEN 'P_REGION_PORT'.
**    IT_DOWNFILE-RECORD+24(2)   = IT_AUSP-ATWRT+0(2).
**    IT_DOWNFILE-RECORD+26(2)   = IT_AUSP-ATWRT+2(2).
  WHEN 'P_COLOR_SER'.
    IT_DOWNFILE-RECORD+21(02)  = IT_AUSP-ATWRT.
**  WHEN 'P_FLEET'.
**    IT_DOWNFILE-RECORD+64(1)   = IT_AUSP-ATWRT.
**  WHEN 'P_MANUAL_ORDER'.
**    IT_DOWNFILE-RECORD+65(1)   = IT_AUSP-ATWRT.
  WHEN 'P_VIN'.
    IT_DOWNFILE-RECORD+69(17)  = IT_AUSP-ATWRT.
**  engine.. key.. sequenced date..??
  WHEN 'P_SEQUENCE_DATE'.
    W_N_8 = IT_AUSP-ATFLV.
    IT_DOWNFILE-RECORD+119(8)  = W_N_8.
  WHEN 'P_RP01_ACTUAL_DATE'.
    W_N_8 = IT_AUSP-ATFLV.
    IT_DOWNFILE-RECORD+127(8)  = W_N_8.
  WHEN 'P_RP02_ACTUAL_DATE'.
    W_N_8 = IT_AUSP-ATFLV.
    IT_DOWNFILE-RECORD+135(8)  = W_N_8.
  WHEN 'P_RP07_ACTUAL_DATE'.
    W_N_8 = IT_AUSP-ATFLV.
    IT_DOWNFILE-RECORD+143(8)  = W_N_8.
  WHEN 'P_RP18_ACTUAL_DATE'.
    W_N_8 = IT_AUSP-ATFLV.
    IT_DOWNFILE-RECORD+151(8)  = W_N_8.
  WHEN 'P_RP19_ACTUAL_DATE'.
    W_N_8 = IT_AUSP-ATFLV.
    IT_DOWNFILE-RECORD+159(8)  = W_N_8.
  WHEN 'P_RP21_ACTUAL_DATE'.
    W_N_8 = IT_AUSP-ATFLV.
    IT_DOWNFILE-RECORD+167(8)  = W_N_8.
  ENDCASE.

  ENDLOOP.
  IF SY-SUBRC = 0.
    IT_DOWNFILE-RECORD+0(3)    = 'O2D'.
    IT_DOWNFILE-RECORD+3(3)    = IT_WOSUM-NATION.
    IT_DOWNFILE-RECORD+6(2)    = ''. "IT_WOSUM-DEALER.

**    IT_DOWNFILE-RECORD+8(5)    = IT_WOSUM-DEALER.
    IT_DOWNFILE-RECORD+08(4)   = IT_WOSUM-WO_SER+1(2).
    IT_DOWNFILE-RECORD+12(2)   = IT_WOSUM-WO_SER+3(2).
    IT_DOWNFILE-RECORD+14(1)   = IT_WOSUM-WO_SER+5(1).

    IT_DOWNFILE-RECORD+15(01)  = IT_WOSUM-WO_SER+2(1).
    IT_DOWNFILE-RECORD+16(02)  = IT_WOSUM-WO_SER+3(2).
    IT_DOWNFILE-RECORD+18(03)  = IT_WOSUM-WO_SER+6(3).

    IT_DOWNFILE-RECORD+23(10)  = IT_WOSUM-SALES.
    IT_DOWNFILE-RECORD+33(10)  = IT_WOSUM-WO_SER.
    IT_DOWNFILE-RECORD+43(18)  = IT_WOSUM-FSC.
    IT_DOWNFILE-RECORD+61(3)   = IT_WOSUM-EXTC.
    IT_DOWNFILE-RECORD+64(3)   = IT_WOSUM-INTC.

    IT_DOWNFILE-RECORD+67(1)   = ''.
    IT_DOWNFILE-RECORD+68(1)   = ''.

    IT_DOWNFILE-RECORD+103(8)  = IT_WOSUM-WOCREDATE.

    APPEND IT_DOWNFILE.
    IF IT_WOSUM-NATION = 'B28'.
      IT_DOWNFILE_HMA = IT_DOWNFILE.
      APPEND IT_DOWNFILE_HMA. CLEAR IT_DOWNFILE_HMA.
    ELSEIF IT_WOSUM-NATION = 'B06'.
      IT_DOWNFILE_HAC = IT_DOWNFILE.
      APPEND IT_DOWNFILE_HAC. CLEAR IT_DOWNFILE_HAC.
    ENDIF.
    CLEAR IT_DOWNFILE.
    W_OBJEK = IT_AUSP-OBJEK.
    W_N_9 = W_N_9 + 1.
  ENDIF.

ENDFUNCTION.
