REPORT ZRPM_UPL_TBL_ZTPM_MTTR_MTBF .
TABLES: ZTPM_MTBT,
        ZTPM_MTTR_MTBF_U,
        ZTPM_MTTR_MTBF.

DATA : IT_ZTPM_MTBT LIKE ZTPM_MTBT OCCURS 0 WITH HEADER LINE,
       IT_ZTPM_MTTR_MTBF LIKE ZTPM_MTTR_MTBF OCCURS 0 WITH HEADER LINE,
*       IT_ZTPM_MTTR_MTBF1 LIKE ZTPM_MTTR_MTBF OCCURS 0 WITH HEADER LINE
       IT_ZTPM_MTTR_MTBF2 LIKE ZTPM_MTTR_MTBF OCCURS 0 WITH HEADER LINE.
DATA: ZMTTR_AVRATE LIKE ZTPM_MTTR_MTBF-ZMTTR_AVRATE ,
      ZMTBF_AVRATE LIKE ZTPM_MTTR_MTBF-ZMTBF_AVRATE.

DATA: WA_SHOP LIKE  IT_ZTPM_MTTR_MTBF-SHOP ,
wa_ajahr LIKE  IT_ZTPM_MTTR_MTBF-AJAHR ,
wa_zmonth LIKE IT_ZTPM_MTTR_MTBF-ZMONTH .

DATA: BEGIN OF IT_ZTPM_MTTR_MTBF1  OCCURS 0,
      MANDT LIKE ZTPM_MTTR_MTBF-MANDT,
      SHOP  LIKE ZTPM_MTTR_MTBF-SHOP,
      AJAHR LIKE ZTPM_MTTR_MTBF-AJAHR,
      ZMONTH LIKE ZTPM_MTTR_MTBF-ZMONTH,
      ZMTTR_AVRATE LIKE ZTPM_MTTR_MTBF-ZMTTR_AVRATE,
     ZMTBF_AVRATE LIKE  ZTPM_MTTR_MTBF-ZMTBF_AVRATE,
     END OF IT_ZTPM_MTTR_MTBF1 .

  SELECT *
       INTO CORRESPONDING FIELDS OF  TABLE IT_ZTPM_MTBT
       FROM ZTPM_MTBT.

       LOOP AT IT_ZTPM_MTBT.
       MOVE IT_ZTPM_MTBT-MANDT TO IT_ZTPM_MTTR_MTBF-MANDT.
       MOVE IT_ZTPM_MTBT-SHOP TO IT_ZTPM_MTTR_MTBF-SHOP.
MOVE IT_ZTPM_MTBT-AJAHR TO IT_ZTPM_MTTR_MTBF-AJAHR.
MOVE IT_ZTPM_MTBT-ZMONTH TO IT_ZTPM_MTTR_MTBF-ZMONTH.
IF IT_ZTPM_MTBT-ZMTBT = 'MTTR'.
MOVE 'MTTR' TO IT_ZTPM_MTTR_MTBF-ZMTTR.
MOVE IT_ZTPM_MTBT-AVRATE TO IT_ZTPM_MTTR_MTBF-ZMTTR_AVRATE.
ENDIF.
IF IT_ZTPM_MTBT-ZMTBT = 'MTBF'.
MOVE 'MTBF' TO IT_ZTPM_MTTR_MTBF-ZMTBF.
MOVE IT_ZTPM_MTBT-AVRATE TO IT_ZTPM_MTTR_MTBF-ZMTBF_AVRATE.
ENDIF.
APPEND IT_ZTPM_MTTR_MTBF.
CLEAR IT_ZTPM_MTTR_MTBF.
ENDLOOP.

LOOP AT IT_ZTPM_MTTR_MTBF.
MOVE IT_ZTPM_MTTR_MTBF-MANDT TO IT_ZTPM_MTTR_MTBF1-MANDT.
       MOVE IT_ZTPM_MTTR_MTBF-SHOP TO IT_ZTPM_MTTR_MTBF1-SHOP.
MOVE IT_ZTPM_MTTR_MTBF-AJAHR TO IT_ZTPM_MTTR_MTBF1-AJAHR.
MOVE IT_ZTPM_MTTR_MTBF-ZMONTH TO IT_ZTPM_MTTR_MTBF1-ZMONTH.
MOVE IT_ZTPM_MTTR_MTBF-ZMTTR_AVRATE TO IT_ZTPM_MTTR_MTBF1-ZMTTR_AVRATE.
MOVE IT_ZTPM_MTTR_MTBF-ZMTBF_AVRATE TO IT_ZTPM_MTTR_MTBF1-ZMTBF_AVRATE.

APPEND IT_ZTPM_MTTR_MTBF1.
CLEAR IT_ZTPM_MTTR_MTBF1.
ENDLOOP.


CLEAR: ZMTTR_AVRATE,ZMTBF_AVRATE.
LOOP AT IT_ZTPM_MTTR_MTBF1.
ZMTTR_AVRATE = IT_ZTPM_MTTR_MTBF1-ZMTTR_AVRATE + ZMTTR_AVRATE.
ZMTBF_AVRATE = IT_ZTPM_MTTR_MTBF1-ZMTBF_AVRATE + ZMTBF_AVRATE.

if IT_ZTPM_MTTR_MTBF1-SHOP = wa_shop and
IT_ZTPM_MTTR_MTBF1-AJAHR = wa_ajahr and
IT_ZTPM_MTTR_MTBF1-ZMONTH = wa_zmonth .

*ZMTTR_AVRATE = IT_ZTPM_MTTR_MTBF1-ZMTTR_AVRATE + ZMTTR_AVRATE.
*ZMTBF_AVRATE = IT_ZTPM_MTTR_MTBF1-ZMTBF_AVRATE + ZMTBF_AVRATE.

MOVE ZMTTR_AVRATE TO IT_ZTPM_MTTR_MTBF1-ZMTTR_AVRATE.
MOVE ZMTBF_AVRATE TO IT_ZTPM_MTTR_MTBF1-ZMTBF_AVRATE.
CLEAR: ZMTTR_AVRATE,ZMTBF_AVRATE.
endif.

IF SY-TABIX = 1.
*ZMTTR_AVRATE = IT_ZTPM_MTTR_MTBF1-ZMTTR_AVRATE + ZMTTR_AVRATE.
*ZMTBF_AVRATE = IT_ZTPM_MTTR_MTBF1-ZMTBF_AVRATE + ZMTBF_AVRATE.

MOVE ZMTTR_AVRATE TO IT_ZTPM_MTTR_MTBF1-ZMTTR_AVRATE.
MOVE ZMTBF_AVRATE TO IT_ZTPM_MTTR_MTBF1-ZMTBF_AVRATE.
ENDIF.
move IT_ZTPM_MTTR_MTBF1-SHOP to wa_shop.
move IT_ZTPM_MTTR_MTBF1-AJAHR to wa_ajahr.
move IT_ZTPM_MTTR_MTBF1-ZMONTH to wa_zmonth.

MODIFY IT_ZTPM_MTTR_MTBF1.
CLEAR IT_ZTPM_MTTR_MTBF1.
ENDLOOP.


LOOP AT IT_ZTPM_MTTR_MTBF1.

DELETE  IT_ZTPM_MTTR_MTBF1 WHERE ZMTTR_AVRATE = 0 OR
                                      ZMTBF_AVRATE = 0.
ENDLOOP.

MODIFY ZTPM_MTTR_MTBF_U FROM TABLE IT_ZTPM_MTTR_MTBF1.
