FUNCTION ZH_HR_GET_BRANCH_EMP_COUNT.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(IV_YEAR) TYPE  NUMC04
*"     VALUE(IV_MONTH) TYPE  MONTH
*"     VALUE(IV_DAY) TYPE  REXCITDATPRIDAY
*"     VALUE(IV_ZCBRACD) TYPE  NUMC08
*"     VALUE(IV_ZMBRACD) TYPE  CHAR80
*"     VALUE(IV_BUKRS) TYPE  BUKRS
*"  TABLES
*"      T_SHEET STRUCTURE  ZGHRSS0016 OPTIONAL
*"----------------------------------------------------------------------

  DATA:
        L_DATUM       TYPE DATUM,
        L_FROM        TYPE DATUM,
        LT_PA0000     TYPE TABLE OF PA0000 WITH HEADER LINE,
        LT_TEMP        TYPE TABLE OF PA0000 WITH HEADER LINE,
        LT_PA0001     TYPE TABLE OF PA0001 WITH HEADER LINE,
        LT_PA0002     TYPE TABLE OF PA0002 WITH HEADER LINE,
        LT_PA9883     TYPE TABLE OF PA9883 WITH HEADER LINE,
        LT_T529A        TYPE TABLE OF T529A WITH HEADER LINE.

  CONCATENATE IV_YEAR IV_MONTH IV_DAY INTO L_DATUM.
  CONCATENATE IV_YEAR IV_MONTH '01' INTO L_FROM.
* get incumbents

  SELECT M~PERNR M~BEGDA M~ENDDA M~MASSN
    FROM PA0000 AS M
    INTO CORRESPONDING FIELDS OF TABLE LT_TEMP
    WHERE PERNR IN ( SELECT PERNR FROM PA0001 WHERE  BUKRS = IV_BUKRS )
          AND BEGDA BETWEEN L_FROM AND L_DATUM.

  SORT LT_TEMP BY PERNR ENDDA DESCENDING.
  DELETE ADJACENT DUPLICATES FROM LT_TEMP COMPARING PERNR.

  SELECT M~PERNR M~BEGDA M~ENDDA M~MASSN FROM PA0000 AS M
   INTO CORRESPONDING FIELDS OF TABLE LT_PA0000
    WHERE PERNR IN ( SELECT PERNR FROM PA0001 WHERE  BUKRS = IV_BUKRS )
      AND STAT2 <> 0
      AND M~BEGDA <=  L_DATUM
      AND M~ENDDA => L_DATUM.


  SORT LT_PA0000 BY PERNR ENDDA DESCENDING.
  DELETE ADJACENT DUPLICATES FROM LT_PA0000 COMPARING PERNR.

* get bukrs
  SELECT * FROM PA0001
    INTO TABLE LT_PA0001
    WHERE BEGDA <= L_DATUM
      AND ENDDA >= L_DATUM.

  SORT LT_PA0001 BY PERNR.

* get gender ( GESCH ).
  SELECT * FROM PA0002
    INTO TABLE LT_PA0002
    WHERE BEGDA <= L_DATUM
      AND ENDDA >= L_DATUM.

  SORT LT_PA0002 BY PERNR.

  SELECT * FROM PA9883
    INTO TABLE LT_PA9883
    WHERE BEGDA <= L_DATUM
      AND ENDDA >= L_DATUM.

  SORT LT_PA9883 BY PERNR.

  SELECT * FROM T529A
    INTO TABLE LT_T529A.

  SORT LT_T529A BY MASSN.

  LOOP AT LT_PA0000.

    READ TABLE  LT_PA0002 WITH KEY PERNR = LT_PA0000-PERNR BINARY SEARCH.
    READ TABLE  LT_PA9883 WITH KEY PERNR = LT_PA0000-PERNR BINARY SEARCH.
    IF SY-SUBRC EQ 0.
      T_SHEET-ZCGSJBGRP   = LT_PA9883-ZZCGSJBGRP.
      T_SHEET-ZCGSJIKUN     = LT_PA9883-ZZCGSJIKUN.
      T_SHEET-ZCGSJIKUB     = LT_PA9883-ZZCGSJIKUB.
    ENDIF.

    IF T_SHEET-ZCGSJBGRP IS INITIAL.

      LOOP AT LT_PA0001 WHERE PERNR = LT_PA0000-PERNR
                                            AND BEGDA <= LT_PA0000-ENDDA
                                            AND ENDDA => LT_PA0000-BEGDA.

        IF LT_PA0001-PERSG EQ '9'.
          T_SHEET-ZCGSJBGRP = 'E'.
        ELSE.
          T_SHEET-ZCGSJBGRP = '1'.
        ENDIF.

      ENDLOOP.

    ENDIF.

    T_SHEET-ZDYEAR          = IV_YEAR.
    T_SHEET-ZMONTH          = IV_MONTH.
    T_SHEET-ZCBRACD       = IV_ZCBRACD.

    T_SHEET-BUKRS           = IV_BUKRS.
    T_SHEET-ZMBRACD       = IV_ZMBRACD.

    CASE LT_PA0002-GESCH.
      WHEN 1.
        T_SHEET-ZQHCMAL = 1.
      WHEN 2.
        T_SHEET-ZQHCFEM = 1.
    ENDCASE.

    T_SHEET-ZQHCTOT = 1.
    COLLECT T_SHEET.
    CLEAR: LT_PA0000, LT_PA0002, LT_PA9883,T_SHEET,LT_T529A,T_SHEET.
  ENDLOOP.


*&   RETIRE/HIRE     count &*
  LOOP AT LT_TEMP.

    READ TABLE  LT_PA9883 WITH KEY PERNR = LT_TEMP-PERNR BINARY SEARCH.
    IF SY-SUBRC EQ 0.
      T_SHEET-ZCGSJBGRP   = LT_PA9883-ZZCGSJBGRP.
      T_SHEET-ZCGSJIKUN     = LT_PA9883-ZZCGSJIKUN.
      T_SHEET-ZCGSJIKUB     = LT_PA9883-ZZCGSJIKUB.
    ENDIF.

    IF T_SHEET-ZCGSJBGRP IS INITIAL.

      LOOP AT LT_PA0001 WHERE PERNR = LT_TEMP-PERNR
                                            AND BEGDA <= LT_TEMP-ENDDA
                                            AND ENDDA => LT_TEMP-BEGDA.

        IF LT_PA0001-PERSG EQ '9'.
          T_SHEET-ZCGSJBGRP = 'E'.
        ELSE.
          T_SHEET-ZCGSJBGRP = '1'.
        ENDIF.

      ENDLOOP.

    ENDIF.

    T_SHEET-ZDYEAR          = IV_YEAR.
    T_SHEET-ZMONTH          = IV_MONTH.
    T_SHEET-ZCBRACD       = IV_ZCBRACD.
    T_SHEET-BUKRS           = IV_BUKRS.
    T_SHEET-ZMBRACD       = IV_ZMBRACD.


    READ TABLE LT_T529A WITH KEY MASSN = LT_TEMP-MASSN BINARY SEARCH.

    IF LT_T529A-FUNCH EQ '1' AND SY-SUBRC EQ 0. "HIRE
      T_SHEET-ZQREC = 1.
    ELSEIF LT_T529A-STAT2 EQ '0' AND SY-SUBRC EQ 0. " RETIRE
      T_SHEET-ZQRET = 1.
    ELSE.
      T_SHEET-ZQOAC = 1.
    ENDIF.

    COLLECT T_SHEET.

    CLEAR: LT_PA9883, LT_TEMP, LT_PA9883,LT_T529A,T_SHEET.
  ENDLOOP.

ENDFUNCTION.
