FUNCTION ZH_HR_IF_PA_MASTER_2ND.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(IV_BRACD) TYPE  HROBJID
*"     VALUE(IV_BUKRS) TYPE  BUKRS
*"     VALUE(IV_BEGDA) TYPE  BEGDA
*"     VALUE(IV_ENDDA) TYPE  ENDDA
*"  TABLES
*"      ET_PA0000 STRUCTURE  ZGHRS0000 OPTIONAL
*"      ET_PA0302 STRUCTURE  ZGHRS0302 OPTIONAL
*"      ET_PA0001 STRUCTURE  ZGHRS0001 OPTIONAL
*"      ET_PA0001ENH STRUCTURE  ZGHRS0001ENH OPTIONAL
*"      ET_PA0002 STRUCTURE  ZGHRS0002 OPTIONAL
*"      ET_PA0008 STRUCTURE  ZGHRS0008 OPTIONAL
*"      ET_PA0022 STRUCTURE  ZGHRS0022 OPTIONAL
*"      ET_PA0022ENH STRUCTURE  ZGHRS0022ENH OPTIONAL
*"      ET_99001 STRUCTURE  ZGHRSS0007 OPTIONAL
*"      ET_99002 STRUCTURE  ZGHRSS0011 OPTIONAL
*"      ET_99003 STRUCTURE  ZGHRSS0012 OPTIONAL
*"      ET_PA9882 STRUCTURE  ZGHRS9882 OPTIONAL
*"      ET_PA9880 STRUCTURE  ZGHRS9880 OPTIONAL
*"      ET_PA9881 STRUCTURE  ZGHRS9881 OPTIONAL
*"----------------------------------------------------------------------

  DATA: LT_PA0023       TYPE TABLE OF PA0023 WITH HEADER LINE.
  DATA: LT_T513C        TYPE TABLE OF T513C WITH HEADER LINE.
  DATA: LT_99001        LIKE TABLE OF ET_99001,
            LS_99001        LIKE ET_99001.
*  DATA: lt_pa0105           TYPE TABLE OF pa0105 WITH HEADER LINE.
*  DATA: lt_pa0105_t        TYPE TABLE OF pa0105 WITH HEADER LINE.
  DATA: LT_PA9883           TYPE TABLE OF PA9883 WITH HEADER LINE.
  DATA: LT_PA9883_T        TYPE TABLE OF PA9883 WITH HEADER LINE.
  DATA:
            L_CHK.

  DATA :  LT_KEY        TYPE TABLE OF  BAPIPAKEY WITH HEADER LINE,
          LS_RETURN     LIKE BAPIRETURN1,
          LT_WAGETYPES  TYPE TABLE OF BAPIP0008P WITH HEADER LINE,
          L_ANNUAL      TYPE BAPIP0008-ANSAL,
          L_BASIC       TYPE BAPIP0008-ANSAL.

  CLEAR: ET_PA0000[], ET_PA0302[], ET_PA0001[], ET_PA0001ENH[], ET_PA0002[], ET_PA0022[], ET_PA0022ENH[].
  CLEAR: ET_99001[], ET_99002[], ET_PA9880[], ET_PA9881[].



*&   Accept only gets more managerial   &*

  SELECT DISTINCT PERNR BEGDA ENDDA ZZCGSJBGRP ZZCGSJIKUN
                  ZZCGSJIKUB ZZCGSAGREE AEDTM
    FROM PA9883
    INTO CORRESPONDING FIELDS OF TABLE LT_PA9883
    WHERE PERNR IN ( SELECT DISTINCT PERNR FROM PA0001 WHERE BUKRS = IV_BUKRS )
      AND BEGDA <= IV_ENDDA
      AND ENDDA >= IV_BEGDA
      AND ZZCGSAGREE EQ 'X'.

  IF SY-SUBRC NE 0.
    RETURN.
  ENDIF.

*&  Read and accept new employee  &*

  SELECT * FROM PA9883
    INTO TABLE LT_PA9883_T
    FOR ALL ENTRIES IN LT_PA9883
    WHERE PERNR = LT_PA9883-PERNR
          AND ZZCGSAGREE EQ ' '
          AND ENDDA <= LT_PA9883-BEGDA.

  SORT LT_PA9883_T BY PERNR ENDDA DESCENDING.
  DELETE ADJACENT DUPLICATES FROM LT_PA9883_T COMPARING PERNR.

**********Infotype 0000/0302**********
*&   Accept only gets more managerial   &*

  SELECT *
    INTO CORRESPONDING FIELDS OF TABLE ET_PA0000
    FROM PA0000
    FOR ALL ENTRIES IN LT_PA9883
    WHERE PERNR = LT_PA9883-PERNR
          AND AEDTM BETWEEN IV_BEGDA AND IV_ENDDA.

*&   Accept only gets more managerial   &*
  IF  LT_PA9883_T[] IS NOT INITIAL.
    SELECT *
      APPENDING  CORRESPONDING FIELDS OF TABLE ET_PA0000
      FROM PA0000
      FOR ALL ENTRIES IN LT_PA9883_T
      WHERE PERNR = LT_PA9883_T-PERNR
            AND ENDDA <= LT_PA9883_T-ENDDA.
  ENDIF.

  IF ET_PA0000[] IS NOT INITIAL.
    PERFORM FILL_BRACD_CODE USING IV_BRACD 3 CHANGING ET_PA0000[].
  ENDIF.

*&   Accept only gets more managerial   &*
  SELECT *
    INTO CORRESPONDING FIELDS OF TABLE ET_PA0302
    FROM PA0302
    FOR ALL ENTRIES IN LT_PA9883
    WHERE PERNR = LT_PA9883-PERNR
          AND AEDTM BETWEEN IV_BEGDA AND IV_ENDDA.

*&   Accept only gets more managerial   &*
  IF  LT_PA9883_T[] IS NOT INITIAL.
    SELECT *
      APPENDING CORRESPONDING FIELDS OF TABLE ET_PA0302
      FROM PA0302
      FOR ALL ENTRIES IN LT_PA9883_T
      WHERE PERNR = LT_PA9883_T-PERNR
            AND ENDDA <= LT_PA9883_T-ENDDA.
  ENDIF.

  IF ET_PA0302[] IS NOT INITIAL.
    PERFORM FILL_BRACD_CODE USING IV_BRACD 3 CHANGING ET_PA0302[].
  ENDIF.
**********Infotype 0001**********
  CLEAR: GT_PA0001[].

*&   Accept only gets more managerial   &*
  SELECT *
    INTO CORRESPONDING FIELDS OF TABLE GT_PA0001
    FROM PA0001
    FOR ALL ENTRIES IN LT_PA9883
    WHERE PERNR = LT_PA9883-PERNR
          AND AEDTM BETWEEN IV_BEGDA AND IV_ENDDA.

*&   Accept only gets more managerial   &*
  IF  LT_PA9883_T[] IS NOT INITIAL.
    SELECT *
      APPENDING CORRESPONDING FIELDS OF TABLE GT_PA0001
      FROM PA0001
      FOR ALL ENTRIES IN LT_PA9883_T
      WHERE PERNR = LT_PA9883_T-PERNR
            AND ENDDA <= LT_PA9883_T-ENDDA.
  ENDIF.

**&   ## ## ##.     &*
*  SELECT * FROM pa0105
*    INTO TABLE lt_pa0105
*    FOR ALL ENTRIES IN lt_pa9883
*    WHERE pernr = lt_pa9883-pernr
*          AND pernr IN ( SELECT DISTINCT pernr
*                                FROM pa0105
*                                WHERE subty = '9002' AND aedtm BETWEEN iv_begda AND iv_endda )
*          AND subty = '9002'.
*
*  IF  lt_pa9883_t[] IS NOT INITIAL.
*    SELECT *
*      INTO TABLE lt_pa0105_t
*      FROM pa0105
*      FOR ALL ENTRIES IN lt_pa9883_t
*      WHERE pernr = lt_pa9883_t-pernr
*            AND subty = '9002'.
*
*  ENDIF.

  IF GT_PA0001[] IS NOT INITIAL.
    LOOP AT GT_PA0001.
      MOVE-CORRESPONDING GT_PA0001 TO ET_PA0001.
      MOVE-CORRESPONDING GT_PA0001 TO ET_PA0001ENH.

* Local work area
      ET_PA0001-ZCLWRKAR = GT_PA0001-WERKS.

      LOOP AT LT_PA9883 WHERE PERNR = GT_PA0001-PERNR AND
                                                       BEGDA BETWEEN GT_PA0001-BEGDA AND GT_PA0001-ENDDA .
        ET_PA0001-ZCGSJBGRP =  LT_PA9883-ZZCGSJBGRP.
        ET_PA0001-ZCGSJIKUN =  LT_PA9883-ZZCGSJIKUN.
        ET_PA0001-ZCGSJIKUB = LT_PA9883-ZZCGSJIKUB.
        ET_PA0001-ZCGSAGREE = LT_PA9883-ZZCGSAGREE.

        L_CHK = 'X'.
      ENDLOOP.

      IF L_CHK IS INITIAL.

        LOOP AT LT_PA9883_T WHERE PERNR = GT_PA0001-PERNR AND
                                            BEGDA BETWEEN GT_PA0001-BEGDA AND GT_PA0001-ENDDA .
          ET_PA0001-ZCGSJBGRP =  LT_PA9883_T-ZZCGSJBGRP.
          ET_PA0001-ZCGSJIKUN =  LT_PA9883_T-ZZCGSJIKUN.
          ET_PA0001-ZCGSJIKUB = LT_PA9883_T-ZZCGSJIKUB.
          ET_PA0001-ZCGSAGREE = LT_PA9883_T-ZZCGSAGREE.

          L_CHK = 'X'.
        ENDLOOP.

      ENDIF.

      CLEAR: L_CHK.

*      LOOP AT lt_pa0105 WHERE pernr = gt_pa0001-pernr AND
*                                                  aedtm BETWEEN gt_pa0001-begda AND gt_pa0001-endda..
*        et_pa0001-email = lt_pa0105-usrid_long.
*        l_chk = 'X'.
*      ENDLOOP.
*
*      IF  l_chk IS INITIAL.
*        LOOP AT lt_pa0105_t WHERE pernr = gt_pa0001-pernr AND
*                                                    aedtm BETWEEN gt_pa0001-begda AND gt_pa0001-endda..
*          et_pa0001-email = lt_pa0105_t-usrid_long.
*          l_chk = 'X'.
*        ENDLOOP.
*      ENDIF.

      CLEAR: L_CHK.
      APPEND ET_PA0001.
      APPEND ET_PA0001ENH.
    ENDLOOP.

    PERFORM FILL_BRACD_CODE USING IV_BRACD 3 CHANGING ET_PA0001[].
    PERFORM FILL_BRACD_CODE USING IV_BRACD 3 CHANGING ET_PA0001ENH[].
    PERFORM FILL_ADDITIONAL_DATA TABLES ET_PA0001[] GT_PA0001[].
  ENDIF.

**********Infotype 0002**********
*&   Accept only gets more managerial   &*
  SELECT *
    INTO CORRESPONDING FIELDS OF TABLE ET_PA0002
    FROM PA0002
    FOR ALL ENTRIES IN LT_PA9883
    WHERE PERNR = LT_PA9883-PERNR.

  IF ET_PA0002[] IS NOT INITIAL.
    PERFORM FILL_BRACD_CODE USING IV_BRACD 3 CHANGING ET_PA0002[].
  ENDIF.

**********Infotype 0008**********
*&   Accept only gets more managerial   &*
  SELECT *
    INTO CORRESPONDING FIELDS OF TABLE ET_PA0008
    FROM PA0008
    FOR ALL ENTRIES IN LT_PA9883
    WHERE PERNR = LT_PA9883-PERNR
          AND AEDTM BETWEEN IV_BEGDA AND IV_ENDDA.

*&   Accept only gets more managerial   &*
  IF  LT_PA9883_T[] IS NOT INITIAL.
    SELECT *
      APPENDING CORRESPONDING FIELDS OF TABLE ET_PA0008
      FROM PA0008
      FOR ALL ENTRIES IN LT_PA9883_T
      WHERE PERNR = LT_PA9883_T-PERNR
            AND ENDDA <= LT_PA9883_T-ENDDA.
  ENDIF.

  IF ET_PA0008[] IS NOT INITIAL.
    PERFORM FILL_BRACD_CODE USING IV_BRACD 3 CHANGING ET_PA0008[].


*&   manager# ### #### ##    &*
    LOOP AT ET_PA0008.

      CLEAR : LT_KEY, LT_KEY[], LS_RETURN.
      CALL FUNCTION 'BAPI_BASICPAY_GETLIST'
        EXPORTING
          EMPLOYEENUMBER   = ET_PA0008-PERNR
*         SUBTYPE          =
          TIMEINTERVALLOW  = ET_PA0008-BEGDA
          TIMEINTERVALHIGH = ET_PA0008-BEGDA
        IMPORTING
          RETURN           = LS_RETURN
        TABLES
          BASICPAYEMPKEY   = LT_KEY.

      IF LS_RETURN IS NOT INITIAL.
        CONTINUE.
      ENDIF.

      CLEAR : LT_WAGETYPES, LT_WAGETYPES[], L_ANNUAL, L_BASIC, LS_RETURN.

      CALL FUNCTION 'BAPI_BASICPAY_GETDETAIL'
        EXPORTING
          EMPLOYEENUMBER = LT_KEY-EMPLOYEENO
          SUBTYPE        = LT_KEY-SUBTYPE
          OBJECTID       = LT_KEY-OBJECTID
          LOCKINDICATOR  = LT_KEY-LOCKINDIC
          VALIDITYBEGIN  = LT_KEY-VALIDBEGIN
          VALIDITYEND    = LT_KEY-VALIDEND
          RECORDNUMBER   = LT_KEY-RECORDNR
        IMPORTING
          RETURN         = LS_RETURN
          ANNUALSALARY   = L_ANNUAL.              "##


      ET_PA0008-ANSAL = L_ANNUAL.

      MODIFY ET_PA0008 TRANSPORTING ANSAL.

      CLEAR: ET_PA0008.
    ENDLOOP.

  ENDIF.

**********Infotype 0022**********
  CLEAR: GT_PA0022[].
*&   Accept only gets more managerial   &*
  SELECT *
    INTO CORRESPONDING FIELDS OF TABLE GT_PA0022
    FROM PA0022
    FOR ALL ENTRIES IN LT_PA9883
    WHERE PERNR = LT_PA9883-PERNR
          AND AEDTM BETWEEN IV_BEGDA AND IV_ENDDA.

*&   Accept only gets more managerial   &*
  IF  LT_PA9883_T[] IS NOT INITIAL.
    SELECT *
      APPENDING CORRESPONDING FIELDS OF TABLE GT_PA0022
      FROM PA0022
      FOR ALL ENTRIES IN LT_PA9883_T
      WHERE PERNR = LT_PA9883_T-PERNR
            AND ENDDA <= LT_PA9883_T-ENDDA.
  ENDIF.

  IF GT_PA0022[] IS NOT INITIAL.
    LOOP AT GT_PA0022.
      MOVE-CORRESPONDING GT_PA0022 TO ET_PA0022.
      MOVE-CORRESPONDING GT_PA0022 TO ET_PA0022ENH.
      APPEND ET_PA0022.
      APPEND ET_PA0022ENH.
    ENDLOOP.

    PERFORM FILL_BRACD_CODE USING IV_BRACD 3 CHANGING ET_PA0022[].
    PERFORM FILL_BRACD_CODE USING IV_BRACD 3 CHANGING ET_PA0022ENH[].
    PERFORM FILL_EXTRA_0022  TABLES ET_PA0022[].
  ENDIF.

***********Infotype 0025(Appraisal)*********
  CLEAR GT_PA0025[].

*&   Accept only gets more managerial   &*

  SELECT * INTO CORRESPONDING FIELDS OF TABLE GT_PA0025
    FROM PA0025
   FOR ALL ENTRIES IN LT_PA9883
    WHERE PERNR = LT_PA9883-PERNR
          AND AEDTM BETWEEN IV_BEGDA AND IV_ENDDA
          AND KRT01 IN ('01', '02').

*&   Accept only gets more managerial   &*
  IF  LT_PA9883_T[] IS NOT INITIAL.
    SELECT *
      APPENDING CORRESPONDING FIELDS OF TABLE GT_PA0025
      FROM PA0025
      FOR ALL ENTRIES IN LT_PA9883_T
      WHERE PERNR = LT_PA9883_T-PERNR
           AND ENDDA <= LT_PA9883_T-ENDDA.
  ENDIF.

  CLEAR: GT_PA0025, ET_99001[].
  LOOP AT GT_PA0025.
*    CLEAR: ls_99001.
*    MOVE-CORRESPONDING gt_pa0025 TO ls_99001.

    CLEAR: LT_99001[].
    CALL FUNCTION 'ZH_HR_APPRAISAL_SCORE_SUM'
      EXPORTING
        IS_0025  = GT_PA0025
*       iv_pernr = gt_pa0025-pernr
      TABLES
        ET_99001 = LT_99001.
    APPEND LINES OF LT_99001 TO ET_99001.
  ENDLOOP.
  IF LINES( ET_99001 ) > 0.
    PERFORM FILL_BRACD_CODE USING IV_BRACD 3 CHANGING ET_99001[].
  ENDIF.

***********Infotype Other/Previous Employers**********
* PA0023
*&   Accept only gets more managerial   &*
  SELECT * FROM PA0023 INTO TABLE LT_PA0023
    FOR ALL ENTRIES IN LT_PA9883
    WHERE PERNR = LT_PA9883-PERNR
          AND AEDTM BETWEEN IV_BEGDA AND IV_ENDDA.

*&   Accept only gets more managerial   &*
  IF  LT_PA9883_T[] IS NOT INITIAL.
    SELECT * FROM PA0023
      APPENDING TABLE LT_PA0023
      FOR ALL ENTRIES IN LT_PA9883_T
      WHERE PERNR = LT_PA9883_T-PERNR
           AND ENDDA <= LT_PA9883_T-ENDDA.
  ENDIF.

  SELECT * FROM T513C INTO TABLE LT_T513C
    WHERE SPRAS = 'E'.
  SORT LT_T513C BY TAETE.

  LOOP AT LT_PA0023.
    CLEAR ET_99002.
    MOVE-CORRESPONDING LT_PA0023 TO ET_99002.
    ET_99002-ZCBRACD = IV_BRACD.
    ET_99002-WPBEG = LT_PA0023-BEGDA.
    ET_99002-WPEND = LT_PA0023-ENDDA.
    ET_99002-ARBGB = LT_PA0023-ARBGB.
*    et_99002-ORGTX
*    et_99002-JIKWI
    CLEAR LT_T513C.
    READ TABLE LT_T513C WITH KEY TAETE = LT_PA0023-TAETE BINARY SEARCH.
    ET_99002-RESDX = LT_T513C-LTEXT.

    ET_99002-LOCAT = LT_PA0023-ORT01.
    APPEND ET_99002.
  ENDLOOP.

**********Infotype 9882(Succesion Planning)**********
*&   Accept only gets more managerial   &*
  SELECT *
    INTO CORRESPONDING FIELDS OF TABLE ET_PA9882
    FROM PA9882
    FOR ALL ENTRIES IN LT_PA9883
    WHERE PERNR = LT_PA9883-PERNR
          AND AEDTM BETWEEN IV_BEGDA AND IV_ENDDA.

*&   Accept only gets more managerial   &*
  IF  LT_PA9883_T[] IS NOT INITIAL.
    SELECT *
      APPENDING CORRESPONDING FIELDS OF TABLE ET_PA9882
      FROM PA9882
      FOR ALL ENTRIES IN LT_PA9883_T
      WHERE PERNR = LT_PA9883_T-PERNR
           AND ENDDA <= LT_PA9883_T-ENDDA.
  ENDIF.

  IF ET_PA9882[] IS NOT INITIAL.
    PERFORM FILL_BRACD_CODE USING IV_BRACD 3 CHANGING ET_PA9882[].
  ENDIF.

**********Infotype 9880(Multi-Language)**********
*&   Accept only gets more managerial   &*
  SELECT *
    INTO CORRESPONDING FIELDS OF TABLE ET_PA9880
    FROM PA9880
    FOR ALL ENTRIES IN LT_PA9883
    WHERE PERNR = LT_PA9883-PERNR
          AND AEDTM BETWEEN IV_BEGDA AND IV_ENDDA.

*&   Accept only gets more managerial   &*
  IF  LT_PA9883_T[] IS NOT INITIAL.
    SELECT *
      APPENDING CORRESPONDING FIELDS OF TABLE ET_PA9880
      FROM PA9880
      FOR ALL ENTRIES IN LT_PA9883_T
      WHERE PERNR = LT_PA9883_T-PERNR
           AND ENDDA <= LT_PA9883_T-ENDDA.
  ENDIF.

  IF ET_PA9880[] IS NOT INITIAL.
    PERFORM FILL_BRACD_CODE USING IV_BRACD 3 CHANGING ET_PA9880[].
  ENDIF.

*  IF lines( et_pa9880 ) > 0.
*    SELECT * INTO CORRESPONDING FIELDS OF TABLE et_pa9880enh FROM zghrlt0001
*      FOR ALL ENTRIES IN et_pa9880
*      WHERE adatanr = et_pa9880-adatanr.
*    IF sy-subrc = 0.
*      PERFORM fill_bracd_code USING iv_bracd 3 CHANGING et_pa9880enh[].
*    ENDIF.
*  ENDIF.

**********Infotype 9881(Talent Mgmt)**********
*&   Accept only gets more managerial   &*
  SELECT *
    INTO CORRESPONDING FIELDS OF TABLE ET_PA9881
    FROM PA9881
    FOR ALL ENTRIES IN LT_PA9883
    WHERE PERNR = LT_PA9883-PERNR
          AND AEDTM BETWEEN IV_BEGDA AND IV_ENDDA.

*&   Accept only gets more managerial   &*
  IF  LT_PA9883_T[] IS NOT INITIAL.
    SELECT *
      APPENDING CORRESPONDING FIELDS OF TABLE ET_PA9881
      FROM PA9881
      FOR ALL ENTRIES IN LT_PA9883_T
      WHERE PERNR = LT_PA9883_T-PERNR
           AND ENDDA <= LT_PA9883_T-ENDDA.
  ENDIF.

  IF ET_PA9881[] IS NOT INITIAL.
    PERFORM FILL_BRACD_CODE USING IV_BRACD 3 CHANGING ET_PA9881[].
  ENDIF.

*  IF lines( et_pa9881 ) > 0.
*    SELECT * INTO CORRESPONDING FIELDS OF TABLE et_pa9881enh1 FROM zghrlt0002
*      FOR ALL ENTRIES IN et_pa9881
*      WHERE tabnr = et_pa9881-thist.
*    IF sy-subrc = 0.
*      PERFORM fill_bracd_code USING iv_bracd 3 CHANGING et_pa9881enh1[].
*    ENDIF.
*
*    SELECT * INTO CORRESPONDING FIELDS OF TABLE et_pa9881enh2 FROM zghrlt0003
*      FOR ALL ENTRIES IN et_pa9881
*      WHERE tabnr = et_pa9881-tplan.
*    IF sy-subrc = 0.
*      PERFORM fill_bracd_code USING iv_bracd 3 CHANGING et_pa9881enh2[].
*    ENDIF.
*  ENDIF.

ENDFUNCTION.
